### ISSUE TITLE
[BUG] Can't select post text 

### ISSUE THREAD

**Issue by K1rakishou** [Adamantcheese/Kuroba#10]
This commit broke it https://github.com/Adamantcheese/Kuroba/commit/26374ee06683be2122bf0455a3d00259a9f74c33

Apparently the easiest fix is to create a separate button for the "scroll to reply" feature.

**Comment by Astridchan** [comment]
IMO the old behaviour where a single tap was enough to jump to a reply should at least be an option, even if it's not the default.

**Comment by K1rakishou** [comment]
@Astridchan The problem is that it is really easy to missclick and it will close the whole reply chain and scroll you to a post and there is no way of undoing it.

**Comment by ghost** [comment]
Make it double click to select.

**Comment by K1rakishou** [comment]
@myuli 
Apparently it is already working with double tap. 
Maybe we should just live it like this? I mean double tap to start the text selection,

**Comment by ghost** [comment]
@K1rakishou
It doesn't work when you open a reply (chain).

**Comment by Adamantcheese** [comment]
Behavior will be changed to double tap to go to post. Text selection won't be available in the popup, but is still available in the actual post. Text selection is either double tap (longer delay) or long click.
