### ISSUE TITLE
Bring back "stop watching" notification button

### ISSUE THREAD

**Issue by Nachtalb** [Adamantcheese/Kuroba#1003]
I saw that you removed that feature in here cc693611e0e67d700443e6864ef0d61b3b6a56ea and I actually use it quite a lot. And I don't think I can be the only one. It'd be very sad to let this feature go...

**Comment by Adamantcheese** [comment]
I'd honestly like an explanation of how you use it that often before that, as stopping watching all threads is rarely what I think you'd want to do. If you want to pin threads but not have them being actively watched when you post or something then that's a setting I can add instead.

**Comment by Nachtalb** [comment]
My main use is the following: 

I have filters activated that auto watch certain threads. So when I open Kuroba it starts watching them and starts giving me notifications about them as expected (btw. love the auto watch feature 👍, thanks for that). 
Though after a certain time this can get cluttered (eg. if it watches 5 threads or so) or I have other things to do and want them out of the way. So I use the wonderful little button to stop watching all the threads instead of having to open the app and stop watching every single one manually which is quite tedious. 

Additionally, I think to remove a feature which has no impact on performance nor makes the code bad, doesn't fix anything and doesn't have any user experience improvements and using as a reason "pretty useless honestly" isn't really the best practice either...

**Comment by Adamantcheese** [comment]
Sounds good to me, but consider this alternative that you might find more useful: a setting that makes filter-watched threads be added to the bookmarks list without actually watching them (ie greyed out). The notification doesn't really provide information about what thread got posted, just posts inside of those threads, and I do agree that the notification becomes pretty useless once you have a sufficient number of threads with enough posts.

I've also been considering removing the watch notification in favor of just having quote notifications like last page notifications as well, do you think that would be a good idea?

**Comment by Nachtalb** [comment]
> quoted posts notifications only

IIRC you can already do that, or not? 

But I don't think you should restrict the notifications to that without the option to get notifications about all posts. Eg. on 4chan - /wg/ (Wallpapers) you probably want to get notified by all posts in a not just the ones replying to your posts. Reply to ones one posts would work more for chat oriented boards like /g/ or /pol/ IMHO. 

And in my case, it's just that. That I want to get notifications on all posts eg. on /s/, /wg/, /a/ etc. so like that the greyed out bookmark thing won't do.

**Comment by Adamantcheese** [comment]
I think you misunderstood my comment. The setting I'm considering would only apply to _filter watched_ posts, which means you wouldn't need to have the "stop watching" button for your use case. They would be bookmarked but not notify you unless you turned them on specifically. If you're only using the watch notification as an indication that there are new filter watched threads and then hitting the "stop watching" button, I could instead add another notification to alert when the filter watcher bookmarks threads.

**Comment by Nachtalb** [comment]
Thanks for adding it again and in general for all your great work!! ❤️
