### ISSUE TITLE
Thumbnails are sometimes tinted dark in the catalog

### ISSUE THREAD

**Issue by ghost** [Adamantcheese/Kuroba#1006]
OP thumbnails sometimes have a black tint to them. When you open the image, it's normal, but the animation of closing itgoes from a lighter to darker version in the thumbnail. This doesn't happen in thread view, and refreshing the board fixes it.

**Comment by Adamantcheese** [comment]
It's not that they're tinted black, it's that for some reason the fade in animation is "finishing" while leaving it partially opaque still, blending it with the background color of the theme making it look dark. It's a "too many things going on with the main thread" issue, but animations necessarily play on the main thread so other stuff has to take less time. Performance stuff that'll get there eventually.
