### ISSUE TITLE
Filenames saved with incorrect characters

### ISSUE THREAD

**Issue by ownBard** [Adamantcheese/Kuroba#101]
Continued issue from #43. Filenames are saved with backslashes before each space character:
![FCuBfOTX](https://user-images.githubusercontent.com/51628221/59572007-9377aa80-9099-11e9-8716-e165abc21351.jpeg)
![CvCHGdlL](https://user-images.githubusercontent.com/51628221/59572011-9a062200-9099-11e9-8d93-fab133a5ca89.jpeg)

**Comment by Adamantcheese** [comment]
I was under the assumption that spaces needed to be escaped, but it appears that this isn't the case.
