### ISSUE TITLE
Accidentally graying out threads in thread watcher

### ISSUE THREAD

**Issue by ghost** [Adamantcheese/Kuroba#1010]
I think something to do with swiping thread watcher open is ignoring the thread near where I swipe. This happens enough that I'm pretty sure It's not me accidentally tapping them when I'm in the menu

**Comment by Adamantcheese** [comment]
I can't reproduce this at all, it probably is you tapping it because the drawer implementation basically hasn't changed since Clover and that issue wasn't reported there.

**Comment by ghost** [comment]
If I had to guess, I think it's possible to tap threads while opening thread watcher. I used clover a lot and didn't encounter this, but I guess I can't really offer any insight

**Comment by Adamantcheese** [comment]
It isn't, if you're dragging the drawer open and try to tap a thread, it'll just snap the drawer open state to your other finger location.
