### ISSUE TITLE
Report "Stuttering"

### ISSUE THREAD

**Issue by K1rakishou** [Adamantcheese/Kuroba#1012]
UUID: 289ac7372e918e85c4a4750a874cb82b
Build flavor: stable
Version name: v4.13.5
OS info: Android 10, sdk version: 29
Report description: When text from a post is selected without quoting, scrolling is noticeably stuttery.

**Comment by Adamantcheese** [comment]
Yeah this one's basically impossible to solve from an application standpoint. Some poor implementation of it on the recycler view side of things.
