### ISSUE TITLE
Left menu can't be opened

### ISSUE THREAD

**Issue by lsvy97** [Adamantcheese/Kuroba#1016]
Left menu can't be opened, just crashes the app.
Device: LeEco Le 2, Android 6.0.1
Kuroba 4.13.6

**Comment by Adamantcheese** [comment]
Not much I can do without some logs from logcat then.

**Comment by 1sad** [comment]
same, oppening left menu crashes app instantly
samsung 850F, 5.0.2

>without some logs

how to get logs without being able to open the menu?

**Comment by Adamantcheese** [comment]
As in hook it up to your computer and run logcat and give me what it spits out during a crash.

**Comment by 1sad** [comment]
> 
> 
> As in hook it up to your computer and run logcat and give me what it spits out during a crash.

okay, how do you actually do this
you need to install something to the pc?

**Comment by lsvy97** [comment]
> > As in hook it up to your computer and run logcat and give me what it spits out during a crash.
> 
> okay, how do you actually do this
> you need to install something to the pc?

1. Download ADB
https://developer.android.com/studio/releases/platform-tools
2. Unpack it
3. Go to "platform-tools" folder, open terminal here (shift+right click)
4. Connect your phone and enable usb debugging
5. Run "adb logcat -> logcat.txt"
6. Logs go brrr
7. Stop logcat with ctrl-c. Logs are in logcat.txt.
I'm trying to do this rn, but adb can't find the device

**Comment by Astridchan** [comment]
@lsvy97 
It's probably a driver issue, getting the ADB drivers to install correctly on Windows 8/10 can be fucky. You should have "ADB device" or "ADB interface" showing up in Windows device manager when you plug the phone with USB debugging enabled. Search for "universal ADB drivers", it might help. You also might have to [disable Driver Signature Enforcement](https://www.howtogeek.com/167723/how-to-disable-driver-signature-verification-on-64-bit-windows-8.1-so-that-you-can-install-unsigned-drivers/) to get the drivers to install properly.

**Comment by lsvy97** [comment]
Here's the output:
https://pastebin.com/6kpivc0S

**Comment by K1rakishou** [comment]
Just FYI but there is nothing in the logs. You need to start logging and then make it crash.

**Comment by lsvy97** [comment]
@K1rakishou It outputs really long file and i just selected what i thought the most relevant part. Trying again, now there's only beginning: 
https://pastebin.com/kqbtx7LR

**Comment by K1rakishou** [comment]
I think it would be better to post the whole thing. From the log you posted it looks like some native crash which probably has nothing to do with the app.

```
07-28 01:08:10.157 18045  6447 F libc    : invalid address or address of corrupt block 0x55afdc89f0 passed to dlfree
07-28 01:08:10.157 18045  6447 F libc    : Fatal signal 11 (SIGSEGV), code 1, fault addr 0xdeadbaad in tid 6447 (/a.4cdn.org/...)
```

Especially this thing - 0xdeadbaad 
Is your phone rooted? Do you use custom ROM?

**Comment by lsvy97** [comment]
Here's the whole thing:
https://mega.nz/file/CdlXCDrJ#GCTHPGjqzsPPAU9_Hl-APPHCzQSlM12Mha7A1onNess

>Is your phone rooted? Do you use custom ROM?

No and no. Stock pre-installed ROM.

>it looks like some native crash which probably has nothing to do with the app.

Some other anons both here and in the 4chan thread had this issue, all of them have different phones. The only common thing is that they're all running older versions of android, so it could be some legacy support issue.

**Comment by K1rakishou** [comment]
Maybe this?
https://stackoverflow.com/questions/23048567/android-signal-11-rs-cpp-error-blur-radius-out-of-0-25-pixel-bound

**Comment by lsvy97** [comment]
Maybe, probably the same issue, but with font size or whatever in this sidebar update.

**Comment by K1rakishou** [comment]
Can you try decreasing the font size, in the OS settings, just to make sure?

**Comment by lsvy97** [comment]
Nah, Kuroba is independent from system font size. And it still crashes.

**Comment by Adamantcheese** [comment]
That stacktrace is pointing to libssl and libcrypto, so it's probably got to do with the OkHttp 4.7.2 -> 4.8.0 upgrade that occurred. That shadow radius thing is also likely, but the text isn't italicized anymore so that code can be removed anyways. I'll roll back OkHttp as well.
