### ISSUE TITLE
Unintentional transparent menu when adding boards from clean install

### ISSUE THREAD

**Issue by Pentaphon** [Adamantcheese/Kuroba#1018]
See below. Latest 4.13.6 on Moto G4. 

![menu](https://user-images.githubusercontent.com/49374058/88790854-a76f5600-d14d-11ea-88ed-12bc575a5b9d.jpg)

**Comment by Adamantcheese** [comment]
Does that happen with other dialogs? Like making a new filter for example.

**Comment by Pentaphon** [comment]
> Does that happen with other dialogs? Like making a new filter for example.

Just checked and yes.

**Comment by Adamantcheese** [comment]
How about something like the help dialog in the theme setup menu, is that transparent as well? Trying to pinpoint if this is an issue specifically with AlertDialogs that set a custom view.

**Comment by Pentaphon** [comment]
> How about something like the help dialog in the theme setup menu, is that transparent as well?

Yes, that too.

**Comment by Adamantcheese** [comment]
I probably should've asked like 2 weeks ago, but has this been resolved on dev? Trying to get alert dialogs to style correctly seems to be a massive pain because there's no good reference on what attributes are used.

**Comment by i-cant-git** [comment]
I have this problem as well. Filter dialogs became transparent after I upgraded to Kuroba version 4.13.6. Android version 7.

![Transparent Dialog](https://user-images.githubusercontent.com/16619091/94322959-c303ab00-ff9c-11ea-9dc6-919d891668a2.gif)

**Comment by Adamantcheese** [comment]
@i-cant-git Does this still occur on the dev version? I still haven't had any confirmation that it's been resolved with those changes I made above.

**Comment by i-cant-git** [comment]
I tried v4.13.6 767d318d, the transparency issue is gone.

**Comment by Adamantcheese** [comment]
Closed with https://github.com/Adamantcheese/Kuroba/commit/767d318d6383d5be4da60a239dfe521cdd45b3c1, thanks @i-cant-git for the confirmation!

**Comment by i-cant-git** [comment]
I use Kuroba and the filter dialog every day, I'd be happy if you can make a new non-dev release soon 🥺
