### ISSUE TITLE
[Feature Request] 8chan access via TOR hidden service

### ISSUE THREAD

**Issue by leEpicBenisxDDDD** [Adamantcheese/Kuroba#102]
Being able to access 8chan through their hidden service would be nice given they're under investigation for closing pools or something.

Lowest effort implimentation should just be copypasting the chan8 site folder, replacing all instances of "https://8ch.net" with "http://oxwugzccvk3dk6tj.onion" in the copy's Chan8.java and adding it to SiteRegistry.java.

You could instead add a toggle under 8chan (or global) settings and make Chan8.java return an alternate domain based on the setting if you want to be elegant and not duplicate shit.

The user would still have to route Kuroba through Orbot manually unless site or tor specific proxy settings were developed, but it's better than no functionality at all.

**Comment by Adamantcheese** [comment]
I won't work on this because I don't use 8chan and only mildly care about it, but if someone else submits a PR I'll merge it.

**Comment by leEpicBenisxDDDD** [comment]
I'll give it a shot but I dont know what I'm doing. Getting a whole ton of internal errors building vanilla Kuroba with Android Studio and something's wrong with the gradle plugin. Wish me luck.

**Comment by Adamantcheese** [comment]
As it has been almost 3 weeks and I've seen nothing implemented on your end (looking at your branch), I'm going to close this issue. If you do end up doing the work, submit your PR.
