### ISSUE TITLE
[Suggestion] Big thumbnail mode

### ISSUE THREAD

**Issue by Astridchan** [Adamantcheese/Kuroba#1020]
An optional setting that makes thumbnails take full width in threads and board mode. Basically the same thing as the new 1-column catalog/album mode. Quick mockup:

![exx1](https://user-images.githubusercontent.com/40862101/88794847-c0a4f080-d1a7-11ea-819a-437b78404837.jpg)

**Comment by Adamantcheese** [comment]
Because posts inside threads can have more than 1 image, I can't really do that. I only implemented 1 column mode for card catalog view because only one image is able to be displayed at a time. I won't work on this or accept a PR, sorry.
