### ISSUE TITLE
opening threads is now harder

### ISSUE THREAD

**Issue by namazso** [Adamantcheese/Kuroba#1022]
only the lower half of the post in catalog makes the thread open. I dont see any feature related to the OP header, could we get back the old behavior?

**Comment by Adamantcheese** [comment]
What? Tapping the image in the catalog always opened up the image, that's been around since Clover.

**Comment by namazso** [comment]
the header of the post (name, subject, id, etc..) opened the thread before the update. now it does absolutely nothing.

**Comment by Adamantcheese** [comment]
Ah, gotcha.
