### ISSUE TITLE
Bring back the quote options

### ISSUE THREAD

**Issue by floppyD** [Adamantcheese/Kuroba#1023]
Tapping the post number is harder on some devices and font sizes, and just worse than having to open the menu in my opinion. Just bring it back and leave it as optional at least.

**Comment by dronewizard** [comment]
I agree. Would love to see a return to the previous quote system as I accidentally quote people all the time now by misclicking.

**Comment by cdr9042** [comment]
I agree with you. I misclick on the post number too much
