### ISSUE TITLE
Report "filters"

### ISSUE THREAD

**Issue by K1rakishou** [Adamantcheese/Kuroba#1027]
UUID: 5ce425d379c2b08ee2cc1c32f4eb2221
Build flavor: stable
Version name: v4.13.6
OS info: Android 9, sdk version: 28
Report description: filter words for example *hello* *hi* *bye* are working togeder in a single filter but filter words like "hello" "hi" "bye" doesn't work, please fix this issue

**Comment by Adamantcheese** [comment]
Filters are working as intended. A filter with the pattern `hello hi bye` will match any of `hello`, `hi`, and `bye`. A filter of just `"hello"` will match `hello` and nothing else. A filter of `"hello" "hi" "bye"` will match `hello" "hi" "bye` exactly and nothing else, as the help dialog explains. For anything that is more complicated, using regex is preferred.
