### ISSUE TITLE
Report "Keyboard doesn't show up in catalog"

### ISSUE THREAD

**Issue by K1rakishou** [Adamantcheese/Kuroba#1028]
UUID: 6d8f1e96f4a6acea35188c9bf00e5a88
Build flavor: stable
Version name: v4.13.6
OS info: Android 9, sdk version: 28
Report description: Steps to reproduce:
-Search for something in catalog
-Enter a thread
-Go back

The keyboard won't show up unless you close the search and open it again

**Comment by Adamantcheese** [comment]
Notes: Specific to Phone layout mode.
