### ISSUE TITLE
Update board list to add /vrpg/, /vmg/

### ISSUE THREAD

**Issue by ghost** [Adamantcheese/Kuroba#1032]
There's a new board, and it doesn't work in the app right now

**Comment by Adamantcheese** [comment]
4chan's boards.json needed to be updated in order for this to work. You may have to force stop the app and restart it in order for it to appear in the board selection window, as boards are only retrieved once upon app startup.

**Comment by ghost** [comment]
I feel silly for not trying this. Good to know how it works

**Comment by Adamantcheese** [comment]
The same applies to Clover, as the thread watcher starts a foreground, persistent task, it doesn't actually allow the application to fully close, which means any "startup" tasks are never actually done when opening the application again.
