### ISSUE TITLE
Make new 'tap post number to reply' optional setting

### ISSUE THREAD

**Issue by lewri** [Adamantcheese/Kuroba#1035]
The change to quote posts by tapping the post number may be a slightly too drastic change for some. Instead, it may be better to make it a toggle option for now.

There are also issues where a post number and quoted post are close to each other, which can cause a user to misclick the wrong thing. Especially as the clickable zone of the post number is smaller than the other.

![Screenshot_20200801_214659_com github adamantcheese chan](https://user-images.githubusercontent.com/20030128/89110229-97eb5800-d440-11ea-822b-2acb0e8774af.png)

**Comment by Adamantcheese** [comment]
I'll consider some alternate UX stuff, but the tap-to-reply change has already been reverted.

**Comment by lewri** [comment]
Ah thanks for letting me know 👍
