### ISSUE TITLE
Upstream merging time!

### ISSUE THREAD

**Issue by TacoTheDank** [Adamantcheese/Kuroba#1036]
It seems that Floens is active once again, and is merging stuff (finally). Of course, feel free to close this if you have this under control.

Things that have been merged so far:
- https://github.com/chandevel/Clover/pull/739 (The super-patch, already part of the repo)
- https://github.com/chandevel/Clover/pull/565 (Accessible post-info dialogue option)
- https://github.com/chandevel/Clover/pull/779 (exoplayer support expansion)

Other commits not part of any pull request have been made. https://github.com/chandevel/Clover/commits/dev

**Comment by Adamantcheese** [comment]
Oh believe me, I know. I just got like 30 email notifications.

**Comment by TacoTheDank** [comment]
Lol. Just making sure. 👍

**Comment by ghost** [comment]
Ooh, nice.

**Comment by Adamantcheese** [comment]
I'm closing this, anything small enough that's a bug in Clover I'll submit a fresh PR for whenever I get around to it. Maybe some features too, dunno. Lots of diversion at this point so it wouldn't be a strict copy/paste.
