### ISSUE TITLE
Comment replies appear minimised and cannot be opened

### ISSUE THREAD

**Issue by saloniamatteo** [Adamantcheese/Kuroba#1038]
Example (see highlighted comment):

![Screenshot_20200802-133318](https://user-images.githubusercontent.com/28765699/89122105-ee01df00-d4c4-11ea-8280-7948e5ac1fa1.png)

Comment text:
```
>>56744844 (OP)
Thank you for making this thread 
Just tried to move up to 15lb from 10 and was shocked at the trouble I had
Will probably go back to 10 and go up to 20 Reps (before I had stopped at 15), focus on strict form, & once I’ve mastered that, only go up to 12 and start over from 10 reps
```

I cannot open/maximize this comment. Sometimes if there are images they don't show up as well (but they show up if I open a previous image, then scroll right; gallery view?)

Is this a bug or is this a feature? The comment does not match any of my filters, so clearly the issue isn't with my filters. Is there an option that I need to enable/disable to show this comment?

**Comment by saloniamatteo** [comment]
Here's a video preview:

[Video preview](https://streamable.com/e/yw82h7)

**Comment by Adamantcheese** [comment]
Stubs are only ever displayed if you've either filter-hidden it, or if you've manually hidden the post from the options menu. Currently, you are only able to unhide a post if you've manually hidden it (or a chain), which means that yes, your filters are the culprit here. You can use Regex101 to help figure out what filter is catching that specific post.
The image thing is a known issue.

**Comment by saloniamatteo** [comment]
Odd. These are my filters:

![Screenshot_20200803-074939](https://user-images.githubusercontent.com/28765699/89150059-ffe39080-d55d-11ea-8b38-493b09a2dbc2.png)

I'm 100% sure they don't match the original text:

```
>>56744844 (OP)
Thank you for making this thread 
Just tried to move up to 15lb from 10 and was shocked at the trouble I had
Will probably go back to 10 and go up to 20 Reps (before I had stopped at 15), focus on strict form, & once I’ve mastered that, only go up to 12 and start over from 10 reps
```

**Comment by saloniamatteo** [comment]
UPDATE: disabling filters also does not change behavior, so it's safe to say my filters aren't the culprits here.

**Comment by saloniamatteo** [comment]
UPDATE 2: it seems like I needed to select "only on OP" and deselect "apply to replies".

Anyway thanks.

**Comment by Adamantcheese** [comment]
Your filter is the culprit here, even if you didn't actually bother to check anything like I said you should. Fix your regular expressions. 
![image](https://user-images.githubusercontent.com/9031585/89152094-3b0ea100-d517-11ea-8f9f-c02e34ddd880.png)

**Comment by saloniamatteo** [comment]
I'm sorry, I didn't specify it.

The first filter (which I wrote wrong) is now `/Mac(?:OS)?/i`, and now it filters correctly, so everything is back to normal.

![Screenshot_20200803-082659](https://user-images.githubusercontent.com/28765699/89152274-1cce9280-d563-11ea-8121-d5e1e362fd15.png)

No posts are hidden (the ones that do not match) and images show up properly.

I just wanted to say thanks for this awesome project!
