### ISSUE TITLE
Report "Improve catalog mode performance"

### ISSUE THREAD

**Issue by K1rakishou** [Adamantcheese/Kuroba#1039]
UUID: ef3795ddc3d7322f41de3cf79e36f9e6
Build flavor: stable
Version name: v4.13.6
OS info: Android 9, sdk version: 28
Report description: Kuroba gets really slow on catalog mode depending on the column setting, while on something like my gallery (simple gallery) I can set it to show much more images than Kuroba and it doesn't even sweat. There's something really inefficient going on there.

**Comment by Adamantcheese** [comment]
Closed with https://github.com/Adamantcheese/Kuroba/commit/9a5e3ac7c6728497f555bc3e211977ceebb8329f.
