### ISSUE TITLE
Cannot post images on lainchan/arisuchan

### ISSUE THREAD

**Issue by ownBard** [Adamantcheese/Kuroba#104]
lainchan:
![aYkUmDau](https://user-images.githubusercontent.com/51628221/59643866-fcbef280-9159-11e9-9258-0f93de18d261.jpeg)

arisuchan:
![UCeHpTdj](https://user-images.githubusercontent.com/51628221/59643887-0d6f6880-915a-11e9-971b-d16c7ecb8348.jpeg)

**Comment by Adamantcheese** [comment]
Because those sites don't have a boards.json, they're manually put in, and they aren't set with a maximum size. I'll put in an exception so that it won't appear if the maximum size isn't defined for the board (in the case of Lainchan/Arisuchan/Wired-7).
