### ISSUE TITLE
[Request] Please add "reply" menu button back

### ISSUE THREAD

**Issue by g-storres** [Adamantcheese/Kuroba#1040]
Latest latch notes state
"The post details area is now single-tap to quote post number only, long-tap for quote with text. Corresponding options menu items have been removed."
But it is really inconvenient having to tap the post you want to quote to actually quite it, because that area is so small and you can also tap it by accident which is really annoying.
I'd like to request that this change be either undone or added as an option in the menu.

**Comment by Adamantcheese** [comment]
This has already been reverted on dev.
