### ISSUE TITLE
Source Aid

### ISSUE THREAD

**Issue by DonaldTsang** [Adamantcheese/Kuroba#1054]
Please check this JSON data to see which imageboards are compatible with each other.
If they are, then not much new code will be needed.
https://github.com/ccd0/imageboards.json

Also https://github.com/miku-nyan/Overchan-Android/blob/master/Imageboards.md and others would provide hints as how how they can be supported.

Top 3 active forks:
- https://github.com/AliceCA/Overchan-Android/blob/master/Imageboards.md
- https://github.com/Eilhart/Overchan-Android/blob/master/Imageboards.md
- https://github.com/everychan/everychan/blob/master/Imageboards.md

**Comment by Adamantcheese** [comment]
I'm not sure I understand the point of this issue? If you want assistance with source code for implementing new sites I can do that, but otherwise sites are supported on a PR basis only.

**Comment by DonaldTsang** [comment]
Some of the websites might just be carbon copies of one another, therefore all it needs is a way to switch URLs for the same web engine.

**Comment by Adamantcheese** [comment]
Websites are generally not carbon copies of each other despite using the same underlying engine and I am not going to put in the effort for a *chan that I do not personally use. Other *chan browsers are implemented differently to Clover/Kuroba as well, which requires some amount of manual configuration and you can't just "switch Urls for the same web engine". Sites are once again supported on a PR basis. See comments on #591.

**Comment by DonaldTsang** [comment]
In that case, I would aid in the support for Lynxchan-based websties, since it seems those tends to be the most "carbon-coppyable".

**Comment by Adamantcheese** [comment]
See #7, #362, #523, probably a few more. It's been requested a few times so I'd be happy to accept a PR for a Lynxchan engine implementation and at least 1 supported site that uses it.
