### ISSUE TITLE
Unable to add 8kun boards

### ISSUE THREAD

**Issue by GutHib1209** [Adamantcheese/Kuroba#1056]
The list that is supposed to automatically populate with boards does not appear for 8kun.

**Comment by Astridchan** [comment]
Each 8kun board needs to be added manually, enter the board name into the search on the top left in the board add menu.

**Comment by Adamantcheese** [comment]
While 8kun does provide a boards.json, due to performance issues of it including 18,000+ boards, it is set to manually type in.
