### ISSUE TITLE
Weird artifact

### ISSUE THREAD

**Issue by floppyD** [Adamantcheese/Kuroba#1057]
I'm not sure if it was introduced on this version (4.13.6) or what, but I just noticed now. It's on top left.
![2020_08_11_20_13_10](https://user-images.githubusercontent.com/29208110/89958164-9aec0280-dc0f-11ea-9eee-b371180780b3.gif)

**Comment by Adamantcheese** [comment]
That is weird, but I can't reproduce it either in emulator or hardware. It's like parts of the rounding in the thumbnail are showing through the floating menu which uhh makes no sense? If you're on release, some stuff changed in dev that may have fixed it but iunno honestly

**Comment by floppyD** [comment]
I tried the dev, it happens there too.

**Comment by Adamantcheese** [comment]
I honestly can't reproduce this anywhere and don't think I can help solve it. If someone else has this issue, do a git-bisect from v4.13.5 and v4.13.6 and try and find where it occurred.
