### ISSUE TITLE
Minor issues with theme previews

### ISSUE THREAD

**Issue by ownBard** [Adamantcheese/Kuroba#106]
![qsbQTFvf](https://user-images.githubusercontent.com/51628221/59679007-4db40280-91bd-11e9-8c3c-1dc140eae57c.jpeg)

Post links are formatted as regular text and the timestamp is formatted according to the currently active theme rather than the one being previewed. Very minor issues.

**Comment by ownBard** [comment]
@Adamantcheese The timestamps still display as the wrong colour in the v4.3.1 release.

Also consider including some quoted text to the preview?

**Comment by Adamantcheese** [comment]
Done.
