### ISSUE TITLE
[BUG] Thread auto-updating stuck on "Loading..."

### ISSUE THREAD

**Issue by Astridchan** [Adamantcheese/Kuroba#1062]
Occasionally some threads will stop loading new replies and the thread info at the bottom just gets stuck on displaying `"Loading..."`. Reloading the thread from the menu fixes it. I tested the recent dev builds and I think 4022f99 is the commit where the issue started occuring.

**Comment by Adamantcheese** [comment]
I'll have to take a look at how Handlers actually work; I only went ahead with that one because inside the Handler class it has a method that effectively makes a singleton main handler, but it's marked as "UnsupportedAppUsage", without any explanation.
