### ISSUE TITLE
Report "Kuroba keeps posting on threads I'm not currently on"

### ISSUE THREAD

**Issue by K1rakishou** [Adamantcheese/Kuroba#1064]
UUID: fc85fec9c8a7793e9e79a80206765bf0
Build flavor: stable
Version name: v4.13.6
OS info: Android 10, sdk version: 29
Report description: This has happened several times already, I write something, press the post button and the post isn't anywhere. When I last expect I find it on another thread I've visited before.

**Comment by K1rakishou** [comment]
I remember there were some changes regarding this issue but people keep reporting it.

**Comment by floppyD** [comment]
And I thought I was just getting crazy.
