### ISSUE TITLE
[Feature Request] Undo Save

### ISSUE THREAD

**Issue by ZenitH-AT** [Adamantcheese/Kuroba#1068]
Other imageboard apps had the functionality to undo saving an image. For example, when saving an image, a toast would display with a confirmation message and "undo" button.

Not sure how useful it would really be but it was one thing a friend mentioned upon first using the app.

**Comment by Adamantcheese** [comment]
If you're accidentally saving images, you're doing something wrong. Either you're wildly swiping downwards on images with gestures on (which probably means you want to save every image, just download the whole album and filter them later) or you're reflexively tapping the download button in the toolbar, to which the same advice applies. I'm going to say no to this one, it's REALLY not that hard to avoid downloading an image.

Also toasts don't display options, you're thinking of a snackbar.
