### ISSUE TITLE
Using a thread link when the toolbar is hidden doesn't bring it back

### ISSUE THREAD

**Issue by ghost** [Adamantcheese/Kuroba#1069]
For example, if I scroll down and there's a "new thread" link, I'm put at the top of the new thread with a blank space where the toolbar normally would be until I scroll up or down.

**Comment by Adamantcheese** [comment]
Toolbar showing is triggered by a scroll event in the code, either because the adapter changed or because of an explicit scroll call immediately after that; don't know why it doesn't occur for you but it does on emulator.
