### ISSUE TITLE
Add a button to quickly enable/disable audio by default in webms

### ISSUE THREAD

**Issue by jkrass1** [Adamantcheese/Kuroba#1074]
For example, when I home I want to have the audio starting playing be default and don't want it when I am at work

Would be nice to have a button which you can use to easily toggle between it instead of navigating through settings every time 

Something like that

![Screenshot_2020-08-22-13-37-16-924_com github adamantcheese chan dev](https://user-images.githubusercontent.com/9212851/90954584-1a829880-e47e-11ea-9208-b4b5c4e6f784.jpg)

**Comment by Adamantcheese** [comment]
Uh, no? Use the setting to toggle the default mute state or just put your phone on vibrate at work.
