### ISSUE TITLE
Text selection ability is removed in specific cases

### ISSUE THREAD

**Issue by Astridchan** [Adamantcheese/Kuroba#1078]
Two different STR that both cause the ability to select text from a post to be removed. The issue happens on my Android 7.0 tablet but not on my Android 10 phone. I can also reproduce both issues on an Android 6.0 emulator.

No.1:
1. Open a thread
2. fast scroll (fling) down some amount and back up again
3. You can no longer select text from posts

I tested many different builds and the commit that caused this issue seems to be 79b4d5d.

No.2:
1. Open a thread
2. Quote a post with the "Quote" menu option
3. The post will get highlighted
4. You can no longer select text from that post (but can from others)

I wasn't able to pinpoint a specific commit that caused this issue but it seems to have happened somewhere between 1cafa33 (works fine) and 3b24910.

In both cases refreshing the thread makes text selection work again. Something else to mention, doing the number 2 steps also breaks things on my Android 10 phone but in a different way: text selection and the default actions (copy, select all etc.) still work but the custom actions (quote, web search) no longer do.

**Comment by Adamantcheese** [comment]
Selection seems to be a known bug on older versions that I've dealt with in the past, see https://issuetracker.google.com/issues/36984016.
Note that selection is broken on Android <6 anyways: https://stackoverflow.com/questions/9458902/overflow-button-forces-action-mode-to-finish.
