### ISSUE TITLE
[Question] Multiple file attachments

### ISSUE THREAD

**Issue by ownBard** [Adamantcheese/Kuroba#108]
Any plans to implement multiple file attachments for boards/sites that support it? Would it even be feasible?

I couldn't find any mention of this on Clover either.

**Comment by Adamantcheese** [comment]
In plans? No. Feasible? Probably, but it will likely break posting on other *chans. Clover doesn't support this either, as 8chan was only really added so it could be browsable, not postable (due to it's weird captcha).

**Comment by ownBard** [comment]
@Adamantcheese Aha, I didn't really have 8chan in mind anyway. Thanks for answering!
