### ISSUE TITLE
Can't post 

### ISSUE THREAD

**Issue by ze0ss** [Adamantcheese/Kuroba#1080]
I cannot post any comment, or media on 4chan, because of captcha error, all the time.
It (4chan) doesn't accept captchas apparently.

Tried all the captcha types as well, but to no avail.

**Comment by Adamantcheese** [comment]
Posting is working fine. Errors with captcha are not the fault of the app.

**Comment by ze0ss** [comment]
But I can never post anything, it's always captcha error (Your IP has been banned, etc)

But on the other hand, using the same IP addr., I can easily post on the 4ch website, it let's me post as much as I want, and it doesn't say "IP banned".

**Comment by K1rakishou** [comment]
Maybe you have a proxy enabled in the app and it's banned?

**Comment by ze0ss** [comment]
> Maybe you have a proxy enabled in the app and it's banned?

no, nothing of that sort.
it's a direct connection.
