### ISSUE TITLE
[feature request] bring back the dropdown menu for quoting

### ISSUE THREAD

**Issue by coty-crg** [Adamantcheese/Kuroba#1085]
Clicking the post number is awkward on mobile.

**Comment by Adamantcheese** [comment]
Duplicate of #1023. I like the implication that "on mobile" isn't the standard usage of the app and you're posting from like a smart fridge or treadmill or, somehow, a car.

**Comment by coty-crg** [comment]
The commit revert implies its coming back in a future update, yeah? Thanks.

Also, you don't use Kuroba in your tesla? wtf

**Comment by Adamantcheese** [comment]
Android Auto support soon™. But not really because it's kinda locked down what can run on a car, see https://developer.android.com/docs/quality-guidelines/car-app-quality. "Apps don't work with Android Auto unless they are installed from the Play Store."
Shame really, would've been fun to test out.
