### ISSUE TITLE
Support for overboards & hidden boards

### ISSUE THREAD

**Issue by ownBard** [Adamantcheese/Kuroba#109]
An option to manually configure boards that do not appear on the boards list (for boards that are not hardcoded or do not show up in the boards.json). Presumably, this would be similar to how 8chan boards are configured.

https://lainchan.org/q/res/6213.html
>Basically Mobile Apps don't like that we don't publish a board listing API, and as such they need to be hardcoded or allow the user to add the page to board mapping themselves.
>
>We don't have a board listing API because the 4chan API doesn't mandate it, and it because it defeats the purpose of having hidden or secret boards.

Is there some way around this issue? It was mentioned in #78 to replace hardcoding but I figure this is mostly seperate from that suggestion.

**Comment by Adamantcheese** [comment]
Boards don't really change often enough for this to be necessary. If there's a board missing on any hardcoded site, just ask for it in an issue and I'll slap it in. Literally one line of code per board, nothing really special.

**Comment by ownBard** [comment]
Ah that's too bad. I'll just make another issue then.
