### ISSUE TITLE
Posts open in browser as 4chan.org instead of 4channel.org

### ISSUE THREAD

**Issue by ghost** [Adamantcheese/Kuroba#1091]
This can be annoying because the redirect changes the site to 4channel, and then when set to open in app by default I get sent right back to kuroba, making the feature useless.

**Comment by Adamantcheese** [comment]
So just remove the default open strategy? I can't imagine you're opening links that often from elsewhere.

**Comment by ghost** [comment]
I actually do use it pretty often.

**Comment by ghost** [comment]
Are you still set on not changing this? It really sucks to choose between not being able to open in a browser and not being able to open links in the app.
I've found that clearing defaults doesn't really help. The only way to open in browser is to copy the link, paste it in the browser, and change .4chan to .4channel so it doesn't redirect. Or at least for my main browser, firefox. Chrome doesn't have the issue but it's also not set as my default browser so I don't really know.
