### ISSUE TITLE
Can't filter posts/threads by image hash

### ISSUE THREAD

**Issue by spaceserval** [Adamantcheese/Kuroba#1092]
Image itself gets hidden/removed, but the post still remains. 
![Screenshot_20200906-110122-01](https://user-images.githubusercontent.com/70836374/92321152-77f71780-f030-11ea-879d-2cf693a4705f.png)

**Comment by Adamantcheese** [comment]
Image hash filtering only applies to the images themselves, not the post that they are attached to, as a result of some sites allowing multiple images per post. I guess I could add a setting to override that.
