### ISSUE TITLE
Report "the colour of the ids on /biz/"

### ISSUE THREAD

**Issue by K1rakishou** [Adamantcheese/Kuroba#1095]
UUID: b47e64c09e610494bf2f2b6e77234dad
Build flavor: stable
Version name: v4.13.6
OS info: Android 10, sdk version: 29
Report description: they used to match the web site ID colours but now they're different

**Comment by Adamantcheese** [comment]
Closed with https://github.com/Adamantcheese/Kuroba/commit/1846b7912366a23e0cd87e498689baee8bbd9d5e.
