### ISSUE TITLE
Viewing transparent images aren't transparent

### ISSUE THREAD

**Issue by shiimizu** [Adamantcheese/Kuroba#1096]
Is it just me? It wasn't like this before. I'm on latest dev.

1. Go to any post that that attached a transparent image (png)
1. Press the thumb to view the full image
1. The background is supposed to be transparent

**Comment by Adamantcheese** [comment]
Duplicate of #1063.

**Comment by shiimizu** [comment]
Oh it was in appearance settings. Thanks!
