### ISSUE TITLE
[BUG] New captcha requires a lot of attempts before it gets accepted

### ISSUE THREAD

**Issue by K1rakishou** [Adamantcheese/Kuroba#11]
Help needed. Apparently NID cookie is not enough. On the other hand, when posting from chrome in incognito mode with forced no-js captcha it works normally without any cookies at all.

Get captcha:
![234234](https://user-images.githubusercontent.com/10332458/58751027-ddf60600-84a1-11e9-9733-e8df34c32e26.png)

Post answer:
![67657567](https://user-images.githubusercontent.com/10332458/58751030-e3535080-84a1-11e9-8c43-cfc9a8da69f1.png)

Why it does not work when I do the same from the app I can't figure it out.

**Comment by K1rakishou** [comment]
Here are captured captcha requests with responses when almost all google scripts disabled. It works flawlesly and does not send any cookies.

[1_Full.txt](https://github.com/Adamantcheese/Kuroba/files/3244113/1_Full.txt)

**Comment by Adamantcheese** [comment]
I'm not having any issues with the current implementation on my usual phone. One to three tries every time.

**Comment by K1rakishou** [comment]
@Adamantcheese Very strange. For me the first one usually goes fast but all consequent require like 10-20 attempts. Does not matter whether I use google cookie or the hardcoded one.

**Comment by K1rakishou** [comment]
And I just don't get how the browser work when I disable all the other google scripts, literally no cookie is being sent but it works flawlessly. I guess the only thing I can do now is to build dashchan and figure out how does it work on their side, what is being sent and received.

**Comment by K1rakishou** [comment]
I think it got a little bit better. Can someone confirm? Here is the debug apk:


[Kuroba.zip](https://github.com/Adamantcheese/Kuroba/files/3244699/Kuroba.zip)

**Comment by floppyD** [comment]
I tried your build but no dice. It was looking good, the first post took 2 tries and the second 3, but then the third took me 32 captchas and when it finally worked I got an incorrect captcha error.

**Comment by floppyD** [comment]
Can't you guys just copy-paste Dashchan's captcha? It works and looks great.

**Comment by Adamantcheese** [comment]
Copy-pasting code and integrating it is not that easy and don't ever assume it to be. That being said the next update will default the new captcha to off.

**Comment by floppyD** [comment]
I mean, not literally copy-pasting, but mimicking it's aesthetics and taking a look and seeing how it works, so you can implement something similar.
