### ISSUE TITLE
Missing boards on lainchan/arisuchan

### ISSUE THREAD

**Issue by ownBard** [Adamantcheese/Kuroba#110]
**lainchan:** /mega/, /culture/, /psy/, /random/
**arisuchan:** /all/

(They're all overboards actually)

**Comment by Adamantcheese** [comment]
/all/ and /random/ don't provide a catalog.json, and since nobody knew how to do it then, nobody knows how to do it now; https://github.com/Floens/Clover/pull/506
The rest have been added.
