### ISSUE TITLE
[Feature Request] streamable.com link title

### ISSUE THREAD

**Issue by stradus64** [Adamantcheese/Kuroba#1100]
Much like for youtube the same functionality of displaying video title instead of link could be added for streamable.com like it's done in 4chanX userscript

**Comment by Adamantcheese** [comment]
Notes for anyone: https://support.streamable.com/api-documentation
Use the second API call, and "title" may be an empty string, in which case probably just use the URL like youtube videos.
Doesn't appear to be any API limitations or special stuff unlike Youtube otherwise.
