### ISSUE TITLE
Report "Sending a crash report breaks settings"

### ISSUE THREAD

**Issue by K1rakishou** [Adamantcheese/Kuroba#1101]
UUID: 767b0f065b6b289b0f499f002eee131a
Build flavor: dev
Version name: v4.13.6-e8c8c15
OS info: Android 10, sdk version: 29
Report description: When you send a crash report and try to use settings, you are sent to the empty crash reporting screen and pressing Back sends you to the threads list with no way to access settings until app restart
Logs:
No logs attached

**Comment by Adamantcheese** [comment]
I'd assume that the steps to reproduce would've been:
1) Send a crash report.
2) Press back before the sending is finished.
3) Be sent to an empty crash reporting screen.

But that didn't do it. I've removed the onBack stuff from LoadingViewController as that was used for some previous stuff, but even then I still don't get that empty crash reporting screen that's reported. Dunno honestly.
