### ISSUE TITLE
[serious] removing filters does not work

### ISSUE THREAD

**Issue by tidux** [Adamantcheese/Kuroba#1104]
I disabled a filter that was hiding several posts I wanted to read, but they did not reappear.  I completely removed all filters but the posts did not reappear, and I can not force Kuroba to display them. v4.13.6, Android 7.

**Comment by tidux** [comment]
Completely removing the application's data and starting from scratch still results in these posts being hidden.  This appears to be a bug with the filtering regex engine itself.

**Comment by tidux** [comment]
This is fixed in the latest dev apk.  Please do not close this issue until a new release has been published.

**Comment by Adamantcheese** [comment]
It would be nice if you posted the filter at fault and the post in question, because I'm thinking you're misunderstanding something about how filters work.

**Comment by tidux** [comment]
Deleting all app data from disk did not fix it, so it wasn't any filter I'd added.

**Comment by Adamantcheese** [comment]
If you have no filters, it's not an issue with filters. Either it's #968 again, which I have no solution for, or it's #931, which it probably isn't. You need to provide me more information otherwise I'm just going to close this and tell you to double check your filters.

**Comment by tidux** [comment]
looks like it's #968 again except it also hits any post in the same thread with the same text as OP, which made me think filtering

**Comment by Adamantcheese** [comment]
Closing as dupe for now.
