### ISSUE TITLE
Minor UI glitch

### ISSUE THREAD

**Issue by floppyD** [Adamantcheese/Kuroba#111]
The square thing in the gif
![ScreenRecord-2019-06-20-13-01-33](https://user-images.githubusercontent.com/29208110/59863841-f1d3b000-935b-11e9-858e-159cfd21397d.gif)

**Comment by floppyD** [comment]
Forgot to mention that this was only happening in that thread, for some reason.

**Comment by Adamantcheese** [comment]
There's no actual bug here, taking a look at it again. It's the white image behind briefly showing through while the replies load.
