### ISSUE TITLE
Filecache injection exception

### ISSUE THREAD

**Issue by hockeymikey** [Adamantcheese/Kuroba#1111]
App doesn't load. Tested dev and stable.
`
10-02 00:27:43.051 E/Kuroba-dev | UNCAUGHT(4894): Caused by: org.codejargon.feather.FeatherException: Can't inject field fileCacheV2 in com.github.adamantcheese.chan.ui.helper.ImagePickDelegate
10-02 00:27:43.051 E/Kuroba-dev | UNCAUGHT(4894): 	at com.github.adamantcheese.chan.Chan.inject(Chan.java:86)
10-02 00:27:43.051 E/Kuroba-dev | UNCAUGHT(4894): 	at com.github.adamantcheese.chan.ui.helper.ImagePickDelegate.<init>(ImagePickDelegate.java:84)`

Phone posting but should be the relevant bits.

**Comment by hockeymikey** [comment]
I suspect this may be an issue with my rom. Okhttp complains about conscrypt not being found either and gapps crashes due to a similar message with a shared library of theirs.

**Comment by K1rakishou** [comment]
@Adamantcheese I recommend you to use this fork of Feather which actually prints the original exception when it crashes during the injection. 

https://github.com/K1rakishou/Kuroba-Experimental/blob/develop/Kuroba/app/build.gradle#L321

**Comment by hockeymikey** [comment]
> @Adamantcheese I recommend you to use this fork of Feather which actually prints the original exception when it crashes during the injection.
> 
> https://github.com/K1rakishou/Kuroba-Experimental/blob/develop/Kuroba/app/build.gradle#L321

Thanks man, did just that. Turns out dumb error should've enabled storage permission. Why doesn't the app ask for the permission? And why is this a problem in a recent build of the rom but not older ones?
