### ISSUE TITLE
Image rotation (bug)

### ISSUE THREAD

**Issue by ghost** [Adamantcheese/Kuroba#1112]
If I tap the screen while an image is loading, it will be rotated 90° clockwise when it finishes. I can't find any way to change it back other than closing the image and opening it without tapping the screen.
Example:
https://i.imgur.com/6XcGPMJ.png
Tested on the latest dev build using a Samsung Note 10 Plus

**Comment by Adamantcheese** [comment]
You're triggering the two finger tap-rotate gesture.

**Comment by ghost** [comment]
How does it work? It doesn't seem intuitive at all.

**Comment by Adamantcheese** [comment]
On an image that's in an "idle" state (no gestures currently being processed), put one finger down and tap the other one; you can do that with a claw-like grip on your phone that's super uncomfortable, or just use two hands, one to hold one finger down and the other to tap and rotate the image. Or you can tap two fingers at a time, which kinda requires two hands anyways.

**Comment by ghost** [comment]
Thanks. That makes a lot of sense.
