### ISSUE TITLE
[BUG/DEV] Post progress spinner and post success message prevent opening side menu or post replies

### ISSUE THREAD

**Issue by Astridchan** [Adamantcheese/Kuroba#1116]
On dev build when you post a reply the post progress spinner and post success message (the emoji guy) that appear at the bottom "lock" up the UI, meaning that while they are visible you can't slide out the sidebar menu or tap on post replies.

Bug in action:
https://streamable.com/lp6xbg

**Comment by Adamantcheese** [comment]
This is intentional to prevent any more of the "wrong loadable" type issues. I can lower the time that things are locked, currently it's 2.15s. I can also get rid of the locking but I don't know if things will start breaking as a result. They shouldn't from what I've examined, but I don't know.

**Comment by Astridchan** [comment]
Having to wait any amount of time is kind of annoying tbh, before you could just tap to post and immediately switch to another thread and you'd just get a "post successful" toast when the post went through in the background. It's especially bad if you've got a poor internet connection or you're uploading a larger file and you're stuck waiting for the post to go through.

>"wrong loadable" type issues.

Which issues were those, the one where replies were getting posted to the wrong thread?

**Comment by Adamantcheese** [comment]
Yeah those issues. I'll take a look.

**Comment by Adamantcheese** [comment]
I've got it set up now that if you're viewing the reply window, you'll get the animation, but if you're not, you'll get a toast saying that you've either posted a new thread or a reply, and the exact thread it was posted in (by thread title, or if missing, the board and thread number).
