### ISSUE TITLE
No boards on 8kun

### ISSUE THREAD

**Issue by ajasibleydeprecated** [Adamantcheese/Kuroba#1119]
When a 8kun is added and you go to configure boards and press the plus icon no boards show up so none can be added. On pixel 4a

**Comment by Adamantcheese** [comment]
Because 8kun has "infinite" boards, you'll need to search for the board you want.
This is a carryover from 8chan, which also had the same "infinite" board count, but instead of like 500ish boards it had 18,000. That was causing serious issues due to how much junk was being stored in the database.
