### ISSUE TITLE
Report "import feature"

### ISSUE THREAD

**Issue by K1rakishou** [Adamantcheese/Kuroba#1124]
UUID: 2095ed30d49106147daf7d5e675244d7
Build flavor: stable
Version name: v4.13.6
OS info: Android 7.0, sdk version: 24
Report description: on import, program gives an error.
is there any other way to backup interesting threads ?
I tried using the download threads button to copy the json on the computer but when I put it in Kuroba "downloaded threads" folder again, it won't appear

**Comment by Adamantcheese** [comment]
Thread downloading has been removed. Bizarre troubleshooting strategy from the reporter.
