### ISSUE TITLE
YouTube link styling out of bounds

### ISSUE THREAD

**Issue by erwinkramer** [Adamantcheese/Kuroba#1128]
![Screenshot_20201026-202751](https://user-images.githubusercontent.com/4255748/97219211-f5860b00-17c9-11eb-87a1-afe5ed5dee8a.png)

The YouTube hyperlink continues where it has to stop. Found in the following post: https://boards.4channel.org/g/thread/78394346#p78395258

**Comment by Adamantcheese** [comment]
Closed with https://github.com/Adamantcheese/Kuroba/commit/4db62be191f07ad4a34bc7b67a80419dd599bbfe and https://github.com/Adamantcheese/Kuroba/commit/5d07496a69fe0425b1d27b29ee671736834efa25.
