### ISSUE TITLE
Add option to hide bookmarked threads from catalog. 

### ISSUE THREAD

**Issue by stradus64** [Adamantcheese/Kuroba#113]
Not like filter hide which still shows part of OP text but completely make bookmarked threads not show in catalog.

**Comment by ownBard** [comment]
But why?

**Comment by stradus64** [comment]
If I already have it bookmarked why have a duplicate in catalog? I sometimes question if I even bookmarked it since on desktop I use css to display: none watched threads from catalog.
Say you bookmarked half a board, why have to dig through catalog to find new ones when you can just hide them and have a clean view of new threads

**Comment by ownBard** [comment]
Oh, why not just select "Remove" once you've bookmarked it? That removes it from your catalog.
