### ISSUE TITLE
About filtered posts showing up on replies

### ISSUE THREAD

**Issue by aandaan** [Adamantcheese/Kuroba#1132]
Filtered posts show up on replies to another post.
![Screenshot_20201030-172724__01](https://user-images.githubusercontent.com/73605377/97710532-4b61f800-1ad5-11eb-9754-3eba70124f7e.jpg)

What my filter looks like 
![Screenshot_20201030-173022__01](https://user-images.githubusercontent.com/73605377/97710923-d511c580-1ad5-11eb-8bee-ee54ed777d00.jpg)

Am I doing anything wrong here?

**Comment by Adamantcheese** [comment]
Duplicate of #447.
