### ISSUE TITLE
Support Hispachan

### ISSUE THREAD

**Issue by kensolano** [Adamantcheese/Kuroba#1133]
It would be great if hispachan.org could be supported

**Comment by Adamantcheese** [comment]
Sites are supported on a PR basis.

**Comment by kennethsg** [comment]
> Sites are supported on a PR basis.

What's a PR ?

**Comment by lewri** [comment]
This one is a dupe of #894 no?

**Comment by kensolano** [comment]
> This one is a dupe of #894 no?

Yes, it's a duplicate, sorry for not checking. I don't know to search issues
