### ISSUE TITLE
[BUG] Thumbnails occasionally failing to load in catalog and in threads

### ISSUE THREAD

**Issue by Astridchan** [Adamantcheese/Kuroba#1135]
When scrolling the catalog or threads you occasionally come across a thread/post where the thumbnail failed to load. Scrolling up and down makes the thumbnail appear again. I'm not 100% certain but it seems that when a thumbnail fails to load it's always a thread with a YouTube link.

https://streamable.com/6gq4sn

On the latest dev build but the issue has been happening for some time already.

**Comment by Adamantcheese** [comment]
I'm aware of the issue, it is a result of embedding engine changes. Happens with any post that has embedding, not just youtube. Pretty sure the invalidate function I've currently got set up has some issues with it.

**Comment by Astridchan** [comment]
Unfortunately it looks like this didn't get fixed with the commit, thumbnails are still failing to load on the latest dev build, now it's also threads that don't have any links to embed.

![1604691533544](https://user-images.githubusercontent.com/40862101/98407654-b2088800-2078-11eb-8130-df6122353b97.jpg)
