### ISSUE TITLE
Please add Koruba to Huawei AppGallery

### ISSUE THREAD

**Issue by kensolano** [Adamantcheese/Kuroba#1137]
Please add Koruba to Huawei AppGallery
or at least add it to Aptoide or APKPure so it gets automatically updated with Petal Search (which takes updated APKs from other sources)

**Comment by Adamantcheese** [comment]
\>huawei

I've submitted it to APKPure (who uses that anyways?) but if it doesn't get accepted whatever.
A better option is FDroid with the alternate repo listed in #134, which has the application in there already. And the app has an updater built in anyways.

**Comment by kensolano** [comment]
> >huawei
> 
> I've submitted it to APKPure (who uses that anyways?) but if it doesn't get accepted whatever.
> A better option is FDroid with the alternate repo listed in #134, which has the application in there already. And the app has an updater built in anyways.

Remember US government filled a ban for Huawei. Models like P40 Pro have the best camera, superb battery life, the processor is a beast. It doesn't have Google Services though.

As these phones have no Google Play from Google, they have Huawei AppGallery. Not everything is there so they invented **Petal Search**; a search engine app that searches for APKs from other sources and keeps them updated without the need of Google Play Store.
