### ISSUE TITLE
Report "Feature request - Low res thumbs on index/catalog mode"

### ISSUE THREAD

**Issue by K1rakishou** [Adamantcheese/Kuroba#1139]
UUID: bac9064a7567300765bb3e6ddbc12d4f
Build flavor: stable
Version name: v4.13.6
OS info: Android 10, sdk version: 29
Report description: I've been using Clover for years but recently I decided to give Kuroba a try, the only issue I've faced so far is that index/catalog view lags really bad while it's perfectly fine on Clover, and have always been since I was on KitKat on a Nexus 5, so I assume the issue is caused by the higher res thumbnails. So could you put some option to use low res thumbs instead? Thanks

**Comment by Adamantcheese** [comment]
Duplicate of #1015.
