### ISSUE TITLE
Material Design 2

### ISSUE THREAD

**Issue by pkly** [Adamantcheese/Kuroba#115]
Please revamp the UI at some point by using the newest guidelines to make it look more modern.
I'd look into it but I can't into android development.

It's been ages since material design was introduced and Google is already moving onto the next version of it, which looks differently than the current implementation.

Obviously this is a low-priority request, but it'd be nice if you could look into it while implementing new features.

**Comment by floppyD** [comment]
Material version "everything must be round" looks really bad. I prefer new features and having current bugs fixed.

**Comment by pkly** [comment]
Get on with the times, gramps

**Comment by Adamantcheese** [comment]
I'm the worst person to ask about UI overhauls. UX I can do, UI I can't. I'll leave this open if someone else wants to take a crack at it. There's a lot of custom stuff that would likely need to be heavily changed in order to do it.

**Comment by ownBard** [comment]
Let's please not decide by upvotes and downvotes.

**Comment by Adamantcheese** [comment]
On second consideration, I'm closing this. It would be far too much work to do a total revamp, and if I were to do that, I would use some of the better UI methods that should probably be used for Android development. Basically, if you want to revamp the UI for Material Design 2, make a fork and do it yourself, as I likely won't merge it.
