### ISSUE TITLE
Page count bugged?

### ISSUE THREAD

**Issue by ghost** [Adamantcheese/Kuroba#1162]
I noticed the page count on /v/ threads wasn't showing up. Restarting the app fixed this, but it makes me wonder if something in the code caused the feature to stop working since the other thread metrics were originally part of clover but this wasn't

Tested on v.4.13.6-f6d50ef on a Samsung Note 10 Plus

**Comment by coggy9** [comment]
Noticing the same thing on a OnePlus 7T on Android 11.
App version v4.13.6

**Comment by Adamantcheese** [comment]
Everything's working fine on my end. If there's no info to display, like the pages call failed for whatever reason, it should say in the log and it'll retry again in a few minutes. Can't display info you don't have after all.

**Comment by ghost** [comment]
I guess that makes sense. Still I find it odd that it's only started happening very recently.
It seems to succeed or fail at random so maybe it is just the server's fault

**Comment by ghost** [comment]
This still sorta happens
![Screenshot_20211224-181757.jpg](https://user-images.githubusercontent.com/30278765/147376132-332503fd-03f0-4002-88bb-e3680bc7f2ac.jpg)
