### ISSUE TITLE
A couple weird things that happen after update

### ISSUE THREAD

**Issue by ghost** [Adamantcheese/Kuroba#1163]
I've noticed that by site/board list is cloned 9 times. Meaning 4chan and all of its boards keep scrolling down forever. This is fixed on app restart but only started happening a few updates ago.
Also the threads in board mode start offset to the right and don't render in the proper location until I scroll or open a menu.

Tested on v.4.13.6-d791574 on a Samsung Note 10 Plus

**Comment by Adamantcheese** [comment]
I'd like screenshots, if possible. Your description is too vague to pinpoint where the issue is located, be it the floating menu, the setup menu, or elsewhere.

**Comment by ghost** [comment]
I'll show you what I mean when the app gets updated next. Basically when you scroll down the board list to change boards it normally stops at the bottom, but it's like 4chan and all the boards I have added count as multiple sites. This only happens in that menu as far as I know.

Edit: I updated manually and it didn't happen this time. I guess I can't do anything until it happens again. Also edited for clarification of the issue.

**Comment by ghost** [comment]
I still don't have any clue what triggers it, but I got the site doublung glitch again. I can add or remove boards and it stays active.
https://imgur.com/a/9Z1vUqf

**Comment by Astridchan** [comment]
I can confirm this bug and found a way to reproduce it:
https://streamable.com/gbts54
