### ISSUE TITLE
Major lag spikes when opening app

### ISSUE THREAD

**Issue by ghost** [Adamantcheese/Kuroba#1165]
Either by tapping a thread watcher notification or switching back to the app from another one, I get about 5-6 seconds of lag where nothing happens on screen no matter what I do.

Tested on v4.13.6-15deaa9 using a Samsung Note 10 Plus

**Comment by Adamantcheese** [comment]
Works fine for me, any additional info might be nice to know I guess?

**Comment by ghost** [comment]
I don't know much, but it happens without fail. Maybe refreshing the thread is running into an error?

**Comment by Adamantcheese** [comment]
If you want, you can export your settings/pins/whatever and I can load that to see possible issues, which would probably help with the other "can't repro" issues you've been posting as well.

**Comment by Adamantcheese** [comment]
Yeah I see what you mean now.

**Comment by Adamantcheese** [comment]
Let me know if this still is happening, because I think that this was an issue resulting from #1163, after a few app open/closes.

**Comment by ghost** [comment]
It hasn't been happening recently. Not that it was particularly common before, though. It just wouldn't go away after it started.

**Comment by Adamantcheese** [comment]
Alright, let me know in about a week or two if it's still occurring then. Pretty sure it's fixed.

**Comment by ghost** [comment]
Gotcha. Also I noticed that exporting settings gives out your 4chan pass login, which I think is pretty sensitive data. Could that be changed?

**Comment by Adamantcheese** [comment]
It's just exporting the entire shared preferences file, of which one is the login. I guess the proper way is probably to use [Android's keystore like in this link](https://www.apriorit.com/dev-blog/432-using-androidkeystore), but for the time being just treat backups like you would any other sensitive piece of information.

**Comment by ghost** [comment]
It looks like this is fixed, though I have had some app freezes that were probably unrelated.

**Comment by Adamantcheese** [comment]
Cheers, closing.
