### ISSUE TITLE
Scrolling down causes posts to "bounce"

### ISSUE THREAD

**Issue by ghost** [Adamantcheese/Kuroba#1168]
This one is hard to explain, but there's basically a visual bug where some posts scroll up faster than others and then bounce back to where they should be. It went away on its own, but it was very odd. It also happens when making a post, so it could be related to that.

Tested on v4.13.6-15deaa9 using a Samsung Note 10 Plus

**Comment by Adamantcheese** [comment]
Probably just something being embedded. Again, without a method of reproduction or any sort of visual proof, I can't really do anything about it because I've never experienced it.

**Comment by Astridchan** [comment]
I think this is the bug in question:
https://streamable.com/17ba8n
