### ISSUE TITLE
[Feature request] Support pasting images from clipboard

### ISSUE THREAD

**Issue by Astridchan** [Adamantcheese/Kuroba#1169]
Chrome (and probably other apps too) has the option to copy an image (rather than the image URL) to the clipboard. 

![1605875454116](https://user-images.githubusercontent.com/40862101/99800962-e6327d00-2b3d-11eb-96a8-ec206e796cb2.jpg)

However pasting it to Kuroba does not work because the app is expecting an URL rather than an image (I think this is what the user from issue #1167 was trying to do). Copying an image takes a couple less taps than copying the image URL in Chrome so it would be nice if pasting an image directly was supported.

Also, Gboard (the default keyboard on a lot of Android phones) has a clipboard manager feature, when you try to paste an image from there (by tapping on the image) it gives the following message:

![1605875454112](https://user-images.githubusercontent.com/40862101/99801197-4c1f0480-2b3e-11eb-8a0c-42b854178551.jpg)

**Comment by Adamantcheese** [comment]
I'm going to put this here and say that if you want it, PR it. https://developer.android.com/guide/topics/text/image-keyboard.html#adding_image_support_to_apps
