### ISSUE TITLE
Error posting 

### ISSUE THREAD

**Issue by dascar5** [Adamantcheese/Kuroba#1171]
Throws this error when I try to post, tried both new and old racaptcha, works through browser. What's up?

**Comment by Adamantcheese** [comment]
You're gonna have to provide more information than that. There's so many possible things that could be going wrong, and I can assure you that posting does work.

**Comment by dascar5** [comment]
Yeah I understand that, however, my logs are empty, and reinstalling the app didn't help.

**Comment by Adamantcheese** [comment]
Does it just say "Error posting" or does it say "Error posting \<extra stuff\>"?

**Comment by dascar5** [comment]
> Does it just say "Error posting" or does it say "Error posting \<extra stuff\>"?

https://ibb.co/Q9wTLQc

**Comment by Adamantcheese** [comment]
Yeah I don't think I can be of any help. As you can see, I posted a test post just fine on that thread.

**Comment by dascar5** [comment]
I saw it. Does this help?

I/Kuroba | WakeManager: Started background alarm with an interval of 15 minutes
E/Kuroba | ReplyPresenter: onPostComplete error

**Comment by Adamantcheese** [comment]
Unfortunately it doesn't, as that information is exactly the same as what's presented to the user in the error message.

**Comment by Adamantcheese** [comment]
It's possible that the app wasn't catching the error, so if anything's changed (and you're using dev) then let me know. Otherwise I'll close this in a week or so as something I have no control over.
