### ISSUE TITLE
Report "Issue a new release pls"

### ISSUE THREAD

**Issue by K1rakishou** [Adamantcheese/Kuroba#1173]
UUID: 32e4d11e9ec9202fabf950a112e3b202
Build flavor: stable
Version name: v4.13.6
OS info: Android 10, sdk version: 29
Report description: For some reason Android doesn't allow moving dev versions to internal storage when I'm using adopted storage, so I'm stuck with the latest release (turns out performance isn't really great when running from a SD). There has been months now, and the tap on post number to reply is still painful, pretty please.

**Comment by Adamantcheese** [comment]
![image](https://user-images.githubusercontent.com/9031585/100038099-446a9480-2db8-11eb-9911-31b50bf9128f.png)
