### ISSUE TITLE
thumbnail for deleted images gets cropped in catalog mode

### ISSUE THREAD

**Issue by Astridchan** [Adamantcheese/Kuroba#1175]
Since thumbnails in catalog mode aren't exactly square the text from the file deleted thumbnail gets cropped out:

![1606147768500](https://user-images.githubusercontent.com/40862101/99986434-d6be6880-2db7-11eb-986f-26f26f74d00f.jpg)

**Comment by Adamantcheese** [comment]
Closed with https://github.com/Adamantcheese/Kuroba/commit/b498c32b5565bdada89559ef9a077480e480ffd2, looks good pretty much anywhere now, even in pin thumbnails.
