### ISSUE TITLE
No pull down to refresh (dev)

### ISSUE THREAD

**Issue by ghost** [Adamantcheese/Kuroba#1185]
I just updated and it looks like this broke. Or was it removed?
Tested on v4.13.6-2f8bde2 on a Samsung Note 10 Plus

**Comment by ghost** [comment]
Oh, it looks like this was just fixed. Nevermind.

**Comment by Adamantcheese** [comment]
Yeah I noticed it during some changes but forgot to fix it. Easy fix though.
