### ISSUE TITLE
Report "[Feature request] Turn the "Bookmarked threads" area into a search bar"

### ISSUE THREAD

**Issue by K1rakishou** [Adamantcheese/Kuroba#1186]
UUID: 2740a86ebb0a70729023638f2a546dd4
Build flavor: dev
Version name: v4.13.6-6ddbf11
OS info: Android 10, sdk version: 29
Report description: would look better

**Comment by Adamantcheese** [comment]
This already exists. Given the person is on dev, either they didn't actually try it, or they can't explain what they want.
