### ISSUE TITLE
Clicking a thread in the catalog instead of selecting an archive

### ISSUE THREAD

**Issue by ghost** [Adamantcheese/Kuroba#1193]
I noticed on a deleted thread, that when I tried to select an archive through the popup it instead sent me to an active thread. It seems like while it's loading there's a moment where it acts like I'm still in the board menu.

Tested on v4.13.6-fcb7afe on a Samsung Note 10 Plus

**Comment by Adamantcheese** [comment]
If you haven't noticed, archives are in-app now. If the bottom bar doesn't have a loading time, you are in an archive; also some functions are disabled in an archived thread.

**Comment by ghost** [comment]
I'm not sure if we're on the same page here. I'm saying after you say you want to view the external archive in the app but before the site selection is loaded, the catalog is selectable. So you can accidentally click a different thread when you just wanted to see the archived version of a deleted one.

**Comment by Adamantcheese** [comment]
I honestly don't understand what you're trying to explain. A video would help.

**Comment by ghost** [comment]
This image should sum it up.
What I did was I loaded a deleted thread, pressed the button to see an archive, and tapped the screen before the popup was loaded. Either the popup doesn't show up at all, or it loads on top of an active thread.

![Screenshot_20201214-195811.jpg](https://user-images.githubusercontent.com/30278765/102158277-bc236080-3e46-11eb-83d2-89c4515acfa0.jpg)

Whereas normally it should stay on the blank background
![Screenshot_20201214-200052.jpg](https://user-images.githubusercontent.com/30278765/102158478-2805c900-3e47-11eb-8564-00550084269f.jpg)

**Comment by Adamantcheese** [comment]
Oh I see what the problem is. I thought I solved this with https://github.com/Adamantcheese/Kuroba/commit/bb2d7ef651cb98369493e96117d8fa4665033500, but I guess I didn't do the error layout.
