### ISSUE TITLE
App sometimes freezes on reopen

### ISSUE THREAD

**Issue by ghost** [Adamantcheese/Kuroba#1194]
May or may not be related to #1165, but I've had a lot of complete freezes with the app, and it seems like it also slows down my phone as a whole when I try to open it and it does this. I usually have to wait for android to notice it isn't responding and force quit.
I don't have the issue where it lags anymore, this is more extreme, but I'm starting this issue because it now seems about as common.

Tested on v4.13.6-3f39897 on a Samsung Note 10 Plus

**Comment by Adamantcheese** [comment]
It's unrelated, I've had this happening even since Clover. Usually my fix has been to lock my phone and unlock it again. No idea how or why it does it though.

**Comment by Astridchan** [comment]
I'm also facing frequent freezes when reopening the app, I'd estimate it happens couple of times a day. It even partially freezes/locks the OS to my home screen or just a black screen, I have to swipe open the notification slider to get to the settings and only then I can open the recents view to force close Kuroba.

I've only recently started seeing this happen on the dev build (past few weeks to a month maybe) so I don't think this is some old Clover bug, or if it is then some recent change has made it occur significantly more frequently.

**Comment by gut5** [comment]
It does this every time for me in a reproducible way, using the dev version. Android 11 on a Pixel 2.

**Comment by dronewizard** [comment]
I have noticed this recently (but very rarely) as well.

**Comment by ghost** [comment]
I'm on dev branch and this also happens shortly after updating the app. A force close always fixes it though.

**Comment by Adamantcheese** [comment]
Seems that my dev pipeline broke for a day or two, but please let me know if this is fixed now; I suspect it was fixed by f94b4f61eac936ce734d5b2e78249a0c333c3369. I suspect that Android was killing the activity for resources, aggressively on some phones it seems.

**Comment by gut5** [comment]
All good now, thanks

**Comment by Adamantcheese** [comment]
@dronewizard @clawyf @Astridchan can any of you confirm as well?

**Comment by ghost** [comment]
@Adamantcheese No freezes so far on latest dev build. Bravo.

**Comment by ghost** [comment]
> can any of you confirm as well?

Probably? At least it didn't freeze after updating, which it usually would.

**Comment by Adamantcheese** [comment]
Alright, I'll leave this open until tomorrow just in case it still occurs. Looks good though.

**Comment by Astridchan** [comment]
I haven't experienced any freezes either since updating.

**Comment by Adamantcheese** [comment]
Cheers, closing then.
