### ISSUE TITLE
Report "Question"

### ISSUE THREAD

**Issue by K1rakishou** [Adamantcheese/Kuroba#1197]
UUID: 486d816efd28780c96ea2048eff7241c
Build flavor: dev
Version name: v4.13.6-c9337e0
OS info: Android 10, sdk version: 29
Report description: Why do dev thumbnails look worse than stable? If you did it for performance reasons, can you make it optional under settings?

**Comment by Adamantcheese** [comment]
Uhh they look the same? Maybe some positioning changes but that's about it. Dunno what this person is complaining about.

**Comment by K1rakishou** [comment]
Question (cont.)
UUID: ef73d25a2c1a6102dd923c99125f5629
Build flavor: dev
Version name: v4.13.6-6c39e65
OS info: Android 10, sdk version: 29
Report description: Hi, I'm the guy that posted the #1197. They are clearly not the same, see. It's really noticeable even in small thumbs
https://imgur.com/a/yNSgShX

**Comment by ghost** [comment]
This guy must be using media pre-fetching, which seems to be broken in catalog mode on the dev version. I tested it out myself and got the same results.
So it's actually not that the thumbnails look worse, it's just that the dev version shows thumbnails when it isn't supposed to.

**Comment by ghost** [comment]
While testing out pre-fetching, I noticed some odd behavior. When you open an image it flickers between the high quality prefetched thumbnail, a lower quality version, and back to high quality again. But, sometimes it just gets stuck on the lower quality so there's this jarring downgrade in quality. Perhaps related to #1071/#1184?

**Comment by Adamantcheese** [comment]
Probably; for now this is somewhat better, but still not perfect.

**Comment by Adamantcheese** [comment]
As for the flicker thing it's how the image viewer works, by setting the image state to load a thumbnail first. I did try to make it not do that when full-size stuff was enabled, but I had a number of issues that just weren't worth it for the time. Maybe later.
