### ISSUE TITLE
[Really fucked up bug] Posts with "since4pass" crash the whole app

### ISSUE THREAD

**Issue by floppyD** [Adamantcheese/Kuroba#120]
Any post with since4pass on the thread will crash the app.

**Comment by Adamantcheese** [comment]
Yeah I'm dumb but I fixed it earlier; I'll release a build in a little bit to fix it. See https://github.com/Adamantcheese/Kuroba/commit/8d5263865cc2032cc733e4c0cee0f256751242e1
