### ISSUE TITLE
Report "External archive images not showing up"

### ISSUE THREAD

**Issue by K1rakishou** [Adamantcheese/Kuroba#1200]
UUID: bf4143309f9980eec3e6b5e14f8425c7
Build flavor: dev
Version name: v4.13.6-6c39e65
OS info: Android 10, sdk version: 29
Report description: When you expand the thumbs it simply says "missing". They are on the archive's website itself, tested with archived.moe and thebarchive.

**Comment by Adamantcheese** [comment]
Archived.moe stores basically no images besides the old april fool's stuff, but thebarchive should have images, so that's a bug.

**Comment by K1rakishou** [comment]
Archived.moe actually gives a real image link (which will point to a different archive site) when you use a real-world user-agent when sending GET request. Otherwise the link will be a redirect link which is probably not supported in the app.

**Comment by Adamantcheese** [comment]
Ah, I see, it's got a remote_media_link field that I'm currently not parsing.

**Comment by ghost** [comment]
I've not been able to get images from arch.b4k.co in the app, either

**Comment by Adamantcheese** [comment]
@clawyf arch.b4k.co doesn't provide images, and the remote media link it does provide isn't even a full http link.

**Comment by ghost** [comment]
@Adamantcheese what do you mean? At least when I use the site in the browser, it seems to have images available.

**Comment by Adamantcheese** [comment]
Gotta love sites not using their APIs correctly. So it does have images stored on the site, but instead of using the media_link field like every other archive, it uses remote_media_link, and also provides a not even correctly formatted relative link to the asset. Bleh.

**Comment by K1rakishou** [comment]
I remember them fixing it, but apparently it broke again.
https://arch.b4k.co/meta/thread/357/

**Comment by Adamantcheese** [comment]
Yeah and arch.b4k.co actually made me find an OkHttp bug with their follow-up interceptors not updating the Host header when it existed. Submitted that bug report to them.
