### ISSUE TITLE
[Suggestion] long press thread stats to open reply menu

### ISSUE THREAD

**Issue by ghost** [Adamantcheese/Kuroba#1202]
I was thinking it's a bit of a hassle to reply when you're at the bottom of a thread and you don't use the reply button, since you have to some gymnastics with your hands if you want to open the reply menu and then go back to typing.
Since long pressing the thread statistics currently doesn't do anything, I thought it might be a convenient place to open the reply menu. Unless it actually does do something, and I never noticed.

**Comment by Adamantcheese** [comment]
No. I'm not doing weird interactions like that. If you want something at the bottom, use the reply button.

**Comment by ghost** [comment]
Ok, that's fair
