### ISSUE TITLE
Report "#1199 is still happening"

### ISSUE THREAD

**Issue by K1rakishou** [Adamantcheese/Kuroba#1208]
UUID: 45d3d75cbe7c21115ca36df59b65887b
Build flavor: dev
Version name: v4.13.6-84252ad
OS info: Android 10, sdk version: 29
Report description: I just got a bookmarked dead thread acting up, when you enter it the bookmark icon is not activated and tapping doesn't change its state.

**Comment by Adamantcheese** [comment]
Closed with https://github.com/Adamantcheese/Kuroba/commit/029de5ac12680b6fdadc1831f9b80631d1dee033
