### ISSUE TITLE
Odd scrolling bug

### ISSUE THREAD

**Issue by ghost** [Adamantcheese/Kuroba#1212]
For some reason when I tried to pull down to scroll up in a thread, it instead refeshed the thread, which from my understanding is supposed to be impossible. It would keep doing this until I scrolled down and then up again.

Tested on v4.13.6-be81d2c on a Samsung Note 10 Plus

**Comment by ghost** [comment]
I'm also having this issue in the board menu. It's relatively often, I think.

**Comment by Astridchan** [comment]
If you try to scroll by tapping on a thumbnail it activates the pull-to-refresh action:
https://streamable.com/weez5p

**Comment by Adamantcheese** [comment]
Closed with https://github.com/Adamantcheese/Kuroba/commit/843e3688c192f7863b34c316704e53e63ce43ab2
