### ISSUE TITLE
Report "Bottom button glitch"

### ISSUE THREAD

**Issue by K1rakishou** [Adamantcheese/Kuroba#1216]
UUID: 2a5f4a5c6eae45c0ebbe8af4592c780b
Build flavor: dev
Version name: v4.13.6-be81d2c
OS info: Android 10, sdk version: 29
Report description: It takes you to bottom then top, it doesn't always behave like that tho
https://streamable.com/012it4

**Comment by Adamantcheese** [comment]
Ah yes, this classic shit again. I'm just gonna close this and hope some random thing I do fixes it eventually.
