### ISSUE TITLE
[Feature Request] Throw error when trying to upload unsupported media type

### ISSUE THREAD

**Issue by maluhia** [Adamantcheese/Kuroba#122]
Scan the extension of a file or MIME type when selected by the image file picker, to ensure it conforms with 4chan before it has uploaded and captcha filled out.

e.g. no uploading PDF, or image files over 4MB on certain boards, WEBMs with sound or certain boards, VP9, etc.

Keep in mind that some rules are board-specific

**Comment by Adamantcheese** [comment]
Most people know what kinds of files can be uploaded on their respective board(s). And as for WebM, if you downloaded it from a *chan (like you probably have), or have made it yourself, you know whether it's uploadable or not already, with respect to the codec allowed (VP8/VP9). Image limits are already checked, the only suggestion of this bunch that is a good idea to implement is the WebM with sound displaying that it HAS sound somewhere (probably a little icon on top of the preview).
