### ISSUE TITLE
Scrolling in quick reply causes thread to refresh in annoying ways

### ISSUE THREAD

**Issue by ghost** [Adamantcheese/Kuroba#1221]
I assume I'm supposed to be able to scroll up in down in the reply field, and I can a little bit, but it always seems to trigger the thread refresh, when that's kind of completely useless to begin with.
If I tap and hold, I can scroll up, but when I hit the top of the reply field it triggers the refresh, and I can't scross down again until I stop scrolling and tap & hold again since the refresh doesn't go away

Example below, but it's not an easy issue to show with a screenshot
Tested on v4.13.6-be81d2c on a Samsung Note 10 Plus![Screenshot_20210103-041608.jpg](https://user-images.githubusercontent.com/30278765/103476366-8b19ba00-4d7a-11eb-8d22-4979eb49ed20.jpg)

**Comment by Astridchan** [comment]
Duplicate of #1215 I think?

**Comment by Adamantcheese** [comment]
Closed with https://github.com/Adamantcheese/Kuroba/commit/843e3688c192f7863b34c316704e53e63ce43ab2
