### ISSUE TITLE
Quote links slightly interfere with post options menu

### ISSUE THREAD

**Issue by ghost** [Adamantcheese/Kuroba#1222]
Links to other posts seem to not wrap as soon as they should, and it overlaps with the post menu which makes things a bit annoying.
Example below is a guy spamming replies

![Screenshot_20210104-103032.jpg](https://user-images.githubusercontent.com/30278765/103557155-60ae2680-4e78-11eb-9db9-9764a8d19b91.jpg)

**Comment by Adamantcheese** [comment]
The wrapping is controlled by the TextView, and I don't really have that much control over it. It's already using the best wrapping method it has, which breaks at logical points (in this case, a space between the number and (You)). And the post menu thing is so minor that I'm not even going to worry about it.
