### ISSUE TITLE
Wrong thumbnail displayed for some threads in catalog

### ISSUE THREAD

**Issue by Astridchan** [Adamantcheese/Kuroba#1224]
Happening on the recent dev builds:
https://streamable.com/qf07u7

**Comment by K1rakishou** [comment]
Here is another report.

Duplicated images in catalog
UUID: f160ba368d55538e68883c80a273056d
Build flavor: dev
Version name: v4.13.6-b4c45ba
OS info: Android 10, sdk version: 29
Report description: Opening the thread with the wrong image fixes it. Reloading the catalog too.
https://streamable.com/likbre

**Comment by gut5** [comment]
Yep I've experienced this on the latest dev
