### ISSUE TITLE
Infinite Loading Randomly

### ISSUE THREAD

**Issue by seniorm0ment** [Adamantcheese/Kuroba#1226]
Since this morning, all boards, on multiple sites are just infinite loading for me. Was working fine yesterday no issues. Nothing changed to my knowledge. Can access via web browser no issues.
v4.13.6 

Edit: Jan 7th, still an issue. Doesn't seem to be a temporary issue. Still unable to figure out what triggered it. 
Was hoping to avoid reinstalling, but in the case I need to does the export export all watched threads, (You)s, and cached threads?

**Comment by ghost** [comment]
Export takes out pretty much everything (even sensitive stuff) so you should be fine unless your settings are what caused the issue

**Comment by seniorm0ment** [comment]
Just did a reinstall, exported and imported everything. All seems to work now.

Not sure what triggered it again, but I guess it may be best to leave this open because it seems like a bug.

**Comment by gut5** [comment]
~~I had the same problem you described and also tried exporting then importing settings and it has fixed it. I upgraded over several nightly builds so it could be that the settings just got messed up over time somehow.~~
Edit: the infinite loading problem still happens even after exporting/importing the settings and clearing app data.

**Comment by Adamantcheese** [comment]
Sufficiently old and not reproducible.
