### ISSUE TITLE
imageboards other than 4chan cannot be added

### ISSUE THREAD

**Issue by ghost** [Adamantcheese/Kuroba#1231]
i cant add boards on other image boards like 8kun on the app, only 4chan works but 8kun doesnt 
i am on the latest version of kuroba on android 6

**Comment by Adamantcheese** [comment]
8kun's boards are dynamic, so you need to know the board code for the board you want, search for it, and add it when it appears in the list. It's that way because 8chan also had dynamic boards, and using boards.json populated over 19K boards into the database, which made things VERY slow.
