### ISSUE TITLE
New board /vt/ added won't appear

### ISSUE THREAD

**Issue by HNKMaster** [Adamantcheese/Kuroba#1237]
Just now there's a new board (/vt/) and it doesn't appear on the app, even when force stopping it and restarting the phone.

**Comment by Adamantcheese** [comment]
Duplicate of #1032. It's working fine, both stable and dev.
![Screenshot_20210129-124434](https://user-images.githubusercontent.com/9031585/106330988-0d41b500-6239-11eb-94f2-cc4b072d4806.jpg)
