### ISSUE TITLE
[Feature Request] Scale the new captcha to fit inside the screen

### ISSUE THREAD

**Issue by happapa** [Adamantcheese/Kuroba#124]
App is currently really unpleasant to use in landscape mode because the new captcha window overflows past the screen. Instead of only making the new captcha match the width of the screen, also constrain it by the height of the screen. 

![Screenshot_2019-06-23-18-15-47-409_com github adamantcheese chan](https://user-images.githubusercontent.com/35754500/59978283-7edc6a80-95e3-11e9-823b-84555444bee4.png)

**Comment by Adamantcheese** [comment]
The verify button is also a little bit bigger and all the buttons should be easier to tap on now as well.
