### ISSUE TITLE
Search menu still doesn't always clear

### ISSUE THREAD

**Issue by ghost** [Adamantcheese/Kuroba#1245]
Sometimes when searching and returning to the board menu, the search bar no longer shows and you can change boards without clearing it, meaning the "found x posts for xxxxxxxx" text stays at the top of the new board even though search isn't being used

Tested on v4.13.6-b4c45ba on a Samsung Note 10 Plus

**Comment by Adamantcheese** [comment]
Closed with 878faca11fe5c30604ec3e696f202717a247ff39
