### ISSUE TITLE
Report "stop using 4chan urls for 4channel sites"

### ISSUE THREAD

**Issue by K1rakishou** [Adamantcheese/Kuroba#1246]
UUID: 22d89839820c7bcb4f0e0a1476376f4c
Build flavor: dev
Version name: v4.13.6-b4c45ba
OS info: Android 7.1.1, sdk version: 25
Report description: I can't post on 4chan. when I click open in browser, it redirects to 4chan instead of 4channel. is the app also using 4channel urls?

**Comment by Adamantcheese** [comment]
The api is still on the 4chan domain. Hiro's nonsense with splitting the site for advertisers lives on I see. 4channel doesn't exist as far as the app is concerned.
