### ISSUE TITLE
[Feature Request] Double tap to reply

### ISSUE THREAD

**Issue by floppyD** [Adamantcheese/Kuroba#125]
Double tap a post and the ID goes to the post field. It could be optional. Way faster than having to tap on the 3 dots thing and selecting "Quote".

**Comment by Adamantcheese** [comment]
Enable "Tap post number to reply" in Behavior.

**Comment by floppyD** [comment]
That's not really the same and really uncomfortable if you are using a large phone single handed. Not to mention that you need some precise aim. Come on Cheese, give this a chance.
