### ISSUE TITLE
Certain images refuse to load correctly

### ISSUE THREAD

**Issue by ghost** [Adamantcheese/Kuroba#1250]
Images that load fine in the browser only partially load. Clearing cache fixes this (force quitting does nothing) so I assume it's a problem with that.
![Screenshot_20210419-005021.jpg](https://user-images.githubusercontent.com/30278765/115187851-a0a4bc80-a0a9-11eb-9ce2-7d7ac01bd70c.jpg)

**Comment by Adamantcheese** [comment]
Closed with #1071. OkHttp's cache guarantees a full cache write or not at all, and all bitmaps must be fully read to decode or fail, so this shouldn't ever occur.
