### ISSUE TITLE
If something is not working...

### ISSUE THREAD

**Issue by ECHibiki** [Adamantcheese/Kuroba#1251]
Can you elaborate on this issue, perhaps post the related logs. I'm downloading the application to see the bug you're talking about.
<img src="https://luna.kissu.moe/b/src/1619261423533.jpg" style="max-width:200px"/>
https://kissu.moe/b/thread/6927

**Comment by Adamantcheese** [comment]
Uh, that wasn't me. I don't go to threads anymore. You'd have to ask that anon what they were doing, because they never submitted a PR with the code or anything so I don't even know what they could've been doing/talking about.

**Comment by ECHibiki** [comment]
hm, alright
