### ISSUE TITLE
[Crash] android.view.InflateException: Binary XML file line #25 in com.github.adamantcheese.chan.dev:layout/cell_post_card: android.widget.RelativeLayout$LayoutParams cannot be cast to android.widget.LinearLayout$LayoutParams

### ISSUE THREAD

**Issue by Astridchan** [Adamantcheese/Kuroba#1256]
I updated to the latest dev build v4.13.6-3e46a81 and it was working fine until I set catalog column count to 1, after that when I opened the catalog and scrolled down a little, the app crashed. Now the app is crashing at start-up so I can't go change the setting back.

Here's the crash log:
https://pastebin.com/hgSX0tzn

I tried rolling back to an older dev build but that also causes crashes on startup, this time with a different error message:
https://pastebin.com/N25705Tz

PS. It's great to have you back!

**Comment by Adamantcheese** [comment]
Yeah you can't rollback to older dev versions if the database version changes; board flags were added into the database so that's why the second one occurs. The first was an oversight on my part.
