### ISSUE TITLE
Proxy port issue

### ISSUE THREAD

**Issue by spectkiller** [Adamantcheese/Kuroba#1262]
It can't set port correctly, the "slider" in port section is only able to set few port which is not feasible at all.

Please remove the slider thing and make it like proxy IP address i.e., manually typing the port instead of adjusting through slider

Also congrats dev, for coming back to development!!

**Comment by Adamantcheese** [comment]
Uh, what port number are you trying to set? The only valid range is 0-65535, which is enforced by InetSocketAddress and what I have the limits set to. Unless you mean to say the UI is confusing somehow, but all the ports that are useable are able to be selected.

**Comment by spectkiller** [comment]
I am trying to set a port 8796 but couldn't do it

**Comment by spectkiller** [comment]
> Uh, what port number are you trying to set? The only valid range is 0-65535, which is enforced by InetSocketAddress and what I have the limits set to. Unless you mean to say the UI is confusing somehow, but all the ports that are useable are able to be selected.

I am trying to set a port 8796 but couldn't do it

**Comment by Adamantcheese** [comment]
Ah, I see the issue is that the progress bar doesn't have the resolution for this case. Understandable, I'll fix that right up.
