### ISSUE TITLE
Removing or hiding threads refreshes whole catalog

### ISSUE THREAD

**Issue by Astridchan** [Adamantcheese/Kuroba#1265]
When you remove or hide a thread in the catalog the whole catalog refreshes. It didn't use to happen on older builds, v4.13.6-2ac77078 is the last dev release without this behaviour.

**Comment by Adamantcheese** [comment]
Correct, 00cd1fb80dbc3d8abe584bde9a2517562498c5e6 adding in a temporary change to fix visual inconsistencies. I suppose I accidentally forgot about it for a time, my bad!
