### ISSUE TITLE
Thumbnails for new posts don't appear unless threads are reloaded

### ISSUE THREAD

**Issue by ghost** [Adamantcheese/Kuroba#1272]
I don't believe I have any fancy settings that should be causing this. The area where the thumbnail is for new posts just appears black, then when I click on it the image opens as normal. 

Tested on v4.13.6-d80cc17 on a Samsung Note 10 Plus

**Comment by ghost** [comment]
Interestingly if these posts happen to be replies, the thumbnail does load in the reply menu.
Also, any posts that I make are inherently affected.

**Comment by Adamantcheese** [comment]
Yeah I'm getting kinda annoyed with RecyclerView's inconsistency with re-drawing stuff since it seems to stem from that.
