### ISSUE TITLE
Report "Image hash filters only hide or remove the image, not entire post"

### ISSUE THREAD

**Issue by K1rakishou** [Adamantcheese/Kuroba#1282]
UUID: 928ad814414093f851587a0e30adf7a0
Build flavor: dev
Version name: v4.13.6-e8231d5
OS info: Android 11, sdk version: 30
Report description: not sure if this is intended behavior, but maybe an extra checkbox option would be nice to specify to remove the entire post

**Comment by Adamantcheese** [comment]
Under Behavior. 
![image](https://user-images.githubusercontent.com/9031585/119916254-0857ee00-bf19-11eb-932a-282ad1fdd787.png)
