### ISSUE TITLE
Report "Signing out of 4chan Pass"

### ISSUE THREAD

**Issue by K1rakishou** [Adamantcheese/Kuroba#1287]
UUID: 3e7fcdf201eb30ff4bf72670ae0da345
Build flavor: dev
Version name: v4.13.6-4005c9f
OS info: Android 9, sdk version: 28
Report description: Noticed it was already reported in #1269 and fixed, but the issue still persists. Logging out of a Pass keeps you logged in

**Comment by Adamantcheese** [comment]
Double checked everything again, working fine for me.

**Comment by ghost** [comment]
I keep getting signed out, can still log out if I want to though

**Comment by Ashtonio** [comment]
This is happening to me since updating to the newer dev builds, I'll sign out of the pass but whenever I leave the screen it'll say I'm logged in still.

**Comment by Ashtonio** [comment]
Found a way to go around the non logging out problem, there's an app called Multiple Accounts where you can clone an app and have a completely different instance of it running alongside the original. I one version of Kuroba with the unable to log out Pass version and another where it isn't logged in, kinda annoying but beats waiting 15 mins for the pass to change to the new IP.
