### ISSUE TITLE
Report "Messages with fortunes are broken on [s4s]"

### ISSUE THREAD

**Issue by K1rakishou** [Adamantcheese/Kuroba#1291]
UUID: 8375b624b453b6b0db8b7083839a553a
Build flavor: dev
Version name: v4.13.6-52ebe48
OS info: Android 10, sdk version: 29
Report description: Color codes and other stuff gets added to the end of the posts, see the example thread:
https://boards.4chan.org/s4s/thread/9677565

**Comment by Adamantcheese** [comment]
Everything is working as expected? Here's a comparison of Kuroba stable vs dev. Don't know if anon understands what [s4s] is or what a #fortune is. Probably should lurk more on the objectively best board on the site.
![Screenshot_20210616-210033](https://user-images.githubusercontent.com/9031585/122335085-95c2a880-ceef-11eb-8369-d9c9b79a1fce.jpg)
![Screenshot_20210616-210006](https://user-images.githubusercontent.com/9031585/122335092-98250280-ceef-11eb-8907-99519c46cdfc.jpg)

**Comment by K1rakishou** [comment]
Messages with fortunes break with non-standard quotes
UUID: 12409b435414b08631ff6ec189e93375
Build flavor: dev
Version name: v4.13.6-52ebe48
OS info: Android 10, sdk version: 29
Report description: Follow up to #1291, this is only reproducible on [s4s] board after enabling the Convert non-standard quotes option in Appearance
