### ISSUE TITLE
YouTube title and duration parsing no longer works

### ISSUE THREAD

**Issue by Astridchan** [Adamantcheese/Kuroba#1292]
The app doesn't replace YouTube URLs with the title and duration anymore on recent Kuroba Dev builds, a progress spinner is sometimes visible when a thread is loaded but the URL just goes from plain text URL to a URL link when it's parsed.

**Comment by Adamantcheese** [comment]
![image](https://user-images.githubusercontent.com/9031585/122331647-08c92080-ceea-11eb-8f37-feb8989e463f.png)
It is working, it might be that the timeout of 2.5 seconds is too low now with the more consistent method of getting data; I couldn't get titles working on emulator anymore for a while now, despite them working on actual devices. This method is basically the same as youtube-dl's after looking at their code. I've adjusted the timeout for the youtube embedder specifically to be 10 seconds; tell me if that helps or if things are still busted.

**Comment by Astridchan** [comment]
I updated to the latest build and it's still not working for me. I don't think the timeout is the issue, as I said, when I open a thread the progress spinner appears for a split second on posts with Youtube links, and then the plaintext URL get's replaced by a URL link. It gives the impression that the app is simply failing to load the data for title and duration, rather than timing out.

https://streamable.com/tpbokv

**Comment by Adamantcheese** [comment]
Well, it's working on emulator 
![image](https://user-images.githubusercontent.com/9031585/122501234-227d6d00-cfa9-11eb-8a9e-cb9da6e9cf21.png)
and also on my OnePlus 6
![Screenshot_20210617-181830](https://user-images.githubusercontent.com/9031585/122501266-31641f80-cfa9-11eb-8296-a095ba65e931.jpg)
so I'm not entirely sure why it isn't working for you.
I've added in a verbose-debug log statement for any failures to embed; you can turn that on in developer settings if you want to provide me with more info. Like I said previously, I'm basically loading a regular youtube video page now as opposed to a deprecated youtube endpoint or the actual API, for example https://www.youtube.com/watch?v=8Fpkod30h8M, which is what I pull the relevant json from and parsing the relevant stuff. I'm curious to see why it's failing on your device.

**Comment by Astridchan** [comment]
```
D/Kuroba-dev | EmbeddingEngine: Embed failed for https://youtu.be/zHC6jDBhqV8
D/Kuroba-dev | EmbeddingEngine: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.util.JsonReader.beginObject()' on a null object reference
D/Kuroba-dev | EmbeddingEngine: 	at com.github.adamantcheese.chan.features.embedding.embedders.YoutubeEmbedder.lambda$convert$0(YoutubeEmbedder.java:83)
D/Kuroba-dev | EmbeddingEngine: 	at com.github.adamantcheese.chan.features.embedding.embedders.-$$Lambda$YoutubeEmbedder$ccVlSE8TbJal9PD4JcgnnqiQkdc.convert(Unknown Source:4)
D/Kuroba-dev | EmbeddingEngine: 	at com.github.adamantcheese.chan.core.net.NetUtilsClasses$ChainConverter.convert(NetUtilsClasses.java:232)
D/Kuroba-dev | EmbeddingEngine: 	at com.github.adamantcheese.chan.core.net.NetUtilsClasses$ChainConverter.lambda$chain$0(NetUtilsClasses.java:226)
D/Kuroba-dev | EmbeddingEngine: 	at com.github.adamantcheese.chan.core.net.NetUtilsClasses$ChainConverter.lambda$chain$0$NetUtilsClasses$ChainConverter(Unknown Source:0)
D/Kuroba-dev | EmbeddingEngine: 	at com.github.adamantcheese.chan.core.net.-$$Lambda$NetUtilsClasses$ChainConverter$BIlSICXRCYlZIpSbj051pRvyv_M.convert(Unknown Source:4)
D/Kuroba-dev | EmbeddingEngine: 	at com.github.adamantcheese.chan.core.net.NetUtilsClasses$ChainConverter.convert(NetUtilsClasses.java:232)
D/Kuroba-dev | EmbeddingEngine: 	at com.github.adamantcheese.chan.features.embedding.embedders.YoutubeEmbedder.convert(YoutubeEmbedder.java:121)
D/Kuroba-dev | EmbeddingEngine: 	at com.github.adamantcheese.chan.features.embedding.embedders.YoutubeEmbedder.convert(YoutubeEmbedder.java:32)
D/Kuroba-dev | EmbeddingEngine: 	at com.github.adamantcheese.chan.core.net.NetUtils$3.onResponse(NetUtils.java:503)
D/Kuroba-dev | EmbeddingEngine: 	at com.github.adamantcheese.chan.features.embedding.EmbeddingEngine$1.onResponse(EmbeddingEngine.java:211)
D/Kuroba-dev | EmbeddingEngine: 	at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:519)
D/Kuroba-dev | EmbeddingEngine: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
D/Kuroba-dev | EmbeddingEngine: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
D/Kuroba-dev | EmbeddingEngine: 	at java.lang.Thread.run(Thread.java:923)
```

**Comment by Astridchan** [comment]
I added a `System.out.println(response)` in YoutubeEmbedder [here](https://github.com/Adamantcheese/Kuroba/blob/288b201bdb8f2badbca92bed70bc5aff83da1c3a/Kuroba/app/src/main/java/com/github/adamantcheese/chan/features/embedding/embedders/YoutubeEmbedder.java#L70) and the result is this:

`Response{protocol=h2, code=200, message=, url=https://consent.youtube.com/ml?continue=https://www.youtube.com/watch?v%3DMTGCNskhQYA&gl=GB&hl=EN-GB&pc=yt&uxe=23983172&src=1}`

Screenshot of the [site](https://preview.redd.it/w9ry0g1gjfl61.png?width=1920&format=png&auto=webp&s=595d0aab7713452d81b0c7b6dbfcfa91e93c1872). So it seems that requests for Youtube URLs get redirected to a cookie consent page, which is why embedding fails. Must be GDPR related which is why it happens on my end but not for you (I'm located in the EU). FWIW, here's what Youtube-DL does to fix it:
https://github.com/ytdl-org/youtube-dl/commit/14f29f087e6097feb46bdb84878924bc410a57eb

**Comment by Adamantcheese** [comment]
Lemme know if that's fixed it or not, I can always roll it back if needed.

**Comment by Astridchan** [comment]
App is freezing on start-up on current build, I think there's a typo:
```
Called from unhandled exception handler.
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.github.adamantcheese.chan.dev/com.github.adamantcheese.chan.StartActivity}: java.lang.IllegalArgumentException: unexpected domain: .youtube.com
	at android.app.ActivityThread.performLaunchActivity(Unknown Source:663)
	at android.app.ActivityThread.handleLaunchActivity(Unknown Source:47)
	at android.app.servertransaction.LaunchActivityItem.execute(Unknown Source:67)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(Unknown Source:77)
	at android.app.servertransaction.TransactionExecutor.execute(Unknown Source:73)
	at android.app.ActivityThread$H.handleMessage(Unknown Source:52)
	at android.os.Handler.dispatchMessage(Unknown Source:19)
	at android.os.Looper.loop(Unknown Source:249)
	at android.app.ActivityThread.main(Unknown Source:134)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(Unknown Source:11)
	at com.android.internal.os.ZygoteInit.main(Unknown Source:313)
Caused by: java.lang.IllegalArgumentException: unexpected domain: .youtube.com
	at okhttp3.Cookie$Builder.domain(Cookie.kt:297)
	at okhttp3.Cookie$Builder.domain(Cookie.kt:287)
	at com.github.adamantcheese.chan.features.embedding.embedders.YoutubeEmbedder.setup(YoutubeEmbedder.java:38)
	at com.github.adamantcheese.chan.features.embedding.EmbeddingEngine.<init>(EmbeddingEngine.java:112)
	at com.github.adamantcheese.chan.features.embedding.EmbeddingEngine.initEngine(EmbeddingEngine.java:124)
	at com.github.adamantcheese.chan.StartActivity.onCreate(StartActivity.java:137)
	at android.app.Activity.performCreate(Unknown Source:81)
	at android.app.Activity.performCreate(Unknown Source:1)
	at android.app.Instrumentation.callActivityOnCreate(Unknown Source:3)
	at android.app.ActivityThread.performLaunchActivity(Unknown Source:399)
	... 11 more
```

**Comment by Astridchan** [comment]
Works now, cheers! 👍

**Comment by Astridchan** [comment]
This is odd, YouTube embedding was working perfectly yesterday and now it stopped working again today with the same NPE error as earlier. Printed out the response again and this time it's getting the right URL so the consent cookie is working. Dug in a little further and it seems the basic issue here is that the response body I receive is slightly different so the regex pattern isn't matching anything.
https://github.com/Adamantcheese/Kuroba/blob/aaefcdf20beb3b28a62326d73d5d0a4d662de7b3/Kuroba/app/src/main/java/com/github/adamantcheese/chan/features/embedding/embedders/YoutubeEmbedder.java#L32

 I changed the pattern from
`"ytInitialPlayerResponse = (.*?);var"`
to
`"ytInitialPlayerResponse = (.*?)\\};"`
and it's back to working again.
