### ISSUE TITLE
Report "thread bookmaring"

### ISSUE THREAD

**Issue by K1rakishou** [Adamantcheese/Kuroba#1293]
UUID: f119c3d28e7d2c1a442773096a0e0817
Build flavor: dev
Version name: v4.13.6-210b8ed
OS info: Android 10, sdk version: 29
Report description: for some reason, any thread cannot be unmarked by tapping the bookmark icon but swipeable from the thread list

**Comment by Adamantcheese** [comment]
Specifically on archived threads.
