### ISSUE TITLE
Getting logged out of 4chan pass

### ISSUE THREAD

**Issue by ghost** [Adamantcheese/Kuroba#1294]
Every couple hours the pass menu has me logged out and I need to use captcha until I log back in manually. I don't really understand why this is happening

**Comment by Adamantcheese** [comment]
I'll roll this into the problems mentioned in #1287 and close this one, as you've mentioned a similar issue there already. I'm pretty sure the standard cookie only lasts for a day before it needs to be refreshed; I might need to add an interceptor to re-login if need be.
