### ISSUE TITLE
Report "flag code option"

### ISSUE THREAD

**Issue by K1rakishou** [Adamantcheese/Kuroba#1295]
UUID: 4496dda5d82db39b2cfe5a9159c24f12
Build flavor: dev
Version name: v4.13.6-210b8ed
OS info: Android 10, sdk version: 29
Report description: bring back flag code option. why is it unavailable in dev ver?

**Comment by Adamantcheese** [comment]
Ah, flag codes for countries anon means.

**Comment by Adamantcheese** [comment]
Nope, checking again anon is just dumb and should try tapping on the flag code area when it is available. 
![image](https://user-images.githubusercontent.com/9031585/122742018-676c0280-d23a-11eb-8fe1-ee560bdf7947.png)
