### ISSUE TITLE
Last page thread watcher issue

### ISSUE THREAD

**Issue by ownBard** [Adamantcheese/Kuroba#130]
Thread watcher should not give a last page notification when bookmarking a thread already on the last page. Especially with *bookmark thread on post* becomes a bit annoying.

**Comment by Adamantcheese** [comment]
Working as intended. Regardless, it would trigger the notification on the next thread update, which is likely to happen before the page request is sent, as they are decoupled from each other for performance reasons.

**Comment by ownBard** [comment]
@Adamantcheese But doesn't the last page notification already only trigger once per bump? So it would just have to ignore until after the first bump (i.e. disable last page notification until the thread is not on the last page for the first time). What am I missing here?

**Comment by ownBard** [comment]
I sorta get that it's currently as intended, but I'm suggesting it as a QoL improvement anyway.

**Comment by Adamantcheese** [comment]
You are free to submit a PR if you can implement it.

**Comment by ownBard** [comment]
Scary...

**Comment by ownBard** [comment]
https://github.com/Adamantcheese/Kuroba/blob/f9783b236047a88b55fe32d3cad73ed65e5f1683/Kuroba/app/src/main/java/com/github/adamantcheese/chan/core/manager/WatchManager.java#L765 @Adamantcheese Since `!notified` returns true when `notified == null` the fix would be to just check `!= null` first, then it would function as I described above. Trying to make a pull request from my phone seems like too much hassle, sorry.

**Comment by Adamantcheese** [comment]
`notified` is a primitive boolean and can never be null. I have no idea what you're talking about.

**Comment by ownBard** [comment]
Then why would you want it to start false?

**Comment by ownBard** [comment]
Yeah okay nevermind I know how to fix it. I'm struggling to be helpful lmao.

**Comment by Adamantcheese** [comment]
I'll can change it to start at `true` instead and that would do what you want. I do appreciate you looking at the code and trying to come up with a solution regardless. I'm trying to get people to do some work on the application rather than bitching at me about it like an annoying client who is unsatisfied with free service. Sorta tired of that.

**Comment by ownBard** [comment]
Well yeah, although I originally avoided suggesting that since it makes no sense with this var name.
