### ISSUE TITLE
Report "convert non-standard quotes"

### ISSUE THREAD

**Issue by K1rakishou** [Adamantcheese/Kuroba#1304]
UUID: 8d87d58425e9874a155271aa46c8236f
Build flavor: dev
Version name: v4.13.6-46079ae
OS info: Android 11, sdk version: 30
Report description: it converts dollar amounts to post numbers.

**Comment by Astridchan** [comment]
Just an idea but maybe the app could check whether a number is an existing post in the thread before converting it to a quote, I think that would eliminate any false positives.

**Comment by Adamantcheese** [comment]
Extra quote parsing acts directly on the HTML of a post's comment to replace text with HTML entities that get parsed normally, same with extra spoilers or markdown subset parsing. I don't have the info when that code is running to do what you're suggesting Astrid; I would need to change the implementation to something completely different to achieve that result, and this is code just attempts but does not guarantee. I'll just remove the $ from the regex.

**Comment by Astridchan** [comment]
Yeah, that works too, 99% of the non-quote quotes I see on 4chan use @, never seen anyone use $.
