### ISSUE TITLE
Report "spacing when 2 thread is selected"

### ISSUE THREAD

**Issue by K1rakishou** [Adamantcheese/Kuroba#1306]
UUID: 775b10d9033856538ffed80c10e0ff46
Build flavor: dev
Version name: v4.13.6-063107c
OS info: Android 10, sdk version: 29
Report description: too much spacing between threads as seen in image. android 10 using asus rogphone2 https://imgur.com/a/6psT4dB

**Comment by Adamantcheese** [comment]
Related to #1270.
