### ISSUE TITLE
Report "Links within spoilers"

### ISSUE THREAD

**Issue by K1rakishou** [Adamantcheese/Kuroba#1319]
UUID: c548cb4936bab32b32a8da6054445dc9
Build flavor: dev
Version name: v4.13.6-1d48096
OS info: Android 10, sdk version: 29
Report description: I am faced with some issues with spoilered links in general, namely:

- Unable to open links, tapping on it instead just toggles the visibility of the spoilered text
- Link doesn't get listed when viewing 'post info'
- External image loading doesn't work with spoilered image links

**Comment by Adamantcheese** [comment]
Closed with 3a411f45b5c37e72063cb61c270cb1306de0a90c
