### ISSUE TITLE
Report "Flags on international boards"

### ISSUE THREAD

**Issue by K1rakishou** [Adamantcheese/Kuroba#1329]
UUID: 707a4099e1c66f1ce3420df2dc8f10b7
Build flavor: dev
Version name: v4.13.6-a23d519
OS info: Android 9, sdk version: 28
Report description: only UK and Germany flags seem to load right after the lasted Dev update. This happened with and without sprite flags being turned on. Just to add more bugs to the increasingly growing list

**Comment by K1rakishou** [comment]
some flags on /sp/ not showing
UUID: 518536232188cf5200d8acbb72f87fdf
Build flavor: dev
Version name: v4.13.6-a23d519
OS info: Android 11, sdk version: 30
Report description: some flags on /sp/ not showing

**Comment by Adamantcheese** [comment]
This is not flag-specific, flags just seem to be not rendering, annoyingly.
Issue caused by commit d6dd8c2.
