### ISSUE TITLE
Inconsistent catalog preview size

### ISSUE THREAD

**Issue by Anonermus** [Adamantcheese/Kuroba#1331]
The previews on the catalog often get much larger than they should be. Sometimes single cells will become the length of several catalogs. When this happens it seems to happen every 5 or so rows of threads. I've also seen some that become smaller than they should be but this is less common. Every once in a while it will fix itself when you scroll back up but this doesn't always happen. Here is a screenshot and video of the issue in action.

https://u.smutty.horse/mcjlffwabjd.png
https://u.smutty.horse/mcjlffxvgid.mp4

**Comment by HamletDuFromage** [comment]
Can confirm, encountered some really egregious cases 

![Screenshot_20210801-032715](https://user-images.githubusercontent.com/61667930/127777360-88c4bf93-2b77-4134-8200-063b45344513.jpg)

**Comment by Adamantcheese** [comment]
Associated with #1272.
