### ISSUE TITLE
Long threads reset to original screen position after some scrolling

### ISSUE THREAD

**Issue by ghost** [Adamantcheese/Kuroba#1362]
I found an issue where after tapping a reply notification and getting put in its thread I was unable to scroll up or down without being teleported to the post that I was at before scrolling (about the middle of the thread)
The top/bottom/new buttons refused to work until I closed the thread and went back to it after opening a new one (slide mode)

Tested on v4.13.6-34a61da1 on a Samsung Note 10 Plus

**Comment by Adamantcheese** [comment]
Duplicate of #1201.
