### ISSUE TITLE
Kuroba saving banned/blocked state

### ISSUE THREAD

**Issue by Ashtonio** [Adamantcheese/Kuroba#1363]
Kuroba seems to save the banned state, changing IP or from wireless to mobile data will give me the "Error posting: Ban evasion" even if I haven't posted in ages and someone from the same IP got banned. The only work around is to clear cache and clear data.

**Comment by ghost** [comment]
Solution is to clear site cookies in site settings
![Screenshot_20210924-202809.jpg](https://user-images.githubusercontent.com/30278765/134754857-4d1f9fb2-720c-4c69-8c6f-c440cd3e10dd.jpg)

**Comment by Ashtonio** [comment]
> Solution is to clear site cookies in site settings
> ![Screenshot_20210924-202809.jpg](https://user-images.githubusercontent.com/30278765/134754857-4d1f9fb2-720c-4c69-8c6f-c440cd3e10dd.jpg)

Ahhhhh, I tried looking in settings for something like that but must've missed it. Thanks for the help, guess I'll just close this then.
