### ISSUE TITLE
New reCAPTCHA

### ISSUE THREAD

**Issue by ghost** [Adamantcheese/Kuroba#1364]
Why have the devs not done anything to support the new reCAPTCHA? It was released ~3 months ago and nothing has been done by the devs

**Comment by ghost** [comment]
Stable releases lag behind, you need the dev branch

**Comment by Adamantcheese** [comment]
Duplicate of #1296. Captcha does work, but has not been pushed to release. Dev is working however.

**Comment by Adamantcheese** [comment]
Also I'm the only developer here.
