### ISSUE TITLE
OP image thread swap

### ISSUE THREAD

**Issue by lewri** [Adamantcheese/Kuroba#1366]
Noticed while browsing in gallery mode two threads swapped their op image. But normal when you open the thread. Kuroba dev 4.13.6-34a61da1

**Comment by Adamantcheese** [comment]
Nice choice of sample image. I've removed it for obvious reasons. But yes I am aware.

**Comment by ghost** [comment]
Probably the same as #1353, right?

**Comment by Adamantcheese** [comment]
Yeah, but I'll close this one in favor of that one. It's pretty much any recycler view with an adapter implementation that's using ImageLoadable.
