### ISSUE TITLE
4chan captcha slider sometimes doesn't appear

### ISSUE THREAD

**Issue by ghost** [Adamantcheese/Kuroba#1367]
see screenshot
![Screenshot_20210927-140955](https://user-images.githubusercontent.com/46851846/134905924-2d4a4648-9e0d-4bf9-914f-072c804025e6.png)
it seems random, refreshing sometimes fixes it, sometimes doesn't, force restaring the app yields the same result
dev v4.13.6-34a61da1

**Comment by Adamantcheese** [comment]
Captchas come in a slider, no-slider, and no-op version. This is a no-slider version, as you can see.
