### ISSUE TITLE
Report "Thread history"

### ISSUE THREAD

**Issue by K1rakishou** [Adamantcheese/Kuroba#1375]
UUID: 9f456ef9f11c74bbb675b270944485cd
Build flavor: dev
Version name: v4.13.6-34a61da1
OS info: Android 11, sdk version: 30
Report description: I looked for an email I could contact but couldn't find one, don't have a github account. Is there a setting I haven't found to disable thread history? On Clover it just has an on/off toggle, so far this is my only issue, otherwise liking the app. If you could email "REDACTED"@gmail.com (there was an actual email here I've removed it just in case) with an answer I'd really appreciate it.

**Comment by Adamantcheese** [comment]
Closed as of c6c014477aa90b8fb5eb9fe530c14b021f652d85.
