### ISSUE TITLE
App crashes on startup

### ISSUE THREAD

**Issue by Suni23** [Adamantcheese/Kuroba#1377]
The dev branch of the app said that it had a new version today and after downloading it, the app crashes on startup.
I tried installing the previous versions and it still crashes on startup now for some reason.

**Comment by Adamantcheese** [comment]
I have not committed anything in two months, so it's not "new". It's probably crashing on rollback because you still have a newer database file around. There's not much I can do to help without crash logs from adb.

**Comment by Suni23** [comment]
> I have not committed anything in two months, so it's not "new". It's probably crashing on rollback because you still have a newer database file around. There's not much I can do to help without crash logs from adb.

I was able to get it to work again by deleting all the data, but sadly I lost my settings and favorites.

**Comment by Adamantcheese** [comment]
Unfortunate to hear; next time I might recommend exporting your settings before upgrading.

**Comment by Adamantcheese** [comment]
Ah, it seems that Github has decided to bug out and mark a release from several months ago as "latest" instead of the actual latest one. I'll submit a support ticket.

**Comment by Adamantcheese** [comment]
I've removed the asset for the time being. People should no longer be able to update to the incorrect release.

**Comment by Adamantcheese** [comment]
For anyone that accidentally upgrades, https://github.com/Adamantcheese/Kuroba-Dev/releases/tag/v4.13.6-34a61da1 is the proper latest release. Just install that and you'll be set.

**Comment by Suni23** [comment]
> I've removed the asset for the time being. People should no longer be able to update to the incorrect release.

Just a heads up, it seems to be doing it again. I'm refraining from updating this time though lol

**Comment by Adamantcheese** [comment]
It's not "doing it again". It will continue to do so until Github figures out what happened. This isn't the first time that Github's messed something up with its API for Kuroba anyways.

Feel free to update, the updater should fail because there's no APK to download anyways. Sucks that the notification will stick around until this is fixed though.

**Comment by ghost** [comment]
That sucks
The unwavering update notification is a bit annoying

**Comment by Adamantcheese** [comment]
While this issue has been "resolved", as in there's a new build, there's still an issue on Github's backend that keeps the "latest" API endpoint pointing to something incorrect, despite me making workflow changes to hopefully alleviate it. Maybe this time Github support won't be total shit.
