### ISSUE TITLE
Captcha HttpsCodeException

### ISSUE THREAD

**Issue by Neofranky** [Adamantcheese/Kuroba#1382]
When I try to post while on 4g data I get hit with this. 
Reinstalling or clearing cache doesn't work, but connecting to wifi does seem to avoid it. 

![Screenshot_2021-12-20-10-32-49-04_83b4c3130c38199daea22da676b8bce2](https://user-images.githubusercontent.com/7104250/146801280-16fd4b3c-4eba-4c99-b250-caf07497413f.jpg)

**Comment by clover-supply** [comment]
Started getting this too. Any help would be appreciated.

**Comment by Adamantcheese** [comment]
Probably the same thing as #1431, closed with 003fe47c0f0547c497aac5d3b10f2e30a2b28e30.
