### ISSUE TITLE
App doesn't handle links to rules page

### ISSUE THREAD

**Issue by ghost** [Adamantcheese/Kuroba#1383]
It's interesting that the app seemingly has all the support to open rules links but doesn't actually do anything with them. If you click the same link in the browser and open it in the app, it sends the page back to the brower, just not if you do it in the app itself.
![Screenshot_20211223-072341.jpg](https://user-images.githubusercontent.com/30278765/147254985-6039700d-fa22-495f-944c-5e1a254f323a.jpg)

**Comment by Twinov** [comment]
Interesting issue, I can't find any thread with a link to a global rule to test, but I'm guessing the link is just accidentally getting caught in a regex filter.

**Comment by ghost** [comment]
> Interesting issue, I can't find any thread with a link to a global rule to test, but I'm guessing the link is just accidentally getting caught in a regex filter.

You can try it yourself in a test thread, or just find an archive link to a post with a rules link
