### ISSUE TITLE
CAPTCHA input isn't consistent with 4chan's all caps

### ISSUE THREAD

**Issue by ghost** [Adamantcheese/Kuroba#1386]
The post CAPTCHA allows use of lower case letters, whereas 4chan's native system will automatically capitalize them, which makes checking them slightly easier, so I feel like this could be an improvement in-app as well.
Examples for reference:

![Screenshot_20220102-232234.jpg](https://user-images.githubusercontent.com/30278765/147904191-1e4aa63b-9fe6-4ef1-8c0f-fcca743f2240.jpg)

![Screenshot_20220102-232321.jpg](https://user-images.githubusercontent.com/30278765/147904194-e077ace3-4c95-4a52-955b-726591a85907.jpg)

**Comment by ghost** [comment]
It would also be nice to be able to use it in the post menu instead of its own separate screen, or at least to be able to save incomplete captcha progress and return to it without having to wait for another one to load.

**Comment by hornetDC** [comment]
How do you even get the new captcha? I still see old google one.

**Comment by Twinov** [comment]
> How do you even get the new captcha? I still see old google one.

You need to be using [Kuroba-dev](https://github.com/Adamantcheese/Kuroba-Dev/releases/) to have the new captcha. Just make sure you get the September 9th build and not the one pinned as latest.

**Comment by Adamantcheese** [comment]
Closed with https://github.com/Adamantcheese/Kuroba/pull/1395.
