### ISSUE TITLE
[Feature Request] Randomize file name + unique hash + remove meta data

### ISSUE THREAD

**Issue by bluefiberbread** [Adamantcheese/Kuroba#139]
When you upload an image, we should be given the options to randomize the file name, give it a unique hash and have the meta data removed.

Can you implement this?

**Comment by K1rakishou** [comment]
It is already implemented. Click the image you have attached to your post and you will see a bunch of options.

**Comment by Adamantcheese** [comment]
As per K1rak's comment, it's implemented. I know because he implemented it and it works great.
