### ISSUE TITLE
Images don't load most of the time

### ISSUE THREAD

**Issue by Zalkor** [Adamantcheese/Kuroba#1392]
Device : Galaxy Tab SM-T550, Android 7.1.1

Kuroba-dev v4.13.6-c9792356

Pretty much the title, I've always had this problem with Kuroba-dev (don't have it on the "non dev" version), images don't load most of the time and I can't swipe right/left to browse other images

[exemple](https://i.imgur.com/cQbvyH5.jpg)

[after several tries it sometimes loads](https://i.imgur.com/t6Zqvxw.jpg)

"Automatically load images" is set to "always"

is there any way to fix this ? thanks in advance

**Comment by ghost** [comment]
I don't know why you would specifically have the problem on dev, though this has been pretty common in the past for me when I had a slower phone. Clover/kuroba are just slow at loading images compared to 4chan and you're on android 7
