### ISSUE TITLE
Download Failed; Reason: Null

### ISSUE THREAD

**Issue by ZenythFactor** [Adamantcheese/Kuroba#1398]
Any reason for this? I was notified an update, so i tried updating, and it doesn't let me. I'm on Kuroba-dev v4.13.6-34a61da1.
Is it a glitch? Is there even an update? It's hard to tell since dev build dates are all over the place.

Kuroba is so good, i hate to go back to slow ass Clover again.

**Comment by Adamantcheese** [comment]
Duplicate of #1377.
