### ISSUE TITLE
Failure to load Custom 4chan captcha 

### ISSUE THREAD

**Issue by DarkTzitzimine** [Adamantcheese/Kuroba#1401]
I'm using Kuroba-dev v4.13.6-34a61da1 on a Redmi 9 running Android 11, MIUI Global 12.0.3, and today, all of the sudden the app stopped loading the captcha on any board. Anytime I try to make a post I get an error message that says

Couldn't initialize captcha, reason: HttpCodeException.

![Screenshot_2022-08-25-15-57-18-619_com github adamantcheese chan dev](https://user-images.githubusercontent.com/44504981/186823057-9543ea64-b176-4ec0-8a74-b6d866965692.jpg)

This happens regardless of the board and is 4chan or 4channel, on different networks, or using data. Opening a posting window through a browser loads the captcha just fine. I've already tried wiping all data and reinstalling Kuroba-Dev

**Comment by clover-supply** [comment]
I tried another chan browser and it loaded a cloudflare check. Could it be this? Is there a way to pass the CF check in kuroba?

**Comment by DarkTzitzimine** [comment]
> I tried another chan browser and it loaded a cloudflare check. Could it be this? Is there a way to pass the CF check in kuroba?

Looking at /g/, that is exactly what happened

> the introduction of always-on cloudflare human check is basically death for non-browser clients because it requires implementing javascript engine on the application, and when you have javascript engine it is basically browser now so why even bother.

**Comment by clover-supply** [comment]
> and when you have javascript engine it is basically browser now so why even bother.

Because I'm not bloating my actual browser with 5 to 20 tabs of threads.

**Comment by ghost** [comment]
Yeah I can confirm this too
I don't know if it's related but I was having other post loading issues the day before this started happening that I was able to fix by clearing cookies
![Screenshot_20220825-042508~2.png](https://user-images.githubusercontent.com/30278765/187017021-2d0ca8cd-1b67-4da6-96fc-483b3569f181.png)

**Comment by Adamantcheese** [comment]
Basically before getting a captcha the first time you need to get a cloudflare cookie. I've adapted the cloudflare interceptor from Tachiyomi and it's working in my development environment. I just need to figure out where the fuck I left off a year ago to clean it up and actually push this work.

**Comment by MrRampage777** [comment]
@Adamantcheese appreciate the potential fix, hope it goes well for you

**Comment by DarkTzitzimine** [comment]
Some anon found that if you use the report function and load its captcha, you can bypass the Cloudflare check once you return to Kuroba and try to post. You'd need to do the process separately for blue and red boards. 

It is not a perfect solution, however, sometimes it works and others do not. It worked at the first attempt when I was using my mobile data but once I connected to my home's wifi the trick didn't work no matter what I did, but after leaving my phone alone for a couple of hours it suddenly worked. Also, no one knows for how long this will work.

**Comment by Adamantcheese** [comment]
> Some anon found that if you use the report function and load its captcha, you can bypass the Cloudflare check once you return to Kuroba and try to post. You'd need to do the process separately for blue and red boards.
> 
> It is not a perfect solution, however, sometimes it works and others do not. It worked at the first attempt when I was using my mobile data but once I connected to my home's wifi the trick didn't work no matter what I did, but after leaving my phone alone for a couple of hours it suddenly worked. Also, no one knows for how long this will work.

Nobody really knows Cloudflare except Cloudflare. I had the same thing in my development environment where it just haphazardly works or doesn't.

**Comment by ghost** [comment]
> Nobody really knows Cloudflare except Cloudflare. I had the same thing in my development environment where it just haphazardly works or doesn't.

The captcha in the report menu works pretty good for me currently. I did it a couple days ago and posting is fine

**Comment by ghost** [comment]
Ok the autosolver is actually epic, good job on this one
Has some issues though
![Screenshot_20220926-041301.png](https://user-images.githubusercontent.com/30278765/192251517-255eed85-d3cf-49a5-80a1-acfe886ea8a4.png)

**Comment by Adamantcheese** [comment]
Probably the same issue as #1431, which was closed with 003fe47c0f0547c497aac5d3b10f2e30a2b28e30.
