### ISSUE TITLE
Kuroba-dev crashing at startup after update

### ISSUE THREAD

**Issue by MegaPramuk** [Adamantcheese/Kuroba#1403]
Just like the title says, Kuroba-dev crashes for me after having updated.
The last version working is Kuroba-dev v4.13.6-c9792356.
This happens on a Xiaomi Redmi Note 10 Pro running Android 12 SKQ1.210908.001 and MIUI Global 13.0.13, both which are the latest versions.

If more information is necessary, I'll be happy to provide.

**Comment by Adamantcheese** [comment]
You can manually update to this release https://github.com/Adamantcheese/Kuroba-Dev/releases/tag/v4.13.6-dbc96a66 for right now, or later releases.
Once again, Github is being horrible and I've submitted a bug report because the "latest" release isn't properly updating. Sometimes it works, sometimes it doesn't.

**Comment by Imadethisforthis** [comment]
Updating to this version still crashes on startup. Both updating from a previously working version, and a first time install.

**Comment by Adamantcheese** [comment]
Stupid Android 12 and its stupid changes. https://github.com/Adamantcheese/Kuroba-Dev/releases/tag/v4.13.6-e52d648c should no longer crash, although the "latest" release is still not correct in the dev build repo. God I fucking hate Github's shit ass API that doesn't update according to its own rules.

**Comment by MegaPramuk** [comment]
Great, that commit seems to work.
Just updated and it didn't crash.
Thanks for resolving it this quickly!

**Comment by Suni23** [comment]
> Stupid Android 12 and its stupid changes. https://github.com/Adamantcheese/Kuroba-Dev/releases/tag/v4.13.6-e52d648c should no longer crash, although the "latest" release is still not correct in the dev build repo. God I fucking hate Github's shit ass API that doesn't update according to its own rules.

Thank you for your continued efforts despite Github's bullshit.

**Comment by Soundtoxin** [comment]
I'm still getting some crashes on the last linked build in thos thread, running Android 12. When I hit a thread that causes the crash, reopening that same thread crashes again instantly.

**Comment by Adamantcheese** [comment]
> I'm still getting some crashes on the last linked build in thos thread, running Android 12. When I hit a thread that causes the crash, reopening that same thread crashes again instantly.

This is likely a different issue, probably #1411.

**Comment by Soundtoxin** [comment]
You're right, thanks. I seem to be able to work around it for now by turning off the image prefetching.
