### ISSUE TITLE
App keeps crashing on 4Chan while writing comments

### ISSUE THREAD

**Issue by zilla249** [Adamantcheese/Kuroba#1418]
While typing comments, typing lags out and crashes. Have reported crash several times on app but will post log too
![Screenshot_20230103_232857](https://user-images.githubusercontent.com/114614208/210484944-dfd62652-9499-4d4d-8526-a6890a029d62.jpg)

**Comment by Adamantcheese** [comment]
Report this for KurobaEx. How do you not know what application you're using?

**Comment by zilla249** [comment]
I'm fucking stupid, my apologies.
