### ISSUE TITLE
[Feature Request] Context menu 

### ISSUE THREAD

**Issue by Sdash24** [Adamantcheese/Kuroba#1422]
![Screenshot_2023-04-23-10-44-47-811_com moffatman chan](https://user-images.githubusercontent.com/85696810/233821158-66e4d89a-2b7b-4d06-b136-50001249bd0d.jpg)
I need this type of context menu especially "Quote in reply" one in Kuroba-dev

thanks.

**Comment by Adamantcheese** [comment]
This already exists.

**Comment by Sdash24** [comment]
> This already exists.

how to do it?
@Adamantcheese

**Comment by Sdash24** [comment]
@Adamantcheese Sir I really need a reply

https://github.com/Adamantcheese/Kuroba/issues/1422#issuecomment-1518965190

**Comment by Twinov** [comment]
![Screenshot_20230423-095750.png](https://user-images.githubusercontent.com/23278147/233844068-5df53f40-a274-40b0-9aac-186508ff96da.png)
the quote button

**Comment by Sdash24** [comment]
> ![Screenshot_20230423-095750.png](https://user-images.githubusercontent.com/23278147/233844068-5df53f40-a274-40b0-9aac-186508ff96da.png) the quote button

No quote button here @Twinov 
It's Redmi note 5 pro 
![Screenshot_2023-04-25-18-27-34-437_com github adamantcheese chan dev](https://user-images.githubusercontent.com/85696810/234283636-68884609-1200-4cc0-b2b6-4e382c92fe0e.jpg)

**Comment by Sdash24** [comment]
Just searched the web and found this
https://xiaomi.eu/community/threads/context-menu-options-gone-in-20-7-23.56767/#js-post-554509

Anyway to fix this?
It's miui global 11.0.5 Stable :(
@Twinov @Adamantcheese

**Comment by Adamantcheese** [comment]
Lmao I ain't touchin MIUI

**Comment by Sdash24** [comment]
> Lmao I ain't touchin MIUI

can't you just implement the webview for replies?
The system webview allows to have custom context menu (that's what Chance does)
make a setting toggle for it for devices like mine.
Thank you.
@Adamantcheese
