### ISSUE TITLE
Automatically pin/highlightbpost in a board with pre-selected keywords (Feature request)

### ISSUE THREAD

**Issue by c933103** [Adamantcheese/Kuroba#1423]
Use case: On for example 4chan's /a/, one might pay particular attention to posts discussing some specific anime, or shows that get discussed every once in a while but not that frequently. Currently users have to either scroll through the catalog or type relevant keywords one by one. It would be nice if the process cam be automated, in a way similar to but function opposite against the keyword blacklist system, by having thread which opening posts and/or thread title and/or opening post file names containing specified keyword be pinned on top of a board, in a way similar to how pinned message by noard admin currently appear in the app but with different visual representation (like instead of a pin, maybe some other icon or some sort of highlight of the post)

**Comment by Adamantcheese** [comment]
That's what filter watching is for. Make a filter, set it to watch, and it'll pop threads into your bookmarks list.
