### ISSUE TITLE
[Feature Request] New Section suggestion 

### ISSUE THREAD

**Issue by Sdash24** [Adamantcheese/Kuroba#1424]
I want a new section on the left side menu named replied threads. For the threads user replied to but not bookmarked. So that I can track the above mentioned type of thread for posts quoting me. Thank you.

**Comment by Adamantcheese** [comment]
So you want something bookmarked and watched, but not "bookmarked" and only "watched". You do realize you're asking a meaningless distinction? The application will do exactly the same work to get the result you want.
