### ISSUE TITLE
Images fail loading

### ISSUE THREAD

**Issue by ImpulseMirror** [Adamantcheese/Kuroba#1425]
Images no longer load with the exception that kuroba.io is not accessible. Did you lose your domain?

**Comment by bonechene** [comment]
Same issue here. Different error message. See attached

Webms load however

![Screenshot_20230526_102721](https://github.com/Adamantcheese/Kuroba/assets/17063454/ff453b48-a362-42dc-8895-10c47fd80daf)

**Comment by Adamantcheese** [comment]
Kuroba.io is a domain I never registered. Maybe you're thinking of Kuroba-ex?

Also I removed that hash check a while ago so you're probably using an old version. It's a 4chan bug.

**Comment by shitbag6969** [comment]
I have this issue as well, i am on the newest version 4.13.6. 
![Screenshot_20230526_171528](https://github.com/Adamantcheese/Kuroba/assets/134743588/05c73771-e766-4f54-aa2a-c7ba5dfa5d6e)

**Comment by Adamantcheese** [comment]
Yeah I bet 4.13.6 still had the old loader code. Dev has this fixed.

**Comment by shitbag6969** [comment]
> Yeah I bet 4.13.6 still had the old loader code. Dev has this fixed.

dev freezes for 10 seconds when i go to save images.

**Comment by Adamantcheese** [comment]
You must be using an older version of dev then because that was resolved as well.

**Comment by shitbag6969** [comment]
> You must be using an older version of dev then because that was resolved as well.

My dev is version v4.13.6-643c5ece . Is that not the newest one?
![Screenshot_20230526_172616](https://github.com/Adamantcheese/Kuroba/assets/134743588/dc1d089d-42e0-4241-a58e-e0f8626197ef)

**Comment by Adamantcheese** [comment]
Maybe I should push then lol, I'm on a38de60a probably from my local branch

**Comment by ghost** [comment]
I'm using the latest version and I still have that same bug

**Comment by gastrodon** [comment]
On latest version and I still have this bug!
