### ISSUE TITLE
Previous issue closed without solution - images not loading correctly.

### ISSUE THREAD

**Issue by AstroShogun** [Adamantcheese/Kuroba#1427]
In the referenced thread, https://github.com/Adamantcheese/Kuroba/issues/1425, Adam suggests using the dev branch to fix the problem.

However, the referenced version is unavailable, with the latest Dev APK dating back to 2022.

Please do not close this issue without a definitive answer or solution.

**Comment by hi-fox** [comment]
Same issue here - previous issue closed without solution. Dev is recommending the latest dev release however this hasn't been pushed since sept

**Comment by AstroShogun** [comment]
For anyone with this issue, I'd highly recommend you use https://github.com/K1rakishou/Kuroba-Experimental

It seems to be updated much more frequently and has more functionality that Kuroba and Clover.

**Comment by Adamantcheese** [comment]
If you were smart you would have checked the pinned issues that explain the resolution. You would also avoid advertising other applications.
