### ISSUE TITLE
/lgbt/ flags

### ISSUE THREAD

**Issue by ghost** [Adamantcheese/Kuroba#1428]
/lgbt/ got flags today, and while they show just fine the app should probably support selecting them

**Comment by Adamantcheese** [comment]
Restarting the app should refresh the board flags in the database once the boards.json file on 4chan updates with the `board_flags` field. Give it a couple of days and it should fix itself.

**Comment by Adamantcheese** [comment]
boards.json has been updated, so I'll unpin this now. Have fun!
