### ISSUE TITLE
Ban evasion after clearing cache on data

### ISSUE THREAD

**Issue by Suni23** [Adamantcheese/Kuroba#1429]
If you're banned on wifi, and then switch to data/a different wifi connection and clear the cache, it will still say you're trying to ban evade.
If you go on a browser and use the data or different wifi connection, it works fine. Not sure what else could cause this, in the past clearing the cache would work fine.

**Comment by Adamantcheese** [comment]
Ban evasion detection probably got upgraded then. Stop being banned for stupid shit.
