### ISSUE TITLE
Captcha wont load,   " Could not do Cloudfare bypass"

### ISSUE THREAD

**Issue by xscaralienx** [Adamantcheese/Kuroba#1431]
it started happening about a week ago, I could no longer get the captcha to load and I always get the same error message about cloudfare bypass.

I'm on dev build v4.13.6-643c5ece

**Comment by shitbag6969** [comment]
Having the same issue at the moment,  same dev build

**Comment by clover-supply** [comment]
Same issue, same build. Even the workaround via report menu doesn't work.

**Comment by DarkTzitzimine** [comment]
Same issue here

**Comment by delta1991** [comment]
I am also having this issue
Does anybody know what to do?

**Comment by DarkTzitzimine** [comment]
People on 4chan are saying the issue is related to the custom UserAgent

>It's a pretty simple change to get it fixed too. Just drop the custom User Agent from the source code. 
>NetUtils.java has the global application user agent. You can probably set it to WebSettings.getDefaultUserAgent(AndroidUtils.getAppContext()), seems to work for me.

**Comment by Adamantcheese** [comment]
I'm aware of that because that's my post lmao

**Comment by delta1991** [comment]
How do you do that?
Sorry I'm a bit of a noob

**Comment by delta1991** [comment]
Help :(

**Comment by Adamantcheese** [comment]
Should be closed with 003fe47c0f0547c497aac5d3b10f2e30a2b28e30.
