### ISSUE TITLE
Can't post images on 4channel

### ISSUE THREAD

**Issue by shitbag6969** [Adamantcheese/Kuroba#1435]
After the new update to v4.13.6-003fe47c
Posting images on blue boards doesn't seem to work. I am able to post just text on both 4chan and 4channel, but attaching an image only works on 4chan. 
When posting with an image attached on 4channel, you get a confirmation it worked but no post actually happens.

**Comment by Adamantcheese** [comment]
Seems like some sort of anti-spam thing from Cloudflare or 4chan when you change user agents. Nothing I can do about it.

**Comment by shitbag6969** [comment]
Is there anything i can do on my end to bypass it? It started working after a few days but broke again after i updated to the newest dev.

**Comment by shitbag6969** [comment]
I ended up finding a work around, connecting to wifi seems to fix it.  You can go back to using mobile data anytime after,  i was only connected for a few moments.

**Comment by lewri** [comment]
Some more update observation from last August dev version:

- can't create a new post (on blue board at least, not checked red)
- you can put a text only comment on any board
- posting a comment with an image on a blue board reports a success message but the post doesn't actually happen (probably related)
