### ISSUE TITLE
Unable to load images - hash/checksum

### ISSUE THREAD

**Issue by jacob-kraniak** [Adamantcheese/Kuroba#1440]
![Screenshot_20231020-075024](https://github.com/Adamantcheese/Kuroba/assets/113630934/2e46a940-fe91-47bf-b4eb-c334217d7ef1)

Latest stable build. Running Android 13 on Pixel 7.

Occurs on all images, on all boards.

`
E/Kuroba | ConcurrentChunked FileDownloader: [FileCacheV2Thread-2]: Error while trying to download, class = FileHashesAre Different, message = Downloaded file's hash differs from the one we got from the server! E/Kuroba | ConcurrentChunkedFileDownloader: Something is Wrong with the file, use force reload! E/Kuroba | ConcurrentChunkedFileDownloader: expected = "31d2defd73209900fce61f2b6926e80d', actual = "b0e5a8636398fa50605053f84238523b", url https://i.4cdn.org/x/1697728024424XXX.jpg, file name = 51f7dOee64f3b5c2b77ee36c82ab41 3a.cache E/Kuroba FileCacheV2: (FileCacheV2Thread-2]: Exception for request [FileDownloadRequest: url https://i,4cdn.org/x/1697728024424XXX.jpg, outputFileName = 51f7dOee64f3b5c2b77ee36c82ab41 3a.cache], network class = WIFI, downloads = 2
E/Kuroba FileCacheV2: com.github.adamantcheese.chan.core.cache.downloader. FileCa cheException$FileHashesAreDifferent: Downloaded file's hash differs from the one we got from the server! E/Kuroba FileCacheV2: Something is wrong with the file, use force reload!
E/Kuroba | FileCacheV2: expected = "31d2defd73209900fce61 f2b6926e80d", actual "bOe 5a8636398fa50605053f84238523b", url https:/i4cdn.org/x/1697728024424XXX.jpg, file name = 51f7d0ee64f3b5c2b77ee36c82ab41 3a.cache
`

**Comment by Adamantcheese** [comment]
Cloudflare is recompressing the images and changing the hash as a result. Apparently setting concurrent chunk downloading to 1 might resolve it? Moving to dev will resolve the issue as well, because the hash checking code was removed.
