### ISSUE TITLE
Unable to use crash reporter

### ISSUE THREAD

**Issue by jacob-kraniak** [Adamantcheese/Kuroba#1441]
Name resolution issue with Kuroba.io, cannot report bugs/issues through app.

![Screenshot_20231020-075705](https://github.com/Adamantcheese/Kuroba/assets/113630934/b7d7758e-0ec8-45af-9291-59ee0ebc0333)

Latest stable build as of post date. 

Pixel 7 running Android 13.

**Comment by Adamantcheese** [comment]
I removed the crash reporting functionality a while ago in dev.
