### ISSUE TITLE
Make the countdown dynamic

### ISSUE THREAD

**Issue by floppyD** [Adamantcheese/Kuroba#15]
You could make it always appear instead of just when you press the post button, this way you can also start solving the captcha before it gets to 0.

**Comment by Adamantcheese** [comment]
Per #253, is that a sufficient solution to this problem? It kinda solves a superset of this problem so I'm willing to accept it as good enough to close this issue.

**Comment by floppyD** [comment]
That's doesn't really solves the problem, what I originally wanted was a countdown that is always visible (and updating) and doesn't stop you from posting. That would allow me to know if I can post without pressing the post button, and if I can't I could just switch to mobile data and post or at least start solving the captcha in the meantime.

**Comment by Adamantcheese** [comment]
Alright, just double checking.

**Comment by K1rakishou** [comment]
A lot of people are also asking to add the ability to post regardless of the cooldown. I guess we could add such ability for when you are using captcha queueing. Like, you queue a captcha the press post and it ignores the current cooldown. Or maybe just long click on the post button would be enough?

**Comment by floppyD** [comment]
Uh, just noticed this issue was closed. That wasn't what the issue originally asked.

To put it simply it would work like this:
You try to post something and the system answer you with something along the lines of "Error posting. You have to wait 59 seconds before posting", but then this text would stick and the timer would simply count down to 0, and after that the text would disappear.

Ex:
"Error posting. You have to wait 59 seconds before posting."
"Error posting. You have to wait 58 seconds before posting."
"Error posting. You have to wait 57 seconds before posting."
...
