### ISSUE TITLE
[BUG] Loaded images sometimes get stuck on displaying the thumbnail

### ISSUE THREAD

**Issue by Astridchan** [Adamantcheese/Kuroba#151]
Sometimes when you're swiping through loaded images, an image will open only to its thumbnail and not load the full resolution version. Closing and reopening the image, or swiping to the previous/next image and back will fix it.

Bug in action (notice there is no loading bar, images are fully loaded):
https://streamable.com/0609m

The bug happens both with media prefetch enabled and disabled.

**Comment by Adamantcheese** [comment]
This is the issue mentioned in #56, but I appreciate you putting in a separate issue for it. Likely related to #150, for the same reasons.

**Comment by Adamantcheese** [comment]
I'm still having this happen (albeit less now), so I'm going to reopen this.
