### ISSUE TITLE
[BUG] Text in text selection menu is illegible with dark/black theme

### ISSUE THREAD

**Issue by Astridchan** [Adamantcheese/Kuroba#152]
With the Black theme enabled, text in the text selection menu becomes white, which makes it illegible since the menu background is also white:

![IMG_20190630_030210](https://user-images.githubusercontent.com/40862101/60390660-034b5380-9ae4-11e9-8d82-f6228dac642b.jpg)

I looked more into it and it seems the font color in the text menu is chosen according to the font color of the currently set Kuroba theme:

![IMG_20190630_030246](https://user-images.githubusercontent.com/40862101/60390666-22e27c00-9ae4-11e9-8de8-964e5ed83eae.jpg)

![IMG_20190630_030304](https://user-images.githubusercontent.com/40862101/60390667-22e27c00-9ae4-11e9-91d7-84c174a15a8b.jpg)

On other apps with a dark theme, the text selection menu background is dark too (here's Google's Keep Notes app with dark mode enabled):

![IMG_20190630_030225](https://user-images.githubusercontent.com/40862101/60390677-6c32cb80-9ae4-11e9-8c4a-ffade78b4c31.jpg)

It's entirely possible this is an issue with MIUI rather than Kuroba. If that's the case, please ignore.

**Comment by ownBard** [comment]
Interesting, I'm on MIUI as well and this doesn't happen for me.

**Comment by Adamantcheese** [comment]
This appears to be specific to whatever you're running, as it looks like this on OxygenOS. I don't know what color asset it's pulling to make it white, as it should be black if it was pulling the background color for the theme. If it's possible to force it to use the proper color assets for the theme, that would be the best.
![Screenshot_20190629-171317](https://user-images.githubusercontent.com/9031585/60390706-5fd15300-9a91-11e9-936b-15f92c636bd8.jpg)

**Comment by Astridchan** [comment]
>Interesting, I'm on MIUI as well and this doesn't happen for me.

>This appears to be specific to whatever you're running

This is MIUI 10 / Android 9.0 on the Pocophone F1. Out of interest, what phone/MIUI version are you on, @ownBard?

**Comment by ownBard** [comment]
@Astridchan MIUI 10 / Android 8.0 on Mi5

**Comment by ownBard** [comment]
![RSVgWSlM](https://user-images.githubusercontent.com/51628221/60390778-9200a600-9acd-11e9-942d-2091d3efda7c.png)

**Comment by Adamantcheese** [comment]
Yeah I can't seem to force it to accept a different color in the theme. You're welcome to try yourself and submit a PR if you can fix it.
