### ISSUE TITLE
Cannot zoom gifs

### ISSUE THREAD

**Issue by ownBard** [Adamantcheese/Kuroba#154]
As intended or bug? Seems like it'd be nice to have.

**Comment by Adamantcheese** [comment]
Gifs have never been zoomable and won't be. Gifs that are one frame long are zoomable.

**Comment by ownBard** [comment]
@Adamantcheese Fair enough, but can we just make it so attempting to zoom doesn't close the gif? (Although I'm not sure how that would be done)
