### ISSUE TITLE
[BUG] filter pinned threads keep returning after being swiped away

### ISSUE THREAD

**Issue by Astridchan** [Adamantcheese/Kuroba#157]
Filter pinned threads that you have swiped away get re-bookmarked after performing certain actions in the app, such as changing the theme, enabling/disabling media prefetching, clearing image cache or updating the app (anything that restarts the app).

**Comment by Adamantcheese** [comment]
By design. If you want to, feel free to submit a PR with this change.

**Comment by ownBard** [comment]
Currently it would require either keeping track more information, which seems messy, or keeping track of post that have been unpinned which also seems kinda messy. Anyway @Adamantcheese shouldn't you leave an enhancement tag too if you be willing to merge it? I don't understand the protocol...
