### ISSUE TITLE
Multiple (You)s in a reply duplicates post in notification

### ISSUE THREAD

**Issue by namazso** [Adamantcheese/Kuroba#159]
title

**Comment by Adamantcheese** [comment]
Can you provide a screenshot or something? I think I know what you mean but I want to make sure.

**Comment by namazso** [comment]
![Screenshot_20190630-203437__01__01](https://user-images.githubusercontent.com/8676443/60402013-c3d74280-9b89-11e9-8583-d4f5c8488c25.jpg)
This is actually a single post, quoting me twice
