### ISSUE TITLE
[BUG] Zooming in on an image and back out again sometimes prevents you from swiping to another image

### ISSUE THREAD

**Issue by Astridchan** [Adamantcheese/Kuroba#164]
When you're zoomed in, swiping to next or previous image is disabled. I guess this is being done intentionally, to prevent from accidentally swiping to another image when you just want to move the zoomed image around, but when you zoom out, the app doesn't always recognise that you've zoomed out and still stops you from swiping to another image. Zooming in and out a couple of times fixes it:

![ezgif-2-eb20d0e46a37](https://user-images.githubusercontent.com/40862101/60585484-8694cf80-9d98-11e9-8851-69642c8c545f.gif)

(Alternatively, what could be happening here is simply that when you think you've zoomed out, the image is still sometimes zoomed in an unnoticeable amount (1-2 pixels), which is why you can't swipe to other images.)

The way Clover did it worked pretty well, I'm not sure why it was removed. With Clover, you can swipe to another image even when you've zoomed in, but to prevent accidentally swiping away from the image you're viewing, the first swipe on an zoomed image will _always only bring you to the edge of the image_, so to swipe past a zoomed image you need at least two swipes:

![ezgif-2-421ec7f8299a](https://user-images.githubusercontent.com/40862101/60586878-bc878300-9d9b-11e9-94bd-a18afd46c6be.gif)

**Comment by K1rakishou** [comment]
I haven't seen the code, but this is probably because of the floating value of the current scale not being equal to the MIN_SCALE when zooming out or something like this (like current scale is 1.00002 and MIN_SCALE is 1.0 so you have to be really precise otherwise it won't work). There is probably should be a little threshold after which the current scale will be set to the MIN_SCALE, like the snapping usually works.

**Comment by ghost** [comment]
This happens to me every time I zoom in on an image. I agree that the clover method of fixing this problem is pretty good.

**Comment by Adamantcheese** [comment]
Closed as of https://github.com/Adamantcheese/Kuroba/commit/373d809d4b4c9ffbcdbf41e4e488500fd28c0346.
