### ISSUE TITLE
Separate cooldown timer for replies and threads

### ISSUE THREAD

**Issue by Astridchan** [Adamantcheese/Kuroba#17]
On 4chan, replies and threads have their own separate cooldown timers, so it is possible to post a reply and then post a thread immediately after, or vice versa, without any delay in between. Kuroba does not discriminate between thread posts and reply posts, so it makes you wait the cooldown time even when it's not necessary.

**Comment by Astridchan** [comment]
@Adamantcheese 
Hey Cheese, it seems there has been a regression with this issue, it was fixed earlier but now posting a new thread will again make you wait 60 seconds to post a reply, like it was before the fix. Curiously it does not make you wait doing it the other way, you can still make a reply and then a new thread immediately after.

**Comment by Astridchan** [comment]
@Adamantcheese 
Sorry to keep bothering you with this but it's still broken on the latest Dev build.

**Comment by Adamantcheese** [comment]
Ya gotta tell me what's wrong from the last time this was adjusted. Also just submit new issues.

**Comment by Astridchan** [comment]
Sorry, it's exactly the same issue as before, seems your latest commit didn't fix it:
>posting a new thread will make you wait 60 seconds to post a reply

The cooldown is separate for posts and threads so you should be able to immediately post a reply after making a thread.
