### ISSUE TITLE
[IMPROVEMENT] Introduce Storage Access Framework

### ISSUE THREAD

**Issue by K1rakishou** [Adamantcheese/Kuroba#172]
So we can have the SD Card support and to prepare for the future Android R release where they introduce the Scoped Storage which will break everything for us. Also to refactor the file manipulation to use SAF. At least for saving threads/images/other files that take space.
Gonna implement it myself.

**Comment by Adamantcheese** [comment]
You may want to look at this stale branch from Clover by the way, Floens was trying to do this a while ago. https://github.com/Floens/Clover/tree/external-storage-support

**Comment by K1rakishou** [comment]
Thanks. I see there is a lot of code to handle SAF on both pre and post lollipop devices. Since we don't support pre lollipop devices we don't need that and it makes things a little bit easier. Btw, I already have SAF support for importing/exporting settings and file cache. What is left is thread saving, but it is not merged yet, and I guess that's it (Maybe I forgot something).
