### ISSUE TITLE
[Feature Request] Additional filtering options

### ISSUE THREAD

**Issue by powerLien** [Adamantcheese/Kuroba#173]
Some additional options for filtering that I think could be useful:
- Image filtering via md5 or sha1 hash. This could have both an option for all posts on a board and an option for only OP posts.
- Allow one to look at the content of hidden posts. As it stands now, you can't look at the content of a hidden post, which could be something you want to do in certain situations, ex: to read a thread that got caught in your filters, or to get better context about a conversation within the thread where at least one reply was caught in the filter. Perhaps this option could be in the menu in the top right corner of each post.
- Allow the user to toggle their filters on and off all at once (unfiltered vs filtered view). This could be useful to see if any posts the user might want to see have been caught in the filter.
- On a similar note: filtering groups that can be toggled on and off. This could be useful in cases where the user regularly swaps between types of posts they want to see and not see.

**Comment by Adamantcheese** [comment]
1) Will consider. The filtering system needs some amount of work.
2) This is already a feature that has existed since Clover? I have no idea what you mean, tapping a hidden thread/post unhides it.
3) This is already a feature in the filter menu. Bottom left button toggles all filters on/off.
4) If it is submitted as a PR I will merge it.

**Comment by powerLien** [comment]
2) It doesn't seem to work for me. Tapping a post only creates the expanding circle effect (not sure of the exact name) that happens when you tap on certain things. Might be a bug? Could be worth noting I'm using a Pixel 3, in that case

**Comment by ownBard** [comment]
Yes, tapping on a hidden post only unhides  if it was manually hidden — doesn't work on filtered posts, and same with *view removed posts*.

**Comment by Lapan** [comment]
Add a highlighting filter that moves the topic to the top of the catalog, in a similar way that the inline expansion and 4chanx do
