### ISSUE TITLE
[Feature Request] Make bold menu font toggleable

### ISSUE THREAD

**Issue by Astridchan** [Adamantcheese/Kuroba#177]
Kuroba 4.4.2 implements #148 and restores menu text to bold font like it was in Clover and pre-4.3.3 Kuroba versions. In my opinion the bookmark list looked better with the regular unbolded font as it was in 4.4.1 though, so it would be nice if there was an option to toggle between bold and unbolded menu text in the settings.

![Screenshot_20190709-182542_3](https://user-images.githubusercontent.com/40862101/60902737-ca944280-a278-11e9-9a4d-05f63811fd77.png)

Alternatively, rather than make a setting for it, you could just make the bookmarked threads font unbolded, and keep the menu fonts bold elsewhere:

![Screenshot_20190709-182542_2](https://user-images.githubusercontent.com/40862101/60902748-cf58f680-a278-11e9-8958-51233027b317.png)

**Comment by Adamantcheese** [comment]
Submit a PR.
