### ISSUE TITLE
[Feature Request] Group bookmarks by board, bookmark folders

### ISSUE THREAD

**Issue by Astridchan** [Adamantcheese/Kuroba#178]
As suggested in https://github.com/Floens/Clover/issues/671, https://github.com/Floens/Clover/issues/571 and https://github.com/Floens/Clover/issues/312.

The bookmark list becomes quite messy when you have a lot of threads bookmarked. It would be better if the bookmarks could be organized, either by automatically grouping them by board, or by allowing the user to organize bookmarks into custom folders.

**Comment by Astridchan** [comment]
>wontfix

Any comment why, @Adamantcheese?

**Comment by Adamantcheese** [comment]
It's mainly a technical issue. If you add in board folders (as in more cells to label groups of items, not actual tap open/close folders), then reorganizing your pins becomes a huge headache to keep consistent. Reorganizing them manually works fine for the majority of use cases and with a recent fix then your pins won't reorder themselves on restart. Per #283, I can add in the board code to the posts/images/page display underneath a pin, or I can add in some sorting options for the pins by replacing the current X button with a three dot menu that includes
1) Toggle all watching pins
2) Clear all bookmarks
3) Sort... (maybe a submenu? depends on how many sorting options there are)
   1) Sort by board code
   2) Sort by reply count
   3) etc. similar to the catalog sorting options
