### ISSUE TITLE
Replies window too small

### ISSUE THREAD

**Issue by namazso** [Adamantcheese/Kuroba#179]
![Screenshot_20190709-190603__01](https://user-images.githubusercontent.com/8676443/60908685-c833e780-a27c-11e9-8345-d43f23da7213.jpg)
It cut off the bottom and I can scroll in it

**Comment by Adamantcheese** [comment]
Resolved by https://github.com/Adamantcheese/Kuroba/commit/20a3203d5d137dcd456a284cae22e077a4383891
