### ISSUE TITLE
"App not installed" unless installed as system

### ISSUE THREAD

**Issue by 1sad** [Adamantcheese/Kuroba#18]
Trying to install normally fails and gives an "app not installed." message.
Installing as system app works, but updating through the app is not possible.

**Comment by yello23** [comment]
It fails to install on my device as well. I tried with ADB and I get: **failure [INSTALL_FAILED_MISSING_SHARED_LIBRARY]**

**Comment by Adamantcheese** [comment]
This is not a problem with the application itself. As far as I'm aware, all I needed to do was sign the release APK and you should be able to install it without much hassle. Anything else is a platform issue specific to your phone that I am unable and unwilling to assist with.
