### ISSUE TITLE
Clover 3.0.2 loads webms much faster than Kuroba 4.4.2

### ISSUE THREAD

**Issue by Pentaphon** [Adamantcheese/Kuroba#180]
Using the same Moto G4 on Wifi on a 200 MB/s connection, I notice that Clover loads webms much faster than Kuroba does when flicking through a long, extended series of webms. Clover will just load every webm almost instantly. When I switch to Kuroba, it will be ok for a minute or so but then will start to slow down and start loading webms at a very slow speed, where the progress indicator moves across the screen at a snails pace. I would then go back to using Clover on the same device after seeing this, and webms would again, load almost instantly. 

Does anybody else notice this on webm heavy boards like /wsg/ when flicking through an entire threads worth of webms?

**Comment by Adamantcheese** [comment]
See issue #150. I'm going to close this because discussion of this problem is more relevant in that issue.
