### ISSUE TITLE
[FEATURE] Scrollbar Toggle

### ISSUE THREAD

**Issue by udevnull** [Adamantcheese/Kuroba#182]
Scrollbar seems to be missing in the latest version. It would be nice to be able to toggle this on or off.

**Comment by floppyD** [comment]
A weird scrollbar is still better than no scrollbar, come on Cheese.

**Comment by K1rakishou** [comment]
Yeah, the main point of scrollbars for me is to see how far in the thread I'm and how far it is until the bottom.

**Comment by Adamantcheese** [comment]
I'm a bit annoyed at it as well, it was a test to see how it would be liked. It'll come back, but I'm going to fix the weird scrollbar size issue, which seems to be as easy as swapping out the layout manager with one with a couple overridden methods for the scrollbar thumb size and track length.

**Comment by Adamantcheese** [comment]
Closed as of https://github.com/Adamantcheese/Kuroba/commit/274408748324ebae7ee1238d050c11e46f6c84ba

**Comment by Adamantcheese** [comment]
Note: layout manager method didn't work. Tried a number of various other things, ended up going with this method, as the FastScroller doesn't ever call the extents method when calculating the extents, oddly.
