### ISSUE TITLE
Fix the share buttons

### ISSUE THREAD

**Issue by Lapan** [Adamantcheese/Kuroba#184]
![share](https://user-images.githubusercontent.com/5336032/60946855-9c057e80-a2ef-11e9-8bad-7056fad7006c.jpg)
Pic related, dashchan does it better

**Comment by Adamantcheese** [comment]
Submit a PR.

**Comment by Adamantcheese** [comment]
By default when you share an image, you will see what you've posted. If you turn on URL sharing, you will only get the share style on the left. You can find that setting under `Media -> Share URL to image`.
