### ISSUE TITLE
Change the name back to Kuroba ಠ_ಠ

### ISSUE THREAD

**Issue by chausies** [Adamantcheese/Kuroba#186]
Kuroba's a fantastic name that's a shoutout to Clover and 4chin's weeb heritage. On the other hand, what the hell is a 13Chag? And the leaves on the new logo look like the 9gag logo.

Literally who asked for this terrible change? At the very least, let this community vote on it by upvoting/downvoting this issue.

(P.S. aside from these subjective arguments, the name of the project is Kuroba on github, and many of the files (README, etc.) still reference this as Kuroba. What's more, the settings backup filename and photo folder were all under the name Kuroba, and none of them would migrate over with the useless name change to 13Chag. Basically, the name change causes a bunch of unnecessary trouble and mess)

**Comment by MilkyPL** [comment]
Don't worry, it's another autism attack from cheese, he'll revert it after a week just like he did with emojis

**Comment by pkly** [comment]
Yeah I just wanna say one thing:
Why.

**Comment by TacoTheDank** [comment]
I think it's 4chan + 9gag = 13 (4+9) chag (chan + gag), hence the 9gag logos as the 4chan clover leaves

It's still a stupid fucking name though lol

**Comment by ownBard** [comment]
>Let this community vote on it by upvoting/downvoting this issue.

I see what you did there.
