### ISSUE TITLE
Thumbnails aren't high-res with prefetch media enabled

### ISSUE THREAD

**Issue by floppyD** [Adamantcheese/Kuroba#187]
I dunno if this is a new issue or if it was introduced in the previous release, but thumbnails aren't displayed in high quality anymore when prefetch is enabled (#117 ). Already tried running 4.4.2 after clearing the cache but thumbs were still low quality. Pic related
![Screenshot_20190710-181501](https://user-images.githubusercontent.com/29208110/61006017-ba936600-a33f-11e9-8703-91d01564cff2.png)

**Comment by Adamantcheese** [comment]
Confirming that this is a new issue, appears even when prefetch is off. The issue mentioned only applied to the album view, not the catalog grid view.

**Comment by Adamantcheese** [comment]
Alright, this isn't an issue with prefetching. It's a similar issue to one that's been helpfully not reported as an issue despite me seeing it elsewhere, in that the album view images don't appear to be high resolution, despite the actual backing image being correct. Essentially, it's an issue with the rescaling being applied to make it fit into the view.
