### ISSUE TITLE
New post format is interfering with flags

### ISSUE THREAD

**Issue by perioloo** [Adamantcheese/Kuroba#188]
On boards with flags the new post format is interfering with flags on longer posts. I have provided a couple examples below.

![Screenshot_20190711-131106_cropped](https://user-images.githubusercontent.com/52796650/61071157-5f648080-a3de-11e9-923a-f6d564a82c76.png)
![Screenshot_20190711-131137_cropped](https://user-images.githubusercontent.com/52796650/61071167-64c1cb00-a3de-11e9-9ed6-0c0d4c716dd4.png)

**Comment by Adamantcheese** [comment]
Duplicate of #174 and #185.
