### ISSUE TITLE
[Feature Request] Catalog sorting by post activity

### ISSUE THREAD

**Issue by happapa** [Adamantcheese/Kuroba#189]
There is currently no good way to see which threads are the most popular/active within a board. It is possible to sort a thread catalog by bump order or the total number of replies, but neither of these gives a good picture of how fast the threads are moving. My proposed solution is to add a new sorting option in the catalog view that sorts threads based on their average post rate (number of replies / age of the thread). An example of this in action is [4stats.io](https://4stats.io/).

**Comment by Adamantcheese** [comment]
Err, do you want to check again? There's already a thread activity sort.

**Comment by happapa** [comment]
Well, crap. I only remember Clover not having it. Thanks for the hard work, closing.

**Comment by Adamantcheese** [comment]
That feature is thanks to K1rakishou, not me. You're welcome however.
