### ISSUE TITLE
[Bug] Fix thread thread activity sorting in catalog mode

### ISSUE THREAD

**Issue by happapa** [Adamantcheese/Kuroba#190]
Threads that have zero replies are currently being presented too high in the thread activity sorting order. It might be because the current implementation replaces 0 replies with 1 reply in the "comparator" function to avoid dividing by zero ([relevant commit](https://github.com/Adamantcheese/Kuroba/commit/5be577193ce609271c1746b1074fcbd2c37d72a7) ). Personally, I think zero reply threads do not have any activity at all and should be presented at the bottom of the sorting. Otherwise, they will pop up high in the catalog just because they're new, not because they're being active.

**Comment by Adamantcheese** [comment]
I can agree with that rationale. We can divide by "zero" instead, i.e. use some really small number like the minimum value of a float.

**Comment by K1rakishou** [comment]
@Adamantcheese But won't Float.MIN_NORMAL be converted to 0 since everything else is a long? Shouldn't you cast everything else to the float first?

**Comment by Adamantcheese** [comment]
Per Java's floating point division rules, any "mixed" equation (that is, a fixed point and a floating point being used in the same equation) will result in a floating point operation. In this case, the numerator is of type Long and the denominator is either of type Float or Integer. In the case of the denominator being a Float, which is what that commit does, the result of the division is a (very large) floating point number, which is cast to a long AFTER the division occurs. You can double check that by stepping through the debugger if you want.

**Comment by K1rakishou** [comment]
Oh, I see.
