### ISSUE TITLE
[BUG] Catalog "jumps" when opening images with immersive image gallery enabled

### ISSUE THREAD

**Issue by Astridchan** [Adamantcheese/Kuroba#195]
@K1rakishou:
When you open or close an image in the catalog mode with immersive mode enabled the catalog "jumps", or jerks up and down in the background. See:
https://streamable.com/00zlb

Immersive mode disabled for comparison's sake:
https://streamable.com/wrdx6

Bug is also present when opening images in the image gallery. EDIT: And in board mode and in threads.

I think what is happening is that when you tap to open an image the status bar gets hidden and in the split second it takes for the image to open, you see the app momentarily get resized to fill up the space the from the status bar being hidden, and resized again when the image is closed.

**Comment by Adamantcheese** [comment]
This is an issue with a feature that @K1rakishou added. Ask him to fix it.

**Comment by thereisanissue** [comment]
Should just handle the project to him since he seems to be the only one that knows what he's doing.

**Comment by Adamantcheese** [comment]
This is because the layout is changing from the usual decor + app view to a fullscreen view, you are correct. Not entirely sure how you want me to fix that though, I can't exactly ease it from non-fullscreen to fullscreen, it just changes immediately.

**Comment by K1rakishou** [comment]
I guess a possible solution would be to use android:fitsSystemWindows="true" for the MainActivity so that 
it always takes the whole screen space therefore it wouldn't need to resize itself when entering fullscreen mode.

**Comment by Astridchan** [comment]
@K1rakishou 
Sorry to bother you, but did you manage to figure anything out regarding fixing this? I know it's a small issue but I find it annoying enough that it prevents me from using immersive mode. It's one of those things that you cannot ignore once you've noticed it...

**Comment by K1rakishou** [comment]
@Astridchan 
Uhhh, no. I was fixing bugs in thread saving feature so I completely forgot about this issue. I made a new issue where I will try to fix it but no guarantees.

**Comment by Astridchan** [comment]
Okay, thanks for looking into it.
