### ISSUE TITLE
App is crashing while browsing threads/opening the gallery mode

### ISSUE THREAD

**Issue by floppyD** [Adamantcheese/Kuroba#197]
All logs report OOM by the looks of it, but this issue wasn't happening on previous versions, even on versions that were possible to have prefetching + hi-res thumbnails, so it isn't just my phone not having enough memory.
```E/Kuroba | UNCAUGHT: java.lang.OutOfMemoryError: Failed to allocate a 1160707 byte allocation with 925408 free bytes and 903KB until OOM
E/Kuroba | UNCAUGHT: 	at com.android.volley.toolbox.DiskBasedCache.streamToBytes(DiskBasedCache.java:329)
E/Kuroba | UNCAUGHT: 	at com.android.volley.toolbox.DiskBasedCache.get(DiskBasedCache.java:121)
E/Kuroba | UNCAUGHT: 	at com.android.volley.CacheDispatcher.run(CacheDispatcher.java:100)
E/Kuroba | UNCAUGHT: .
E/Kuroba | UNCAUGHT: ----------------------------------------
E/Kuroba | UNCAUGHT: END OF CURRENT RUNTIME MESSAGES
E/Kuroba | UNCAUGHT: ----------------------------------------
E/Kuroba | UNCAUGHT: .
E/Kuroba | UNCAUGHT: Android API Level: 25
E/Kuroba | UNCAUGHT: App Version: v4.4.3-dev Official
E/Kuroba | UNCAUGHT: Phone Model: Motorola MotoG3
```

**Comment by Adamantcheese** [comment]
You've posted half of a crash log, which is utterly useless.

**Comment by floppyD** [comment]
Well, that's everything that was on the log page. I can trigger a crash easily tho, wait a second.

**Comment by floppyD** [comment]
That's everything.
```E/Kuroba | UNCAUGHT: java.lang.OutOfMemoryError: OutOfMemoryError thrown while trying to throw OutOfMemoryError; no stack trace available
E/Kuroba | UNCAUGHT: .
E/Kuroba | UNCAUGHT: ----------------------------------------
E/Kuroba | UNCAUGHT: END OF CURRENT RUNTIME MESSAGES
E/Kuroba | UNCAUGHT: ----------------------------------------
E/Kuroba | UNCAUGHT: .
E/Kuroba | UNCAUGHT: Android API Level: 25
E/Kuroba | UNCAUGHT: App Version: v4.4.3-dev Official
E/Kuroba | UNCAUGHT: Phone Model: Motorola MotoG3
```

**Comment by floppyD** [comment]
The copy button isn't working as indeed by the looks of it.
![Screenshot_20190714-214505](https://user-images.githubusercontent.com/29208110/61191429-05cfb080-a681-11e9-9ef3-0c1a3f2e21ce.png)

**Comment by floppyD** [comment]
And this while browsing the gallery mode on basically any thread on /p/
![Screenshot_20190714-215105](https://user-images.githubusercontent.com/29208110/61191484-88587000-a681-11e9-975b-5119af4d0981.png)

**Comment by Adamantcheese** [comment]
I'm going to hazard a guess and say that it's attempting to rescale a whole bunch of 4K images every single render frame, which doesn't have the restriction on memory like the actual loader does. That makes it lag pretty hard, or crash if you don't have enough memory.

**Comment by Adamantcheese** [comment]
I'll also take a look at that copy issue, bit strange.

**Comment by Adamantcheese** [comment]
Yeah I can't reproduce that second issue. I've made one change but I have no idea if it'll help.
