### ISSUE TITLE
RTL override in filename

### ISSUE THREAD

**Issue by namazso** [Adamantcheese/Kuroba#199]
![Screenshot_20190718-082341__01](https://user-images.githubusercontent.com/8676443/61434138-7141a880-a935-11e9-9988-20ed1304c49e.jpg)
I'm not sure if this is how it's meant to be, but it isn't looking nice.
It shows normally in browser:
![Screenshot_20190718-082520__01](https://user-images.githubusercontent.com/8676443/61434216-a817be80-a935-11e9-8e54-9e029c737030.jpg)

**Comment by Adamantcheese** [comment]
Yeah that looks like it's rendering incorrect for sure. If you don't mind providing a link to that post so I can keep it loaded in an emulator for testing with, that would be nice.

**Comment by namazso** [comment]
https://boards.4channel.org/g/thread/71928805#p71929698

or you can just make your own by copypasting a right-to-left override character into any filename

**Comment by Adamantcheese** [comment]
Thanks, appreciate it.
