### ISSUE TITLE
[BUG] Tapping "X" clears all bookmarked threads, not just archived ones

### ISSUE THREAD

**Issue by Astridchan** [Adamantcheese/Kuroba#2]
On Floens' build of Clover, when you **tap** on the "X" next to the Bookmarked threads list, it clears *only* archived and 404'd threads. When you **hold** the "X" it clears *all* bookmarked threads (this behaviour requires that thread watcher is enabled). 

On your Clover build, when you tap on the "X", it will clear *all* bookmarked threads, but give you the message "No bookmarks cleared. Hold to remove all." If someone replies to your post after this, you will still receive a notification, so it would seem the threads aren't actually removed from the watch list, just hidden. If you then hold on the "X", the bookmarks that are now hidden will properly be removed. This video demonstrates the bug in action:
https://streamable.com/sbga8

Another anon pointed this out in a Clover thread on /g/:
>if you close and reopen Clover, the active threads show up again. so the button does delete the right rows from the db but also deletes all threads from the bookmarks bar temporarily.

I am submitting this here because Floens' build doesn't seem to have this issue.

**Comment by Adamantcheese** [comment]
Cool, I'll take a look. I never messed with that functionality directly, maybe another pull messed with it.

**Comment by Adamantcheese** [comment]
Issue was in https://github.com/Floens/Clover/pull/655. It's been fixed as of that commit above. New build is up as of this comment being posted.
