### ISSUE TITLE
Why are you willingly dropping support for API 21 and under?

### ISSUE THREAD

**Issue by floppyD** [Adamantcheese/Kuroba#20]
I just wanted to know, it doesn't seem to be any new feature that justify bumping the minimum SDK version.

**Comment by Adamantcheese** [comment]
![](https://upload.wikimedia.org/wikipedia/en/6/62/This_Is_America_%28single_cover%29_2018.jpg)

**Comment by floppyD** [comment]
Hmm, I understand.
