### ISSUE TITLE
[BUG] Text selection menu doesn't appear when long pressing on the new reply/new thread textbox

### ISSUE THREAD

**Issue by Astridchan** [Adamantcheese/Kuroba#202]
From time to time, the text selection menu (see picture) will stop appearing when long pressing on the new thread or new reply textbox. If there is text in the textbox, long pressing it will not highlight it. Once the bug occurs, the only way to make it work again is to close Kuroba by swiping it away from the recents menu and reopen it.

![42395348-418af008-8166-11e8-8803-da633744826c](https://user-images.githubusercontent.com/40862101/61467963-34050700-a985-11e9-9807-ebc254cc0cf7.png)

This is an old Clover bug that is still happening on latest versions of Kuroba, see:
 https://github.com/Floens/Clover/issues/183
https://github.com/Floens/Clover/issues/523

**Comment by ayy91** [comment]
Happens to me on two different phones. I don't know what triggers it but it seems to always happen after using the app or keeping it opened for a long period of time.

**Comment by Adamantcheese** [comment]
I suspect this is because the comment field uses a TextView instead of an EditText. Not sure why Floens decided to use that instead (and it's still like that in the current release of Clover), but I'll take a look and see if switching it over will solve it.

**Comment by Adamantcheese** [comment]
This was actually fixed in v4.10.0 but I didn't notice that there was an issue for this. See #425.
