### ISSUE TITLE
[Feature Request] Make hiding bookmarked threads from catalog optional

### ISSUE THREAD

**Issue by Astridchan** [Adamantcheese/Kuroba#203]
Please make hiding bookmarked threads from the catalog (https://github.com/Adamantcheese/Kuroba/issues/113) an optional feature. Sometimes the page number isn't enough and you want to know the exact position of a thread in the catalog. (+after implementing #113 bookmarked threads don't show up in search results which can be confusing).

**Comment by Adamantcheese** [comment]
Closed as of https://github.com/Adamantcheese/Kuroba/commit/77d5fafeae9bd3958e3ba32777595d7760c0ad5e
