### ISSUE TITLE
Number of new posts badge isn't updated

### ISSUE THREAD

**Issue by Adamantcheese** [Adamantcheese/Kuroba#205]
This is a regression caused by https://github.com/Adamantcheese/Kuroba/commit/bd10a51452304ce89d479bf1fad000e374254a26#diff-5397341e9eccd0a33e8f846b1878807e @K1rakishou; that total > 0 should not be there because the badge is cleared when total is 0.

**Comment by K1rakishou** [comment]
There probably should be an additional check because as it is right now, after your fix, the badge will be updated even if you have no pins that watch threads, but only pins that download them. I will look into it today.

**Comment by Adamantcheese** [comment]
The badge only applies to pins that are being watched. If no pins are watching threads, the total post count should always be 0 and always be invisible as a result. Unless you meant to tie it into thread downloading somehow, but that implementation wasn't correct.
