### ISSUE TITLE
[BUG] New posts counter doesn't have enough space

### ISSUE THREAD

**Issue by K1rakishou** [Adamantcheese/Kuroba#207]
Should be easy to fix by just adding more space for it. I have changed it because of the new icon but didn't expect that it may take this much space.

![1563604917938](https://user-images.githubusercontent.com/10332458/61575330-03cb7e80-aad3-11e9-9db5-2a7e7afee98b.png)

**Comment by Astridchan** [comment]
Somewhat related: it looks like the font of the bookmarked threads in the sidebar got smaller too, could that be restored back to its old size?

**Comment by K1rakishou** [comment]
Yes I made it smaller because otherwise with both icons visible there will be almost no space left for the thread title. I've also shifted the icon a little bit to the left. There is just almost no free space left. If someone can make a good design for this screen when both icons are visible (there is actually a third one that shows up when a thread gets archived) then I will be happy to implement it.

**Comment by Astridchan** [comment]
Couldn't the downloading icon just take 0 space until you actually start downloading and when you do start downloading just cut the thread title with "..." as already happens with long thread titles to make space for the downloading icon? Also, the downloading icon is kinda big, you could probably make that smaller.

**Comment by K1rakishou** [comment]
>Couldn't the downloading icon just take 0 space until you actually start downloading and when you do start downloading just cut the thread title with "..." as already happens with long thread titles to make space for the downloading icon? 


Well it already works like this right now. But still with the old font size there is little space left for the thread title. The pin list should be refactored anyway (so that you can group pins by site/board and shit) so I think we can leave this issue until then. But yeah, I guess I could make the icon a little bit smaller.
