### ISSUE TITLE
[IMPROVEMENT] Pins list is hard to scroll

### ISSUE THREAD

**Issue by K1rakishou** [Adamantcheese/Kuroba#209]
When you have a lot of pins, enough for the scrollbar to appear in the drawer, it's kinda hard to scroll down because, apparently, the drawer intercepts touch events and uses them to control the drawer's open/closed state. Some kind of touch slop should be added to ignore drawer's events and use them for the recyclerview scrolling instead.

**Comment by Adamantcheese** [comment]
I don't have this problem really, but then again I try to keep my bookmarks fairly clean. I don't see any mentions of this in Clover's issues either, and I would've expected someone to mention it there.

**Comment by K1rakishou** [comment]
Right now when you scroll either up or to the left the drawer takes the priority of the events for some reason. What I think of doing is to separate scroll events that are heading up and to the left and send events that are heading to the left into the drawer and ones that are heading up into the recycler. But yeah, it's strange that I'm the one who noticed it first and there seems to be no other people complaining about it. Maybe it's a better idea to not touch it?

![56456](https://user-images.githubusercontent.com/10332458/61613498-28a62a00-ac6a-11e9-8ede-178fe5dc69a1.png)

**Comment by Adamantcheese** [comment]
When I implemented the swipe up/down actions on gallery images I basically had the same conundrum. As you can tell by the lack of their existence now, it didn't work so well and had adverse effects on other unexpected items, zooming in particular. I expect a similar issue would arise for swipe deletion vs drawer control. Either way the drawer is going to consume the event first and see if it needs processing, as touch events are passed from root view to child in the view tree. You would need to be modifying the drawer controller itself to deal more finely with touch events before passing any unused touch events down to the child element. It's probably fine to not touch it, but if you want to you might want to take a look at the internals of that class to see how it's dealing with touch events, as well as the layout inspector to see view bounds and run through some methods manually to get a feel for it.

**Comment by K1rakishou** [comment]
Yeah, I will try to do it and if it won't work then I will leave it like it is.

**Comment by K1rakishou** [comment]
So I tried to implement this and it didn't work like I wanted it to so I'm going to close this and forget about it.
