### ISSUE TITLE
[Feature Request] webm streaming

### ISSUE THREAD

**Issue by ekisu** [Adamantcheese/Kuroba#21]

**Comment by Adamantcheese** [comment]
I'm guessing you want something like Overchan has. I don't know anything about JNI and that implementation uses ffmpeg to stream WEBMs. Also that would probably require a major rework of the way the app currently works.

**Comment by ekisu** [comment]
I'm pretty sure ExoPlayer can stream them, as I've tried to implement it once (it kinda worked, but ExoPlayer itself was pretty buggy - and I also couldn't make it work together with the file cache).

**Comment by Adamantcheese** [comment]
It had a couple bugs in it due to ProGuard really not liking HTTP requests on the main thread, but that was resolved.

**Comment by Adamantcheese** [comment]
As far as I can tell, no actual streaming is happening with the new method and it's just downloading it without any user facing status. I will be reverting those changes in the future if no further changes are made.

**Comment by ekisu** [comment]
It is streaming, it's just that it needs to do like 3 HTTP requests to even begin to stream (blame ExoPlayer for this) - and considering how shit 4chan servers are, latency easily becomes a bigger issue than network speed (if your connection is decent). I won't deny my implementation has its problems, especially when swiping through many WebMs really fast which seems to kill network performance.

Reverting is fine though, the old player is more polished and worked just fine for most people (which is why I made the change optional in the first place).

**Comment by Adamantcheese** [comment]
I'm going to chock it up to 4chan's servers being shit like usual and nothing wrong with your implementation. Even on a 100Mbps connection it was doing that waiting thing before showing me any video. It'll be reverted in the next update, but hang on to it in case it's ever needed. I'll be closing this request as it's been proven that despite the implementation being correct, the other end just doesn't want to deal with streaming the content in a reasonable manner.
