### ISSUE TITLE
[UI] Toolbar is collapsed when entering a thread with few posts

### ISSUE THREAD

**Issue by K1rakishou** [Adamantcheese/Kuroba#211]
Happens in the downloaded threads (maybe in normal ones too, didn't check it) when you switch from a thread while the toolbar is collapsed to the downloaded thread that has few posts (they all fit on the screen). I guess it's okay when you switch to a thread with a lot of posts and your are somewhere in the middle of a thread but in this case it looks kinda strange.

![45345345](https://user-images.githubusercontent.com/10332458/61577603-684a0600-aaf2-11e9-8e6b-79b59cf48484.png)

**Comment by K1rakishou** [comment]
Actually, it happens not only when you enter a thread with few posts but any thread. There should be a check that if we enter a thread and we are at the top of the thread and the toolbar is collaped - show the toolbar. If we are not at the top then do nothing.

**Comment by Astridchan** [comment]
I got this bug on v4.5.3, except the toolbar was collapsed in the catalog (can't remember if it was collapsed in threads too). Had to restart the app to get it to show again. Didn't have thread downloading enabled but I did enable the immersive mode to try it out, then disabled it again, and the toolbar was gone after that.
