### ISSUE TITLE
[Request] Sync Watched Threads with PC

### ISSUE THREAD

**Issue by seniorm0ment** [Adamantcheese/Kuroba#216]
Would it be possible to talk with 4chanX dev and see if there's some kind of way to setup a random generated key that a user types into Kuroba that can sync watched threads with one another?

Or maybe there's some other way to do it that wouldn't require the use of 4ChanX?
Either way I think it'd be a good feature to have. You wouldn't be signing into any accounts, it'd just be some kind of passkey. (Similar to how DuckDuckGo can import/export settings with a passphrase)

**Comment by Adamantcheese** [comment]
The solution you mention first would need to be a separate server running somewhere that would take care of handling a push from one device to another, even using DDG's method, which is beyond the scope of this application.

A workaround using some existing technology would be to open threads in your phone's browser (Chrome/Firefox, likely), and use a tab sync (Chrome has it built in iirc, Firefox you need to set up an account to sync) to get it from your phone to PC. If you want to do it anonymously then you'll have to set up your own server to handle the messaging, in whatever capacity it would be implemented.
