### ISSUE TITLE
[Feature Request] Thread stickying by user

### ISSUE THREAD

**Issue by Astridchan** [Adamantcheese/Kuroba#23]
Allow the user to manually sticky threads so that they appear at the top of the catalog. This feature could be accessible as an "sticky / unsticky" option in a thread's three dot menu in the catalog view. Additionally, a "Sticky post" option could be added to the filter options to automatically sticky threads that match the given string (alternatively, this feature could be combined with the "watch post" action so that watched/bookmarked threads are **also** automatically stickied to the top of the catalog).

>What is a "sticky"?
>"Stickied" threads are posts that are stuck (hence "sticky/stickied") to the top of a board's index page. A stickied thread is denoted by a small thumbtack icon placed next to its post number.

**Comment by Adamantcheese** [comment]
Bookmarks already cover this. Bookmark the thread you want and turn off the thread watcher for that specific thread. Filter watching acts like permanent stickies if your regex is good. Plus, threads are then stickied even if you're not on the board they're specifically for.
