### ISSUE TITLE
Removing a bookmarked thread delete files(thread) downloaded using incremental thread downloading

### ISSUE THREAD

**Issue by ugaugabuga** [Adamantcheese/Kuroba#231]
This also happens when I disable the experimental feature; threads downloaded by using this feature will be gone from phone.

**Comment by K1rakishou** [comment]
This is expected behavior. Otherwise there is just no way to access the downloaded thread once it's pin/bookmark is gone.

**Comment by ugaugabuga** [comment]
Okay. Closing the issue then.
