### ISSUE TITLE
[Suggestion] Give thumbnails some padding

### ISSUE THREAD

**Issue by Astridchan** [Adamantcheese/Kuroba#232]
Currently the thumbnails are aligned to the very top left corner of the post, but I think it would look a little better if there was a small amount of padding on the top, bottom and left edge of the thumbnail:

![xddd](https://user-images.githubusercontent.com/40862101/61895963-97aaa980-af1c-11e9-9c9b-90cb5a23c8f8.png)

![ezgif com-resize](https://user-images.githubusercontent.com/40862101/61896199-1d2e5980-af1d-11e9-809c-6ddeb44eccaf.gif)

Also, a minor bug I noticed that is related: 
When a post with an image is at the smallest possible height (0 or 1 line of text, no replies), the thumbnail goes on top of the bottom post divider line (it's really only noticeable when the image is the same color as the background color):

![Screenshot_2019-07-25-21-47-37-655_com github adamantcheese chan](https://user-images.githubusercontent.com/40862101/61900688-c6c61880-af26-11e9-8171-0e5c5f1d321f.jpg)

**Comment by Adamantcheese** [comment]
I'll add this as a setting with it defaulted to on.

**Comment by ownBard** [comment]
Any reason the setting was removed? I still preferred the flush version.

**Comment by Adamantcheese** [comment]
Felt it was better as a design choice rather than something the user should be able to control.

**Comment by ownBard** [comment]
Alright, that makes sense. I guess I just don't agree with the design choice.
