### ISSUE TITLE
[Feature Request] Move the thread archiver icon to left

### ISSUE THREAD

**Issue by floppyD** [Adamantcheese/Kuroba#239]
It's not like it'll be used more often than the bookmark button or the gallery button, moving it to a place that is harder to reach would be logical.

**Comment by Adamantcheese** [comment]
I'll wait until the archiver is mostly issue free before doing this.

**Comment by K1rakishou** [comment]
I guess now is a good time.

**Comment by gergesh** [comment]
Is it possible to perhaps put this change behind a switch? The buttons are very crammed right now on my 6" screen.

**Comment by Adamantcheese** [comment]
I'll bump up the spacing, I agree the icons are a bit too close together now. I use a OnePlus 6 by the way.
