### ISSUE TITLE
[Feature Request] Make the "banned" word a hyperlink to 4chan.org/banned

### ISSUE THREAD

**Issue by floppyD** [Adamantcheese/Kuroba#241]
Just like in desktop, that would avoid having to open the browser and typing the URL manually there.
![Screenshot_20190726-150527](https://user-images.githubusercontent.com/29208110/61972922-24a34080-afb9-11e9-96c5-1477484839cd.png)

**Comment by Adamantcheese** [comment]
If there's a "banned" page for all the sites currently implemented, please provide that list, as that would be a better solution than doing it just for 4chan.

**Comment by floppyD** [comment]
No idea, I only browse 4chan. By the way, I noticed that there's a 4channel.org/banned and a 4chan.org/banned, but I dunno if it's any different.

**Comment by Adamantcheese** [comment]
4channel redirects to 4chan after captcha verification.

**Comment by Pentaphon** [comment]
@floppyD @Adamantcheese Honestly, this seems very, very low priority to the point that it doesn't need to be added. The display is enough. Most people who get banned already have the banned page in their browser history.

**Comment by MilkyPL** [comment]
Most vichan based sites should use [site]/banned like 4chan. Lainchan definitely does, but arisu and dvach seem to use something else. Sushi is down right now and looks like 8chan is still dead

**Comment by Yoirkie** [comment]
stop posting C on /tv/ my dude...

**Comment by Adamantcheese** [comment]
I'm going to go with Pentaphon here, this feature isn't really necessary. If you're banned for whatever reason, just go to the website itself; and I can sense a slippery slope of "let me unban myself in the app".

**Comment by Adamantcheese** [comment]
Meh whatever, it's implemented but I won't work on it further; https://github.com/Adamantcheese/Kuroba/commit/d9cd26f50b1d986f467eca9199c87d7a4c694aa9.
