### ISSUE TITLE
Immersive mode gifs issue

### ISSUE THREAD

**Issue by ownBard** [Adamantcheese/Kuroba#250]
Trying open the image menu in immersive mode while viewing an animated gif will close the image viewer. Since animated gifs do not allow zoom they tend to be more sensitive to closing (#154).

The only way around this currently is by swiping back up after opening the menu. My suggestion is to be consistent with both webms and gifs by having *double tap to close* for all files that do not zoom.

**Comment by Adamantcheese** [comment]
Sure, that sounds like a good idea.

**Comment by ownBard** [comment]
Thanks!
