### ISSUE TITLE
[IMPROVEMENT] Add ability to enter multiple captchas before posting, use entered captchas until they expire

### ISSUE THREAD

**Issue by K1rakishou** [Adamantcheese/Kuroba#252]
UPD: For some reason one captcha cannot be used to make multiple posts right now. 4chanx just removes a captcha after the reply. I dunno whether it depends on the board or 4chan does not support it anymore (I tested it on /g/ and /qa/). So, for now, one captcha will be used to make one post. But you still will be able to enqueue multiple captchas. Once I figure out why it does not work (and if it is still possible) I will make captchas to be used until expired rather than one per a post.

**Comment by Adamantcheese** [comment]
Should I wait to pull this before you figure that issue out?

**Comment by K1rakishou** [comment]
I think, yes, let's wait a little bit.

**Comment by K1rakishou** [comment]
So, after a little bit of investigation, it looks like using one captcha for multiple posts is only possible with JS captcha. Doesn't work with forced (via 4chanx) no-js captcha. Nothing can be done about it. 
Don't merge this yet, though, because there is a tiny bug left that needs to be fixed.
