### ISSUE TITLE
[BUG] Minor UI glitch with hamburger menu icon

### ISSUE THREAD

**Issue by Astridchan** [Adamantcheese/Kuroba#256]
The hamburger menu icon has a dot behind the middle line:

![Screenshot_2019-07-30-20-29-29-618_com github adamantcheese chan](https://user-images.githubusercontent.com/40862101/62151353-cd7ad400-b308-11e9-9b50-41e7276dc733.jpg)

![1564487088516](https://user-images.githubusercontent.com/40862101/62151419-f0a58380-b308-11e9-9a21-4e39a572bd09.jpg)

It's not visible on smaller display sizes (in terms of DPI), I guess the scaling makes it completely hidden behind the hamburger icon:

![Screenshot_2019-07-30-18-23-02-029_com github adamantcheese chan](https://user-images.githubusercontent.com/40862101/62151983-39117100-b30a-11e9-9615-c788b9cff07f.jpg)

**Comment by Adamantcheese** [comment]
Interestingly the emulator only started showing this when I made a Pixel 3 emulator with 560dpi. My normal Pixel 2 emulator with xxhdpi didn't show this issue.
