### ISSUE TITLE
Permanent immersive mode issue

### ISSUE THREAD

**Issue by ownBard** [Adamantcheese/Kuroba#259]
When the keyboard is open it is possible to open an image without immersive mode taking effect for a few moments. If you then close the image viewer before the app catches up the status bar will be hide itself anyway and the app will stay in fullscreen.

**Comment by ownBard** [comment]
This issue is unchanged in v4.5.4 even though the keyboard closes.

**Comment by Adamantcheese** [comment]
I probably didn't understand the original issue, so I'll go back and take a look at it again.

**Comment by Adamantcheese** [comment]
Yeah I can't reproduce this issue the way I understand it. If you could provide a video or some instructions on how to reproduce it that would be very helpful.

**Comment by ownBard** [comment]
**Here is the whole bug in action: https://files.catbox.moe/0d4ecc.mp4
And here is just a partial: https://files.catbox.moe/gmy46y.mp4**

If the keyboard is open, the image viewer will not immediately go into immersive mode. If the image viewer is then closed during this time the permanent fullscreen bug will occur.

**Comment by ownBard** [comment]
(In the first link I'm also showing how to escape from the bugged state at the end.)

**Comment by Adamantcheese** [comment]
It looks like on whatever ROM you're running, the UI is triggering the UI change listener, which shows the display for 2.5 seconds before making it disappear. On the ROM I was testing with, this wasn't the case.

**Comment by ownBard** [comment]
I am using the release version.

**Comment by Astridchan** [comment]
I can reproduce this bug with both my Android 9.0 phone running MIUI and stock Android 7.0 tablet, albeit with different steps to reproduce it:

1. Enable immersive mode.
2. Open image. Status bar (and navigation bar) will be hidden.
3. Swipe down at the top of the screen to make status bar appear, *then* close the image.
4. After image is closed, status bar will display momentarily, then disappear.
5. You're now in permanent immersive mode.

Video of bug in action: https://streamable.com/h8d60

**Comment by Adamantcheese** [comment]
Figured it out and can reproduce it. Probably know how to fix it.

**Comment by ownBard** [comment]
@Astridchan Good point. The bug occurs whenever the UI tries to return to fullscreen mode after the image viewer has been closed. I think I was fixating too much on the strange keyboard behaviour.

**Comment by Adamantcheese** [comment]
It wasn't how I expected to fix it, but it's way better than my original idea of thread interrupts.
