### ISSUE TITLE
[Feature Request] Archive threads

### ISSUE THREAD

**Issue by floppyD** [Adamantcheese/Kuroba#26]

**Comment by Adamantcheese** [comment]
I have no clue what this is supposed to mean.

**Comment by floppyD** [comment]
Save them, so you can still read even after they get 404'd or when there's no connection is available.

**Comment by Adamantcheese** [comment]
I mean, they're saved right now just unviewable because all the images wouldn't load anyways, do you want to get rid of the 404 screen or actually pull from the archives?

**Comment by floppyD** [comment]
I think the anon that asked for this feature probably wanted to save a copy of the thread on its current state by choosing an option, so he could read it later even after it gets deleted. But I think saving the thread + current thumbnails and fetching "new" replies + redirecting images to some external archive if network is available would be a nice idea too. But it's up to you.

**Comment by Adamantcheese** [comment]
For now they'll have to live with using the external archives. I'll leave this open.
