### ISSUE TITLE
[Bug] Symbol ">" in regex

### ISSUE THREAD

**Issue by ownBard** [Adamantcheese/Kuroba#261]
I can't get filters to work with `>` or `&gt;` in the latest update. Am I doing something wrong or are they not escaping properly?

**Comment by Adamantcheese** [comment]
I'll double check it, but for anything that isn't a watch filter it should automatically escape HTML characters for you, i.e. `>` will be translated to `&gt;` internally.

**Comment by Adamantcheese** [comment]
Well there was an issue with the filter test not properly displaying if something would or wouldn't match, but otherwise it seems to be working correctly. If you have a highlight filter that you change, you'll need to reload a thread to have it apply.

**Comment by ownBard** [comment]
Ah alright. Thank you.

**Comment by ownBard** [comment]
I tested a bit more and using `^` operator with `>` there also seems to be some issue.

**Comment by Adamantcheese** [comment]
I'll test some more. Trying to change a few oddities in the filter stuff anyways.

**Comment by Adamantcheese** [comment]
Ah, I'm escaping the entire string as if it were HTML when I really shouldn't be; `/^test$/` would compile to `&hat;test&dollar;`, which is incorrect as it should compile to `^test$`.

**Comment by Adamantcheese** [comment]
Rather than escaping entities in the pattern itself, I'm changing it to unescape the text being matched against. That should be far more compatible than implementing a bunch of workarounds.

**Comment by ownBard** [comment]
Good thinking!

**Comment by ownBard** [comment]
In v4.5.4 there is still an issue with using `>` with `^` operator. It now works fine in the filter test but still not on actual posts.

**Comment by Adamantcheese** [comment]
If you could provide the regular expression you're using, complete with the slashes, that would help me debug. I'm assuming it's something like `/^>>\d+$/i`, which would match all replies, which is what I'll test with for now.

**Comment by ownBard** [comment]
Usually something like `/^>test/i` and then just replace `test` with whatever I'm testing. Even something simple like `/^>/` or `/^>.*$/` will match in the filter test but not for any posts.

**Comment by Adamantcheese** [comment]
Alright, appreciate it.

**Comment by Adamantcheese** [comment]
This is a note for me tomorrow, but it's filter matching on the raw post data coming from the server, so even something basic like `>>123456` is coming in as `<a href=\"#p123456\" class=\"quotelink\">&gt;&gt;123456</a><br>`, which is probably why it's not right at all; the >> isn't at the start of the string, the <a> tag is. Dumping it through to HTML and then just taking the text out of it without the spans will probably fix this?

If you want a workaround for now, you can probably use `/^<.+?>>/` to avoid any starting tags.

**Comment by Adamantcheese** [comment]
Additional info: because of the `<br>` tags, "start of line" i.e. the ^ symbol, probably only applies to the whole post because it's currently a single line, so if it's a bunch of replies followed by greentext then you probably want to use `/^(<.+?>.*?)+?>/`

**Comment by Adamantcheese** [comment]
Alright, so the test regex I'm using is `/(?<!>)>(?!>).*/`, which should only match posts with greentext in them, which works as of this fix.

Note that because the entire post comment is contained in a single string, if you want to match a single line in the comment body that may or may not start at the beginning of the comment, using `\n?>` instead of `^>` is the way to do it. Maybe that can change later to split up the post comment on newlines and match against all of them, but for most people's purposes the filtering should work well enough now. If you do want that feature, submit a new issue please!

**Comment by ownBard** [comment]
Thank you! I honestly prefer them not being split up. On 4chan for example that's how it works by default.

**Comment by Adamantcheese** [comment]
Also probably don't try that crazy regex on the current version. It probably won't work anyways.
