### ISSUE TITLE
[BUG] Pins reordering only works on second attempt

### ISSUE THREAD

**Issue by K1rakishou** [Adamantcheese/Kuroba#264]
STR:
- Have couple of threads pinned
- Change the order of a pin
- Close the app (swipe to close)
- Open the app again
- Pin ordering didn't change
- Try changing it again
- Restart the app again
- Now the ordering should be changed

**Comment by K1rakishou** [comment]
I am currently on my custom test branch so it may not be reproducible in the release. But I think it should be.

**Comment by K1rakishou** [comment]
This is reproducible on the main branch.

**Comment by K1rakishou** [comment]
It looks like pins in the drawer and in the watch manager are not the same pins (more like a copy) and when you exit the app the pins in the db with the right ordering are getting overwritten with pins with wrong ordering.

**Comment by Adamantcheese** [comment]
Ah, alright. I'll take a closer look and see what's exactly wrong.

**Comment by Adamantcheese** [comment]
I can confirm those steps reproduce the issue, taking a look at it now.
