### ISSUE TITLE
Thread downloader notification issue

### ISSUE THREAD

**Issue by ownBard** [Adamantcheese/Kuroba#265]
Thread downloader sometimes appears in notifications even when the feature is disabled.

**Comment by K1rakishou** [comment]
You mean the message "Downloading N threads?". Have you used the thread downloading at least once and then turned it off or you haven't used it at all and it appeared out of nowhere?

**Comment by ownBard** [comment]
Haven't used it at all and it appeared out of nowhere.

**Comment by K1rakishou** [comment]
I guess it was something like "Watching N posts, Downloading 0 posts"? Because if there was any number other than zero then it's super strange.

**Comment by ownBard** [comment]
I've had it happen a few times now. I didn't notice if it ever changed from 0 posts.
