### ISSUE TITLE
[BUG] Bookmarked thread reply count doesn't subtract deleted posts

### ISSUE THREAD

**Issue by Astridchan** [Adamantcheese/Kuroba#271]
Thread below had 203 replies, of which two were deleted. The reply count at the bottom of the thread displays the reply count with **deleted posts subtracted**:

![Screenshot_2019-08-04-13-27-45-991_com github adamantcheese chan](https://user-images.githubusercontent.com/40862101/62422481-21e0d380-b6bc-11e9-965f-8eedf88fda25.jpg)

The reply count in the bookmark list displays the reply count with **deleted posts included**:

![Screenshot_2019-08-04-13-28-02-124_com github adamantcheese chan](https://user-images.githubusercontent.com/40862101/62422475-142b4e00-b6bc-11e9-8b64-33665195e53b.jpg)

**Comment by Adamantcheese** [comment]
Since I changed the number it's grabbing from to be the internally saved number in #257, I'll leave this open and see if this issue still occurs. That may have fixed it though.

**Comment by Adamantcheese** [comment]
@Astridchan if you could give me an update (to double check my tests) to make sure this was fixed then that would be great.

**Comment by Astridchan** [comment]
The issue is still present in v4.5.4.

**Comment by Adamantcheese** [comment]
Alright, when there's no thread loaded it'll use the pin's database value for how many posts were in the thread, but if it's loaded then it'll get whatever the latest information is from the thread. So it should be more consistent now and give some indication of what it was if you close the app for whatever reason.
