### ISSUE TITLE
[BUG] Another glitch with hamburger menu icon

### ISSUE THREAD

**Issue by Astridchan** [Adamantcheese/Kuroba#274]
The bottom bar of the hamburger menu is now different to the other two, thicker and rounded:

![1565000573595](https://user-images.githubusercontent.com/40862101/62458465-ad726700-b785-11e9-8d8d-90776debbbba.png)

I guess due to the changes in https://github.com/Adamantcheese/Kuroba/commit/3932062e812a71d9ee55db2959c9dd6d10854956 to fix https://github.com/Adamantcheese/Kuroba/issues/256.

**Comment by Adamantcheese** [comment]
I was testing this on the Yotsuba theme so I didn't catch it. Will fix real quick.
