### ISSUE TITLE
[BUG] When you open a thread after search, back button takes you to catalog, not back to search results

### ISSUE THREAD

**Issue by Astridchan** [Adamantcheese/Kuroba#276]
Issue as described by anon:

\>search for a thread, ie: stallman
\>Get two stallman threads in the list
\>Tap into the first one
\>Use system back button
\>It goes back to the catalogue, not the search results for stallman

The bug occurs when the app is set to phone layout. In slide layout pressing the back button brings you back to the search results as expected.

**Comment by Adamantcheese** [comment]
I double checked this when I implemented that for all the layout modes (slide/split/phone), as they all needed different implementations to get it to work right, but something seems to have messed up with it. I'll check it out.

**Comment by Adamantcheese** [comment]
This solution works, but I'm not sure if there are any strange side effects as a result. Didn't seem to be in my rudimentary tests.
