### ISSUE TITLE
[Suggestion] Captcha button inactive

### ISSUE THREAD

**Issue by ownBard** [Adamantcheese/Kuroba#277]
The captcha button is redundant on sites that do not use captcha (e.g. lainchan and arisuchan) or when using a 4chan pass. My suggestion is:

- grey-out / cross-out the captcha button whenever captchas aren't needed
- on 4chan use long press to toggle pass (as suggested in #112) and re-enable captcha

**Comment by Adamantcheese** [comment]
The first one will be implemented, the second one is slightly unintuitive and I'll leave that implementation separate to this one.

**Comment by ownBard** [comment]
That's fine by me. Thanks!
