### ISSUE TITLE
[BUG/REGRESSION] Go to post via a link doesn't work anymore

### ISSUE THREAD

**Issue by K1rakishou** [Adamantcheese/Kuroba#279]
STR:
- Click a link that should bring you to a certain post in a thread (e.g. https://boards.4channel.org/g/thread/11223344#p11223345)

Expected:
Link should bring to the post. Post should be highlighted.

Actual:
The thread is opened at some other random post (or even at the OP).

The same thing works in Clover (Actually it only works the first time, after that it has the same bahavior as Kuroba).

**Comment by Adamantcheese** [comment]
Testing https://boards.4channel.org/qa/thread/3131228#p3136185
