### ISSUE TITLE
[BUG] Unhidable snackbar with last posts info

### ISSUE THREAD

**Issue by K1rakishou** [Adamantcheese/Kuroba#289]
![5345](https://user-images.githubusercontent.com/10332458/62787298-15e67e80-bacd-11e9-9133-0ac73534b171.png)

I don't have the STR for this one. I was just switching through pins and then I noticed that this thing got stuck and wouldn't hide itself. Switching to a different thread with new posts would show the second snackbar which would hide itself normally but this one would still stay. This happened on my test branch where I'm testing thread downloading, btw.

**Comment by Adamantcheese** [comment]
That's really weird; I'll leave this open but it's such a minor thing that it'll be one of those "look at it when you just want to fix something small" type bugs.

**Comment by Adamantcheese** [comment]
This probably fixes it, but because there's no real reproduction method I can't really test it.
