### ISSUE TITLE
[BUG] Watching 0 threads, Downloading 0 threads

### ISSUE THREAD

**Issue by Jamayyy** [Adamantcheese/Kuroba#291]
After going back to the Android homescreen, the Kuroba notification turns to 
_Watching X threads, Downloading 0 threads
[Stop watching]_
After clicking the _stop watching_ button, it will now say "Watching 0 threads, Downloading 0 threads" and the button disappears.
Expected behaviour: The whole notification dissappears, because nothing is being watched.
Actual behaviour: The notification is still there. It's impossible to remove the notification. I can't slide it away. It remains for hours. Not even killing all apps from RAM removes the notification. It stays until I reboot the phone.

Here is a picture of the notification that never goes away: https://i.imgur.com/UixJIqE.png

I have at some point enabled thread downloading, and then disabled it again. It is currently disabled.
The bug has existed for a couple of weeks / versions now. I'm on Android 8.1.0, if that's relevant.

**Comment by Adamantcheese** [comment]
@K1rakishou is this fixed with #247?

**Comment by K1rakishou** [comment]
Yeah, should be fixed.

**Comment by Adamantcheese** [comment]
Alright, I'll assign this to you so I can keep track in my update log.
