### ISSUE TITLE
[Feature Request]  Save images on extenal memory

### ISSUE THREAD

**Issue by Gifkun** [Adamantcheese/Kuroba#30]
Just like Clover this app can't save files to external memory. If implemented it would help many move from clover since the creator doesn't want to implement this feature.

**Comment by Adamantcheese** [comment]
Use [FolderSync](https://play.google.com/store/apps/details?id=dk.tacit.android.foldersync.lite&hl=en_US) as a workaround. SD cards are annoying to code for, [as you can see here.](https://stackoverflow.com/questions/40068984/universal-way-to-write-to-external-sd-card-on-android)

**Comment by floppyD** [comment]
Can't you just call Storage Access Framework tho? Basically every single app I know that stores stuff on the internal memory use this, it allows you to choose the exact path you want to save your files, including external storage. Doesn't seem to be hard to implement, we aren't on KitKat anymore.

**Comment by Adamantcheese** [comment]
If it isn't hard to implement then someone else can do it. I don't have a device or a way to test SD card support reliably.

**Comment by floppyD** [comment]
Fair enough. But just so you know, that's how it looks like when implemented:
[https://www.youtube.com/watch?v=0MCNri1JzCk](url)

**Comment by Adamantcheese** [comment]
Submit a pull request if this feature is implemented. I myself won't be implementing this.
