### ISSUE TITLE
404 on every thread of the lainchan's /mega/ board

### ISSUE THREAD

**Issue by pExeen** [Adamantcheese/Kuroba#300]

**Comment by ownBard** [comment]
All multiboards / overboards are currently broken or unsupported.

**Comment by Adamantcheese** [comment]
Multiboards/overboards with a threads.json are supported, however the site itself does not redirect threads and therefore will 404 all threads. Because threads.json doesn't provide the actual board it is posted on, the site itself must change before I can do anything about this.
