### ISSUE TITLE
[Feature] Add board names above threads of "mega" boards

### ISSUE THREAD

**Issue by pExeen** [Adamantcheese/Kuroba#301]
On boards like /mega/ from lainchan it would be nice to see the name of the board the thread comes from, this is also shown on lainchan's site for example.

Thanks for this cool fork btw

**Comment by Adamantcheese** [comment]
Multiboards/overboards with a threads.json are supported, however the site itself does not redirect threads and therefore will 404 all threads. Because threads.json doesn't provide the actual board it is posted on, the site itself must change before I can do anything about this.
