### ISSUE TITLE
Keyboard stays open without focus

### ISSUE THREAD

**Issue by ownBard** [Adamantcheese/Kuroba#303]
The keyboard doesn't close when no input field (posting window, searchbar etc.) is focused. It wouldn't surprise me if it was phone-specific but it is kind of unpleasant anyway.

Focused:
![xaMcenDn](https://user-images.githubusercontent.com/51628221/63203410-c3820080-c07e-11e9-8bb8-5d822ecc52ad.png)

Unfocused:
![zEOwgDQH](https://user-images.githubusercontent.com/51628221/63203412-c8df4b00-c07e-11e9-95ed-c4b19d2f0f0b.png)

**Comment by Adamantcheese** [comment]
If you could provide some sort of reproduction for this that would be nice, because I couldn't get the search bar to unfocus.

**Comment by ownBard** [comment]
**https://files.catbox.moe/z2uynn.mp4**

Is this helpful? I'm just tapping away from the input field and it works the same with the posting window. I'm using MIUI 10 if that makes any difference.

**Comment by Adamantcheese** [comment]
Yep that helps.

**Comment by ownBard** [comment]
**https://files.catbox.moe/u937g5.mp4**

**Comment by Adamantcheese** [comment]
I mean, I can't really help more than literally telling it "if this search unfocuses, close the keyboard". Works on emulator and OxygenOS.

**Comment by ownBard** [comment]
You fixed the searchbar, not the posting window.

**Comment by Adamantcheese** [comment]
Oh didn't notice that. Will do.
