### ISSUE TITLE
[Feature Request] Immersive Mode Hold Down

### ISSUE THREAD

**Issue by seniorm0ment** [Adamantcheese/Kuroba#310]
Can you make the option where if you hold down on an image, it puts the gallery into immersive mode, then you hold down again and it toggles off immersive mode?

Its annoying to keep swapping in settings when you want to download an image or something.

**Comment by ownBard** [comment]
The menu can already be opened in immersive mode from the top of the screen.

**Comment by seniorm0ment** [comment]
@ownBard where is this option, I still dont see it

**Comment by Adamantcheese** [comment]
You swipe from the top of the screen. https://developer.android.com/training/system-ui/immersive#immersive
