### ISSUE TITLE
Can't open external links on pinned post.

### ISSUE THREAD

**Issue by generoberts** [Adamantcheese/Kuroba#326]
For example, on /sci/ https://boards.4chan.org/sci/thread/5942502#p5942502 when clicking the external link, nothing happend.
This happens on the following pinned posts of these boards as well:
/g/ https://boards.4chan.org/g/thread/51971506#p51971506  

/t/ https://boards.4chan.org/t/thread/687343#p687343  

/u/ https://boards.4chan.org/u/thread/2324624#p2324624  

These are what I have tested but may be happen to other boards too.
What's weird is pinned post on /int/ https://boards.4chan.org/int/thread/13531746#p13531746 doesn't have this problem.

I'm using version 4.6.0 with setting "ask before opening links" enable.

**Comment by Adamantcheese** [comment]
There's also another small issue for /g/'s sticky in that the >>>/g/catalog will say "No applications available to open this link", but it's such a corner case that I'm not going to fix that.
