### ISSUE TITLE
Searching for board doesn't show all the matched boards

### ISSUE THREAD

**Issue by generoberts** [Adamantcheese/Kuroba#328]
Ex. Search for /jp/ -> type "j" will show no results -> type "jp" will show the board /jp/
Search for /vip/ -> type "v" will show /vip/ among other boards -> type "vi" shows fewer board but doesn't show /vip/ -> type /vip/ shows /vip/
Search for /soc/ -> type "s" will show /soc/ among other boards -> type /so/ doesn't show /soc/ but show /hm/ and /hr/ -> finally type /soc/ shows /soc/

**Comment by Adamantcheese** [comment]
This fix will also be ported to the super-patch branch for Clover.
