### ISSUE TITLE
Archived bookmarked thread with unread (You) no longer has red numbers

### ISSUE THREAD

**Issue by stradus64** [Adamantcheese/Kuroba#329]
With thread watcher on the back arrow on top left has red dot if you have unread (you), same for alive bookmarked threads, red font to show you have (you), archived ones don't turn red anymore so it's harder to find now. Maybe the red for archived threads could be darker too to show it has (you)s but also is archived?

**Comment by K1rakishou** [comment]
>Maybe the red for archived threads could be darker too to show it has (you)s but also is archived?

Nah, we already do grey out the thread icon in the pins list when it gets archived so I think this is enough. But the counter not being red when you have yous and a thread is archived is not good.
