### ISSUE TITLE
More html formatting support

### ISSUE THREAD

**Issue by ownBard** [Adamantcheese/Kuroba#331]
Currently bolded text is supported but other simple things such as coloured text, italics, strikethrough, underline would be nice to have too. The one thing I think couldn't be supported is text size. On 4chan these are mostly reserved for staff but for some chans things like italics are quite common.

**Comment by ownBard** [comment]
Only remembered about this because of #330 which would probably fall under this if you chose to implement it.

**Comment by Adamantcheese** [comment]
Italics, strikethrough, and underline are all supported and must be implemented by the individual sites as the HTML for each site varies.

**Comment by ownBard** [comment]
Ah I see, thanks. I would like to look into it for those sites but I don't think I'd understand anything. I'm fine with leaving it for now.
