### ISSUE TITLE
[BUG] Search layout covers text in reply layout

### ISSUE THREAD

**Issue by Astridchan** [Adamantcheese/Kuroba#334]
![Screenshot_2019-08-26-15-48-24-785_com github adamantcheese chan](https://user-images.githubusercontent.com/40862101/63693615-3a588f80-c81d-11e9-875c-26eb7b45c1f3.jpg)

Do we really even need the white search info box that pops up? The text could just go in the search box itself:

![Screenshot_2019-08-26-15-48-24-785_com github adamantcheese chan](https://user-images.githubusercontent.com/40862101/63694171-82c47d00-c81e-11e9-85d6-9d73ecf7acf9.jpg)

![Screenshot_2019-08-26-15-49-05-119_com github adamantcheese chan](https://user-images.githubusercontent.com/40862101/63694187-8a842180-c81e-11e9-9761-c97a5bb1b917.jpg)

**Comment by Adamantcheese** [comment]
This is such a minor thing that I'm just not going to fix it this time.
