### ISSUE TITLE
[RESEARCH] Figure out whether it's possible to fix #195 by using android:fitsSystemWindows=true

### ISSUE THREAD

**Issue by K1rakishou** [Adamantcheese/Kuroba#338]
Relates to #195

**Comment by Adamantcheese** [comment]
Just a thing to jumpstart your research, setting that in `controller_navigation_drawer.xml` under the id `drawer_layout` or `container` will prevent that jump, however then the UI when opened back up will end up underneath the decor view once it appears. Also it leaves behind a gross sliver of the background color where the decor view was.

**Comment by Adamantcheese** [comment]
This does not work as mentioned above.
