### ISSUE TITLE
[Feature Request] Make changing the order of filters possible

### ISSUE THREAD

**Issue by floppyD** [Adamantcheese/Kuroba#34]
It's only possible to change their order by deleting them. It would be nice if you could change their order just like you can change the bookmarks order.

**Comment by Adamantcheese** [comment]
Is there any reason to reorder filters though? They're basically set and forget, I basically never look at mine and I can just read them if I need to change them.

**Comment by floppyD** [comment]
I dunno, just asking for some anon. Maybe consistency?
