### ISSUE TITLE
Can't add 55chan to kuroba 

### ISSUE THREAD

**Issue by bkdwt** [Adamantcheese/Kuroba#344]
Hi. I don't remember what last version worked, but in the last update I can't add 55chan on boards list. 
![Screenshot_20190829-145302](https://user-images.githubusercontent.com/51302074/63964472-8f8ae000-ca6d-11e9-8448-c1bea156d1de.jpg)

See on attached image. Thanks in advance!

**Comment by Adamantcheese** [comment]
55chan was removed in [v4.6.0](https://github.com/Adamantcheese/Kuroba/releases/tag/v4.6.0).

**Comment by bkdwt** [comment]
Thanks for support, cheese.
