### ISSUE TITLE
[Feature Request] Provide an option to enable/disable saving duplicate images 

### ISSUE THREAD

**Issue by Nbotz** [Adamantcheese/Kuroba#35]
One of my favorite features was the prevention of saving duplicate images. I understand some people like to be able to save dupes, but it would really be great if you could provide an option to enable/disable the use of duplicate images.

**Comment by Adamantcheese** [comment]
This was resolved in https://github.com/Adamantcheese/Kuroba/commit/2bde753c4c0619802c5aeed80cd4bff976034d2b, which will be released in 4.0.10.
