### ISSUE TITLE
Add option to disable copy URL when holding on an image.

### ISSUE THREAD

**Issue by Yoirkie** [Adamantcheese/Kuroba#350]
There are times where I scroll slow, and I accidentally copy a lot of URL due to this.

**Comment by K1rakishou** [comment]
Is this really that critical? I mean they should replace each other and even then who cares?

**Comment by Yoirkie** [comment]
> 
> 
> Is this really that critical? I mean they should replace each other and even then who cares?

i find it annoying and accidentally sending links to people instead of something else I thought i had saved.

**Comment by K1rakishou** [comment]
Well I guess why not.
