### ISSUE TITLE
[BUG] Time starts at 60 minutes.

### ISSUE THREAD

**Issue by Yoirkie** [Adamantcheese/Kuroba#355]
Instead of a thread saying "Posted 1 minute ago" it shows me "Posted 59 minutes ago"
This has shown me on 2 different devices.

**Comment by Adamantcheese** [comment]
When does this occur? New thread post?

**Comment by Yoirkie** [comment]
Yes, and whenever i open any thread.

**Comment by Adamantcheese** [comment]
What site as well, because as far as I can tell, there's nothing wrong. The code hasn't changed since Clover so it would happen there as well. Likely it's a timezone issue with your device, as the whole calculation of that is in Android code.

**Comment by Adamantcheese** [comment]
I'm closing this as no new information has come up, and my previous response notes that it may be something not solvable by me.
