### ISSUE TITLE
[Feature Request] Add bookmarked_on timestamp to database

### ISSUE THREAD

**Issue by shiimizu** [Adamantcheese/Kuroba#358]
`[Feature Request]`: If you bookmark a thread, the current time gets inserted into the `bookmarked_on` entry in the database.

This would make it easier for people who have an external DB of a list of threads to keep a sane order of them all based on the `bookmarked_on` timestamp, without having rely on the arbitrary `order` entry which is tied down to the app.

```json
"exported_loadable": {
    "board_code": "g",
	"bookmarked_on": 1569110681,
    "last_loaded": 72363680,
    "last_viewed": 72363680,
    "list_view_index": 0,
    "list_view_top": 0,
    "loadable_id": 2659,
    "mode": 0,
    "no": 72346206,
    "site_id": 1,
    "title": "/mkg/ - Mechanical Keyboard General"
}
```

**Comment by Adamantcheese** [comment]
I know you've closed this, but you can use the `no` field to keep track of threads in-order (server-wise), which would roughly be the same as the `bookmarked_on` field you were suggesting, especially if sorted on the board code.
