### ISSUE TITLE
IRC / Discord / whatever

### ISSUE THREAD

**Issue by TheStranjer** [Adamantcheese/Kuroba#361]
Is there an IRC channel, Discord server, or anything to that effect for the development of this project? Opening a separate ticket for every little problem or question seems tedious.

**Comment by K1rakishou** [comment]
>Opening a separate ticket for every little problem or question seems tedious.

That's how it should be, though. Otherwise it'll just get lost.

**Comment by Adamantcheese** [comment]
Yeah, not really. Post issues here; it serves as a to-do list for me and K1rak, and lets people know of updates on their reports if something happens for their issue. It's the best for everyone really.
