### ISSUE TITLE
2ch keeps changing to sushichan

### ISSUE THREAD

**Issue by That-Thing** [Adamantcheese/Kuroba#364]
I added dvach and when I restarted the app it changed to sushichan and gave off a 404 error when I tried to enter any board.
![Screenshot_20190926-133518](https://user-images.githubusercontent.com/41160238/65711402-d49d3480-e062-11e9-893e-02b3502e48ed.jpg)

**Comment by K1rakishou** [comment]
Duplicate of #351 and should already be fixed (but the fix is not released yet) in https://github.com/Adamantcheese/Kuroba/commit/3b6a1f735b7e44a33add387184caa8efeec07056
