### ISSUE TITLE
Board changes on arisuchan

### ISSUE THREAD

**Issue by ownBard** [Adamantcheese/Kuroba#365]
Various changes are being made to the site. Anyway, here's the updated board list unless it changes again:
- /tech/ technology
- /art/ art and creative
- /cult/ culture and media
- /psy/ psychology and psychonautics
- /λ/ programming
- /Δ/ shape your world
- /ru/ киберпанк-доска
- /r/ miscellaneous
- /q/ arisuchan meta
- /all/ ukko

The hidden boards have also been removed so that's one less thing to worry about.

**Comment by ownBard** [comment]
Still no catalog.json for /all/ though.

**Comment by Adamantcheese** [comment]
Are overboards going away as well?

**Comment by ownBard** [comment]
/all/ was the only overboard on arisuchan and I sorta stopped using lainchan.

**Comment by ownBard** [comment]
The admins aren't too interested in fixing them in any way so they're probably not worth trying to support afterall.

**Comment by Adamantcheese** [comment]
Per my own investigation, /cyb/, /feels/, /x/, /z/ will be removed and /all/ will not be supported as it doesn't have a catalog.json and is basically an overboard, which I don't really want to support as it's better handled server-side with a redirect.

**Comment by ownBard** [comment]
Yes, that is correct. Other than that some boards were renamed slightly.

**Comment by Adamantcheese** [comment]
Could you tell me what boards were renamed? There wasn't really a news post about it

**Comment by ownBard** [comment]
@Adamantcheese The removed boards are still showing up for me, though the renamed boards appear correctly.
