### ISSUE TITLE
Kuroba doesn't follow set font size

### ISSUE THREAD

**Issue by generoberts** [Adamantcheese/Kuroba#367]
I use the largest font size in the android setting. In Kuroba 4.8.1, all font looks smaller than it should be. Moreover, the font size of OP post when viewing from category mode looks fine, but the font in the other area such as OP subject field, UI, comments, when you typing, look small.
I'm using android 5.1.1.

**Comment by K1rakishou** [comment]
Uhhh, you can change the font size in the Appearance settings.

**Comment by generoberts** [comment]
Yes, but like I said that only most font size look small.
Here is what it looked like for older version https://imgur.com/a/DarePF4
And this is what it looks like for version 4.8.1 https://imgur.com/a/eqrgtau
I change font size in Kuroba to size 17 to make the comment's font size bigger but other part, like '1 reply' are too big and other parts are too small.

**Comment by Adamantcheese** [comment]
Probably an AndroidX library update that did it.

**Comment by Adamantcheese** [comment]
Still probably an AndroidX library that did it, however I can't reproduce this on Android 5.0 or 5.1 on emulator.

**Comment by ElRattin** [comment]
this problem is also present on Android 7.0
on Lollipop i solved this problem using Xposed+App Settings but it doesn't work on 7.0
Thanks m8

**Comment by K1rakishou** [comment]
We actually had a similar problem at work, and indeed, it was an Android X library bug.

**Comment by Adamantcheese** [comment]
Does this still occur for anyone that has this issue? Quite a number of things have changed since this was opened so perhaps it fixed itself.
