### ISSUE TITLE
Re add non-padded thumbnails

### ISSUE THREAD

**Issue by floppyD** [Adamantcheese/Kuroba#368]
What's even the point of that thing? The padding it adds is minimal, not even enough to make them aligned with the text or that line between posts. Not only that, it also makes thumbnails smaller, and their animation buggy (gif). Please revert to the old behavior, or at least make it optional, if you don't like it for some reason.
![outp](https://user-images.githubusercontent.com/29208110/65941771-331b3780-e402-11e9-923f-a039fbffe4b8.gif)

**Comment by Adamantcheese** [comment]
Doesn't make them smaller by the way. Animation was always a bit buggy anyways, I don't see it as an issue. Not coming back.
