### ISSUE TITLE
[BUG] When saving a post "Delete post" option appears which shouldn't

### ISSUE THREAD

**Issue by K1rakishou** [Adamantcheese/Kuroba#37]
STR:
While a in thread click post options -> more -> save.
Then click that post's options again and "Delete" option will apear which, if clicked, will show an error message "Password is incorrect".

**Comment by Adamantcheese** [comment]
This is a very minor concern that rightfully doesn't let you delete posts on devices other than the one you posted from. Won't fix, the error is good enough.
