### ISSUE TITLE
[IMPROVEMENT] Thread opening by clicking on the watcher notification is inconsistent 

### ISSUE THREAD

**Issue by K1rakishou** [Adamantcheese/Kuroba#371]
Sometimes it opens the catalog sometimes it opens one of the pinned threads. This thing should be thought out. But it's not clear what thread exactly should be opened? Lets say you have three pinned threads. When clicking the notification which one of them should we open? Then one with thread lastest post? Or the one where you were mentioned?

**Comment by K1rakishou** [comment]
So how about the following:
- If there are replies to your posts - open them first in descending order (the most recent reply will be opened first)
- If there are no replies to your posts then we open the latest bumped thread.

What do you think?

**Comment by Adamantcheese** [comment]
The current logic is as follows:
If there's one thread with new posts, open that thread.
If there's more than one thread with new posts, open the bookmark sidebar so the user can pick what thread they want to view.

Personally I'm fine with how it's currently implemented, but if we were to assign priority for opening up a thread, it would be quotes first, followed by latest post timestamp, just like how you said. No new posts at all should just open up the bookmark sidebar, so it still has some functionality in that edge case.

**Comment by K1rakishou** [comment]
Oh, so that's how it is I didn't even notice that. Yeah, I agree that if there are no new posts at all then we should open the bookmarks list.
