### ISSUE TITLE
Support for proxy authentication.

### ISSUE THREAD

**Issue by joaovitorbf** [Adamantcheese/Kuroba#376]
I have a personal proxy server with basic auth, but it seems like Kuroba doesn't support proxies with authentication. It would be nice for it to have some kind of way to enter basic auth credentials so I can use my proxy directly on the app instead of passing all my Android HTTP traffic through the proxy.

**Comment by Adamantcheese** [comment]
Kinda like #128, I don't really use a proxy and can't effectively test it. If you submit a PR, I'll merge it.
