### ISSUE TITLE
Filenames while using 'Download Album"

### ISSUE THREAD

**Issue by GaryMericano** [Adamantcheese/Kuroba#377]
While saving images individually, they save correctly per the settings I have selected (board folder on, thread folder on, server filename off)
Ex: kuroba/4chan/wsg/18871517_srsly_no_breakfast_thread/eating_cereal.webm
but while saving through the 'Download Album' button (both from the "⋮" button in Gallery and the "⋮" button from an individual item) it saves files like
kuroba/fill_the_the_shoes/224816209125.jpg
kuroba/fill_the_the_shoes/224816209126.jpg
kuroba/fill_the_the_shoes/224816209134.jpg
kuroba/fill_the_the_shoes/224816209277.jpg
kuroba/fill_the_the_shoes/224816210125.jpg

I'm not sure if this problem is happening for anyone else or if there's something obvious I'm missing, but I get pretty much the same behavior from Clover (not sure when it started, but used to work correctly on clover,)

**Comment by Adamantcheese** [comment]
This is actually pretty old and hasn't changed from Clover to Kuroba. See https://github.com/chandevel/Clover/issues/155 and https://github.com/chandevel/Clover/pull/159.

**Comment by GaryMericano** [comment]
Ahh, sorry for the duplicate. I also noticed that hidden posts will still show up in Album/Gallery, not sure if that one is known about (and sorry for being a "summer friend" I'm relatively new to the git repository format)
