### ISSUE TITLE
The Split Mode is Just Bad

### ISSUE THREAD

**Issue by ghost** [Adamantcheese/Kuroba#379]
![bug_1](https://user-images.githubusercontent.com/44249820/66708630-c9a7fc80-ed10-11e9-8f54-a63402f53b33.png)

The icons in the menu are cut, the float bottom appears two times in the screen (its confusing.) And I can't even change the board in this mode. This needs a responsive desing improvement.

Maybe the ability to change the size of the sides of the screen would be good too. (A draggable bar in the middle for example)

**Comment by Adamantcheese** [comment]
Split mode is meant for tablets, not phones. You can "use" it landscape mode, but it's pretty terrible on a phone, yes. There's nothing really to fix as it wasn't meant to be used that way.

**Comment by K1rakishou** [comment]
Why would you use two instances of an app in split mode with portrait orientation?
