### ISSUE TITLE
[Question] Why did the apk size go from 3 MB to 15 MB in the latest release?

### ISSUE THREAD

**Issue by floppyD** [Adamantcheese/Kuroba#38]
Anon question.

**Comment by K1rakishou** [comment]
The only thing that was added between 4.0.8 and 4.0.9 besides the code is this library - https://github.com/Adamantcheese/Kuroba/blob/multi-feature/Kuroba/app/build.gradle#L116
So probably it's because of it.

**Comment by Adamantcheese** [comment]
Fixed as of https://github.com/Adamantcheese/Kuroba/commit/5ad17fc6ba1a4611886779262e922ea2b82d80f7
