### ISSUE TITLE
Bot detection error on arisuchan

### ISSUE THREAD

**Issue by ownBard** [Adamantcheese/Kuroba#380]
Occassionally arisuchan uses a soft warning when your post looks like it may be a bot — it will display a message but still let your post go through. However, on Kuroba this will just display "An error occurred while posting" and the post will not go through.

**Comment by Adamantcheese** [comment]
I need an example post body to test it with, or even better, an HTML response with all the headers and whatnot so I can figure out where it's erroring out.

**Comment by ownBard** [comment]
Still haven't found a reliable method of reproducing and what's more the devs are still in process of changing things on their end.

**Comment by Adamantcheese** [comment]
Closing, arisuchan is defunct.
