### ISSUE TITLE
[IMPROVEMENT] Small fixes for FileCacheDownloader

### ISSUE THREAD

**Issue by K1rakishou** [Adamantcheese/Kuroba#381]
Right now if some exception occurrs while reading data from the socket (`Sink`) it will fail the file downloading right away which is bad when the network is flaky. What should be done in this case is the downloading should be restarted whenever an `IOException` was thrown for couple of times (lets say 3 times and if it still fails with `IOException` then fail the whole downloading).

~~Also I have noticed that we may not close some closeable resources when exception occurrs in `pipeBody()` method:~~

~~https://github.com/Adamantcheese/Kuroba/blob/multi-feature/Kuroba/app/src/main/java/com/github/adamantcheese/chan/core/cache/FileCacheDownloader.java#L255~~

~~If `source.read()` throws an exception then we won't close nor source nor sink nor the body of the response which will cause a memory leak and probably some other leak as well.~~

I'm also thinking about converting this whole class into Kotlin and using Kotlin coroutines there.

**Comment by Adamantcheese** [comment]
If the network is flaky, it'll fail in getBody(), not pipeBody(); this will always be closed due to the finally clause in execute(). And I don't think there's ever been an instance of the finally clause having the source closeable being null, so I really don't see any need to do anything to the downloader.

**Comment by K1rakishou** [comment]
`
Source source = body.source();
sourceCloseable = source;
`

Fuck me I didn't notice this part. Yeah it will always be closed. 

Well then just the Retry-On-IOException should be implemented in this task.

**Comment by Adamantcheese** [comment]
For the retry three times thing, you can set a retry policy for the request before the `call.execute()`. Dunno if that's the same thing as what you wanted, but I'm letting ya know

**Comment by K1rakishou** [comment]
I'll look into it, thanks.
