### ISSUE TITLE
Add 8kun as a site

### ISSUE THREAD

**Issue by TacoTheDank** [Adamantcheese/Kuroba#383]
https://github.com/chandevel/Clover/issues/751

Maybe keep this issue up for re-integrating 8chankun if it relaunches, I guess...

**Comment by GaryMericano** [comment]
8kun.top currently. Idk why in particular, but I like Watkins, probably his refusal to be defeated… I'd love to see 8kun added to kuroba

**Comment by bronzagency** [comment]
Can we get this in the next release?

**Comment by Adamantcheese** [comment]
The next release will be next year, but yes.

**Comment by Z3ROGRAV1TYx** [comment]
Bump

**Comment by AoiSeaghdha** [comment]
Think this fell through the cracks for the last release

**Comment by seniorm0ment** [comment]
> Think this fell through the cracks for the last release

#547 
> Adamant Cheese (3 Days Ago) - I'm going to delay adding this one in for two weeks or so; I  haven't tested any of it, and maybe 420chan will be ready in around the  same time.

**Comment by AoiSeaghdha** [comment]
Oh my bad, you're right. I checked the issue & posted from a mobile client, and apparently it didn't show me all the events. Glad to see it didn't fall through the cracks after all.
[phoneposting is a sin as always, it seems](https://i.imgur.com/WgWPysg.png)
