### ISSUE TITLE
App not installed

### ISSUE THREAD

**Issue by volcbs** [Adamantcheese/Kuroba#384]
So, when I tried to install new release, I got error telling that I couldn't install the app. My android is pie (9) btw.

**Comment by Adamantcheese** [comment]
Weird. Both the emulator I use to test and my usual phone are Android 9 as well and nothing went wrong. Probably something to do with the new build variants, but stableRelease should be the same as the old release.

**Comment by volcbs** [comment]
I honesty wish I could provide the installation log, but I don't know how and my phone isn't rooted either.

**Comment by Adamantcheese** [comment]
You shouldn't need a rooted phone to view any logs.

**Comment by volcbs** [comment]
Yeah, you're right. Here we go, hope it helps you.

[logcat_10-17-2019_11-02-41.zip](https://github.com/Adamantcheese/Kuroba/files/3737361/logcat_10-17-2019_11-02-41.zip)

**Comment by Adamantcheese** [comment]
Yep, that helps a bunch. Thanks!

**Comment by Adamantcheese** [comment]
You should be able to install it in the next release; if you want to use it for the time being, follow the instructions in #382.

**Comment by volcbs** [comment]
Thanks for the release, mate.
