### ISSUE TITLE
Kuroba crashes when opening webms

### ISSUE THREAD

**Issue by StylinGreymon** [Adamantcheese/Kuroba#387]
Whenever I try to play a webm, Kuroba crashes to homescreen. 
Logs:
>E/Kuroba | UNCAUGHT: java.lang.IllegalArgumentException: Couldn't find meta-data for provider with authority com.github.adamantcheese.chan.fileprovider
E/Kuroba | UNCAUGHT: 	at androidx.core.content.FileProvider.parsePathStrategy(FileProvider.java:606)
E/Kuroba | UNCAUGHT: 	at androidx.core.content.FileProvider.getPathStrategy(FileProvider.java:579)
E/Kuroba | UNCAUGHT: 	at androidx.core.content.FileProvider.getUriForFile(FileProvider.java:417)
E/Kuroba | UNCAUGHT: 	at com.github.adamantcheese.chan.ui.view.MultiImageView.setVideoFile(MultiImageView.java:446)
E/Kuroba | UNCAUGHT: 	at com.github.adamantcheese.chan.ui.view.MultiImageView.access$1100(MultiImageView.java:77)
E/Kuroba | UNCAUGHT: 	at com.github.adamantcheese.chan.ui.view.MultiImageView$6.onSuccess(MultiImageView.java:422)
E/Kuroba | UNCAUGHT: 	at com.github.adamantcheese.chan.core.cache.FileCache.handleFileImmediatelyAvailable(FileCache.java:155)
E/Kuroba | UNCAUGHT: 	at com.github.adamantcheese.chan.core.cache.FileCache.downloadFile(FileCache.java:111)
E/Kuroba | UNCAUGHT: 	at com.github.adamantcheese.chan.core.cache.FileCache.downloadFile(FileCache.java:84)
E/Kuroba | UNCAUGHT: 	at com.github.adamantcheese.chan.ui.view.MultiImageView.setVideo(MultiImageView.java:413)
E/Kuroba | UNCAUGHT: 	at com.github.adamantcheese.chan.ui.view.MultiImageView.lambda$setMode$0$MultiImageView(MultiImageView.java:191)
E/Kuroba | UNCAUGHT: 	at com.github.adamantcheese.chan.ui.view.-$$Lambda$MultiImageView$shKI1JtMKREPy760_mbgGoeA6iM.onMeasured(Unknown Source:8)
E/Kuroba | UNCAUGHT: 	at com.github.adamantcheese.chan.utils.AndroidUtils.waitForLayoutInternal(AndroidUtils.java:333)
E/Kuroba | UNCAUGHT: 	at com.github.adamantcheese.chan.utils.AndroidUtils.waitForMeasure(AndroidUtils.java:305)
E/Kuroba | UNCAUGHT: 	at com.github.adamantcheese.chan.ui.view.MultiImageView.setMode(MultiImageView.java:179)
E/Kuroba | UNCAUGHT: 	at com.github.adamantcheese.chan.ui.adapter.ImageViewerAdapter.setMode(ImageViewerAdapter.java:96)
E/Kuroba | UNCAUGHT: 	at com.github.adamantcheese.chan.ui.controller.ImageViewerController.setImageMode(ImageViewerController.java:348)
E/Kuroba | UNCAUGHT: 	at com.github.adamantcheese.chan.core.presenter.ImageViewerPresenter.onLowResInCenter(ImageViewerPresenter.java:229)
E/Kuroba | UNCAUGHT: 	at com.github.adamantcheese.chan.core.presenter.ImageViewerPresenter.onModeLoaded(ImageViewerPresenter.java:177)
E/Kuroba | UNCAUGHT: 	at com.github.adamantcheese.chan.ui.view.MultiImageView.onModeLoaded(MultiImageView.java:624)
E/Kuroba | UNCAUGHT: 	at com.github.adamantcheese.chan.ui.view.MultiImageView.access$500(MultiImageView.java:77)
E/Kuroba | UNCAUGHT: 	at com.github.adamantcheese.chan.ui.view.MultiImageView$3.onResponse(MultiImageView.java:283)
E/Kuroba | UNCAUGHT: 	at com.android.volley.toolbox.ImageLoader$4.run(ImageLoader.java:501)
E/Kuroba | UNCAUGHT: 	at android.os.Handler.handleCallback(Handler.java:873)
E/Kuroba | UNCAUGHT: 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/Kuroba | UNCAUGHT: 	at android.os.Looper.loop(Looper.java:214)
E/Kuroba | UNCAUGHT: 	at android.app.ActivityThread.main(ActivityThread.java:6986)
E/Kuroba | UNCAUGHT: 	at java.lang.reflect.Method.invoke(Native Method)
E/Kuroba | UNCAUGHT: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
E/Kuroba | UNCAUGHT: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1445)
E/Kuroba | UNCAUGHT: .
E/Kuroba | UNCAUGHT: ----------------------------------------
E/Kuroba | UNCAUGHT: END OF CURRENT RUNTIME MESSAGES
E/Kuroba | UNCAUGHT: ----------------------------------------
E/Kuroba | UNCAUGHT: .
E/Kuroba | UNCAUGHT: Android API Level: 28
E/Kuroba | UNCAUGHT: App Version: v4.9.0-dev Official
E/Kuroba | UNCAUGHT: Phone Model: samsung SM-G965U1

**Comment by Adamantcheese** [comment]
This is likely the same issue as #384. Weird that it only affects WEBM files though. I'll do a release to fix it.

**Comment by StylinGreymon** [comment]
Sorry, but it's still crashing when viewing webms
Logs:
>E/Kuroba | UNCAUGHT: java.lang.IllegalArgumentException: Couldn't find meta-data for provider with authority com.github.adamantcheese.chan.fileprovider
E/Kuroba | UNCAUGHT: 	at androidx.core.content.FileProvider.parsePathStrategy(FileProvider.java:606)
E/Kuroba | UNCAUGHT: 	at androidx.core.content.FileProvider.getPathStrategy(FileProvider.java:579)
E/Kuroba | UNCAUGHT: 	at androidx.core.content.FileProvider.getUriForFile(FileProvider.java:417)
E/Kuroba | UNCAUGHT: 	at com.github.adamantcheese.chan.ui.view.MultiImageView.setVideoFile(MultiImageView.java:446)
E/Kuroba | UNCAUGHT: 	at com.github.adamantcheese.chan.ui.view.MultiImageView.access$1100(MultiImageView.java:77)
E/Kuroba | UNCAUGHT: 	at com.github.adamantcheese.chan.ui.view.MultiImageView$6.onSuccess(MultiImageView.java:422)
E/Kuroba | UNCAUGHT: 	at com.github.adamantcheese.chan.core.cache.FileCacheDownloader.lambda$execute$0$FileCacheDownloader(FileCacheDownloader.java:154)
E/Kuroba | UNCAUGHT: 	at com.github.adamantcheese.chan.core.cache.-$$Lambda$FileCacheDownloader$sqhYgnWi8_e2NrX-h6ykw01y18o.run(Unknown Source:4)
E/Kuroba | UNCAUGHT: 	at android.os.Handler.handleCallback(Handler.java:873)
E/Kuroba | UNCAUGHT: 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/Kuroba | UNCAUGHT: 	at android.os.Looper.loop(Looper.java:214)
E/Kuroba | UNCAUGHT: 	at android.app.ActivityThread.main(ActivityThread.java:6986)
E/Kuroba | UNCAUGHT: 	at java.lang.reflect.Method.invoke(Native Method)
E/Kuroba | UNCAUGHT: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
E/Kuroba | UNCAUGHT: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1445)
E/Kuroba | UNCAUGHT: .
E/Kuroba | UNCAUGHT: ----------------------------------------
E/Kuroba | UNCAUGHT: END OF CURRENT RUNTIME MESSAGES
E/Kuroba | UNCAUGHT: ----------------------------------------
E/Kuroba | UNCAUGHT: .
E/Kuroba | UNCAUGHT: Android API Level: 28
E/Kuroba | UNCAUGHT: App Version: v4.9.1-dev Official
E/Kuroba | UNCAUGHT: Phone Model: samsung SM-G965U1

**Comment by Adamantcheese** [comment]
Weird; WebM's work fine in both emulator and my actual phone on the same Android API level. I'll take another look.

**Comment by Adamantcheese** [comment]
Are you on a DEV build from K1rakishou perchance?

**Comment by StylinGreymon** [comment]
don't believe so, I grabbed the 4.9.1 build directly from here.

**Comment by Adamantcheese** [comment]
That took way too long to find. v4.9.2 has been released to fix that issue. The logs really helped out.

**Comment by StylinGreymon** [comment]
looks like that did the trick.
thanks for your hard work!
