### ISSUE TITLE
Spoiler doesn't black the quoted post's number

### ISSUE THREAD

**Issue by generoberts** [Adamantcheese/Kuroba#389]
Like in this image: https://imgur.com/a/lKswGuA
It should be all black, isn't it?
Make/unmake post as my post don't make the red text go aways.
Using Kuroba 4.9.2 on Android 5.1.1.

**Comment by Adamantcheese** [comment]
If you could provide a link to the post in question that would be extremely helpful.

**Comment by generoberts** [comment]
It's not the same link but I can reproduct it easily on /vg/ (haven't tested on othee board yet). Here is the new link: https://boards.4chan.org/vg/thread/269109153#p269479984

**Comment by Adamantcheese** [comment]
Weird, the priorities for spans seem to function differently now. Fixed, hopefully no strange other rendering issues come as a result. It's only a visual thing by the way; if it's spoilered, the quote isn't clickable anyways.
