### ISSUE TITLE
Long pressing on something doesn't show the option to Google search it anymore

### ISSUE THREAD

**Issue by illusma** [Adamantcheese/Kuroba#390]
You have implemented the new quote feature but the Google search came in handy a lot of times. Please bring that back

**Comment by Adamantcheese** [comment]
Not sure what new quote feature you're talking about?

**Comment by Adamantcheese** [comment]
There was never any Google search implemented in Kuroba/Clover as a context menu item. Likely a feature of your OS as a default context menu item that may have been removed.
