### ISSUE TITLE
[Suggestion] Unspoiler images instantly

### ISSUE THREAD

**Issue by ownBard** [Adamantcheese/Kuroba#392]
Directly open unspoilered image when tapping a spoilered thumbnail.

**Comment by Adamantcheese** [comment]
This is already an option?

**Comment by ownBard** [comment]
What I mean is when spoilers are on, clicking a spoilered thumbnail should open straight to the unspoilered image (instead of first opening the image viewer then tapping again to unspoil the image).

**Comment by ownBard** [comment]
Sorry, I made that really unclear at first.

**Comment by Adamantcheese** [comment]
Would it be preferable that this is the default behavior of the application? It would cause issues for people who just browse through the album view, but still want to see when an image is spoilered. I'm leaning towards doing nothing in this case anyways because the existing setting is sorta the best solution.

**Comment by ownBard** [comment]
I would think that you'd leave the current behaviour for swiping through images and only unspoil when tapping again would be redundant (i.e. tapping a spoilered thumbnail from a thread or tapping a spoilered thumbnail from gallery). There would be no need to add another setting as it's just removing the need to tap twice.

**Comment by Adamantcheese** [comment]
I can't have it be for only when you open an image from the thread/gallery view, but this setting should do what you want mostly.

**Comment by ownBard** [comment]
Yep, a three tiered option for *no spoilers—only thumbnails—all spoilers* seems like a good solution!

**Comment by ownBard** [comment]
Just realised that enabling *Remove image spoilers* ought to lock the option for *Reveal image spoilers*.

**Comment by Adamantcheese** [comment]
The two are still separate, as their descriptions say.

**Comment by ownBard** [comment]
But having the option to *reveal* non-thumbnails is redundant when all spoilers are *removed*. The setting does nothing when *remove* is enabled.

**Comment by Adamantcheese** [comment]
Yes, and the two settings don't interfere with each other and so no locking is needed, unlike the board/thread folder settings where the thread folder setting requires the board folder setting to be enabled for any functional change. The reveal setting doesn't affect the operation of the remove setting and vice versa; one may be a superset of the other, but they are doing different operations codewise; locking the reveal setting when the remove setting is on will still be applying the reveal setting previously set. If you want to submit a PR to do this, go ahead, but I think that I've wasted enough time writing this to explain my reasoning.

**Comment by ownBard** [comment]
If you like it how it is I am happy, also then I can't code so I'm useless besides bug-reporting.
