### ISSUE TITLE
Error Posting: timeout 

### ISSUE THREAD

**Issue by bavefiy111** [Adamantcheese/Kuroba#396]
I have this issue with error posting sometimes. I solve the captcha and after loading it gives me this.
I have to turn my wifi off and on on the phone to be able to post again.
After a while (a couple minutes) the error comes back so I have to turn off/on wifi again.

![Screenshot_2019-10-28-23-01-26-134_com github adamantcheese chan](https://user-images.githubusercontent.com/57114255/67715387-d1d38d80-f9da-11e9-93b7-a89c70cbbf09.jpg)

**Comment by Adamantcheese** [comment]
If it's timing out it's a network issue of some sort that I can't help with.
