### ISSUE TITLE
[DEV/BUG(???)] When downloading thread albums a new "Kuroba" directory is created inside the user selected directory

### ISSUE THREAD

**Issue by K1rakishou** [Adamantcheese/Kuroba#397]
So it looks like this:
User selects a directory Kuroba/files.
Then downloads a thread album.
And gets the following directory structure: 
Kuroba/files/Kuroba/img1.jpg
Kuroba/files/Kuroba/img2.jpg
Kuroba/files/Kuroba/img3.jpg

I don't remember it working like this when implementing SAF and I think the new Kuroba directory shouldn't be created. Tested using SAF as a base directory but it is probably the same with normal directories.

**Comment by Adamantcheese** [comment]
Sounds like the subfolder isn't correct anyways. I'll take a look.
