### ISSUE TITLE
[Feature Request] Sticky bookmarks to the top of the catalog, or display thread info in sidebar

### ISSUE THREAD

**Issue by Astridchan** [Adamantcheese/Kuroba#40]
Regarding https://github.com/Adamantcheese/Kuroba/issues/23:
>Bookmarks already cover this. Bookmark the thread you want and turn off the thread watcher for that specific thread. Filter watching acts like permanent stickies if your regex is good. Plus, threads are then stickied even if you're not on the board they're specifically for.

Sorry, I think I didn't explain myself properly.  What is meant by "stickying", is that a thread that is stickied will *always* appear at the **top of the board catalog**. The browser extension "4chan X" has a feature where threads you have bookmarked are automatically stickied to the top of the catalog (bookmarked threads marked in red):

![Capture1111](https://user-images.githubusercontent.com/40862101/58953193-69231480-879e-11e9-9a62-1d16321ec26f.PNG)

This allows you to get an overview of each thread you follow on a given board, as you can quickly see the **number of replies** and **page number** for each thread, and whether the thread is at **bump limit** or not. 

The bookmarks in Kuroba do not cover this. To view the same thread information, you either have to search through the catalog for each thread, or look through all the bookmarked threads individually, as the bookmarked threads list in the side bar does not display total number of replies, page number or whether a thread is at bump limit or not, only the number of unseen replies.

An alternative solution I thought of would be to have a toggle in the boomarked thread list where you could change the number displayed from **unseen replies** to **total replies** and **page number**. Quick mockup:

![Screenshot_2019-06-05-14-47-15-177_com github adamantcheese chan](https://user-images.githubusercontent.com/40862101/58954823-e2246b00-87a2-11e9-9cde-d1177428ef57.png)

This could actually be a better way since you see the information for ALL bookmarked threads, regardless of what board they are on.

**Comment by Adamantcheese** [comment]
Number of replies in the bookmark menu: ok.
Page number italics: use last page notifications. I tried and it's way too laggy because of how many redraw events are called. Tapping the notification takes you to the thread anyways.

Don't expect everything to be like 4chan-X. If you want that experience, go use a desktop.
