### ISSUE TITLE
Incorrectly applying remembered encoding options

### ISSUE THREAD

**Issue by ownBard** [Adamantcheese/Kuroba#412]
If *Remove filename* is remembered by the encoding menu but a different encoding option is applied, the filename still changes despite the option being deselected.

**Comment by Adamantcheese** [comment]
I'm not seeing the behavior you're describing. A set of steps to reproduce would be helpful; my current steps are
1) Remove filename only. Apply. Repeat several times to see the name change for sure.
2) Remove metadata only. Apply. The filename doesn't change from the last time it was checked.

**Comment by ownBard** [comment]
I tested it again, turns out it's a completely different bug. I'll open a new issue.
