### ISSUE TITLE
420chan support

### ISSUE THREAD

**Issue by DigitalCorgi** [Adamantcheese/Kuroba#413]
I would really like for there to be support for 420chan, I don't really know what else to say I just hope it's possible to add support for it.

**Comment by Adamantcheese** [comment]
I do like that the developers have a fully documented API at https://api.420chan.org/; if you want to develop for the application, this is a good first thing to try to do!

**Comment by Lolzen** [comment]
I'm too lazy and uncomfortable to do a proper PR on a WiP.
i've tried to my best abilities and with peeking into overchan and dashchan for guidance to bring 420chan support to Kuroba (or rather my Clover Fork tbh). Checked out, it is buildable with Kuroba  without errors.
Here are the added/changed files for inspection: http://ge.tt/8qluDn03 (based on commit hash 84a5fd1)
[added] core/site/common/taimaba
[added] core/site/sites/Chan420.java
[modified] core/site/SiteRegistry.java

I've basically copied over vichan and modified it slightly. My first approach was to copy the chan4 folder and modify it. This is all i can do, as i don't properly understand Java so this is a hackfest at best.

What's working: Sitesetup, thread/thumbnail/image viewing, saving threads and reading comments.
What's not working: There are quite a bit formatting issues. either the comments don't run through the CommentParser or i'd have to override some function(s). no yellowtext (greentext), no bold/italic etc. No Posting/deleting a comment, quotepatterns (reply to #). I did do some modifications in these regards in TaimabaApi.java, but i think the proper way to handle these things should be the CommentParser - please correct me if i'm wrong.

I know this is a "good first issue" but it is outside of my capabilities. I've been trying for about 1-2 weeks now and i need help going further. I'm not even sure if my approach is "correct" or it is simply dirty/hacky and unmergable.

Happily awaiting some feedback.

[![Bild screenshot_shishi_202ufjnp.png auf abload.de](https://abload.de/thumb/screenshot_shishi_202ufjnp.png)](https://abload.de/image.php?img=screenshot_shishi_202ufjnp.png)

**Comment by Adamantcheese** [comment]
Yeah I'd rather you submit an actual PR. Not only for my sake, but so you can learn how to use Git and Github more effectively.

**Comment by Lolzen** [comment]
That's not the issue, the isuue was that i had forked Clover, so i couldn't fork Kuroba. Came down to pure laziness on my part, but i'll do it in a bit.

**Comment by Adamantcheese** [comment]
Closed; 420chan has been implemented.
