### ISSUE TITLE
[BUG/DEV] Sharing an image does not work in dev

### ISSUE THREAD

**Issue by K1rakishou** [Adamantcheese/Kuroba#415]
Sharing a thread works, though.

**Comment by Adamantcheese** [comment]
As a result of your MediaScanner commenting out, `afterScan` is never called, which would do the share. https://github.com/Adamantcheese/Kuroba/blob/multi-feature/Kuroba/app/src/main/java/com/github/adamantcheese/chan/core/saver/ImageSaveTask.java#L137 and https://github.com/Adamantcheese/Kuroba/blob/multi-feature/Kuroba/app/src/main/java/com/github/adamantcheese/chan/core/saver/ImageSaveTask.java#L169-L173

**Comment by K1rakishou** [comment]
Ohhh, I see.
