### ISSUE TITLE
[IMPROVEMENT] Replace Feather with Dagger 2

### ISSUE THREAD

**Issue by K1rakishou** [Adamantcheese/Kuroba#419]
Because fuck Feather for swallowing exceptions.
And dagger has lots of good checks, like, the recursive dependencies check during the project build.
Shouldn't be hard since we already use component/module schema that is similar to what dagger uses. But there will be difficulties replacing all those "Feather.instance(XXX.class)" but at least we will finally stop doing that because it's a bad practice.

**Comment by K1rakishou** [comment]
Bonus: use regular dagger (https://github.com/google/dagger) for release builds and use dagger reflect (https://github.com/JakeWharton/dagger-reflect) for dev builds. 
Dagger generates all the boilerplate code during project compilation and this increases the project build time, so it's a good idea to use reflection which is a little bit slower in runtime but doesn't affect the build time which is crucial during the development.

**Comment by Adamantcheese** [comment]
It's all singletons anyways, dependency injection or not.
