### ISSUE TITLE
[IMPROVEMENT] Always load images/files from the disk when a thread has a local copy

### ISSUE THREAD

**Issue by K1rakishou** [Adamantcheese/Kuroba#421]
Should have been implemented the moment the local threads were implemented. With this thing done, local threads will supercede the media prefetching functionality . What should we do about it?

**Comment by Adamantcheese** [comment]
I do agree that loading a local file if available is the best course of action, however that wouldn't strictly supersede the media prefetcher, as local threads are downloaded to on-device memory for more permanent storage, while the media prefetcher only loads it into the filecache, which can be purged at any time and may take up significantly less space over time. I know the prefetcher is still kinda shitty and needs work though, but the two features aren't really exactly the same as a result.
