### ISSUE TITLE
[BUG] When switching from one base directory to another that is INSIDE the previous one, when deleting old one it will delete the new one as well

### ISSUE THREAD

**Issue by K1rakishou** [Adamantcheese/Kuroba#423]
Lets say you had this base directory - "Kuroba-dev", then decided to use a new one for files "Kuroba-dev/files". So when you are asked to delete the old directory it will be successfully deleted, meaning that the new one is deleted as well because it's inside the old one. 

Basically, it should be checked that the new base directory is somewhere inside the old one.

**Comment by K1rakishou** [comment]
Since #399 is not merged yet I'm going to fix this in that PR.

**Comment by K1rakishou** [comment]
This task is probably going to not be an easy one. So instead of implementing this check, I think I will just add the source and the destination directory paths to the "Moving files" dialog and another directory path to the "Delete old files" dialog so that the users can see them and decide for themselves. Otherwise we probably won't be able to do a release this week.

**Comment by Adamantcheese** [comment]
Yeah I was waiting to see if you were going to fix this one up. I can delay the release until Sunday if needed, but I kinda want to release what's been added in.

**Comment by K1rakishou** [comment]
Well, I can try to implement this thing today, and if, by the end of the day, it still won't be implemented then I can just go the easy route and add the paths to those dialogs and then implement this thing after the release.

**Comment by Adamantcheese** [comment]
Sounds good to me, I'm working on other things that won't affect that anyways. I've updated the release time estimate in the releases.

**Comment by K1rakishou** [comment]
Alright, it's actually turned out to be a lot easier than I initially thought.

**Comment by Adamantcheese** [comment]
Sweet, if it's all ready to merge just let me know. I'll probably finish up the thing I'm working on ~~tomorrow~~ today and merge/release as well.

**Comment by K1rakishou** [comment]
Yes, it's ready to be merged.
