### ISSUE TITLE
[MEMORY LEAK] AnimatedVectorDrawable's animation callback leaks StartActivity

### ISSUE THREAD

**Issue by K1rakishou** [Adamantcheese/Kuroba#428]
![image](https://user-images.githubusercontent.com/10332458/69483484-e61f7480-0e38-11ea-8b39-cb7aa1a2781d.png)

**Comment by K1rakishou** [comment]
Probably we should clear the callbacks for every AnimatedVectorDrawable when the DrawerAdapter is destroyed (in onDetachedFromWindow())

**Comment by Adamantcheese** [comment]
This is kinda the only way I had access to that field. I haven't tested it though, so if that does fix it, please close the issue.

**Comment by K1rakishou** [comment]
Yeah, it looks like it is fixed now, so I'm closing this issue.
