### ISSUE TITLE
[BUG] When quickly swiping through images in the gallery previous downloading files do not get canceled

### ISSUE THREAD

**Issue by K1rakishou** [Adamantcheese/Kuroba#431]
STR:
- Open any thread on /hr/.
- Start swiping through the images without waiting for them to be completely downloaded.
- After 10-20 swipes the next one will get stuck and won't be downloaded (then you will probably see a chain of "Failed to load image" toasts).

We should doublecheck the canceling mechanism.

 It apparently got even worse with the addition of the `Thread.sleep()` after a every failed attempt to download an image. These `Thread.sleeps` should be removed completely. 

This is also probably the same issue as the one where webm won't load after quickly swiping through lots of them.

**Comment by K1rakishou** [comment]
Maybe we should remove the `Thread.sleep()` (this one https://github.com/Adamantcheese/Kuroba/blob/multi-feature/Kuroba/app/src/main/java/com/github/adamantcheese/chan/core/cache/FileCacheDownloader.kt#L129) for the next update (because it was a really bad idea to add it in the first place, I should have removed it after removing the `Thread.currentThread().interrput()`) and then do the proper canceling some time in the future.

**Comment by K1rakishou** [comment]
So I have removed the Thread.sleep() in this commit https://github.com/Adamantcheese/Kuroba/commit/e83263629e24826406773a367724bb4366a896ca But the main problem still persists.

**Comment by Adamantcheese** [comment]
The downloader cancel code that you want to examine is here https://github.com/Adamantcheese/Kuroba/blob/multi-feature/Kuroba/app/src/main/java/com/github/adamantcheese/chan/core/presenter/ImageViewerPresenter.java#L288

**Comment by Adamantcheese** [comment]
Also see #150, which is a similar issue that may be the same.

**Comment by K1rakishou** [comment]
Yeah. I think I'm going to completely rewrite FileCache and the downloader using rxjava or coroutines so it's more flexible than it is right now.
