### ISSUE TITLE
[BUG] There is no way to copy text now

### ISSUE THREAD

**Issue by K1rakishou** [Adamantcheese/Kuroba#432]
![image](https://user-images.githubusercontent.com/10332458/69578335-579a2700-0fe1-11ea-9940-380694fcad94.png)

**Comment by K1rakishou** [comment]
https://github.com/Adamantcheese/Kuroba/blob/e83263629e24826406773a367724bb4366a896ca/Kuroba/app/src/main/java/com/github/adamantcheese/chan/ui/layout/ReplyLayout.java#L647

**Comment by Adamantcheese** [comment]
This was intentional, as otherwise not all the new context menu options would be accessible directly and would overflow into the context menu dropdown. If Copy is a better function to keep than Cut, I'll swap what is getting removed, but something has to be removed regardless.

**Comment by K1rakishou** [comment]
I personally think that cut/copy/paste/quote should be in the normal context menu and all the tags can be moved to the overflow context menu.

**Comment by Adamantcheese** [comment]
I'll see if I can do that then.
