### ISSUE TITLE
[Feature Request] Set password on vichan sites

### ISSUE THREAD

**Issue by ownBard** [Adamantcheese/Kuroba#433]
Feature to allow user to set password for posting/deleting on sites that use a password system (e.g. arisuchan and lainchan).

**Comment by Adamantcheese** [comment]
Could I get some justification? Passwords are already used for posting and deleting, and are generated from a secure random generator; saved replies are stored in the database with their passwords. This is all transparent to the user.

**Comment by ownBard** [comment]
I was not aware of that. I was mostly concerned with switching between computer and mobile, is there no way to view the saved passwords in the app?

**Comment by Adamantcheese** [comment]
No, not really. I can add a dialog box to the "Mark as my post" option so you can set a password, if desired.

**Comment by Adamantcheese** [comment]
Closing, no response for 2 months.
