### ISSUE TITLE
[Bug] Copy disappeared since last update

### ISSUE THREAD

**Issue by floppyD** [Adamantcheese/Kuroba#438]
It was there just before updating, and it only affects the post box. I can still copy content from posts just fine.
![Screenshot_20191129-111731_Kuroba](https://user-images.githubusercontent.com/29208110/69874715-75de7c00-129a-11ea-8a68-6a57d2765fc8.png)

**Comment by floppyD** [comment]
And no, it's not under the 3 dots thing. I only have "Translate" and "Search on Wikipedia" there.

**Comment by tdawson-42** [comment]
Are you on v4.10.1 or v4.10.0? The copy option was removed in v4.10.0 and added back in v4.10.1.
https://github.com/Adamantcheese/Kuroba/issues/432

**Comment by ownBard** [comment]
Duplicate of #432

**Comment by floppyD** [comment]
Oh, didn't notice. Thanks.
