### ISSUE TITLE
[Enhancement] Update EventBus to 3.x.x

### ISSUE THREAD

**Issue by TacoTheDank** [Adamantcheese/Kuroba#44]
`de.greenrobot:eventbus:2.4.0` can be updated to `org.greenrobot:eventbus:3.1.1`

Here's some documentation to help out with upgrading:
http://greenrobot.org/eventbus/changelog/
http://greenrobot.org/release/eventbus-3-release-annotations/
http://greenrobot.org/files/eventbus/javadoc/3.0/

**Comment by K1rakishou** [comment]
I think the better idea would be to get rid of eventbus completely, but that's a huge chunk of code to refactor.

**Comment by TacoTheDank** [comment]
👍
