### ISSUE TITLE
[Feature Request] Add "Web Search" option to context menu 

### ISSUE THREAD

**Issue by Astridchan** [Adamantcheese/Kuroba#442]
See: https://github.com/chandevel/Clover/issues/637

Re: your reply in the above thread, you linked to [ACTION_PROCESS_TEXT](https://developer.android.com/reference/android/content/Intent.html#ACTION_PROCESS_TEXT), but would it be correct to assume that [ACTION_WEB_SEARCH](https://developer.android.com/reference/android/content/Intent.html#ACTION_WEB_SEARCH) would be the relevant action to use in this case?

**Comment by Adamantcheese** [comment]
Yeah, my original comment was wrong. I've deleted it and implemented it in that commit above.
