### ISSUE TITLE
[IMPROVEMENT] Unviewable inlined files (like pdfs) shouldn't be shown in the Image Gallery

### ISSUE THREAD

**Issue by K1rakishou** [Adamantcheese/Kuroba#443]
Since we can't render then anyway so there is no point in showing them. Like we already do with dead images.

**Comment by Adamantcheese** [comment]
They might not be internally viewable, but then they also wouldn't be downloadable. PDFs are basically the only file that fits that criteria and I don't really want to hamper boards that have PDF share threads like /po/ or /tg/.
