### ISSUE TITLE
[IMPROVEMENT] When clicking an unviewable inlined file (like pdf) it should show apps suggestions to open it with

### ISSUE THREAD

**Issue by K1rakishou** [Adamantcheese/Kuroba#444]
Instead of showing "Can't open this file" we should let the user to open it via an external app.

**Comment by Adamantcheese** [comment]
Yeah, I tried to set that up, following a similar structure to how external media players work with video files, but adding in a chooser. Despite the fact that it should work, every single PDF application I try to use tells me that the file can't be read and fails with `open failed: ENOENT (No such file or directory)`. But WEBMs still load fine in external apps, so I dunno what's wrong file-system wise.

**Comment by K1rakishou** [comment]
Shouldn't we only need to send an intent with an action (Intent.ACTION_VIEW I believe) to open the pdf? Or you were planning to implement some custom pdf handling?

>following a similar structure to how external media players work with video files

I think it's better to do it like how the image sharing works now.

**Comment by Adamantcheese** [comment]
I've tried with Intent.ACTION_VIEW, which is how the external media players option works. Image sharing uses INTENT.ACTION_SEND, which isn't handled by most PDF viewers and isn't a viable solution; unless you meant using a chooser, which is an option if the thing would actually work. Don't know why only PDF files have this issue.

**Comment by K1rakishou** [comment]
Oh maybe because it's in the internal storage? You could try to copy it into the saved files base directory  (which will be either somewhere in SAF or in the external storage) and then use the new file's path in the intent.

**Comment by K1rakishou** [comment]
>unless you meant using a chooser

Yeah I meant this thing:
![image](https://user-images.githubusercontent.com/10332458/70609878-9ea82f00-1c13-11ea-9f9e-b06827fc2ebe.png)

**Comment by tidux** [comment]
As an alternative, you could link against mupdf and support PDFs internally.  IANAL but I believe the GPLv3 and AGPLv3 are compatible.

https://mupdf.com/downloads/
