### ISSUE TITLE
[IMPROVEMENT] Ability To Auto-subscribe To Threads

### ISSUE THREAD

**Issue by seniorm0ment** [Adamantcheese/Kuroba#446]
**Would be an awesome feature to be able to autosubscribe to threads based on their title.**

**For example:** 
**Auto-subscribe To Threads With These Phrases In The Title:** _/pcbg/, /mkg/_
`<It then monitors /g/ for threads created with _/pcbg/_ and _/mkg/_ in the title, and adds it to your subscribed list. Even if you aren't actually on the site at the moment.>`

_Maybe allow a different color for the threads being automatically subscribed, Until you click into them via the thread watcher._

**Comment by Adamantcheese** [comment]
This already exists as filter watching. You'll need to enable the thread and background watcher, and then enable the option at the bottom of the list. Then add in filters with the "watch" option to match what threads you automatically want to be bookmarked. Catalogs are checked according to the background watch period.
