### ISSUE TITLE
[BUG] Check the branch before checking the SECRETKEY in upload_apk script

### ISSUE THREAD

**Issue by K1rakishou** [Adamantcheese/Kuroba#451]
This should fix the issue with PRs failing the build and I will probably be able to revert the change I made recently.

**Comment by Adamantcheese** [comment]
Closing as this no longer appears to be an issue as of https://github.com/Adamantcheese/Kuroba/commit/6c0f7f813bbee22dc135555332d84a72f6bb84dd
