### ISSUE TITLE
[Feauture] Make it unable to run/install if person has certain apps.

### ISSUE THREAD

**Issue by Yoirkie** [Adamantcheese/Kuroba#452]
I really dont want more tranny phone posters.
If a user has apps downloaded such as Tiktok, snapchat, instagram, reddit (other related apps), twitter (other related apps), grinder, etc.
Thank you Floens.

**Comment by Adamantcheese** [comment]
![](https://i.kym-cdn.com/photos/images/original/000/637/273/7c6.png)
