### ISSUE TITLE
SAF crashes app if base folder is missing when downloading image

### ISSUE THREAD

**Issue by Coy-Allen** [Adamantcheese/Kuroba#453]
When you delete the save location or saved threads location in Kuroba while you are in SAF mode it works fine until you try to save an image or thread. When you do save an the app crashes.
I am using Kuroba v4.10.1

I should also note that I am using SAF pointing to (local storage)/Kuroba

**Comment by K1rakishou** [comment]
>When you delete the save location or saved threads location

Well you shouldn't do that or if you have already done it then you can choose a new base directory. But the app shouldn't crash, yes. I will add checks and will show toasts in case having no base directory.
