### ISSUE TITLE
Unable to post on sushichan

### ISSUE THREAD

**Issue by pExeen** [Adamantcheese/Kuroba#456]
I get this error: "Error posting: Your browser sent an invalid or no HTTP referer".
Thanks for this client btw ^^

**Comment by Adamantcheese** [comment]
This looks like it's been an issue for over 2 years, even for browsers; the owner of Sushichan says they couldn't find any way to turn off it being required. No guarantees.

**Comment by Adamantcheese** [comment]
@pExeen, I've got some info if you want to forward it to the Sushichan administrators. According to https://sushigirl.us/yakuza/res/191.html#504, they couldn't find something to disable this check in the configuration, but according to the vichan source code, there's this bit `$config['referer_match']` that should disable the check, and would allow posting probably.

**Comment by Adamantcheese** [comment]
Closing as a solution on the site admin's side has been provided and is up to them to fix.
