### ISSUE TITLE
Captcha is broken

### ISSUE THREAD

**Issue by JohannesZomir** [Adamantcheese/Kuroba#457]
The captcha does not load. it gives the error pictures below.
![Screenshot_20191215-121717](https://user-images.githubusercontent.com/58912592/70866217-07a1e680-1f35-11ea-8890-3c9303886302.jpg)

**Comment by JohannesZomir** [comment]
Error message 

> E/Kuroba | CaptchaNoJsPresenterV2: Error while trying to parse captcha html data E/Kuroba | CaptchaNoJsPresenterV2: com.github.adamantcheese.chan.ui.captcha.v2.CaptchaNoJsHtmlParser$CaptchaNoJsV2ParsingError: Could not parse any checkboxes!
E/Kuroba | CaptchaNoJsPresenterV2: 	at com.github.adamantcheese.chan.ui.captcha.v2.CaptchaNoJsHtmlParser.parseCheckboxes(CaptchaNoJsHtmlParser.java:274)
E/Kuroba | CaptchaNoJsPresenterV2: 	at com.github.adamantcheese.chan.ui.captcha.v2.CaptchaNoJsHtmlParser.parseHtml(CaptchaNoJsHtmlParser.java:83)
E/Kuroba | CaptchaNoJsPresenterV2: 	at com.github.adamantcheese.chan.ui.captcha.v2.CaptchaNoJsPresenterV2.handleGetRecaptchaResponse(CaptchaNoJsPresenterV2.java:303)
E/Kuroba | CaptchaNoJsPresenterV2: 	at com.github.adamantcheese.chan.ui.captcha.v2.CaptchaNoJsPresenterV2.getCaptchaInfo(CaptchaNoJsPresenterV2.java:234)
E/Kuroba | CaptchaNoJsPresenterV2: 	at com.github.adamantcheese.chan.ui.captcha.v2.CaptchaNoJsPresenterV2.lambda$requestCaptchaInfo$1$CaptchaNoJsPresenterV2(CaptchaNoJsPresenterV2.java:187)
E/Kuroba | CaptchaNoJsPresenterV2: 	at com.github.adamantcheese.chan.ui.captcha.v2.-$$Lambda$CaptchaNoJsPresenterV2$uicMjkiJC8AEs7esRrZg5IotKaw.run(Unknown Source:2)
E/Kuroba | CaptchaNoJsPresenterV2: 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:459)
E/Kuroba | CaptchaNoJsPresenterV2: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
E/Kuroba | CaptchaNoJsPresenterV2: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
E/Kuroba | CaptchaNoJsPresenterV2: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
E/Kuroba | CaptchaNoJsPresenterV2: 	at java.lang.Thread.run(Thread.java:764)
E/Kuroba | CaptchaNoJsLayoutV2: CaptchaV2 error
E/Kuroba | CaptchaNoJsLayoutV2: com.github.adamantcheese.chan.ui.captcha.v2.CaptchaNoJsHtmlParser$CaptchaNoJsV2ParsingError: Could not parse any checkboxes!
E/Kuroba | CaptchaNoJsLayoutV2: 	at com.github.adamantcheese.chan.ui.captcha.v2.CaptchaNoJsHtmlParser.parseCheckboxes(CaptchaNoJsHtmlParser.java:274)
E/Kuroba | CaptchaNoJsLayoutV2: 	at com.github.adamantcheese.chan.ui.captcha.v2.CaptchaNoJsHtmlParser.parseHtml(CaptchaNoJsHtmlParser.java:83)
E/Kuroba | CaptchaNoJsLayoutV2: 	at com.github.adamantcheese.chan.ui.captcha.v2.CaptchaNoJsPresenterV2.handleGetRecaptchaResponse(CaptchaNoJsPresenterV2.java:303)
E/Kuroba | CaptchaNoJsLayoutV2: 	at com.github.adamantcheese.chan.ui.captcha.v2.CaptchaNoJsPresenterV2.getCaptchaInfo(CaptchaNoJsPresenterV2.java:234)
E/Kuroba | CaptchaNoJsLayoutV2: 	at com.github.adamantcheese.chan.ui.captcha.v2.CaptchaNoJsPresenterV2.lambda$requestCaptchaInfo$1$CaptchaNoJsPresenterV2(CaptchaNoJsPresenterV2.java:187)
E/Kuroba | CaptchaNoJsLayoutV2: 	at com.github.adamantcheese.chan.ui.captcha.v2.-$$Lambda$CaptchaNoJsPresenterV2$uicMjkiJC8AEs7esRrZg5IotKaw.run(Unknown Source:2)
E/Kuroba | CaptchaNoJsLayoutV2: 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:459)
E/Kuroba | CaptchaNoJsLayoutV2: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
E/Kuroba | CaptchaNoJsLayoutV2: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
E/Kuroba | CaptchaNoJsLayoutV2: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
E/Kuroba | CaptchaNoJsLayoutV2: 	at java.lang.Thread.run(Thread.java:764)
I/Kuroba | CaptchaNojsLayout: 1:Uncaught TypeError: Cannot read property 'value' of null https://www.google.com/recaptcha/api/fallback?k=6Ldp2bsSAAAAAAJ5uyx_lx34lJeEpTLVkP5k04qc

**Comment by Yoirkie** [comment]
I was about to post, glad im not the only one

![w345](https://user-images.githubusercontent.com/55001676/70866624-839a2f80-1f31-11ea-8ff1-865a43411a1c.png)

**Comment by MilkyPL** [comment]
Noscript captcha seems to be broken sitewide, it's either Hiro or google

**Comment by K1rakishou** [comment]
It's broken for everyone. Use javascript captcha for now.

**Comment by MilkyPL** [comment]
> It's broken for everyone. Use javascript captcha for now.

how do I enable it in 4.10.2?

**Comment by K1rakishou** [comment]
Settings -> Site settings -> Captcha type

**Comment by ghost** [comment]
I have this problem too.
