### ISSUE TITLE
[IMPROVEMENT] After updating OkHttpClient to 4.3 remove hack introduced in #449

### ISSUE THREAD

**Issue by K1rakishou** [Adamantcheese/Kuroba#464]
https://github.com/Adamantcheese/Kuroba/pull/449

The hack is to fix this issue https://github.com/square/okhttp/issues/3146

**Comment by K1rakishou** [comment]
We should also test that it works and the hack can be removed. They merged the fix but who knows. Still needs manual testing.

**Comment by Adamantcheese** [comment]
The 4.3 release is scheduled for next year, and I'm not going to do any Kuroba releases until then so this can wait.

**Comment by K1rakishou** [comment]
Well yes, it's not in yet so if it so happens that 4.3 comes out earlier than FileCacheV2 is merged then I will remove the hack right away.

**Comment by K1rakishou** [comment]
So 4.3 is out and the hack is already removed.
