### ISSUE TITLE
[MEMORY LEAK/BUG] When using "Get image from clipboard url" feature with a broken link StartActivity gets leaked

### ISSUE THREAD

**Issue by K1rakishou** [Adamantcheese/Kuroba#466]
I guess that's because the request is active and when you close the app it's still active and does not get canceled so everything gets leaked. And the timeout for that thing is pretty high (like 30 seconds?). I guess if you try to use another link when a request is being executed the previous request won't be canceled which should be fixed as well. So:

- Timeout should be decreased to 10 seconds or something.
- When closing the app the active request should be canceled.
- When posting a link while there already active request the previous request should be canceled.

UPD: This was found in my branch with the new FileCache so I will fix it myself.

![Screenshot_20191220-134350](https://user-images.githubusercontent.com/10332458/71250041-bc6e4600-232f-11ea-9acc-18fa112c5865.png)

**Comment by Adamantcheese** [comment]
Closed with merge.
