### ISSUE TITLE
[BUG] "Apply to own posts" and "Apply to replies" filter options don't seem to work

### ISSUE THREAD

**Issue by Astridchan** [Adamantcheese/Kuroba#470]
If I make a filter as follows it will highlight every thread and reply as expected:

![Screenshot_20191220-202605](https://user-images.githubusercontent.com/40862101/71283027-b2683980-2367-11ea-997a-315f75a3e217.jpg)

But if I edit the filter to check "Apply to replies", it seems absolutely nothing changes. Every thread and post still remains highlighted. And if I uncheck that option and check "Apply to own posts" instead, _nothing_ will be highlighted, not even your own posts like it should.

**Comment by Adamantcheese** [comment]
Your pattern is incorrect, should be `/.*/`. `*` should only be matching things with that literal character in them, or be erroring out because that's not valid regex. Will look at that sometime.
The apply to replies option is only used when hiding or removing posts currently. In any case, apply to replies when matching every single post wouldn't change anything. 
And apply to own posts did have a bug in it, which has likely been present since Clover (if it ever implemented that feature).

**Comment by Astridchan** [comment]
>\* should only be matching things with that literal character in them

Should it? From reading the filter help section (the (?) icon in the above screenshot) it seems you don't actually need to use regex for the search patterns.

>The apply to replies option is only used when hiding or removing posts currently. In any case, apply to replies when matching every single post wouldn't change anything.

Ah ok, I though "apply to replies" meant replies to _my_ posts, ie. (You)'s. Disregard that part then. Maybe that would make sense as an option though?

**Comment by Adamantcheese** [comment]
Yes, without the slashes around the word, it's treating everything as literal text, as in `match words that are exactly * in posts`.

**Comment by Astridchan** [comment]
But from this:

![Screenshot_20191220-234002](https://user-images.githubusercontent.com/40862101/71294799-4941ef80-2382-11ea-9329-39354725d850.jpg)

I understand it that if you don't use the slashes it doesn't use regex at all for pattern matching, and in point 1 it says the * will match to any character.

**Comment by Adamantcheese** [comment]
Mm, well then the reason why * matches every post is that every post has at least 1 character in it. If you come across a blank post then it wouldn't match that.

**Comment by Astridchan** [comment]
Yeah, that's right, I did notice it wasn't matching empty posts at first, but since on 4chan the only way you can make a post without text in it is to have an file attached, you can just make the filter match both post text and the file name, that way you can match almost* everything with just the `*`.

\* I just noticed that with the regular pattern matching `*` only matches to letters, numbers, `_` and `π` (out of the symbols on my phone keyboard), whereas with regex `/.*/` it matches all the other special characters too. So the regex filter does work better for matching everything but it's kind of an edge case (a post containing special characters and nothing else).
