### ISSUE TITLE
[Feature request] Allow us to use what ever filepicker we want

### ISSUE THREAD

**Issue by Managor** [Adamantcheese/Kuroba#474]
My current filepicker that kuroba automatically selects does not support webm thumbnailing. I'm unable to uninstall or disable it so an option would be very nice.

**Comment by Pentaphon** [comment]
Sorta of related but does anybody have an issue where, when using the filepicker, Kuroba closes before you can finishing selecting a webm from your gallery app and you have to write your post again?

**Comment by K1rakishou** [comment]
Post logs right after it does it again.
