### ISSUE TITLE
Context Menu not working on MIUI 10.3

### ISSUE THREAD

**Issue by uenoshita** [Adamantcheese/Kuroba#476]
Context menu (spoilers/code) does not work on MIUI. I'm currently using a stock Redmi Note 7 and MIUI version 10.3 Global.
--

**Comment by uenoshita** [comment]
Context menu (spoilers/code) does not work on MIUI. I'm currently using a stock Redmi Note 7 and MIUI version 10.3 Global.

**Comment by Adamantcheese** [comment]
Yeah, too bad MIUI fucks with everything.
