### ISSUE TITLE
Duplicate setting

### ISSUE THREAD

**Issue by TacoTheDank** [Adamantcheese/Kuroba#477]
Both Appearance and Behavior have the same Emoji parsing and posting setting. Fix pl0x

**Comment by K1rakishou** [comment]
![434234234](https://user-images.githubusercontent.com/10332458/71827967-6f6dcc00-30b2-11ea-911e-d70d1b6c68db.png)

Looking at the code, apparently, it was made intentionally. 
@Adamantcheese do we really need two of them in different places?

**Comment by Adamantcheese** [comment]
Yeah it was an intentional duplicate because the setting covers an Appearance function and a Behavior function. I'll leave it as-is for the time being.
