### ISSUE TITLE
[BUG] Clicking an image, in a rolling sticky thread, that is already removed from the server makes the app stuck in the gallery view which you can't exit by pressing back button

### ISSUE THREAD

**Issue by K1rakishou** [Adamantcheese/Kuroba#487]
I found this in my branch with the new FileCache so maybe it's my bug. **Not confirmed in the dev yet**.
I remember we already had the same issue some time in the past but I can't find it. It's literally the same as the old one.

**Comment by K1rakishou** [comment]
Not it's not like this. It's when you have an image already downloaded and you open it again after the post associated with it gets deleted from the server and you receive the diff without it that's when it get's stuck in the gallery.

**Comment by K1rakishou** [comment]
**Confirmed in the dev**.

Here is the code where it fails:
```
if (!setTransitionViewData(startImageView)) {
     Logger.test("Oops");
     return; // TODO
}
```

`ImageViewController.startPreviewInTransition()`

**Comment by Adamantcheese** [comment]
This one's actually the same as #914 and should've been closed a while ago.
