### ISSUE TITLE
Captcha is listed under 'Media' settings when in reality itcs found in the 'Sites'

### ISSUE THREAD

**Issue by Managor** [Adamantcheese/Kuroba#497]
It should not be  listed here 
![Screenshot_20200107-051000_Kuroba](https://user-images.githubusercontent.com/42655600/71865684-3a8e6300-310c-11ea-9273-640bfe4d32ed.png)

When it is found here
![Screenshot_20200107-051012_Kuroba](https://user-images.githubusercontent.com/42655600/71865706-52fe7d80-310c-11ea-8c5d-6b95b90a3bbe.png)

**Comment by Adamantcheese** [comment]
Resolved as of https://github.com/Adamantcheese/Kuroba/commit/98e6ba7af4ed3ca8ccc78d52ba2c988cd745842e.
