### ISSUE TITLE
list of supported sites

### ISSUE THREAD

**Issue by DigitalCorgi** [Adamantcheese/Kuroba#502]
I don't know if it already exists somewhere or if it doesn't exist, but I would really like to have a list somewhere in the readme of what sites are supported.

**Comment by K1rakishou** [comment]
Here you go - https://github.com/Adamantcheese/Kuroba/tree/multi-feature/Kuroba/app/src/main/java/com/github/adamantcheese/chan/core/site/sites

**Comment by DigitalCorgi** [comment]
Thank you
