### ISSUE TITLE
[Question] Use cookie for easier Captcha solving

### ISSUE THREAD

**Issue by Astridchan** [Adamantcheese/Kuroba#503]
Now that everyone is forced to use the JS captcha, could you look into the possibility of using Google Chrome's cookies for easier Captcha solving in the app? If you've submitted yourself to the Google botnet and browse with Chrome logged into a Google account, Google will give you easier Captchas to solve. When posting on the 4chan website on Chrome, the majority of time it either makes you just click a checkbox to solve Captcha, or doesn't require you to solve a Captcha at all:

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/40862101/72098588-70f3fa00-3327-11ea-87a1-b5f28fa6921e.gif)

![ezgif com-optimize](https://user-images.githubusercontent.com/40862101/72098596-74878100-3327-11ea-8468-83fc2c441992.gif)

**Comment by K1rakishou** [comment]
But will the cookie alone be enough? I mean when loading a JS captcha use also load a huge obfuscated JS blob which is then executed and it decideds whether you are a bot or not. It's unknown what it does (it's probably a VM that executes some checks received from the google servers).

This thing is nothing like the old no-js captcha where a cookie could fool it into giving you the easiest  captchas.

**Comment by Astridchan** [comment]
I assumed WebView would be able to access Chrome cookies similar to Chrome Custom Tabs since it is (or was) powered by Chrome but seems that is not the case:
https://stackoverflow.com/questions/35150678/share-cookies-between-webview-and-chrome

To be clear, is Kuroba currently setting a cookie with the JS Captcha? The reason I opened this issue is because I've seen anons mention they've got the easy Captchas (where only clicking checkbox is often enough to solve Captcha similar to the website) in other 4chan Android apps, so it must be possible somehow. See here for example:
https://rbt.asia/g/thread/71979086/#71981074

Maybe this is relevant? Specifically the answer by user barbolo:
https://stackoverflow.com/questions/27286232/how-does-google-recaptcha-v2-work-behind-the-scenes

**Comment by K1rakishou** [comment]
Well, we can try. But no promises.

**Comment by K1rakishou** [comment]
Alright, apparently it's pretty easy to implement and, what's more important, it actually works!

**Comment by Astridchan** [comment]
That's great to hear, thanks!

**Comment by Pentaphon** [comment]
I wonder if people will try cookie spoofing with this.

**Comment by ghost** [comment]
You can use a 4chan pass cookie to get around captchas too.
