### ISSUE TITLE
Saving thread albums to their own folder

### ISSUE THREAD

**Issue by articpinecone** [Adamantcheese/Kuroba#512]
On version 4.10.2 of kuroba when you use the download albums feature to download all the images of a thread the images just get dumped to the same base folder as all the other image/webm downloads. In the clover app which kuroba is a fork of when you use the download album feature a new folder with the name of the thread gets created then the images from that thread get saved there. Could we perhaps have the option to choose between the two, saving the album images to the base folder or save them to their own dedicated folder that has the name of the thread?

**Comment by Adamantcheese** [comment]
Use the board folder and thread folder options if you'd prefer album downloads to be downloaded into appropriate folders rather than the base directory.
