### ISSUE TITLE
Place files downloaded through the share function in a subdirectory

### ISSUE THREAD

**Issue by Managor** [Adamantcheese/Kuroba#517]
I think there needs to be a distinction between explicitly downloaded files and the files that are downloaded to make the share functionality work. As my suggestion, I wish that the shared files are placed in a subdirectory in the save location whereas the files downloaded by explicitly tapping the download button are placed in the root of the save location.

For me the benefit of this would be when I eventually sort out reaction images to their own storage. I don't really need to save images of lewds that I share to discord.

**Comment by Adamantcheese** [comment]
It actually does add _shared to the file, but only after the first download. Oversight on my part.

**Comment by Managor** [comment]
The solution isn't exactly what I needed. I want the files saved with the share functionality to be placed in a subfolder for easy differentiation from files that have been saved intentionally. 
For example any time I save a file by pressing the download button, it would be saved in `/Kuroba` but when I want to share a file it would be saved in `/Kuroba/shared`

It's hard to find the important images from the mass of lewds.

**Comment by Adamantcheese** [comment]
As shared files are no longer visible to the user (they're shared directly from the file cache), I'm closing this.
