### ISSUE TITLE
[BUG] Pasting formatted text removes spaces from post

### ISSUE THREAD

**Issue by Astridchan** [Adamantcheese/Kuroba#521]
See: https://github.com/chandevel/Clover/issues/679

Sadly it seems this commit https://github.com/Adamantcheese/Kuroba/commit/9410cb47391e276dc9016e34d11f40eeb4b983d7 did not make any difference with regards to this issue. On the other hand, if you select "paste as plain text" instead of "paste" when pasting the text does then get posted correctly. The bug happens on Galaxy S10 running Android 10, Pocophone F1 running Android 9.0 and Nvidia Shield K1 running Android 7.0.

**Comment by Adamantcheese** [comment]
Note for me: see the last comment #469 as well and fix at the same time.
