### ISSUE TITLE
[IMPROVEMENT] Mark unread posts with a colored line

### ISSUE THREAD

**Issue by K1rakishou** [Adamantcheese/Kuroba#526]
Remove the line (mark it as read) when a post was either read normally (it was scrolled over) or when a post is opened in a reply chain.

Rationale: this is really useful when you were reading a huge reply chain and then you close it and don't want to read the same posts, so the post marker would be really useful to just ignore those posts and concentrate only on posts you haven't read yet.

Something like this:
![345346347347](https://user-images.githubusercontent.com/10332458/73125017-317a0e80-3fb3-11ea-8558-d218a93f9bfc.png)

Read posts ~~(site id (but I think it would be a better idea to somehow the site name - like 4chan.org - instead of id because we really need to get rid of these ids, they are really bad), board code and post id)~~ (I guess it will be really fucking hard, like half of the app will need to be rewritten and then the merge conflicts will literally kill the person who will have to resolve them, so fuck it) should be stored in the DB, no json files allowed! Don't forget to make sure this thing works with local threads.

**Comment by K1rakishou** [comment]
I guess it would also be a really good idea to refactor PostCell.bindPost() method because right now it's a fucking mess. Or even the whole PostCell because there are lots of things that should be extracted into separate classes.

**Comment by K1rakishou** [comment]
We could even use different colors (like for replies to your posts) in future after this task is implemented.

**Comment by Astridchan** [comment]
Kuroba already uses color lines for the filter highlight feature, it might conflict with this since you'd end up with two different color lines on some posts. Dashchan has this feature except that is uses a slightly different shade of background colors for read and unread replies, might want to check that out.

One suggestion, if this does get implemented then scrolling past a (You) reply should mark it read and clear the notification. Currently you need to scroll to the bottom of the thread to do that.

**Comment by K1rakishou** [comment]
@Astridchan Oh damn it, you are right. Then the line could just be ignored for the posts matched by the filters. In other words, the filters would take precedence over this feature, or something like that. I wonder what else I'm missing.

**Comment by Adamantcheese** [comment]
Closing as it seems that most people who use Kuroba-Ex have this disabled anyways. It's neat from a technical standpoint, but adds visual clutter for no real benefit.
