### ISSUE TITLE
[IMPROVEMENT] Allow displaying of more than 5 inlined files

### ISSUE THREAD

**Issue by K1rakishou** [Adamantcheese/Kuroba#528]
Since we now also support inlining of webp files I think it would be great. 

If there are more than 5 inlined files, instead of displaying all of them, we should add some kind of button (or rather display some kind of hint, like "view the rest X" to the last image), on the last image and when clicking it a dialog window (or rather a new controller with transparent background so that when you click an image it opens on top of this controller (it may not work with dialog window)) will show up where the user will be able too see the rest of inlined files/images. (or maybe just show all of them together?) All inlined files will have the same thumbnail, but there is nothing we can do with this.

But I guess it will become possible to abuse this thing which will make thread loading times slower (or it won't?) so we  probably should set some maximum amount of inlined files to something like 20-30? Or even make it a separate setting.

**Comment by Adamantcheese** [comment]
I think I've told you this before, but inlining/hotlinking files isn't meant to act as a "oh hey let's just dump links" style way of dumping images; it's abusable that way. I've got it capped at a max of 5 images because that's the max that most *chans tend to support natively. I don't want posts to become albums themselves, it'll look like shit.

**Comment by K1rakishou** [comment]
Alright, then how about this: some chans allow attaching up to 8 images (and we support them). Along with inlined files there may be up to 13 attached files in one post (I guess we don't limit the amount of regular attached files in any way, or do we?). This PR could be useful for such cases where there are lots of attached files.

So, basically, if a post has more than 4/5 attached images, the last one will act like a button that will bring up a list of all (or not all but not ones in the post) attached files. Like how dashchan does that.
