### ISSUE TITLE
[Bug] Problems with image saving. 

### ISSUE THREAD

**Issue by Yoirkie** [Adamantcheese/Kuroba#530]
One of two things happen when I try to save an image. Using current version. 

1. App automatically closes.
2. "Base directory for files does not exist"

It used to download images perfectly after a fresh install and create its own directory, but now I have to do everything manually.

**Comment by K1rakishou** [comment]
1. Do use use SAF or the old API?
2. If you use SAF, do you store your images on an SD-card?
3. If you use SD-card did you remove it from your phone and then put it back?
4. If you use SD-card do you have the root access on your phone? And if you do do you use some kind of SD-card software?
5. Gib logs when it crashes next time.

**Comment by K1rakishou** [comment]
@Yoirkie So what was that? Did you manage to fix it? I'm really interested.
