### ISSUE TITLE
Opacity setting resetting every image open

### ISSUE THREAD

**Issue by namazso** [Adamantcheese/Kuroba#533]
https://streamable.com/kl6x6

**Comment by Adamantcheese** [comment]
If you would prefer that images are transparent by default, there is a setting for that. Otherwise, this is working as intended.

**Comment by namazso** [comment]
oh. I assumed it's meant to remember whatever you set last time. Also, why did I need two clicks then to flip from the default?

**Comment by Adamantcheese** [comment]
Not sure what you mean? Any menu item is always two taps away, and recently image transparency was defaulted to off. If it's better to have it on, I can put in a change for that.

**Comment by namazso** [comment]
rewatch the video.
when default setting is opaque, you need to "toggle" opacity *twice* to get it to display transparent. As if the initial state of the toggle button was transparent, except the global setting was overriding it

**Comment by Adamantcheese** [comment]
Ah, my mistake.
