### ISSUE TITLE
Not seeing archives

### ISSUE THREAD

**Issue by Yoirkie** [Adamantcheese/Kuroba#534]
What could be a reason for me not being able to see archives on current or deleted threads?
Did incremental thread downloading replace this?
![Screenshot_20200128-114535](https://user-images.githubusercontent.com/55001676/73301658-cad63a00-41d8-11ea-99e9-4bdfd045e3c2.jpg)

**Comment by Adamantcheese** [comment]
See #480, #531, #492. Also see #504. Don't post this again and look at your old issues beforehand.
