### ISSUE TITLE
App doesn't remember save location setting [Video]

### ISSUE THREAD

**Issue by Esildor** [Adamantcheese/Kuroba#537]
Video of STR: https://m.imgur.com/a/WrL90fL

Get an error when trying to save an image.
 Set it up in settings.
 Restart app. 
Settings are lost and error repeats

Pixel 4 stock Android

**Comment by Adamantcheese** [comment]
Cool picture of a panda, I'm going to assume that #506 fixes this probably.

**Comment by K1rakishou** [comment]
@Adamantcheese No, I just added more logs in that update. One anon had a similar problem and then he figured out that his sd-card was at fault. For some reason it would always reset the path if he selected some directory on the sd-card but it would work as expected if he selected the sd-card root as a base directory. And that was really strange. I dunno why would it happen. But he said that his sd-card was at fault.

1. Do use use SAF or the old API?
2. If you use SAF, do you store your images on an SD-card?
3. If you use SD-card have you ever removed it from your phone and then put it back after selecting it as a base directory?
4. If you use SD-card do you have the root access on your phone? And if you do do you use some kind of SD-card software?
5. Gib logs.
6. You posted the wrong link to a video.

**Comment by Esildor** [comment]
Updated original post with correct video

**Comment by Esildor** [comment]
As you'll see in the video I use SAF.

Following the same STR using the old API I get this error
![Screenshot_20200201-121946](https://user-images.githubusercontent.com/5234969/73587371-6b846c80-44ed-11ea-81d3-d7bfe3acdb88.png)

The Pixel 4 doesn't have an SD card slot, so no changes with that

**Comment by K1rakishou** [comment]
Ohhh, so you are using the Downloads directory as your base directory. That may explain a lot. For now, could you try creating a new dir inside Downloads directory and try selecting the new directory?

>The Pixel 4 doesn't have an SD card slot, so no changes with that

Yeah, that was a stupid question, haha.

**Comment by K1rakishou** [comment]
There is something strange with the directory you are selecting as a base directory. It has some strange provider in it's path. I have no idea what it is (Apparently it's download manager but I have no idea what to do with it). Maybe it's giving a new id every time you open the app and that's why it won't save it. Man, fuck SAF and fuck Google. The most retarded API in existence. 

I couldn't reproduce it on the emulator. I can only suggest you to try another directory, not Downloads. Try the one Kuroba creates by default of it's first run. Or try creating a new directory inside the Downloads directory and select it.

**Comment by Esildor** [comment]
Seems like the latest version fixes this

**Comment by K1rakishou** [comment]
That's very strange because fixes are not in yet.

**Comment by K1rakishou** [comment]
By the way, I have one more question: do you have multiple users/accounts on your phone and if you do which user/account do you use when running kuroba?

**Comment by K1rakishou** [comment]
This one should be closed since there were no new reports.
