### ISSUE TITLE
[Feature Request] Ability to view cross-board/thread linked posts without leaving the current thread

### ISSUE THREAD

**Issue by Astridchan** [Adamantcheese/Kuroba#54]
On the 4chan desktop website, you can view posts that have been cross-board or cross-thread linked to, without leaving the current thread, by hovering over the link with your cursor:

![Capture1111](https://user-images.githubusercontent.com/40862101/59149919-7e10d980-8a24-11e9-972b-d9e1ca31ae97.PNG)

In Kuroba, when you click on a cross-thread/board link, you only get a prompt to open the thread the linked post is in:

![Screenshot_2019-06-08-19-36-21-477_com github adamantcheese chan](https://user-images.githubusercontent.com/40862101/59150144-8880a280-8a27-11e9-9870-096ded37acf8.png)

It would be convenient if, when you clicked on a cross-board/thread link in Kuroba, it would fetch the content of the linked post and display it as if it was a post in the currently open thread, so that the user could view it and interact with it without having to leave the current thread. Only thing needed to be added would be an "Open" reply button to open the thread the cross-board/thread post is in.

Quick mockup (maybe the background color should be made different to visually distinguish cross-thread/board posts from regular posts):

![Screenshot_2019-06-08-19-36-21-477_com github adamantcheese chan](https://user-images.githubusercontent.com/40862101/59150349-9edc2d80-8a2a-11e9-8367-66152f768162.png)

**Comment by Astridchan** [comment]
Was closing this issue intentional? As the commit doesn't actually seem to introduce the feature described in this issue.

**Comment by Adamantcheese** [comment]
Between the two of #52 and this one, #52 makes more sense. I need to have it scroll to the correct location now though.
