### ISSUE TITLE
[Feature Request] youtube link title preview

### ISSUE THREAD

**Issue by stradus64** [Adamantcheese/Kuroba#55]
Option to display video title next to or instead of YT link like on web browser
![image](https://user-images.githubusercontent.com/10760147/59151170-cf25cb00-8a2e-11e9-99ed-997c98da17a6.png)

**Comment by Adamantcheese** [comment]
Whoever works on this (if not me), can grab the information from 4chanX. https://github.com/ccd0/4chan-x/search?utf8=%E2%9C%93&q=youtubeAPIKey&type=
