### ISSUE TITLE
Odd URI encoding possibly breaking SAF

### ISSUE THREAD

**Issue by spencerhakim** [Adamantcheese/Kuroba#553]
Just switched from Clover and I'm running into an issue when trying to use my SD card for storage via SAF. I'm able to select the folder I want, but when I try to save an image, the app just hangs (possibly related to whatever was going on in #530?). The URI displayed in settings definitely doesn't look correct:
![Screenshot_20200203-104515](https://user-images.githubusercontent.com/606857/73699329-80a9f880-46b1-11ea-8a64-ad485f23349a.png)

Sometimes when trying to switch back to using the old API I get this error toast, though I haven't been able to reproduce it reliably:
![Screenshot_20200203-104542](https://user-images.githubusercontent.com/606857/73699405-b51db480-46b1-11ea-9ccf-2c1308338739.png)

The URI is also oddly encoded when selecting internal storage via SAF:
![Screenshot_20200203-105826](https://user-images.githubusercontent.com/606857/73699453-d7173700-46b1-11ea-92d5-c407f1d4ca59.png)

Using the current release build (v4.10.2) on a Moto Z3 Play running Android 9 (Nov 2019 patch level). Not rooted or anything.

**Comment by K1rakishou** [comment]
>I'm able to select the folder I want, but when I try to save an image, the app just hangs

Can you please do it again and then post the logs here?

**Comment by spencerhakim** [comment]
Apparently if I wait long enough, the image does eventually save successfully, but it takes 10+ seconds. Interestingly, subsequent image saves occur much quicker (though still slower than Clover).

Logs (pulled from Developer Settings):
```
I/Kuroba | WakeManager: Started background alarm with an interval of 5 minutes
E/Kuroba | Chan4: Failed to get archives for 4Chan
I/Kuroba | FilterWatchManager: Processing filter loaders, started at 10:52:48 AM
E/Kuroba | FileCache: Could not set last modified time on file
E/Kuroba | FileCache: Could not set last modified time on file
E/Kuroba | FileCache: Could not set last modified time on file
E/Kuroba | FileCache: Could not set last modified time on file
```

So I guess the SAF URI encoding is fine, even though it looks different than what I'd expect/have seen in other screenshots, so feel free to update the title or close this in favor of another issue.

**Comment by K1rakishou** [comment]
>but it takes 10+ seconds

Damn that's a lot. I mean SAF is really slow but that is way too much. Do you have a lot of files in a directory where you save new files? Or maybe just a lot of file on the sd-card? Because this might be the case.

>though still slower than Clover

Clover uses standard Java File API which is blazing fast compared to SAF.

**Comment by spencerhakim** [comment]
I do have a ton of files in that folder and on the SD card in general, and it probably takes about the same amount of time to open that folder up in a file browser. Clover/Kuroba check for a pre-existing file with the same name before saving so they can append a `_0` or something to the name, right? I'm guessing that's what's killing my performance here. Would it be possible to disable that check when "Save server filename" is enabled? Those filenames should already be unique, correct?

**Comment by K1rakishou** [comment]
>Clover/Kuroba check for a pre-existing file with the same name before saving so they can append a _0 or something to the name, right?

Yes.

> I'm guessing that's what's killing my performance here.

Yeah, I would say it's definitely the cause. SAF is like 30-50 times slower than the regular Java File API and we do check whether a file exists before saving it. You could just probably select a different directory, it should help. 

>Would it be possible to disable that check when "Save server filename" is enabled? Those filenames should already be unique, correct?

Well, we still need to check whether a file exists or not to figure out whether we even need to download it in the first place.

**Comment by spencerhakim** [comment]
Fair enough. I'll close this out then, thanks for the help.

**Comment by K1rakishou** [comment]
@spencerhakim 
By the way, how many files did you have in that directory? I'm planning to generate the same amount of files to debug this stuff and maybe try to improve the speed.

**Comment by spencerhakim** [comment]
A bit over 10k; years of random crap that I've just moved from phone to phone without ever cleaning up 😬

**Edit** - Oh, and for further reference, [this](https://smile.amazon.com/gp/product/B07FCMKK5X/) is the SD card I'm currently using. I don't have it formatted for adopted storage, so it should be exFAT.

**Comment by K1rakishou** [comment]
Damn that's really a lot of files, I tested this thing on a directory with like 500 files in it. Alright, thanks for the info.
