### ISSUE TITLE
2ch.hk: every post in a pinned thread is marked as pinned

### ISSUE THREAD

**Issue by fgsfds** [Adamantcheese/Kuroba#554]
![Screenshot_2020-02-04-14-23-39-771_com github adamantcheese chan](https://user-images.githubusercontent.com/4870330/73731476-5d875380-475a-11ea-88a2-e3dc3575ed1f.jpg)

**Comment by Adamantcheese** [comment]
I have reason to suspect that the Dvach API has issues, because it was marking every post in the thread as the OP and a sticky. Other threads also had the issue of every post being the OP; the OP field sent by the site doesn't correspond to the actual thread number either.

**Comment by fgsfds** [comment]
Sent bug report to 2ch admin. Hopefully it'll be fixed.
