### ISSUE TITLE
[BUG?] Apparently context menu doesn't work as expected on some phones so people can't use tags

### ISSUE THREAD

**Issue by K1rakishou** [Adamantcheese/Kuroba#558]
We should add an option to disable it and let people use the old option. Can't confirm this since I don't have a phone where this thing doesn't work. it's probably some chinkphone or samsung.

UPD:
One of the phones is Samsung on Android 5 and IIRC this shit only works starting with Android 6. So that's the problem.

**Comment by Astridchan** [comment]
I will add that phones with MIUI also cannot access the context menu options either regardless of Android version since MIUI replaces the context menu with their own implementation, see 
https://github.com/Adamantcheese/Kuroba/issues/476
https://github.com/chandevel/Clover/issues/699

**Comment by Adamantcheese** [comment]
ActionMode based context menus are not Android 6, they're Android 3. If context menus aren't working, your ROM sucks. Same thing goes for MIUI, tough luck, but I'm not going to put any effort into it.
