### ISSUE TITLE
allow setting any combination of HSID, SSID, SID and NID cookies.

### ISSUE THREAD

**Issue by drogga3** [Adamantcheese/Kuroba#559]
reCAPTCHA on my end (Botnet google chrome browser version 79.0.3945.117) only ever set NID cookies, no matter how much captcha I solve.

https://policies.google.com/technologies/types?hl=en

EDIT: HSID and SID only shows up if you logged in to Google, additionally, SSID are also set, but not required to keep you logged into Google.

**Comment by Adamantcheese** [comment]
All cookies are required because otherwise you won't have the best chance of getting non-fade captchas.
