### ISSUE TITLE
[BUG] Swiping through WebMs sometimes fail to load a WebM

### ISSUE THREAD

**Issue by kurobaissues** [Adamantcheese/Kuroba#56]
Title. 

Video: https://files.catbox.moe/w1iasx.mp4

Edit: Sorry for being retarded, forgot the bitrate very high video is lagging will record a new one ASAP. 

Edit 2: The video isn't lagging while playing from local file, everything is fine.

**Comment by Adamantcheese** [comment]
This is probably the same issue that makes images not load and only the thumbnail to stick around.

**Comment by Adamantcheese** [comment]
Please double check that with the new streaming webms this still occurs.

**Comment by kurobaissues** [comment]
Yeah still occurs, here are some interesting facts: 

When sound on: https://files.catbox.moe/srz8tj.mp4
When sound off: https://files.catbox.moe/lei8lh.mp4
(Don't know if it actually matters but I see different behavior) 

So when there is a "play" sign ([image](https://files.catbox.moe/1pptvf.png)) there is no way it can recover itself it needs to swipe another WebM and back (sometimes the swiped WebM also stuck) 

The other case is when there is a "stop" sign ([image](https://files.catbox.moe/wkc1g8.png)) when its black but waiting a bit recovers it can it plays fine.

Not entirely sure but the last one has been added after the streaming update thumbnail stuck ([image](https://files.catbox.moe/ib62no.png)) this is also the same behavior like the "stop" sign. 

Since @ekisu is looking at these issues best to mention him here also. 

I really don't know this can be solved (I am not a developer) this bug is the most important one IMO because it directly affects usability of the app if its gonna be useful I can also try to grab logs for you. Is it possible to rewrite the image/WebM viewer part of the app or its too much of a headache?

**Comment by Pentaphon** [comment]
@kurobaissues high bitrate webms lagging might also be due to a phone that isn't fast or new enough to play them. You may want to tell the dev what phone you own.

**Comment by Adamantcheese** [comment]
Does this issue still occur? I changed the media source from a deprecated one in commit https://github.com/Adamantcheese/Kuroba/commit/373d809d4b4c9ffbcdbf41e4e488500fd28c0346, and I can't see this issue currently occuring.

**Comment by Pentaphon** [comment]
@Adamantcheese For me, the issue happens when going on a webm-heavy thread like on /wsg/ or /gif/. When you flick through webms and play them one by one in a speedy fashion, they start to get slow to the point where the progress meter is barely crawling across the screen. They take minutes to load, even over Wifi on a decent device like a Moto G4. Meanwhile, Clover 3.0.2 does not do this when I flick through the same thread, on the same device, right after experiencing the slowness on Kuroba.

**Comment by Adamantcheese** [comment]
I've added in a change that will cancel the last thing you swiped past, assuming it didn't already finish downloading. This should help. After the next release (4.4.3), please tell me if this issue still occurs.

**Comment by Pentaphon** [comment]
@Adamantcheese the same behavior I described persists in 4.4.3. You may want to get a closer look at what Clover 3.0.2 is doing because it never exhibits this behavior on the same device. Perhaps something new was added which stalls the loading of webms.

**Comment by Adamantcheese** [comment]
Closed with merge.
