### ISSUE TITLE
catalog open thread highlight stays when switching thread from bookmark

### ISSUE THREAD

**Issue by namazso** [Adamantcheese/Kuroba#566]
1. Open a thread from catalog
2. Open a thread from bookmarks
3. Swipe it away, getting back to catalog
4. Catalog still highlights first thread OP

only a minor cosmetic issue, but still one

**Comment by Adamantcheese** [comment]
This was a cosmetic change in a recent release, however if people don't like it I can remove the one line of code that makes it do da thing

**Comment by namazso** [comment]
I don't think you understood it.
The second thread (from bookmarks) will be opened (to the right) while catalog still highlights first thread. Is that intentional?
At least I'd expect the highlight to be of the currently opened thread, not the one that I last opened from that catalog.

**Comment by namazso** [comment]
https://streamable.com/ykutk

here's what I mean

**Comment by Adamantcheese** [comment]
Ah, yeah okay I get it. The thread highlight is only applied when you tap on a thread the catalog, not when loading from bookmarks. It may even be the case that your catalog isn't the same board as the bookmarked thread you've posted. The last thread you went to in your bookmarks will be highlighted in the drawer, while the last thread you went to in your catalog will be highlighted there. The two don't interact. Not sure what you want me to solve here given this explanation.

**Comment by namazso** [comment]
I just expected that it's meant to highlight currently opened thread. If this is how it's intended to work that's fine too.
