### ISSUE TITLE
[Feature] Grouping bookmarks

### ISSUE THREAD

**Issue by TacoTheDank** [Adamantcheese/Kuroba#567]
I think it'd be pretty nice to be able to have the option to group bookmarked threads by board (and/or also custom named groups).

I see there's a similar suggestion https://github.com/Adamantcheese/Kuroba/issues/178, I think this could be purely optional. Even if it makes bookmarks a pain to keep consistent, it'd only become a problem for the people who choose to enable this setting.

Anyway, I hope this is something you would consider adding. Thanks for all the work you do for this app!

**Comment by Adamantcheese** [comment]
I'm going to close this as a duplicate, because it is, and because I've explained my rationale there.
