### ISSUE TITLE
Automatic reporting of logs does not work on release builds

### ISSUE THREAD

**Issue by Adamantcheese** [Adamantcheese/Kuroba#568]
Gotta love Android and it's "uhh can't send cleartext without this permission" crap. It's not a runtime permission either. I really don't want to enable cleartext for release builds, BUT apparently WebViews don't honor the cleartext permission, so it might be possible to make a webview and send the logs there. Or your server might just need to be upgraded to HTTPS at this point @K1rakishou.

**Comment by namazso** [comment]
I think making the automatic reporting thing require user interaction would be better overall. Just showing a WebView with what gets sent and a big Send button would make the "hurr durr botnet telemetry" crowd much less justified while probably solving this issue too

**Comment by K1rakishou** [comment]
Yeah that was pretty retarded, on my part, to not think about what would happen in the release build. Well, I guess I will have to buy a domain and add https. On the other hand people using release may just relax since this shit doesn't work.

**Comment by K1rakishou** [comment]
>I think making the automatic reporting thing require user interaction would be better overall

Well yes, I guess it is. I will add a dialog. I just though that ability to disable it completely is enough. I even put it in the same place as in Clover so you don't have to look for it.

**Comment by K1rakishou** [comment]
Just saw this:

![image](https://user-images.githubusercontent.com/10332458/74042952-8e28f080-49d9-11ea-8883-a9f0ab9f3691.png)

So apparently it only doesn't work on Android 10.

**Comment by K1rakishou** [comment]
Alright I extracted this part of the task:

>I will add a dialog. 

into a separate issue - https://github.com/Adamantcheese/Kuroba/issues/600
So this one can be safely closed now.
