### ISSUE TITLE
[Feature Request] Optional Gesture-based WEBM interaction

### ISSUE THREAD

**Issue by Pentaphon** [Adamantcheese/Kuroba#570]
Perhaps a disabled by default but optional webm gesture system could be implemented where when enabled:

1. Removes the player controls entirely. 

1. Lets users tap the middle of the webm to pause, tap the left and right of the webm to fast forward or rewind the current webm. 

1. Swiping right or left would still always go to the previous or next webm.

1. Swiping down would close the webm viewer and let you resume posting

I made this its own issue from an earlier comment here: https://github.com/Adamantcheese/Kuroba/issues/557#issuecomment-582436128

**Comment by ghost** [comment]
Sounds great to me.

**Comment by Adamantcheese** [comment]
1 is now true, and depending on how many people use ff/fr I may avoid doing that. Swiping up to close is the usual gesture functionality, with down being save, so 4 is a moot point. This will remain open for the time being.

**Comment by Adamantcheese** [comment]
I'm going to close this as fast forward/rewind doesn't seem like a feature many people use. The rest of the points above still apply.
