### ISSUE TITLE
[BUG] Alert notification sometimes turns into a silent notification when you get a reply

### ISSUE THREAD

**Issue by K1rakishou** [Adamantcheese/Kuroba#571]
Dunno how to reproduce this. But I have a hunch why this may happen. Apparently, when there are a lot of pinned threads, we may call startService/stopService way too often and there may form a race condition where you start a service then stop it immediately then start again, etc. I think we need to add a debouncer so that start/stop is only called once in 500-1000ms. I believe this should help.

**Comment by Astridchan** [comment]
Not sure if this is related or not but I tried changing the "Watch notification" channel behaviour from "show silently" to "make sound" and after than if I got a (You) notification I would get a notification sound/vibration for the same notification over and over every few seconds.

**Comment by K1rakishou** [comment]
Well yes, because you changed the channel priority. There are two notification channels - one for regular notifications (without sound/vibration/etc) and one for (You)s (with sound/vibration/etc). You changed the regular channel to have the same properties as the (You) one that's why it vibrates on every post now. So change it back and it should help.

**Comment by Astridchan** [comment]
>that's why it vibrates on every post now

I have in Kuroba settings
> Notify about: Only posts quoting you
>Notification sound: Only posts quoting you

And I only had one (You) notification but it still kept vibrating every few seconds. Here's STR:
1. Have Kuroba notification settings as above
2. Set Watch notification behaviour to "make sound"
3. Have only one thread bookmarked (try pick an inactive one that won't get new replies)
4. Make a post yours and mock a reply
5. Now every time you open and close Kuroba it will play a notification sound/vibration for the same (You) notification, over and over

**Comment by K1rakishou** [comment]
Oh this might be something new. Alright, thanks.
