### ISSUE TITLE
Captcha still appears in the bottom-left corner on tablets

### ISSUE THREAD

**Issue by K1rakishou** [Adamantcheese/Kuroba#572]
![image](https://user-images.githubusercontent.com/10332458/73941498-72045100-48fe-11ea-8da2-77987d596132.png)

Maybe we could decide where to put it depending on the display dimensions?

**Comment by K1rakishou** [comment]
Maybe we could do something I did with the Android 10 gesture exclusion zones editor where you are able to select the zones manually by moving rectangles on the screen? I.e. you select a point on the screen where you want this shit to appear, we do some checks so that it won't go out of the screen and if it's all ok, then the captcha view will appear at that place. This setting will be pretty useless for phones (because no space) but it will be pretty useful for tablets.

**Comment by Adamantcheese** [comment]
As of https://github.com/Adamantcheese/Kuroba/commit/cfb4609b1dda90ae4bd279100e31a6fcb936e7d3, captcha location can be set to be top/bottom, but always on the left hand side. I don't expect people using tablets to be using anything but split mode or auto; in the case of split mode, captcha will be in the bottom left and bottom right corner, depending on which side it is being displayed on.

And it's remarkably difficult to convert screen coordinates to webview coordinates, and then set the CSS appropriately. Webview kinda just does what it wants. And you don't have any visibility to where the captcha will render either, unless you REALLY like digging through obfuscated Javascript code. I'm calling it good enough.
