### ISSUE TITLE
Watch post filter action not working

### ISSUE THREAD

**Issue by stradus64** [Adamantcheese/Kuroba#59]
If watch post means bookmark it doesn't work. For example agdg pattern with highlight action highlights /agdg/ on /vg/ but watch post action doesn't add it to bookmarks.

**Comment by Astridchan** [comment]
It does work, just make sure you have thread watcher and the "Enable filter watching" setting enabled. Keep in mind that watch filters don't work instantly like the highlight filters do, there's a small delay before it bookmarks the thread matching the filter (I think it's based on the background update interval).

Here, just copy these settings and it'll work:

![Screenshot_2019-06-09-19-28-35-437_com github adamantcheese chan](https://user-images.githubusercontent.com/40862101/59161646-1626c580-8aee-11e9-8f63-f630b0866ec8.png)

![Screenshot_2019-06-09-19-29-55-712_com github adamantcheese chan](https://user-images.githubusercontent.com/40862101/59161657-3eaebf80-8aee-11e9-920b-318b946928c7.png)
