### ISSUE TITLE
[BUG/DEV] Thread title takes full width and hides menu buttons

### ISSUE THREAD

**Issue by Astridchan** [Adamantcheese/Kuroba#597]
Bug in latest Dev, when you open a thread from catalog the thread title will take full width and hide the menu buttons. Sometimes it happens only for a few seconds, sometimes it stuck like that until you close and open the thread again.

![Screenshot_20200208-102643](https://user-images.githubusercontent.com/40862101/74081993-ebff1c00-4a5d-11ea-833f-d05264647192.jpg)

**Comment by K1rakishou** [comment]
Also this

![image](https://user-images.githubusercontent.com/10332458/74087509-f7723780-4a9d-11ea-830d-39e09d57fc8c.png)

**Comment by Astridchan** [comment]
Also this. STR:
1. Open a thread from catalog.
2. Swipe to go back from thread to catalog, 
3. Wait a few seconds and the toolbar of the thread you last opened will replace the catalog toolbar and be stuck there until you open another thread.

![Screenshot_20200209-103132_resize_31](https://user-images.githubusercontent.com/40862101/74099041-f38af780-4b27-11ea-9e4f-ca82cbbb038f.jpg)
