### ISSUE TITLE
[IMPROVEMENT] Make automatic crash reporting not as sneaky as it is right now

### ISSUE THREAD

**Issue by K1rakishou** [Adamantcheese/Kuroba#600]
What I'm thinking of doing is not just adding a dialog that will be thrown in your face every time you open the app after it crashed (this shit will make anyone angry and they will just disable it completely) but implementing a notification system, but not with android notifications, but rather how unread posts/yous notification works (the little circle with numbers on top of the three line menu). So, basically, if crash logs are enabled and you have unsent crash logs another circle will appear (with exclamation mark or something similar) notifying that there are new crash logs to be uploaded.

**Comment by Pentaphon** [comment]
Also known as the "remove the troll's ammunition to call your app a botnet" fix. This is probably for the best.
