### ISSUE TITLE
Add bottom padding to player controls to prevent conflict with gesture navigation

### ISSUE THREAD

**Issue by Astridchan** [Adamantcheese/Kuroba#602]
Many android phones have a gesture navigation system where a swipe up from the bottom edge of the display is used for different actions such as home / recents. In Kuroba, if you're using a small display size setting / DPI the player controls are close enough to the bottom edge of the display that taps on the seek bar can register as gestures instead. The pic below demonstrates the issue (exaggerated but you get the point). Moving the seek bar slightly higher, away from the bottom edge, would be sufficient to fix this issue.

![Screenshot_20200208-155534r](https://user-images.githubusercontent.com/40862101/74086710-2da7bb00-4a8e-11ea-90ca-6f66479a86fd.jpg)

EDIT: Another thing related to this issue, if you have a phone with very rounded display corners (retarded design, I know) then part of the seek bar gets cut off as seen here:

![IMG_20200208_163342](https://user-images.githubusercontent.com/40862101/74087074-bf64f780-4a91-11ea-90a5-8aeba980c658.jpg)

2. EDIT: How about having the seek above the playback controls? That's how a lot of Android media players have it.

![xx](https://user-images.githubusercontent.com/40862101/74091018-98bbb680-4abb-11ea-9542-75825cd0ad79.png)

**Comment by K1rakishou** [comment]
I wonder can we even edit this thing? Because it's being drawn by the library we use to play webms - Exoplayer.

**Comment by Astridchan** [comment]
Yeah, seems like it's possible:
https://exoplayer.dev/ui-components.html
