### ISSUE TITLE
[Feature Request] Open URLs with Kuroba

### ISSUE THREAD

**Issue by maluhia** [Adamantcheese/Kuroba#61]
In Firefox, I can select YouTube URLs and NewPipe is able to open directly to the link. It would be great if Kuroba could open the URL in the same fashion.
![Screenshot_20190607-230505_Firefox](https://user-images.githubusercontent.com/33070562/59161012-c9ad9c80-8a91-11e9-9f28-77dd896dd1ca.jpg)

**Comment by maluhia** [comment]
I see. It works with specific threads like: https://boards.4chan.org/pol/thread/143684145#p143684145
But not 4channel threads: https://boards.4channel.org/int/thread/106742452

**Comment by Adamantcheese** [comment]
Whoops, looks like that stuff was for NFC. Uh, still looking.
