### ISSUE TITLE
Unable to save images in archived threads when chunk count is greater than 1

### ISSUE THREAD

**Issue by Adamantcheese** [Adamantcheese/Kuroba#616]
I have no idea. I would've sent a report but I wasn't on dev so the cleartext thing prevented me from doing so. Both album and single downloads fail; I remember the topmost error being the one in FileCacheV2.kt at line 161.

**Comment by Adamantcheese** [comment]
Well, it doesn't happen on some archived threads. Maybe it was because it was an archived thread that was close to being pushed out of the internal site archive or something.

**Comment by K1rakishou** [comment]
Probably has something to do with 404 response code handling.

**Comment by Adamantcheese** [comment]
Can't reproduce this one anymore, likely was resolved through some other fixes.
