### ISSUE TITLE
[IMPROVEMENT] Add settings' state that may conflict with each other to the crash logs/reports

### ISSUE THREAD

**Issue by K1rakishou** [Adamantcheese/Kuroba#617]
Like, we have prefetching and thread downloading. They may conflict sometimes and cause bugs. So the idea is to add whether those settings were on or off at the time of the crash/report. The point of this issue is to come up with a lost of settings (I don't think we need ALL settings in the log) and to actually add them to the logs. So far candidates are:

- Prefetching.
- Thread downloading (maybe even amount of currently downloading threads).
- Hi-res thumbnail (depends on the prefetching).
- Image inlining.
- Maybe youtube titles parsing (since to filter out reports of people saying that everything is slow). 
- Concurrent file downloading (amount of chunks).
- Base directory provider (Java File API or SAF).
- WEBM streaming.
- ...

**Comment by Adamantcheese** [comment]
Inlining and youtube parsing are just parsing steps, they don't ever conflict with each other. The rest sound fine though.

**Comment by K1rakishou** [comment]
Well, inlining yes, but I think youtube parsing is great to filter out people who says "everything started lagging for no reason".
