### ISSUE TITLE
No longer able to focus thread on post from thread search

### ISSUE THREAD

**Issue by stradus64** [Adamantcheese/Kuroba#625]
Before last update you could search for post in thread, then double tap it to exit from search filter view to full thread view scrolled to that post. I found it useful and would like it back, removal seems unintentional

> post comments in the replies popup are now selectable. The double-tap goto functionality remains the same, and overrides the usual double-tap to select all functionality of the text.

this works but no longer for the results list from search in thread, goto function is gone

**Comment by Adamantcheese** [comment]
This is likely the exact line that made this change https://github.com/Adamantcheese/Kuroba/commit/343791e32d845b796cf39d26a02fea050018cecf#diff-11a73134694682aa22015a85af8a93a4R1061
Neat side effect that wasn't ever really intended, as the double-tap was meant for popups.
