### ISSUE TITLE
Is this supposed to work

### ISSUE THREAD

**Issue by floppyD** [Adamantcheese/Kuroba#627]
![Screenshot_20200211-043009_Kuroba](https://user-images.githubusercontent.com/29208110/74217871-6b236880-4c87-11ea-9488-2c9ab26ac84e.png)

**Comment by Adamantcheese** [comment]
See #599 and #568.

**Comment by Adamantcheese** [comment]
Also don't report a bunch of Info level (I/Kuroba rather than W/Kuroba for warnings or E/Kuroba for errors) stuff, it's worthless.
