### ISSUE TITLE
Crash report "java.lang.OutOfMemoryError: Failed to allocate a 24197532 byte allocation with 11899864 free bytes and 11MB until OOM"

### ISSUE THREAD

**Issue by K1rakishou** [Adamantcheese/Kuroba#636]
UUID: 7c89268adb94fd82e96bd877b3fe3a81
Build flavor: dev
Version name: v4.11.0-cf89929
OS info: Android 7.1.1, sdk version: 25
Report description: No title
Logs:
```
Called from unhandled exception handler.
java.lang.OutOfMemoryError: Failed to allocate a 24197532 byte allocation with 11899864 free bytes and 11MB until OOM
	at java.util.Arrays.copyOf(Arrays.java:3256)
	at java.io.ByteArrayOutputStream.toByteArray(ByteArrayOutputStream.java:178)
	at com.android.volley.toolbox.BasicNetwork.inputStreamToBytes(BasicNetwork.java:293)
	at com.android.volley.toolbox.BasicNetwork.performRequest(BasicNetwork.java:152)
	at com.android.volley.NetworkDispatcher.processRequest(NetworkDispatcher.java:132)
	at com.android.volley.NetworkDispatcher.processRequest(NetworkDispatcher.java:111)
	at com.android.volley.NetworkDispatcher.run(NetworkDispatcher.java:90)
```

**Comment by K1rakishou** [comment]
I don't think there is anything we can do. Maybe add additional logs?

**Comment by Adamantcheese** [comment]
Considering it all happened even before it hit the application, there really isn't anything we can do, especially considering this design decision: https://github.com/google/volley/wiki/Frequently-Asked-Questions#why-doesnt-volley-support-large-downloadsuploads

**Comment by K1rakishou** [comment]
Oh, so it's a Vollery problem. Well, then the only thing we can do is to get rid of Volley which is already planned.

**Comment by K1rakishou** [comment]
But I wonder what was even being downloaded via volley that weighs 25MB? We use it for thumbnails, apk updates and to retrieve site json I guess?

**Comment by Adamantcheese** [comment]
Maybe some site puts literally everything into their json and it's just massive.

**Comment by K1rakishou** [comment]
I remember only 8chan was doing that shit.

**Comment by Adamantcheese** [comment]
Dvach has some weird stuff going on, so maybe that was it. Anyways, doesn't matter, can't really do anything against this OOM. How are people getting so close to OOM anyways on these not super terrible systems anyways

**Comment by K1rakishou** [comment]
Probably Firefox with 1000+ unread tabs is running in the background.

**Comment by K1rakishou** [comment]
Here is another similar one:

```
E/Kuroba-dev | UNCAUGHT: java.lang.OutOfMemoryError: Failed to allocate a 152538328 byte allocation with 50331648 free bytes and 101MB until OOM, max allowed footprint 211855968, growth limit 268435456
E/Kuroba-dev | UNCAUGHT: 	at java.util.Arrays.copyOf(Arrays.java:3164)
E/Kuroba-dev | UNCAUGHT: 	at java.io.ByteArrayOutputStream.toByteArray(ByteArrayOutputStream.java:191)
E/Kuroba-dev | UNCAUGHT: 	at com.android.volley.toolbox.BasicNetwork.inputStreamToBytes(BasicNetwork.java:293)
E/Kuroba-dev | UNCAUGHT: 	at com.android.volley.toolbox.BasicNetwork.performRequest(BasicNetwork.java:152)
E/Kuroba-dev | UNCAUGHT: 	at com.android.volley.NetworkDispatcher.processRequest(NetworkDispatcher.java:132)
E/Kuroba-dev | UNCAUGHT: 	at com.android.volley.NetworkDispatcher.processRequest(NetworkDispatcher.java:111)
E/Kuroba-dev | UNCAUGHT: 	at com.android.volley.NetworkDispatcher.run(NetworkDispatcher.java:90)
```

**Comment by K1rakishou** [comment]
They all come from the Volley callbacks.
