### ISSUE TITLE
Feature request: disable (undo) sending post on captcha screen

### ISSUE THREAD

**Issue by namazso** [Adamantcheese/Kuroba#643]
I often write a post, continue to captcha then realize halfway through that I messed up something in my post. Then I have to go back, change my post, then start the captcha again.

Would it be possible to add a button (or toggle?) to the captcha screen that "converts" the current posting action into only a captcha filling / queuing action and lets you continue filling the captcha?

**Comment by Adamantcheese** [comment]
I would recommend you proofread what you post. Entering a captcha takes a minimal amount of time with captcha cookies. Also see https://github.com/Adamantcheese/Kuroba/issues/275#issuecomment-518442815.
