### ISSUE TITLE
DEV build APKs download as ZIP archives

### ISSUE THREAD

**Issue by Astridchan** [Adamantcheese/Kuroba#672]
When you download a Dev APK through the website they get downloaded as zip archives on Chrome. As a result you can't install the app, trying to open the APK through Chrome gives "can't open file",  tapping on the APK in the default Android file manager (Google Files) just opens its contents. Renaming the file doesn't help.

![Screenshot_20200218-091056](https://user-images.githubusercontent.com/40862101/74713116-86b2e400-5230-11ea-80ca-6a34dc93c42c.jpg)

Possible fix?:
https://stackoverflow.com/questions/7296829/how-to-download-apk-as-apk-not-as-zip

**Comment by Adamantcheese** [comment]
This MIME type is already set in UpdateManager, `intent.setDataAndType(apkURI, "application/vnd.android.package-archive");`. This is likely a security feature of Chrome/Google Files.

**Comment by Astridchan** [comment]
> This MIME type is already set in UpdateManager, `intent.setDataAndType(apkURI, "application/vnd.android.package-archive");`.

Sorry, should have been clearer, the issue is with the https://kuroba.io:8443/ website, APKs downloaded through the in-app updater install just fine, even with Files.

**Comment by Adamantcheese** [comment]
Then this is out of scope for the application. You'll likely run into the same issue downloading other APKs with Chrome.

**Comment by Astridchan** [comment]
It's the only website I've had this issue with, I can still download APKs off other websites just fine. I dunno if the MIME TYPE is set on the website but if it isn't then that's probably what's causing it.

**Comment by Adamantcheese** [comment]
It seems to be a Chrome on Android issue. A quick google search gave me this from about a month ago: https://forums.ivanti.com/s/article/renaming-zip-to-apk

**Comment by Astridchan** [comment]
@K1rakishou any comment on this issue? (since the website is hosted by you)

**Comment by K1rakishou** [comment]
Well I don't remember setting a mime type for apk downloads so probably that's the issue. I will try adding the correct mime type.

**Comment by Astridchan** [comment]
Dev APKs correctly download as APKs now so as far as I'm concerned this is fixed. Thanks!

**Comment by K1rakishou** [comment]
Yeah, I added the correct ContentType on the server so it should work now.
