### ISSUE TITLE
[REGRESSION] Swipe-to-save is getting called instead of swipe-to-close when viewing a zoomed in image

### ISSUE THREAD

**Issue by K1rakishou** [Adamantcheese/Kuroba#673]

**Comment by Adamantcheese** [comment]
Everything seems to be working fine? Give me some steps to reproduce because every scenario seems to be functional.

**Comment by K1rakishou** [comment]
- Open any image.
- Zoom in a little bit.
- Swipe down (so the viewport moves up).
- Previous logic would close the image but right now it saves it instead.

Image should only be saved if we are no zoomed in, otherwise both gestures should close the image. That's how it was before.

**Comment by Adamantcheese** [comment]
Bitwise logic is hard yo
