### ISSUE TITLE
[BUG] Snackbar appears higher than it should be sometimes

### ISSUE THREAD

**Issue by K1rakishou** [Adamantcheese/Kuroba#674]
STR:
- Bookmark an active thread (or even better couple of them).
- Kill the app (I think just swiping it away is enough, but maybe you will have to force stop it).
- Wait until one of the receives new posts.
- Open the thread with replies.
- The snackbar will appear in a wrong position.

I think it's because of the recent snackbar library update.

![34234234](https://user-images.githubusercontent.com/10332458/74762801-9f9eb200-528f-11ea-9e15-71622e1c5143.png)

**Comment by Adamantcheese** [comment]
I can't duplicate this behavior. Judging by your image, it's trying to place the snackbar above the FAB, which according to material design is "correct". In my testing on emulator, the snackbar has always pushed up the FAB and stayed stuck to the bottom of the screen.

I've added a test option in the thread menu to display an indefinite snackbar, for easier testing.

**Comment by Adamantcheese** [comment]
I should note that I tested with and without the "always show toolbar" setting. Both had the same behavior of the snackbar appearing at the bottom of the screen, below the FAB.

**Comment by K1rakishou** [comment]
Alright, so this thing is not reproducible on the emulator. Apparently it's device-specific and it is an Android or androidx library bug. So far there were no complains about this thing so I guess I'm the only lucky one who got it. I guess it can just postpone it until the next release or something.

**Comment by Adamantcheese** [comment]
This is probably the related bit that I found in the changelogs https://github.com/material-components/material-components-android/commit/904d063bb483da7fd8ab84c46bdc5969363efc69

**Comment by Adamantcheese** [comment]
Some more testing shows me that if I scroll up while a snackbar is showing, it'll hide itself super far down, but otherwise nothing out of the ordinary. It's an issue with HidingFloatingActionButton, but I don't see any changes mucking around with the translationY stuff.

**Comment by K1rakishou** [comment]
>material-components/material-components-android@904d063

This actually looks like something that might cause this issue. But I wonder why it doesn't reproduce on every device including emulators.
