### ISSUE TITLE
[Feature Request] Flag support on 8kun

### ISSUE THREAD

**Issue by jeremybullen** [Adamantcheese/Kuroba#675]
8kun has board specific custom flags and location flags. It would be nice if kuroba could display the flags on posts and provide a way to select your flag when posting.

[A flag URL](http://media.8kun.top/static/custom-flags/christian/1580915581272.png).

**Comment by Adamantcheese** [comment]
I'll accept a PR for this one but otherwise will not work on it.

**Comment by Adamantcheese** [comment]
8kun does not provide flags anywhere in their API, only in HTML. Closing because the site doesn't provide the relevant info in any appropriate way.
