### ISSUE TITLE
[Bug] Posting refreshes the entire thread

### ISSUE THREAD

**Issue by Yoirkie** [Adamantcheese/Kuroba#676]
Using v4.11.0.

Lets say im at the bottom of the thread, if i make a post, it refreshes and send me back to the top.

**Comment by Adamantcheese** [comment]
#347 and #229 are related issues.

**Comment by Adamantcheese** [comment]
While I'm fairly certain that this should mitigate the majority of the issue, if it continues to persist then turning off shift-post-format should prevent that issue from happening. As noted in the conversation in #229, there doesn't seem to be any reason why the layout manager chooses to refresh everything.
