### ISSUE TITLE
Posts by yourself shouldn't announce as "1 new post [View]"

### ISSUE THREAD

**Issue by Pentaphon** [Adamantcheese/Kuroba#697]
This is still happening as of Koruba 4.11.1

Just a small tweak that I think should be made. We already get a popup when a post is successful. It is redundant to have this happen along with a "1 new post [View]" bottom notification. 

Please leave the "1 new post [View]" bottom notifications solely to posts made by other users and only display the "Post Successful" when making your own posts.

**Comment by Adamantcheese** [comment]
This behavior has not been modified since Clover. The previous adjustment was to the watch notification, not to the snackbar. This will not change.
