### ISSUE TITLE
kohlchan.net support

### ISSUE THREAD

**Issue by StephenLynx** [Adamantcheese/Kuroba#7]
Documentation of their software can be found here:
https://gitgud.io/LynxChan/LynxChan/tree/2.2.x/doc

**Comment by Adamantcheese** [comment]
Are there any other sites that use LynxChan as a backend, other than LynxChan itself?

**Comment by StephenLynx** [comment]
I keep a list here
http://lynxhub.com/lynxchan/res/285.html
But I don't keep much track of sites that shutdown, so don't be surprised if you find a bunch of dead links.

**Comment by Adamantcheese** [comment]
Alright, good to know it's not just for a single *chan. It's a low priority for me though, if someone else wants to take a crack at it go ahead (but you'll have to write a custom set of parsers kinda like how it is for ViChan).

**Comment by yilmzfurkan** [comment]
Here was some work done. https://github.com/Floens/Clover/pull/664 Maybe @krautbernd can have a look again.

**Comment by StephenLynx** [comment]
@yilmzfurkan that was from before they changed their software.
@Adamantcheese you can see the version lynxchan sites use on /index.json so you can do different things when needed according to the specs of that version. Specs are locked per minor version and maintained for a year after release.

**Comment by krautbernd** [comment]
> 
> 
> Here was some work done. [Floens#664](https://github.com/Floens/Clover/pull/664) Maybe @krautbernd can have a look again.

yea that was just a converted vichan-package for kc. still have my head in the code, but without documentation i still have my problems with understanding what and where to do. 8)

**Comment by Adamantcheese** [comment]
Per comments on #362, this is closed.
