### ISSUE TITLE
Search box covers up search result when reply box is active

### ISSUE THREAD

**Issue by Astridchan** [Adamantcheese/Kuroba#707]
Issue related to #334 : Often when I'm writing a reply I'll want to quote a certain post or copy text from it. If it's a thread with a lot of posts I'll use the search to find the post rather than try to find it by scrolling through the thread. The issue is that if you have the reply box and search box open simultaneously the search box will cover the first search result and prevent quoting the post since the post text and menu button are covered:

![Screenshot_20200223-150158 (1)](https://user-images.githubusercontent.com/40862101/75112614-1a7c1a00-564e-11ea-8bce-d12058332292.jpg)

Another issue is with the back button behaviour. You would think an easy solution to the above issue would be to just close the reply box and then quote the post, but if you have the keyboard, search box and reply box all open then the back button closes them in the following order:
1. back button press closes keyboard
2. closes search
3. closes reply box

so trying to close the reply box ends up clearing the search instead. The following order would make sense since the reply box can be toggled without losing the content:
1. back button press closes keyboard
2. closes reply box
3. closes search

**Comment by Adamantcheese** [comment]
I can't replicate the "found x posts" box appearing over any posts. Because of how the UI is structured, I can't change the back press behavior; the toolbar always gets priority.

**Comment by Astridchan** [comment]
>I can't replicate the "found x posts" box appearing over any posts.

It happens on my Android 9.0 phone and Android 7.0 tablet. I can also reproduce it using a virtual device in Android Studio. Just to be clear, you need to have the reply box and and search box both visible for this issue to happen.

![Uuntitled](https://user-images.githubusercontent.com/40862101/75139509-7d74bc00-56f5-11ea-86dc-e0b3a7598014.png)
