### ISSUE TITLE
[BUG] Wrong image is being used for exit transition when viewing images

### ISSUE THREAD

**Issue by K1rakishou** [Adamantcheese/Kuroba#709]
STR:
- Start downloading a thread.
- Wait until all images are downloaded (it's better to choose a thread with few images).
- Open an image.
- Swipe forward couple of image.
- Press back/swipe-to-close.

The first clicked image will flash for an instant before being replaced with the one that should be actually used for exit transition. 

Apparently it happens after calling `callback.setPreviewVisibility(true);` which means `previewImage` has the wrong image, so it flickers for an instant before getting replaced with an image that we open in `startPreviewOutTransition`. When viewing images in regular threads everything works as expected.

**Comment by Adamantcheese** [comment]
This is just a regular old bug, as it happens in live threads as well.
