### ISSUE TITLE
[Feature Request] Filter options to never target capcode posts or stickied posts

### ISSUE THREAD

**Issue by ownBard** [Adamantcheese/Kuroba#71]
Options to add exceptions to filters, especially options for:
- don't target stickied posts
- don't target capcode posts (admins, mods, developers etc.)

**Comment by ownBard** [comment]
You could generalize to just having an "AND NOT" system to add exceptions to certain filters. Whatever you prefer.

**Comment by Adamantcheese** [comment]
Rather than be an option, this should be always on by default. Stickies and capcode posts are few and far between and should never be filtered for the information provided with them.

**Comment by ownBard** [comment]
That makes sense unless someone wants highlight/watch filters to work on stickied/capcode posts — but I assume you just mean hide/remove filters. Cheers!
