### ISSUE TITLE
[Suggestion] Add sort button to catalog toolbar

### ISSUE THREAD

**Issue by Astridchan** [Adamantcheese/Kuroba#711]
With the recent change to the catalog toolbar there is a lot of empty space in the toolbar, especially if the display is set to a low DPI:

![Screenshot_20200223-171054x](https://user-images.githubusercontent.com/40862101/75115042-f7f4fb80-5663-11ea-9719-868e285858e0.jpg)

With all this space available, it would be nice to have the catalog sort option moved from the menu to a toolbar button (out of all the menu options I think it's the most useful one to have in the toolbar):

![Screenshot_20200223-171054e](https://user-images.githubusercontent.com/40862101/75115065-2246b900-5664-11ea-91b4-02e1cd6f005c.jpg)

**Comment by Adamantcheese** [comment]
I don't think having it as a toolbar option is a good idea unless you use that option a lot, which I don't think anyone really does? I'll accept a PR for this as a setting but otherwise won't implement it.

**Comment by Congrav1ty** [comment]
Agreed, I've wished this for a long time, and actually I'd even go as far as making it some kind of customizable toggle switch if I could (maybe enable/disable certain sort options with checkboxes, and then use the button to cycle between them). That's only personally though I realize that'd be overkill for the average user. I mainly only use reply count, thread activity, and bump order, as it really helps depending on if for example I want the latest most active threads on /pol/ (even if they only have 20 replies, but all in the last minute), or just the densest most-discussed threads at the expense of them being older.

**Comment by Adamantcheese** [comment]
Closed with https://github.com/Adamantcheese/Kuroba/commit/6ce8440ae613932c0f14491a65ec0e5d78f74e0b.
