### ISSUE TITLE
Firefox Google Image Search

### ISSUE THREAD

**Issue by K1rakishou** [Adamantcheese/Kuroba#718]
UUID: a707bca98c13750f2f62bf6e7d109176
Build flavor: stable
Version name: v4.11.1
OS info: Android 10, sdk version: 29
Report description: Using Firefox fenix (preview/preview nightly) to reverse image search something through Google only loads the Google homepage. All other reverse image search engines work fine.

**Comment by Adamantcheese** [comment]
Shoutouts to Google for being the open web player that it is. https://bugzilla.mozilla.org/show_bug.cgi?id=1200652
