### ISSUE TITLE
Add support for 8kun custom captcha

### ISSUE THREAD

**Issue by K1rakishou** [Adamantcheese/Kuroba#721]
UUID: 0acddd18250f184b05b5fefbd0bce8e0
Build flavor: stable
Version name: v4.11.1
OS info: Android 9, sdk version: 28
Report description: When I try to post there, it gives a 403 error. When using 8kun in my browser it posts normally so it's not an IP issue. That's all I can really say. I won't attach logs because they don't have any info, like at all.

**Comment by Astridchan** [comment]
Posting works, the issue seems to be the loading the Captcha. If you open 8kun in the browser and fill the Captcha it then lets you post from the app.

**Comment by K1rakishou** [comment]
@Astridchan what captcha do they use? I guess it's not google's captcha.

**Comment by Astridchan** [comment]
Yeah, not Google Captcha, this is how it looks like:

![Annotation 2020-02-24 124015](https://user-images.githubusercontent.com/40862101/75146054-e9a9ec80-5702-11ea-906a-e1138af18583.jpg)

**Comment by K1rakishou** [comment]
Oh well we don't support it.

**Comment by Adamantcheese** [comment]
At a minimum the authentication URL was incorrect, but I still have no idea if it works and it's gonna be SUPER annoying to test because it's a one time thing kinda. Guess other people are gonna have to see if that worked.

**Comment by Astridchan** [comment]
The captcha loads in app now but nothing happens when pressing on "Let me post!".

**Comment by Adamantcheese** [comment]
Yeah 8kun's captcha is weird. It's going to need a custom implementation.

**Comment by jeremybullen** [comment]
8kun has a [dedicated url](https://sys.8kun.top/dnsbls_bypass.php)  for captchas. The site gives you this link if you try and post without javascript.

If kuroba could just open this link when the poster needs to fill out a captcha that would be a great convenience. That's how it worked for 8ch if I remember correctly.

**Comment by Adamantcheese** [comment]
Thanks for the info! Replacing the URL worked just fine.
