### ISSUE TITLE
[BUG/REGRESSION] Cross-thread and cross-board links no longer take you to the linked post

### ISSUE THREAD

**Issue by Astridchan** [Adamantcheese/Kuroba#725]
Tapping on a cross-thread or cross-board link in the app no longer scrolls you to the linked post like it used to. When you tap on cross-thread/board link it opens the correct thread and highlights the correct post, but the scroll position stays at the top of the thread (or if you had opened the thread before the scroll position stays where you left it).

#279 still seems broken too, if I click on 4chan post links outside the app (in a browser for example), it sometimes goes to the correct post but often it just open the thread to the first post, haven't figured any logic out why it sometimes works and sometimes doesn't.

**Comment by Adamantcheese** [comment]
For #279, K1rak has run into a similar issue so I've provided a similar solution that should help.
