### ISSUE TITLE
[Feature Request] Rename the "Save" button

### ISSUE THREAD

**Issue by floppyD** [Adamantcheese/Kuroba#73]
It doesn't really save anything, just make the post yours. Call it something like "(You)", "Make post yours" or something like that.

**Comment by Astridchan** [comment]
You could just have "You" and a toggleable checkbox next to it in the menu, like in 4chan X.

[ ] You
[X] You

Would also take care of #36 and #72

**Comment by ownBard** [comment]
Seems like something he doesn't want to change, but "Claim" would be a more accurate term than "Save."

**Comment by Adamantcheese** [comment]
With a change to the display code, the length of the text doesn't matter as much any more for the popup. For clarity I'll use "Mark as my post" or "Unmark as my post", but suggestions are appreciated.
