### ISSUE TITLE
[Feature Request] Use proper Unix timestamp

### ISSUE THREAD

**Issue by floppyD** [Adamantcheese/Kuroba#74]
The Unix timestamp used as filename when "Remove filename" is used is "wrong". 4chan servers also include milliseconds. So instead of 1560172235 it would be 1560172235940.

**Comment by namazso** [comment]
The title is confusing, what you described isn't a Unix timestamp.
Anyways, maybe a setting entry for file name removal behavior would be nice. Defaulting to something like `{unix}{miliseconds}.{ext}` and allowing change to `.{ext}` for example

**Comment by floppyD** [comment]
You are right, Unix timestamps are generally in seconds. But all he needs to do is not divide by 1000 as he's probably doing. Didn't make a PR because I'm lazy.

**Comment by Adamantcheese** [comment]
Is this an issue that happens strictly because of reencoding? Because that's what your PR seems to allude to and I'm not gonna merge it until I know for sure that it's only an issue with that.

**Comment by floppyD** [comment]
It seems to be more than that, yes. Better take a look yourself.

**Comment by Adamantcheese** [comment]
Will do.

**Comment by Adamantcheese** [comment]
Understand that images generated by the reencoder are temporary and their filenames do not matter in the grand scheme of things.

**Comment by floppyD** [comment]
Just to be 100% sure, this makes filenames generated when tapping on this look like what I described, right? I thought you needed to change something else.
![Screenshot_20190611-235547](https://user-images.githubusercontent.com/29208110/59320399-9727bd80-8ca4-11e9-9f36-cbd1e3c17bf2.png)

**Comment by Adamantcheese** [comment]
Correct, when the remove filename image is checked, the current millisecond timestamp will be used as the image name.

**Comment by floppyD** [comment]
Excellent.
