### ISSUE TITLE
Report: replicateable freeze/lock when opening images and thread/post links at the same time.

### ISSUE THREAD

**Issue by K1rakishou** [Adamantcheese/Kuroba#744]
UUID: 2489d7103622831c49420470e7b76691
Build flavor: stable
Version name: v4.11.1
OS info: Android 9, sdk version: 28
Report description: when you tap on the thumbnail and a link to another post (>>postnum) at the same time, both load up and after closing the post the image becomes uncloseable, forcing a restart of the app.
Logs:
No logs attached

**Comment by Adamantcheese** [comment]
Alternative method of replication: tap an image and then tap the back button immediately afterwards.
