### ISSUE TITLE
[Question] Force thread refresh

### ISSUE THREAD

**Issue by ownBard** [Adamantcheese/Kuroba#75]
Is there any way to force a thread to refresh without having to wait for the JSON to be updated? (As can be done in browser by refreshing the page)

**Comment by K1rakishou** [comment]
You can't. That's how 4chan API works nowadays. Desktop does not use the API that's why it updates instantly.

**Comment by Adamantcheese** [comment]
K1rak is correct, you can't force the API to update faster than it does.
