### ISSUE TITLE
Issues with multiple filters acting on the same post

### ISSUE THREAD

**Issue by ownBard** [Adamantcheese/Kuroba#76]
- Post hidden by one filter is not removed by another filter
- Post hidden/removed by one filter cannot have it's replies hidden/removed by another filter
Results are inconsistent and also seem to depend on filter order as well as the order in which they are enabled/disabled. If any of this is intentional I couldn't figure it out.

**Comment by Adamantcheese** [comment]
Filter priority is from top to bottom on the filters list. I would recommend putting removes at the top, followed by hides, then highlights. Watches are used by a separate manager that does it's own thread requesting and only looks at the OP for those filters. If there's something more specific that you need fixed, please say so.

**Comment by ownBard** [comment]
It's still depends on the order they're disabled/enabled, for example:
- Filter 1 removes all posts containing A or B
- Filter 2 hides all posts containing A
- Filter 1 is above Filter 2
- If Filter 2 is enabled before Filter 1 then posts containing A are hidden and posts containing B are removed.

I can't tell if this is only until you load a different thread or not, but it is unaffected by refreshing the thread. If it's intentional for posts to only be affected by one filter then the filters at least shouldn't be applied in the wrong order.
