### ISSUE TITLE
[REPORT] Passcode 2ch.pm

### ISSUE THREAD

**Issue by K1rakishou** [Adamantcheese/Kuroba#760]
UUID: 89027840dc8744d4795a4e1149f0f001
Build flavor: stable
Version name: v4.11.2
OS info: Android 10, sdk version: 29
Report description: Where is my fucking passcode for 2ch.hk, faggot? U need to add passcode support in ur shitty app if u want people to use it on 2ch.hk

**Comment by Adamantcheese** [comment]
Don't give me things that aren't reports. If people want to request features and be shitty about it, they can do that here directly.

**Comment by K1rakishou** [comment]
Well, I mean, in-app reporter was supposed to be a replacement for github, because some people can't or just don't want to register here.
