### ISSUE TITLE
[Suggestion] Exclude threads that aren't being watched from the total unread posts count

### ISSUE THREAD

**Issue by Astridchan** [Adamantcheese/Kuroba#765]
In the following situation there's two watched threads with 12 unread posts in total, the rest of the threads are active but not being watched:

![Screenshot_20200228-153920](https://user-images.githubusercontent.com/40862101/75553688-8e009b80-5a41-11ea-8f64-5121a052c48f.jpg)

the count in the toolbar shows total of unread posts in all bookmarked threads when most people would only care about the unread posts in the threads they're watching:

![Screenshot_20200228-154150](https://user-images.githubusercontent.com/40862101/75553788-c1432a80-5a41-11ea-9a7a-a7673dd48e97.jpg)

**Comment by K1rakishou** [comment]
What if you have a reply in an archived thread? Should it be counted or not?

**Comment by Astridchan** [comment]
That's a good point, I would think that if a watched thread with unread posts gets archived you'd probably still want to count those posts in the total, but does the app keep track of whether a bookmark was being watched or not _after_ it gets archived?

**Comment by K1rakishou** [comment]
>but does the app keep track of whether a bookmark was being watched or not after it gets archived?

Uhhh, what do you mean? If a thread is archived we just set a flag to a pin associated with that thread that it's archived and depending on that flag do some additional stuff.

**Comment by Astridchan** [comment]
Once a watched thread is archived, does it stop being watched?

**Comment by K1rakishou** [comment]
Yes. Once we detect that it is archived we do not send any more requests to get new posts. We do it only once when you open an archived thread.

**Comment by Astridchan** [comment]
Ok, so my suggestion is to have the unread post count in the toolbar only include watched threads, and exclude threads that aren't being watched. But if a watched thread got archived, you'd still want to include the unread posts that thread got before it got archived in the count.
