### ISSUE TITLE
[Feature Request] Add separate catalog mode column count setting for portrait and landscape orientation + adjustable "Auto" mode

### ISSUE THREAD

**Issue by Astridchan** [Adamantcheese/Kuroba#77]
Currently, the catalog mode column count setting applies the same number of columns to both landscape and portrait orientation, which doesn't really make sense since the display area is wider in landscape and will fit more columns. A column number that looks good in portrait doesn't necessarily look good when it is also applied to landscape orientation.

In Auto mode, more columns are displayed in landscape than in portrait, but in "Auto" you cannot adjust  how many columns you get. (for example, on my phone "Auto" makes 4 columns in portrait and 7 in landscape, but if I wanted 3 in portrait and 6 in landscape, or 5 and 8, it isn't possible.) 

My suggestion is to have a separate catalog column count setting for landscape and portrait orientation when the column count is set manually, and optionally to also have the ability to adjust how the "Auto" setting works. With these features applied, the settings could look something like this:

Catalog column count: 
* Auto 
* Custom

// if "Auto" selected show the following option
Catalog thumbnail size:
* Default [same as the current "Auto" option]
* Big [fewer columns and bigger thumbnails than with the default option]
* Small [more columns and smaller thumbnails]

// if "Custom" selected show the following options:
* Columns in portrait: Y
* Columns in landscape: X

**Comment by Adamantcheese** [comment]
I've opted just to stick with a column adjustment for the time being and no customization of the thumbnail size as that is set in XML. You can access the appropriate setting if your phone/tablet is rotated to be portrait/landscape for portrait/landscape settings.

**Comment by Astridchan** [comment]
Yeah, I think it's fine as it is now, since the column count also adjusts the thumbnail size there isn't really a need for a separate setting just for that.
