### ISSUE TITLE
[Regression] Post info isn't tappable for scrolling to post anymore

### ISSUE THREAD

**Issue by Astridchan** [Adamantcheese/Kuroba#776]
The post info area (with the post number, post date, file name etc.) in the post window used to be tappable to scroll to that post. Since the "touch area" for post number links and the "X replies" button covers the whole width of the post window, it can be very hard to perform the scroll to post action on certain posts now. The screenshots below demonstrate the issue, the touch area for post links and the reply button is in red, the area that's tappable for scroll to post in green. In blue is the area that used to be tappable but now isn't.

![Screenshot_20200229-185125](https://user-images.githubusercontent.com/40862101/75612000-3557fe00-5b28-11ea-8812-5a154165bd9f.jpg)

![Screenshot_20200229-190829](https://user-images.githubusercontent.com/40862101/75611999-338e3a80-5b28-11ea-81cf-cd8eb6c93cf0.jpg)

**Comment by K1rakishou** [comment]
Maybe we could leave some free space at the right side (in replies) so you can always click it to scroll to a post?
