### ISSUE TITLE
Feature request: Allow bookmarks to be slid into view

### ISSUE THREAD

**Issue by ghost** [Adamantcheese/Kuroba#784]
When viewing catalog, allow the bookmarks side panel to be slid into view when swiping from left to right on any part of the screen.

Currently bookmarks can be slid into view by swiping from the edge of the screen, but this can interfere with gesture navigation in Android 10.

**Comment by K1rakishou** [comment]
>but this can interfere with gesture navigation in Android 10.

This problem should actually go away when this PR https://github.com/Adamantcheese/Kuroba/pull/544 is merged
