### ISSUE TITLE
Add "File Deleted" for deleted images or load them from archive

### ISSUE THREAD

**Issue by ayy91** [Adamantcheese/Kuroba#79]
Currently, if an image is deleted kuroba will show empty space unlike the website which displays an image saying "file deleted". Please make it similar to the desktop/mobile website or better yet load the deleted image from archive and display a small icon notification near the image to indicate that it's being loaded from an archive.

Kuroba:
![20190610_162838](https://user-images.githubusercontent.com/51542078/59199306-504fa000-8b9e-11e9-8210-3bf885fdb8d4.jpg)
![20190610_162817](https://user-images.githubusercontent.com/51542078/59199304-4fb70980-8b9e-11e9-8b12-25e6107490e1.jpg)

Website:
![20190610_162954](https://user-images.githubusercontent.com/51542078/59199353-68bfba80-8b9e-11e9-8525-b7097bdca48a.jpg)
![20190610_162918](https://user-images.githubusercontent.com/51542078/59199352-68bfba80-8b9e-11e9-9eea-293f9cec070b.jpg)

**Comment by Adamantcheese** [comment]
This is a subset of #26, and as that feature will implement this one and much better, I'm closing this request.
