### ISSUE TITLE
[REGRESSION/DEV] Jump to last seen post sometimes brings you to the top of a thread

### ISSUE THREAD

**Issue by K1rakishou** [Adamantcheese/Kuroba#796]

**Comment by Adamantcheese** [comment]
This is that whole shift-post-format scrolling to top bug. Again, I don't know how to fix it.

**Comment by Astridchan** [comment]
I don't think this is related to that bug, but to how the app updates your read progression in a thread, which only seems to be updated each time you scroll to the bottom of the thread. This can be tested fairly easily:
1. Open two active threads.
2. In the first thread, scroll some way down but not to the bottom. In the second, scroll to the bottom and then back up.
3. In the first thread, clicking on "view new posts" will always take you to the top of the thread as long as you haven't scrolled to the bottom.
4. In the second thread, clicking on "view" will scroll you to what was previously the last reply, with the new posts below a red line. If you don't scroll to the bottom again, clicking to view new posts will always take you to this position.
