### ISSUE TITLE
[Feature Request] Open thread from notification

### ISSUE THREAD

**Issue by ownBard** [Adamantcheese/Kuroba#80]
Opening the app from a notification should direct you to the relevant post/thread. (e.g. (You) notifications, page 10 notifications and any other thread watcher notifications)

**Comment by Adamantcheese** [comment]
Page 10 notifications will take you to their respective thread. Watch notifications will take you to the thread iff there is only one thread with unviewed quotes.

**Comment by ownBard** [comment]
Oh sorry, then it's just doesn't work for me.
