### ISSUE TITLE
[Feature Request] Add thumbnail size / column count setting for image gallery

### ISSUE THREAD

**Issue by Astridchan** [Adamantcheese/Kuroba#81]
Add an option to change thumbnail size / column count in image gallery (a column count setting would be enough since it also changes thumbnail size). Also, if any of the features proposed for catalog mode in #77 get added, it would make sense to provide similar options for the image gallery for consistency.

**Comment by Toblerone1** [comment]
Would really appreciate this since last update changed gallery to 4 wide and now images are tiny. Basically turns gallery into useless for me
