### ISSUE TITLE
Option to reduce thumbnail/image file sizes

### ISSUE THREAD

**Issue by azumukupoe** [Adamantcheese/Kuroba#813]

**Comment by Adamantcheese** [comment]
This isn't enough information to know what you want.

**Comment by azumukupoe** [comment]
Like a data saving mode? The app uses too much data on my phone.

**Comment by Adamantcheese** [comment]
I can't change the size of the files that are downloaded from a server, I can only change the size of the displayed image. The amount of data usage would be exactly the same; if you're worried about data usage, text-only mode might be up your alley?

**Comment by azumukupoe** [comment]
Text only mode would be the ideal data saver if it had "tap to load" function

**Comment by K1rakishou** [comment]
>The app uses too much data on my phone.

Do you have media prefetching/hi-res cells turned on or maybe you are downloading threads?

**Comment by Pentaphon** [comment]
> Text only mode would be the ideal data saver if it had "tap to load" function

This is clearly what he wants so this should be the actual feature request/title.

**Comment by K1rakishou** [comment]
Please let's no do this one before https://github.com/Adamantcheese/Kuroba/pull/810 is merged. I've changed some stuff related to Post/PostCell/etc so  changing them will cause a ton of merge conflicts for me.

**Comment by Pentaphon** [comment]
> Please let's no do this one 

I don't think it will ever get done.  Only the OP seems to want it.
