### ISSUE TITLE
Crash when opening a picture when system language is in Arabic

### ISSUE THREAD

**Issue by moun3m** [Adamantcheese/Kuroba#816]
Failed to show image, reason:
Unknown exception, class=IllegalArgumentException, message=Unexpected char 0x660 at Range value: bytes= - ١٣٩٣٠٠

char 0x660 is the Arabic "0" or "٠". 

![photo_2020-03-14_07-14-08](https://user-images.githubusercontent.com/16887599/76676443-7be33900-65bb-11ea-8038-d99d452568a1.jpg)

I have little to no experience coding for Android applications, but I'll try to pinpoint the exact problem and maybe fix it.

**Comment by K1rakishou** [comment]
@moun3m
Could you, please, open the image again then go to Settings -> Developer settings -> View logs and post the logs here? So we can see where exactly it crashes.

**Comment by moun3m** [comment]
I will do in a minute, I think I've pinpointed the problem.

(This is the first time I'm posting here so I'm sorry if I don't follow the proper protocols)

I cloned the project and found the file:
/Kuroba/blob/multi-feature/Kuroba/app/src/main/java/com/github/adamantcheese/chan/core/cache/downloader/ChunkDownloader.kt

On line 134 you will see: 
private const val RANGE_HEADER_VALUE_FORMAT = "bytes=%d-%d"

Kuroba assumes that  %d will return as an ASCII digit but since the system language is in Arabic it will not. I think if you'll make sure that the string is passed as a non-Arabic locale it should render as an ASCII.

I will post the log in a minute.

**Comment by K1rakishou** [comment]
>Kuroba assumes that %d will return as an ASCII digit but since the system language is in Arabic it will not. I think if you'll make sure that the string is passed as a non-Arabic locale it should render as an ASCII.

Yeah I guess I should explicitly use Locale.US there and in every other similar place throughout the whole project.

**Comment by moun3m** [comment]
This is my first time with Java, but could this work?

private const val RANGE_HEADER_VALUE_FORMAT = ("bytes=%d-%d", Locale.ENGLISH)

**Comment by K1rakishou** [comment]
Yeah it should be something like this but the Locale.ENGLISH should be the first parameter of String.format()
