### ISSUE TITLE
Missing spoilers on my phone

### ISSUE THREAD

**Issue by ghost** [Adamantcheese/Kuroba#819]
Got a new phone and the spoiler/code stuff is not there on the context menu. [Similar issue](https://github.com/Adamantcheese/Kuroba/issues/476) as this, except my phone isn't from Xiaomi

There are two options to resolve this.
1) Give us the option to choose between the context menu or the reply window
2) revert back to the reply window

**Comment by Adamantcheese** [comment]
Closed as of 338f62ea7980152174dc62cb009305678e205e79.
