### ISSUE TITLE
Some enhancements to country codes could be made

### ISSUE THREAD

**Issue by ghost** [Adamantcheese/Kuroba#820]
First, I'd like to thank you for implementing country codes. While it's there now, some enhancements could be made.

I just saw [this](https://github.com/Adamantcheese/Kuroba/commit/a84cbcf95585a4f0d555b2aa110b467e7f614287) and it'd be much easier for us to change the country code from the reply window with a dropdown menu with all of the imageboard's current country codes instead of opening the app > opening the menu > clicking on the imageboard > clicking on country flag code > figuring out the country code > putting in the country code. 

What do you think?

**Comment by Adamantcheese** [comment]
Per the comment I left on #591, I'll accept a PR.

**Comment by Adamantcheese** [comment]
Closed with merge.
