### ISSUE TITLE
Make thread search instantly focus on input field

### ISSUE THREAD

**Issue by stradus64** [Adamantcheese/Kuroba#83]
3 dot menu in thread -> search opens search bar but you have to tap it for keyboard to pop up, would be neat if it autofocused so you can just start typing after tapping search

**Comment by ownBard** [comment]
I still can't get this to work for the in-thread search.

**Comment by Adamantcheese** [comment]
Yeah I noticed and fixed it again with https://github.com/Adamantcheese/Kuroba/commit/d1259f097f87843d6d793a7f9d087b0aa071726f

**Comment by Adamantcheese** [comment]
Apparently that didn't fix it or something else borked it again. Taking a better look at it tells me I was doing some things wrong.
