### ISSUE TITLE
[BUG] YouTube title parsing not working on OP posts

### ISSUE THREAD

**Issue by Astridchan** [Adamantcheese/Kuroba#837]
YouTube links do not get parsed if they're in the OP post, neither in catalog or board mode nor when you open the thread. YouTube links in replies still get parsed. I'm using my own YouTube API key and it's below the quota so that isn't the issue. There was a couple of times where the YouTube title did get parsed when in board or catalog mode but if I refreshed the catalog it'd stop working again and go back to displaying only the link.

![Screenshot_20200323-122125](https://user-images.githubusercontent.com/40862101/77306902-ff5e0200-6d00-11ea-8581-8e1d8079a7d0.png)

**Comment by K1rakishou** [comment]
Should be fixed when https://github.com/Adamantcheese/Kuroba/pull/810 is merged.
