### ISSUE TITLE
2ch.hk, failed to show image: file's hash differs from the one we got from the server

### ISSUE THREAD

**Issue by jkrass1** [Adamantcheese/Kuroba#839]
No every but some images give that error

![Screenshot_2020-03-25-01-50-15-815_com github adamantcheese chan dev](https://user-images.githubusercontent.com/9212851/77486182-48d74b80-6dec-11ea-989d-3c601c0d3a79.jpg)
![Screenshot_2020-03-25-01-50-42-864_com github adamantcheese chan dev](https://user-images.githubusercontent.com/9212851/77486183-4a087880-6dec-11ea-87d5-720a8728bb5d.jpg)

**Comment by Adamantcheese** [comment]
Gonna guess that you did try the force reload like it asked?

**Comment by jkrass1** [comment]
I don't even know what force reload means

**Comment by Adamantcheese** [comment]
When viewing an image, in the toolbar overflow menu, there's an option called force reload. Try that first.

**Comment by jkrass1** [comment]
You mean this?
Still gives me error 
![Screenshot_2020-03-25-07-07-20-305_com github adamantcheese chan dev](https://user-images.githubusercontent.com/9212851/77501002-e1cd8d00-6e13-11ea-9369-a37232af62d0.jpg)

**Comment by Adamantcheese** [comment]
Bah, guess 2ch hashes can't be trusted either. Alright, thanks for the update.

**Comment by K1rakishou** [comment]
Yeah, they send incorrect hashes sometimes. I event notified them about this but got no reply yet.
