### ISSUE TITLE
Full image and webm preview before posting

### ISSUE THREAD

**Issue by ayy91** [Adamantcheese/Kuroba#84]
Please make it so that we can preview a selected image or webm before posting them.

We can already view images when we press them but half the image is covered by options. just make it so that the full image is shown and hide the options like this for example:
![image_preview](https://user-images.githubusercontent.com/51542078/59223524-cd960780-8bd4-11e9-93f6-bd066cd3fb45.jpg)

As for webms Kuroba doesn't even show a thumbnail, it just displays a text saying "No preview":
![Screenshot_20190610-083946_Gallery](https://user-images.githubusercontent.com/51542078/59223720-514ff400-8bd5-11e9-985e-45f992efcffc.jpg)
Kuroba should show a thumbnail and allow us to play the webm before posting.

**Comment by Adamantcheese** [comment]
Please submit another issue for webm thumbnails.
