### ISSUE TITLE
Report "Kuroba tablet support"

### ISSUE THREAD

**Issue by K1rakishou** [Adamantcheese/Kuroba#844]
UUID: 72f4a2829fee9f27489a238cb21f5679
Build flavor: stable
Version name: v4.12.0
OS info: Android 9, sdk version: 28
Report description: I use Kuroba on a Tab A 10.1 2019 model. Captcha floats towards the enter of the screen causing half of the images to be blocked because Captcha does not to fit to the right side window upon Captcha verification. Text also has a common tendency to be hidden behind image thumbnails in posts. Qif I refresh the thread then the text becomes how it should be. I should note this only seems to happen in portrait mode. I am currently on the latest version of Kuroba.

**Comment by Adamantcheese** [comment]
Closed with https://github.com/Adamantcheese/Kuroba/commit/8d761480f941210980062bbd1989122b22cad69c
