### ISSUE TITLE
Report "canceling saving a file"

### ISSUE THREAD

**Issue by K1rakishou** [Adamantcheese/Kuroba#848]
UUID: c8853a16a98b39f156c45a6b806372dc
Build flavor: stable
Version name: v4.12.0
OS info: Android 9, sdk version: 28
Report description: if I accidently use the gesture to save when ever I try to cancel saving in the overhead android notification it crashes the app.

**Comment by Adamantcheese** [comment]
No idea what would cause it, but it seems to be working fine?

**Comment by Adamantcheese** [comment]
Closing, not enough info to debug properly and everything appears to be working fine.
