### ISSUE TITLE
Report "Toggling opacity doesn't work"

### ISSUE THREAD

**Issue by K1rakishou** [Adamantcheese/Kuroba#851]
UUID: 3602d6e3b82074a4762eab7d54c6b6b1
Build flavor: dev
Version name: v4.12.0-a8754b8
OS info: Android 10, sdk version: 29
Report description: problem as described in title

**Comment by Adamantcheese** [comment]
Working fine. I can't remove baked in colors from JPEGs to make things look transparent.
