### ISSUE TITLE
Bug: YouTube Titles and Durations no longer display

### ISSUE THREAD

**Issue by ghost** [Adamantcheese/Kuroba#853]
Problem as described in title. Toggling both settings off and on, restarting the app, and clearing the database do not fix the problem.

**Comment by Adamantcheese** [comment]
Parsing works fine. Likely the API key you're using (either the default 4chanX key or your own) [ran out of quota](https://developers.google.com/youtube/v3/getting-started#quota). Do note #837 has been fixed on dev.
