### ISSUE TITLE
Webm playback before posting

### ISSUE THREAD

**Issue by ayy91** [Adamantcheese/Kuroba#86]
Please make Kuroba display a thumbnail for webms and add the ability to play them by pressing the thumbnail before posting/uploading.
Currently, when a webm is selected for upload, Kuroba doesn't show a thumbnail, it just displays a text saying "No preview":
![59223720-514ff400-8bd5-11e9-985e-45f992efcffc](https://user-images.githubusercontent.com/51542078/59305611-41064a80-8ca3-11e9-8cd5-32cf3ef6cf19.jpg)

Edit: just noticed that someone else requested webm thumbnails. Should I submit another issue for webm playback?

**Comment by Adamantcheese** [comment]
You've provided more information than the other submitter, so I've kept this one as the request. If I can get previews working then playback shouldn't be an issue.

**Comment by Adamantcheese** [comment]
This adds a static thumbnail for webm files, but it won't be animated, for now. I'll leave it open for the time being and change the title of the request.

**Comment by Pentaphon** [comment]
>and add the ability to play them by pressing the thumbnail before posting/uploading.

@ayy91 Do we really need this? You just have to know you didn't upload the wrong thing.  A thumbnail seems like enough of a solution.

**Comment by Adamantcheese** [comment]
Yeah I'm going to go with Pentaphon here; the current solution is good enough for most people's purposes, and implementing it will clash with other features. If you want to make sure you're uploading the right thing, play it back locally first.
