### ISSUE TITLE
Add "Copy the link to post" and let us customize our context menu 

### ISSUE THREAD

**Issue by ghost** [Adamantcheese/Kuroba#862]
Crosslinking posts to other boards is a pain in the ass. Being able to copy the link to a post will make it easier. Add "copy link" in the context menu please.

We should also be allowed to customize the context menu. There's so much junk in the list and I only need "quote", "report", "delete", "open in a browser" and "mark as my post".
What is the point of "remove" when there's "delete"?
Why is there a "filter image hash" when the post doesn't have an image?
Does anyone use "share" and "copy text"?
Why would I click on "info", when the time and date can be seen on the post already?
The context menu is a mess.

If you want to keep these in the context menu because it's your app, that's fine, But give us the option to customize it.

**Comment by ghost** [comment]
The share option is what allows you to copy a link to the post

**Comment by Adamantcheese** [comment]
Removing a post removes it from display.
Deleting a post deletes it from the website, if you've posted it.
Filter image hash isn't an option on posts without images. You must be on an older version.
Share is as @clawyf explained.
Info provides additional info that isn't presented in the post cell. You don't have to keep it on the main options page as there is already a setting for that.

Basically, quit whining and learn what everything does. If you want a context menu editor, you are free to submit a PR for it.
