### ISSUE TITLE
Sharing a file to Google Drive results in a failure

### ISSUE THREAD

**Issue by Esildor** [Adamantcheese/Kuroba#863]
Video with STR

Pixel 4

https://m.imgur.com/a/2zQUYqn

**Comment by Adamantcheese** [comment]
I've recently changed how file sharing works; the file is no longer downloaded to your save directory and instead is shared directly from the file cache. I tested it with Share.Pho.to on an emulator and it seemed to work fine, so if you're on the dev build you can see if this was fixed.

**Comment by Adamantcheese** [comment]
Working now.
