### ISSUE TITLE
Notifications don't go away

### ISSUE THREAD

**Issue by ghost** [Adamantcheese/Kuroba#868]
Posts quoting me that appear in the thread watcher notification don't go away when I tap on it, even after disabling notifications for the thread or removing it from thread watcher
Only force closing the app or turning off thread watcher entirely will close it, and the problem happens again when the next post quoting me appears in thread watcher.
Everything was working normally beforehand

Using kuroba dev v4.12.0-db0938f on a Samsung Note 10 Plus

**Comment by ghost** [comment]
To add to this, tapping a notification for a thread the 404s brings you to one of the other threads you opened (I don't know if it even has to be bookmarked)

**Comment by ghost** [comment]
It seems like removing every bookmark with the button also removes the notification. Tapping the notification when the thread 404s just brings you to the topmost thread you have bookmarked that hasn't 404'd

**Comment by Adamantcheese** [comment]
The thread watcher notification has always been sticky and only goes away when there are no unread posts. When you have threads being watched and they have unread posts, the first pin with unread posts in the bookmarks menu will be opened when the notification is tapped.

**Comment by ghost** [comment]
@Adamantcheese 
I'm pretty sure this is a bug, and I figured out why it happens
I had turned off the watch notification for Kuroba dev in Android's notification settings and I assumed that it would show me the notification only when a post replied to me. It still did, but they don't go away until either that setting is reenabled, or every thread I'm watching has no new posts of any sort.
In the standard Kuroba app, I don't get the "Watching XX threads" notification anyway, so it makes sense that I didn't bother to disable it.

**Comment by ghost** [comment]
It's also maybe worth noting that I can't create this issue in the same way on the normal Kuroba. Disabling the "watch notification" setting in android doesn't change anything, I would assume because that notification doesn't appear.

**Comment by Adamantcheese** [comment]
When a quote alert appears, the notification will stay until you have read through the thread with a quote in it. The reason why turning off "watch notification" doesn't work is because of how notification channels work; in order to have an "alert", a separate channel had to be made, and the notification is posted to that channel. Anything outside of the application is beyond my control once notification channels are registered; the settings in the app are basically only for compatibility with older Android versions that don't have notification channels.

**Comment by ghost** [comment]
Well, thanks anyway. I guess the main issue for me then is that I have to choose which app version to use if I don't want the sticky. I hope you can put a toggle for that instead

**Comment by Adamantcheese** [comment]
There is no app version where the notification isn't sticky. I might still do some more notification changes because I still get the occasional "null notification channel" crash even though they are definitely set up.
