### ISSUE TITLE
"1 new post" stuck at the bottom of the screen

### ISSUE THREAD

**Issue by ghost** [Adamantcheese/Kuroba#871]
This happened I believe after I refreshed a thread with only one reply and it carried over to any other threads I went in. Going in other threads displays their own new post popup over this one, but doesn't get rid of it. Closing the app fixes this.

Using kuroba dev v4.12.0-db0938f on a Samsung Note 10 Plus

**Comment by Adamantcheese** [comment]
It's unfortunate that this continues to occur, but pretty much everything's already been done from a number of other issues/attempts to fix it. If it happens again, just restart I guess.
