### ISSUE TITLE
Option to toggle between kB and KiB

### ISSUE THREAD

**Issue by ghost** [Adamantcheese/Kuroba#873]
Since 4chan displays filesizes in KiB values, it can sometimes be confusing when users mention filesizes and the numbers don't match up with Kuroba's info.

**Comment by Adamantcheese** [comment]
Uh, 4chan displays filesizes in KB? The only place I found it displays stuff as KiB is on find.4chan.org results. An example would be nice.

**Comment by ghost** [comment]
Do you not get different filesize numbers when opening a thread in a browser vs in the app? 4chan always reports image sizes in KiB for me

**Comment by Adamantcheese** [comment]
Ah, I see. 4chan displays them as KB and not kB, SI prefixes and whatnot. I'll double check all the other sites to see if they have the same display, it might be that the entire method needs to change outright.
