### ISSUE TITLE
Tap and hold the post numbers should copy the post's link, and some context menu improvements

### ISSUE THREAD

**Issue by ghost** [Adamantcheese/Kuroba#874]
[Continuation of 862 because Adamantcheese keeps locking for no reason](https://github.com/Adamantcheese/Kuroba/issues/862)

> Removing a post removes it from display.

No shit. You still haven't explained why there's Hide AND Remove. They are both the exact same thing, the only difference is that two extra clicks are required to "unremove" a post. 

> Filter image hash isn't an option on posts without images. You must be on an older version.

I'm on the latest release build (v4.12.0). It is an option on posts without images on the latest version.

> Share is as @clawyf explained.

You still haven't explained why we can copy the image's link and not the post's link. If you want to play this game and persist, it's either both ways, or none. 

> Info provides additional info that isn't presented in the post cell. 

The only thing Info provides is the resolution of the picture inside a post and nothing else. The filename, size and time of date can already be seen from the post itself, which makes Info completely useless.

Just accept the truth, you have so much garbage in the context menu and it needs to get cleaned up. If you got rid of Remove and Info, nobody would bat an eye.

**Comment by Astridchan** [comment]
>I'm on the latest release build (v4.12.0). It is an option on posts without images on the latest version.

It's fixed in the dev builds, see 3c79831.

>You still haven't explained why we can copy the image's link and not the post's link.

But you _can_ copy the post link, post menu -> share -> copy link.

>The only thing Info provides is the resolution of the picture inside a post and nothing else. 

The info menu is useful to view the exact post date 
and time when you have relative time (eg. "posted 1hr ago") enabled.
