### ISSUE TITLE
can't enter the app

### ISSUE THREAD

**Issue by mchridz** [Adamantcheese/Kuroba#880]
Hello, I have problem with lastest `kuroba-dev` builds they just stuck at logo picture and i can't do anything(tried reinstalling app didn't work). Pic related
Phone: Samsung S7
Android version: 8.0
![Screenshot_20200508-104122](https://user-images.githubusercontent.com/55925178/81394133-60a72c80-9119-11ea-8a77-4d52687076c5.jpg)

**Comment by mchridz** [comment]
I just tried all dev versions and this problem started since this update https://kuroba.io:8443/commits/41200_36adc98d9d47960d6117e177e5b503dc5e6e06d2_commits.txt

**Comment by Adamantcheese** [comment]
Likely related to #878, but if you could give me some logcat logs that would be nice.

**Comment by Adamantcheese** [comment]
@mchridz, I've updated a few things, could you try and tell me if the same result occurs?

**Comment by Adamantcheese** [comment]
Closed as of 40ce675.
