### ISSUE TITLE
Report "Video link titles"

### ISSUE THREAD

**Issue by K1rakishou** [Adamantcheese/Kuroba#883]
UUID: d03add740d31a796edd080b150d21640
Build flavor: stable
Version name: v4.12.0
OS info: Android 9, sdk version: 28
Report description: For some reason, when a video URL converts to the video title in youtube links, it has a habit of occasionally erasing a good chunk of the text immediately following the link.

**Comment by K1rakishou** [comment]
A link to the post would be really useful here.

**Comment by Adamantcheese** [comment]
Yeah, I don't think I've ever seen it swallow any extra text.

**Comment by Adamantcheese** [comment]
I'm just gonna close this one, don't have enough info to debug and everything seems fine.
