### ISSUE TITLE
Skipping forward on a WEBM takes a long time

### ISSUE THREAD

**Issue by ghost** [Adamantcheese/Kuroba#884]
I've been looking at /wsg/ sound webms and skipping forward toward the end (usually a couple minutes). It takes maybe 10 seconds to start playing again after that, which is slower than if I download the file and play it on my device.
Using Kuroba-dev v4.12.0-1bd1ade on a Samsung Note 10 Plus

**Comment by Adamantcheese** [comment]
Likely an issue with Exoplayer, which is out of my hands.
