### ISSUE TITLE
2ch.hk, couldn't not apply new image options (attempt to invoke java.lang.Sting java.io.File.getAbsolutePath() on a null obj reference)

### ISSUE THREAD

**Issue by jkrass1** [Adamantcheese/Kuroba#892]
**This hasn't not been fixed**

I could apply options to a photo successfully. 
And then I could try to apply options even to the same photo and it gives me this error
I had to restart the app and it works again for one time. 
Then error again

Logs: https://pastebin.com/ryq8bpVj

MIUI 11.2, Android 10

![IMG_20200517_181938](https://user-images.githubusercontent.com/9212851/82153040-c8721b80-986d-11ea-9f30-c6caac9bc2a2.jpg)

**Comment by Adamantcheese** [comment]
Are you trying to re-encode the same file after re-encoding it? Because the original file comes from a storage location on your device, but a re-encoded file is in the internal file cache which would give me a better indication of what's wrong.

**Comment by jkrass1** [comment]
Different images

I just tested

Created thread with photo 1 - ok
Replied with photo 2 - ok
Replied with photo 3 - error

Looks like second and subsequent replies always gives the error until you restart the app

Also, after a few minutes I can apply options again without restarting the app, but the next try will be the error

Verbose log 
https://pastebin.com/6XJuJc8c

**Comment by Adamantcheese** [comment]
Okay, so is this an issue related to reencoding or not? I can't really figure out what you're talking about here.

**Comment by jkrass1** [comment]
Yes, only applying options.
I mean, I can post fine, but I can't apply option.

Sorry for confusing explanation

**Comment by Adamantcheese** [comment]
I added in some comments to the dev build that might lead me to an answer, but I'll keep looking anyways.

**Comment by jkrass1** [comment]
Still doesn't work. 

https://pastebin.com/zPnnWcaZ

![Screenshot_2020-05-20-07-53-38-532_com github adamantcheese chan dev](https://user-images.githubusercontent.com/9212851/82406946-98469a80-9a70-11ea-85ba-7fcabf361490.jpg)

Also I want to draw your attention, it's problem only with 2ch.
4chan and 8kun work fine

**Comment by Adamantcheese** [comment]
Bizzare, thanks for the information.

**Comment by Adamantcheese** [comment]
I've made a small change that probably fixes it, as I believe a similar issue occured in the past with 2ch.hk. The dev version should be up to date with that fix.

**Comment by jkrass1** [comment]
Hurraaaay!!
It works!

**Comment by Adamantcheese** [comment]
@jkrass1, I've done a little bit of modification to how reply responses were being processed, could you make sure this issue still doesn't occur? I hope that it doesn't anymore with this new method which should also prevent future issues of this sort.

**Comment by jkrass1** [comment]
I downloaded latest dev build and it works just fine. 

But it has another issue, reduce size in pixels is incorrect and image quality gets back to 100% after posting  

![IMG_20200524_193518](https://user-images.githubusercontent.com/9212851/82759387-ca9c2300-9df5-11ea-871d-f720a11e006b.jpg)

**Comment by Adamantcheese** [comment]
I truly appreciate the help you've provided while debugging this issue; similar issues shouldn't arise anymore as a result of this.
