### ISSUE TITLE
Skipping forward/backward in a webm causes artifacting

### ISSUE THREAD

**Issue by ghost** [Adamantcheese/Kuroba#895]
Only on specific files, I can't really find a reason why. It just looks like black and white decoding errors that cover the entire video, I can post a screenshot if need be.
Interestingly I don't seem to be experiencing the bug that I reported a while back about skipping too far making webms stop working. Was that fixed?

Tested using a Samsung Note 10 Plus on v4.12.0-3b24910

**Comment by Adamantcheese** [comment]
Again, that's not something I have control over. That's on either Exoplayer's part, or your OS's software/hardware decoders not functioning correctly.
No, that bug was not fixed, nor do I have the ability to fix it. None of that code was touched at all.

**Comment by ghost** [comment]
Thanks for the insight. In the future I'll assume issues related to webms are probably not solvable.

**Comment by lewri** [comment]
I believe the only thing that can be done is keep updating exoplayer periodically hoping it gets fixed.

Apparently exoplayer are very picky about how you report issues.
