### ISSUE TITLE
Kuroba-dev being replaced on home screen by LeakCanary on update

### ISSUE THREAD

**Issue by ghost** [Adamantcheese/Kuroba#896]
I'm using the app's built-in update downloader. If this is somehow intended, let me know I guess

Tested using a Samsung Note 10 Plus on the last few dev updates

**Comment by Adamantcheese** [comment]
That's weird but also out of my control. [Whatever Leak-Canary is doing is on Leak-Canary's part, and should be reported over there.](https://github.com/square/leakcanary/issues) It's also possible that it's just your phone's installer that isn't handling things correctly. Either way, out of my hands.

To be more specific, the actual installation isn't handled by Kuroba, it's handled by the phone OS. That isn't something I can control.

**Comment by ghost** [comment]
Yeah, that's what I thought. I'll take your advice then.
