### ISSUE TITLE
Posting and/or commenting on WIRED-7 doesn't work

### ISSUE THREAD

**Issue by ultra-azu** [Adamantcheese/Kuroba#899]
Title says it all. I'll add to this some screenshots and a useless report log.

![Screenshot_20200521-212820_Kuroba](https://user-images.githubusercontent.com/19539392/82621878-4dc93900-9baa-11ea-966d-7284cc9a0de5.png)
![Screenshot_20200521-212829_Kuroba](https://user-images.githubusercontent.com/19539392/82621881-4efa6600-9baa-11ea-9275-c6ca23187bbf.png)

`W/Kuroba | WakeManager: Background update broadcast ignored because it was requested too soon
W/Kuroba | WakeManager: Background update broadcast ignored because it was requested too soon
W/Kuroba | WakeManager: Background update broadcast ignored because it was requested too soon
W/Kuroba | WakeManager: Background update broadcast ignored because it was requested too soon
E/Kuroba | ReplyPresenter: onPostComplete error
E/Kuroba | ReplyPresenter: onPostComplete error
W/Kuroba | WakeManager: Background update broadcast ignored because it was requested too soon
E/Kuroba | ReplyPresenter: onPostComplete error
E/Kuroba | ReplyPresenter: onPostComplete error`

**Comment by Adamantcheese** [comment]
If you could provide a version number that would be helpful.
For the HTTP referer, it could be a similar problem to #456, but I can't be certain just yet.
For the bot stuff, I can't really do much about that. Usually that's based on the text being sent over, so changing that should work? It's based on Vichan, but as far as I know the antispam is already enabled on Wired-7. 
@Wired-7 is likely a better point of contact on this as they provided the original implementation back in #46.

**Comment by Wired-7** [comment]
I think I know what causes this problem, I will try to fix this on my side.

**Comment by ultra-azu** [comment]
> If you could provide a version number that would be helpful.

Kuroba v4.12.0

**Comment by Adamantcheese** [comment]
@Ultracoolguy does this still occur?

**Comment by ultra-azu** [comment]
It works. Thanks!
