### ISSUE TITLE
Report "Audio from video plays when screen is off"

### ISSUE THREAD

**Issue by K1rakishou** [Adamantcheese/Kuroba#901]
UUID: ea936a20374b62b51247834db4b2db86
Build flavor: stable
Version name: v4.12.0
OS info: Android 9, sdk version: 28
Report description: when I turn the screen off while a video loads the audio will play when it finishes loading

**Comment by lewri** [comment]
Can reproduce. "Start videos muted" must be off though.

Does not happen if video is already loaded when you close the screen.
