### ISSUE TITLE
Report "Replying, specifically "tap post number to reply""

### ISSUE THREAD

**Issue by K1rakishou** [Adamantcheese/Kuroba#902]
UUID: d807937813493a1fdbf5a55fe73593c5
Build flavor: dev
Version name: v4.12.0-9d12f0f
OS info: Android 7.1.1, sdk version: 25
Report description: the option to do so is gone, and no longer works, please fix. :)

**Comment by K1rakishou** [comment]
I think it's been fixed recently but the dev apk's version hash is recent.

**Comment by Adamantcheese** [comment]
The entire post details field is long-tappable for the same functionality, with the setting being removed.
