### ISSUE TITLE
How do "country flag code" work?

### ISSUE THREAD

**Issue by Tarumath** [Adamantcheese/Kuroba#904]
What are supposed to be the codes to change your country flag?

**Comment by ghost** [comment]
I believe it's the filename of the memeflag that you want to select but with capital letters. E.g. RE for Republican, PR for Pirate.
P.S. it isn't that hard to check your grammar before posting

**Comment by Adamantcheese** [comment]
They only work on /pol/. Here's the stuff from the website.
![](https://user-images.githubusercontent.com/9031585/82976699-9c087e80-9f94-11ea-9d65-5fd28c0dd897.png)

**Comment by Tarumath** [comment]
Thks!
