### ISSUE TITLE
Image reencode WEBM option

### ISSUE THREAD

**Issue by namazso** [Adamantcheese/Kuroba#907]
Would it be possible to include an option in image reencode to encode it as webm?

It's a somewhat popular anti-iToddler meme to encode still images as webm, since Apple devices are unable to play them.

Example: https://archive.rebeccablacktech.com/g/thread/76108576/#76111610

**Comment by Adamantcheese** [comment]
That would require the inclusion of FFMpeg as a native lib and a huge set of changes to the way image reencoding works. Cool meme, but no, it's not worth the engineering effort. If apple devices don't support WebP, that would be a better possibility that is easily added.

**Comment by namazso** [comment]
I didn't mean FFMPEG necessarily, considering the app can already decode images, only webm encoder would be needed. I guess it'd still be hard then, I'm unfamiliar of what libraries are used in Kuroba.

As for webp, unfortunately 4chan doesn't support it either, so that's kinda a dead-end.

**Comment by Adamantcheese** [comment]
Yeah I took a look at it and it's really quite a bit of work to get either Android's own MediaCodec stuff working, let alone FFmpeg. For such a small feature, I'm going to say I won't do it, but if someone else does it, I'll happily accept a PR.

**Comment by Adamantcheese** [comment]
Actually I'll opt for not accepting a PR for this. Kinda falls under "bloat". Sorry!
