### ISSUE TITLE
Report "420chan posting"

### ISSUE THREAD

**Issue by K1rakishou** [Adamantcheese/Kuroba#912]
UUID: 3305480ca024fbb1fbc344bb230a1e4d
Build flavor: stable
Version name: v4.12.0
OS info: Android 10, sdk version: 29
Report description: When posting, Kuroba does not mark your own post as yours. And the post ID changes every once in a while.

**Comment by Adamantcheese** [comment]
Closed as of 6079a04f4f64a5a798d5764a446c291674050a71.
