### ISSUE TITLE
Report "application crash"

### ISSUE THREAD

**Issue by K1rakishou** [Adamantcheese/Kuroba#913]
UUID: f8122353f5238960ef3905174bdc9a08
Build flavor: stable
Version name: v4.12.0
OS info: Android 9, sdk version: 28
Report description: when going to another application, say to my browser to find a picture to post after having already typed my reply, and coming back to Kuroba the application will reload itself and clear the reply box. as if I closed it and opened it again. your crash report system is calling this a crash so here you go I hope the log helps make the software better. love u
Logs:
```
I/Kuroba | WakeManager: Started background alarm with an interval of 5 minutes
I/Kuroba | FilterWatchManager: Processing filter loaders, started at 12:01:18 AM
W/Kuroba | WakeManager: Background update broadcast ignored because it was requested too soon
I/Kuroba | WatchManager: 3 pin watchers beginning updates, started at 12:06:26 AM
I/Kuroba | WatchManager: All watchers updated, finished at 12:06:27 AM
I/Kuroba | WakeManager: Started background alarm with an interval of 5 minutes
I/Kuroba | FilterWatchManager: Processing filter loaders, started at 12:06:46 AM
W/Kuroba | WakeManager: Background update broadcast ignored because it was requested too soon
```

**Comment by Adamantcheese** [comment]
Not really enough info, if the user reads this, if they could make a video and post it here, along with more logs that would be helpful.

**Comment by K1rakishou** [comment]
I think we should disable the ability to edit logs when sending them because I saw a lot of reports where the logs are like this. I dunno whether we just don't log some info sometimes or users just cut out everything they think is unnecessary. Probably the latter.

**Comment by Adamantcheese** [comment]
It's been a month and I've gotten no additional information about this, so I'm going to close this issue. Probably was the notification channel stuff, which from some reports I saw still occurs and I literally have no idea how.
