### ISSUE TITLE
double tapping the back button right before opening an  unloaded image freezes the app

### ISSUE THREAD

**Issue by Managor** [Adamantcheese/Kuroba#914]
Demonstrative video: https://youtu.be/xhXrvB06m0A

Steps to reproduce:
Go into a thread
Quickly scroll down before the images load
Double tap the back button (either physical or digital)
Before the animation the thread leaving the screen finished, open an unloaded image

The app is now softlocked and must be reset to recover.
Really low priority bug.

**Comment by K1rakishou** [comment]
This also happens when the image gets deleted on the server and you accidentally open it when swiping through other images in a thread. The transition animation between the thumbnail image and the full size image is the cause. There is also Log.test("oops") right where it happens.

**Comment by Adamantcheese** [comment]
Thank you both for the very useful information. This "fixes" it in that the controller will still be presented, but won't softlock the application. So the image viewer might not be able to do anything, but you'll still be able to back out of it now.
