### ISSUE TITLE
[Feature Request] Sort posts inside a thread by the number of replies they have

### ISSUE THREAD

**Issue by crisalis2** [Adamantcheese/Kuroba#916]
This is useful in general to find the "best" inside a thread. For example, in threads about images/webm you could quickly find the "best" ones.

**Comment by lewri** [comment]
I wouldn't call this a bad feature if I'm honest. As long as it's not the default setting. And you'd want a secondary sort by post number when two comments (replies) have the same number of responses

**Comment by ghost** [comment]
I think this feature probably takes away from the site's design. For certain types of threads like YLYL or image dumps I can understand, but in those cases I think it might be better just to hide all posts without any replies

**Comment by jkrass1** [comment]
Also, would be nice to show posts which have some amount of replies you specify
Like show only post with 5 or more replies

**Comment by crisalis2** [comment]
Thanks.
