### ISSUE TITLE
Report "updating app"

### ISSUE THREAD

**Issue by K1rakishou** [Adamantcheese/Kuroba#920]
UUID: 3c93865b9c0af630e479f9589599a4ce
Build flavor: dev
Version name: v4.12.0-b1963c3
OS info: Android 7.1.1, sdk version: 25
Report description: app auto crashes on update option

**Comment by Adamantcheese** [comment]
Yeah this isn't enough info at all, and I can't reproduce it either, emulator or hardware.

**Comment by Adamantcheese** [comment]
Probably the same as #926, closing.
