### ISSUE TITLE
[Feature Request] Filter empty subjects, comments, etc.. 

### ISSUE THREAD

**Issue by ghost** [Adamantcheese/Kuroba#922]
Filtering by subject, comments, etc. works great, but you still got stuck with all threads leaving the field in question empty. As regex filtering for empty strings doesn't seem to work, I'd suggest adding an "empty" checkbox.

**Comment by Adamantcheese** [comment]
Is this a similar concern as https://github.com/chandevel/Clover/issues/744?

**Comment by ghost** [comment]
I guess it's pretty much the same issue. Considering it's still up, is this harder to fix than it looks like?

**Comment by Adamantcheese** [comment]
Regular expressions that match the empty string (like /^$/) should now work in dev. Note that any expression that would reduce to a pattern input of empty string (like //, "", or any number of spaces) have been prevented, as those would match everything.

**Comment by ghost** [comment]
Ah, I'm just on the regular version, thanks for your efforts!
