### ISSUE TITLE
[BUG] Posting a new thread opens to '404 thread not found'

### ISSUE THREAD

**Issue by Astridchan** [Adamantcheese/Kuroba#928]
Normally when you post a new thread the app would open the thread but now the "404 thread not found" page opens instead. If you have the "bookmark on post" option enabled the bookmark will also lead to the 404 page. If you try to open the thread in archives it leads to https://archive.rebeccablacktech.com/g/thread/0

Opening the thread from the catalog still works.

**Comment by Adamantcheese** [comment]
Uhh, isn't this the same as #915? Even you said it was fixed.

**Comment by Astridchan** [comment]
#915 was about threads going 404 when being opened from the catalog, in this case the thread goes to the 404 page after you post it and the app tries to automatically open it afterwards, but the same thread opens fine from the catalog.
