### ISSUE TITLE
Report "Filters not working (Android 10 one UI)"

### ISSUE THREAD

**Issue by K1rakishou** [Adamantcheese/Kuroba#931]
UUID: 7afa3580c8ae0b46bbe94ac06e7dbcca
Build flavor: stable
Version name: v4.12.0
OS info: Android 10, sdk version: 29
Report description: Filters stop working, making it so that I have to reset the app for them to work. But even then, they stop working again after a few minutes

**Comment by Adamantcheese** [comment]
They work fine, likely whoever this is doesn't know how to use regular expressions.
