### ISSUE TITLE
Refreshing threads takes longer than it should

### ISSUE THREAD

**Issue by ghost** [Adamantcheese/Kuroba#938]
I've noticed that it takes about 30 seconds for new posts to show up after they've been made, whether by auto refresh or doing it manually. Opening the thread in the browser always shows these posts immediately, but the app takes longer.

**Comment by Adamantcheese** [comment]
The application does not handle new posts specially for displaying them directly unlike the website; note that the website itself is the one that causes this behavior. Active threads will refresh much faster with more new posts.

**Comment by ghost** [comment]
I'm just wondering why it is that when I manually refresh a thread that it doesn't show posts that have been made when it would in the browser.
