### ISSUE TITLE
App closes sometimes when opening other apps

### ISSUE THREAD

**Issue by harky9000** [Adamantcheese/Kuroba#940]
Is there a way to make the app save whatever you were writing before exiting?

**Comment by Adamantcheese** [comment]
Duplicate of #913, however additional logs would be useful. That being said, you’re probably on v.4.12.0, which I would recommend trying the dev APK to see if this issue has been resolved. Probably notification channel stuff still, makes no sense at all.

**Comment by Adamantcheese** [comment]
Duplicate of #913, however additional logs would be useful. That being said, you’re probably on v.4.12.0, which I would recommend trying the dev APK to see if this issue has been resolved. Probably notification channel stuff still, makes no sense at all.
