### ISSUE TITLE
Cannot change accent color on Dark theme

### ISSUE THREAD

**Issue by Pentaphon** [Adamantcheese/Kuroba#952]
**Edited to reflect actual problem of not being able to change the accent color of the "Dark" theme.**

**Comment by Adamantcheese** [comment]
These items are controlled by your selected accent color.

**Comment by Pentaphon** [comment]
@Adamantcheese it seems I am unable to change the accent color on the "Dark" theme. No matter how many times I try, it remains black. Please confirm?

**Comment by Adamantcheese** [comment]
Tap the "Tap to change accent color" button, select your preferred color, and then click the checkmark button. I have mine set to orange right now so I know it is working.

**Comment by Pentaphon** [comment]
@Adamantcheese I've done all that but it does not change on the Dark theme. It stay black no matter what color I choose. I've recorded a video of me trying to change it twice with no success as proof. This is on a clean install of v4.13.2

https://files.catbox.moe/4hcpig.mp4
