### ISSUE TITLE
[bug] error posting 

### ISSUE THREAD

**Issue by baraa272** [Adamantcheese/Kuroba#953]
kuroba dev-41303_0585a9261230bf5f94d64529747ea3b393c33770
Getting error posting inside kuroba while posting in browser works normally

**Comment by Adamantcheese** [comment]
Try disabling IPv6 in experimental settings, otherwise there's not much I can do without additional information.

**Comment by baraa272** [comment]
Actually did, it seems like there is an additional cloudflare catcha that you have to solve 
I tried a browser on my pc (same ip) and I discovered I have to check and solve cloudflare captcha additionally to Google captcha to be able to post and reply

**Comment by Adamantcheese** [comment]
The fuck? Alright well that's super annoying but I'll keep it in mind if the issue crops up again.

**Comment by baraa272** [comment]
Sorry for bother, but when I use android systemwebview i don't counter this problem on my mobile but inside kuroba it happen and it give me error posting like what I described 
So maybe handle post/reply on systemwebview ?
 Or this is an different story?

**Comment by Adamantcheese** [comment]
The posting system only uses a webview for captcha authentication, everything else goes through OkHttp as basically just a regular network request. Cloudflare isn't liking something about the request then but it's kinda a black box that I can't debug.

Replacing the current system with a webview would 1) be a ton of work for only a few people having the issue and 2) really fucking ugly UI wise. It's not an option to consider.

**Comment by baraa272** [comment]
I know you have a lot of work , but I noticed this in my browser , in 4chanX quick reply method doesn't work at all , but original reply form always work so maybe at least change post method in kuroba to original form or something?

**Comment by Adamantcheese** [comment]
The posting method between the original form and the quick reply shouldn't matter as they use the same PHP posting endpoint and form data. If it's not working in the browser with 4chanX, then it isn't specific to this application and is an issue elsewhere in your network.

**Comment by baraa272** [comment]
Yeah it seems like cloudflare hate my ip , I really need to find a solution otherwise 
Anyway thanks for clarification
