### ISSUE TITLE
Report "Site Deletion"

### ISSUE THREAD

**Issue by K1rakishou** [Adamantcheese/Kuroba#954]
UUID: ff75eb0e6da2ef807fdabe48e3c19851
Build flavor: stable
Version name: v4.13.3
OS info: Android 6.0.1, sdk version: 23
Report description: Crash / error occurred upon deleting site.
Logs:
```
I/Kuroba | WakeManager: Started background alarm with an interval of 15 minutes
I/Kuroba | FilterWatchManager: Processing filter loaders, started at 07:47:19
W/Kuroba | WakeManager: Background update broadcast ignored because it was requested too soon
```

**Comment by Adamantcheese** [comment]
Uhh I thought and tested that you couldn't delete stuff from logs? There's literally no information about the exception being thrown here and it's definitely being logged. I can't do anything without that info because there are too many places where an exception can be thrown by database calls.

**Comment by K1rakishou** [comment]
Yeah, that's strange, I dunno why there is no stacktrace.
