### ISSUE TITLE
"error posting" 4chan post creation

### ISSUE THREAD

**Issue by hockeymikey** [Adamantcheese/Kuroba#955]
I can't create a post on 4chan on any boards. I get an error posting message. Turning on debug messaging shows nothing useful in the logs. Using the most recent version you posted on here. Older versions have the same issue. No idea what the issue is, wifi or mobile has the same issue. Tried searching for similar issues but wasn't seeing any. I'm using Android 8.1.0, RR on an Xperia XZ1 compact.

**Comment by Adamantcheese** [comment]
See #953. The debug logging setting is only for image loading as K1rak told me. Without any other information, I can't do much.

**Comment by hockeymikey** [comment]
> See #953. The debug logging setting is only for image loading as K1rak told me. Without any other information, I can't do much.

What's the point of debugging if its only for image loading!?! I bet there's some exception being thrown that would help that should be printed out. Christ, give me something. I don't wanna load this up into Android studio and debug it. Need to be more verbose in the logs.

**Comment by Adamantcheese** [comment]
Release builds don't print any debug logs, Dev builds do, for performance reasons. That setting exists because image loading spams the log with a lot of stuff that isn't particularly useful unless you're debugging that. If you want to get some logs without booting up Android Studio, use the dev build.

**Comment by hockeymikey** [comment]
W

> Release builds don't print any debug logs, Dev builds do, for performance reasons. That setting exists because image loading spams the log with a lot of stuff that isn't particularly useful unless you're debugging that. If you want to get some logs without booting up Android Studio, use the dev build.

Why wouldn't you have the debug option turn that on then? Make it easy for users to debug and submit issues. Or split them out like general printing and image issue printing.

**Comment by Adamantcheese** [comment]
Users are not good at debugging. Logs are already split out by log tag. If you want to argue over something found in developer settings while not being a developer, feel free, but it's not going to get you any closer to solving the issue you presented at the beginning.
