### ISSUE TITLE
Scrolling before swiping animation is over = stuck

### ISSUE THREAD

**Issue by floppyD** [Adamantcheese/Kuroba#956]
![2020_06_27_20_52_30](https://user-images.githubusercontent.com/29208110/85934489-80590680-b8b9-11ea-80fc-9f988db5baa9.gif)

**Comment by Adamantcheese** [comment]
For the time being, just tapping the back button fixes it. Note that this is only a problem on Phone layout mode with swipeable screens enabled, so if it annoys you enough, Slide layout will work fine.

**Comment by floppyD** [comment]
It doesn't seem to be easily reproducible during regular use, I just reported because someone mentioned it on a thread. Pretty low priority imo

**Comment by Adamantcheese** [comment]
I have a reproduction method, but since it requires some quick quick movement I'm going to have to try and debug this on hardware instead of emulator. It only happens when the event is a "fling" rather than a regular drag as well, so doing it slowly will also prevent the problem for the time being.
