### ISSUE TITLE
Report "Album view not following layout rules"

### ISSUE THREAD

**Issue by K1rakishou** [Adamantcheese/Kuroba#957]
UUID: 226faa831c92b8701f61f7af8d7295fe
Build flavor: stable
Version name: v4.13.4
OS info: Android 10, sdk version: 29
Report description: I have the layout set to 3-columns slide mode. Album view has 4 columns of thumbnails, making each individual thumbnail too small. Please add a way to make the thumbnails larger again.

**Comment by Adamantcheese** [comment]
I'm marking this as a duplicate of #81, even if it really isn't. The end result of the two will be equivalent.
