### ISSUE TITLE
Report "PNG banding issues"

### ISSUE THREAD

**Issue by K1rakishou** [Adamantcheese/Kuroba#958]
UUID: f4c1cbd3db465cbaa1c0a4e9a4f128b2
Build flavor: stable
Version name: v4.13.3
OS info: Android 10, sdk version: 29
Report description: There is very noticeable banding when viewing PNG pictures through the app, especially visible when the picture is mostly red gradients. This of course does not happen when the same picture is viewed in browser or anywhere else. This also does not happen with JPEGs.
Screenshot:
https://i.imgur.com/XkwE78b.png
Thread for repro:
https://boards.4chan.org/s4s/thread/8803739#p8804284

**Comment by Adamantcheese** [comment]
Resolved as of https://github.com/Adamantcheese/Kuroba/commit/769bd9af71a82275e1a2cf2e4b9f4be20951e989
