### ISSUE TITLE
Report "Insomnia Theme"

### ISSUE THREAD

**Issue by K1rakishou** [Adamantcheese/Kuroba#959]
UUID: f50f994133b731ed331f2fd411d6112d
Build flavor: stable
Version name: v4.13.3
OS info: Android 9, sdk version: 28
Report description: Insomnia theme no longer removes the ugly bars in-between posts. I really prefer them to not be there, as they make the screen feel visually cluttered and are ultimately useless for telling individual posts apart. Since I don't see an option to remove them, and since it doesn't seem to be possible to remove them by making a custom theme, I'll simply be downgrading back to V4.12.0. I hope you'll add an option to remove them in a future iteration.
Other than that, this is a great app. Thanks for making it.

**Comment by Adamantcheese** [comment]
Resolved as of https://github.com/Adamantcheese/Kuroba/commit/457fd001e1e8e917014f0758580ee656acf77bea
