### ISSUE TITLE
Report "link colour on dark theme"

### ISSUE THREAD

**Issue by K1rakishou** [Adamantcheese/Kuroba#964]
UUID: b1107358bfe96f1d61210e46cdcf6d6b
Build flavor: stable
Version name: v4.13.4
OS info: Android 10, sdk version: 29
Report description: The red on the link colour clashes with the post quoting. it gets messy and hard on the eyes. go back to the blue for links please.

**Comment by ghost** [comment]
I agree with this sentiment. The red is too strong. If you're intent on keeping it, I would elect to go for something lighter

**Comment by Adamantcheese** [comment]
Colors were reverted with https://github.com/Adamantcheese/Kuroba/commit/0ae0426ec65e1dec2d7b7cdec2973ddffa3f350c, I agree it was a bit ugly.
