### ISSUE TITLE
[BUG] Thumbnails failing to load in image gallery

### ISSUE THREAD

**Issue by Astridchan** [Adamantcheese/Kuroba#966]
If you open a thread, go straight to the image gallery and then scroll through it, many thumbnails will fail to load and display 'error' instead: 

![Screenshot_20200629-225821706 (1)_resize_19](https://user-images.githubusercontent.com/40862101/86050734-efbb2b80-ba5c-11ea-8a39-23cb47a9ab40.jpg)

When scrolling up and down some thumbnails will load and others that had already loaded will now show 'error' instead.
https://streamable.com/y9zr26

If you scroll through the thread first and then open the image gallery, all thumbnails will be loaded and no errors happen.

**Comment by ghost** [comment]
For me, anythingover 2 columns produces a lotof errored images
With 5 columns I get 80-90% errors so I wouldn't consider this solved

**Comment by Adamantcheese** [comment]
Given the information you provided in #977, you were not using the most recent development version. Is that still the case?

**Comment by Astridchan** [comment]
Thumbnails are still failing to load on the latest dev build:

![Screenshot_20200711-143140202 (1)_resize_6](https://user-images.githubusercontent.com/40862101/87223178-63293b00-c383-11ea-96c0-0083c07da228.jpg)

They mostly load fine when regularly scrolling, but by rapidly scroll up and down a small distance you can consistently cause thumbnails to not load:
https://streamable.com/dasv4b

Tapping the thumbnail that failed to load will not open the image (can't remember if it was like that previously). Thumbnails failing to load happens both with HTTP/2 enabled and disabled.
