### ISSUE TITLE
OP occasionally doesn't show up

### ISSUE THREAD

**Issue by ghost** [Adamantcheese/Kuroba#968]
After tapping a thread, it's possible to see only the replies and not the OP itself. I know this was also bug in Clover that probably never got fixed, it's just pretty rare. Refreshing the thread usually doesn't fix this. I can show an example if need be, but I think it's self-explanitory.

**Comment by Adamantcheese** [comment]
An example would actually be nice because I've never come across this bug.

**Comment by ghost** [comment]
Here you go. The thread was already archived when I took this, but I don't think that's relevant. It's a fairly rare bug as I've only seen it a dozen or so times in a few years, but it appears that it still exists
https://i.imgur.com/Md52BlY.jpg
Edit: I should actually point out that this thread was missing way more than just the OP, though that isn't always the case as far as I know. Take a look for yourself. I don't use any filters or remove any posts.
https://boards.4chan.org/v/thread/514946058
For reference I believe in the screenshot that was the first time I had loaded the thread at all, and most of the posts were obviously missing.

**Comment by lewri** [comment]
Can't replicate myself. I'm guessing a specific set of actions may cause this behaviour. I launched the thread several times and every time it was fine 

https://user-images.githubusercontent.com/20030128/86268676-70df0380-bbc0-11ea-8d47-99349bb20c88.jpg

**Comment by ghost** [comment]
Unfortunately I don't have any insight as to why it happens. I can just say that the first time certain threads are opened they can be missing posts, namely the OP. Maybe it's a server issue?

**Comment by Adamantcheese** [comment]
I'm leaning towards it being a strange server issue, when I checked that thread on my phone in a browser last night it was showing up as a 404, but now it's appearing as a regular archived thread. As if the thread was in the process of being deleted but then wasn't and was just archived instead, but the API was returning some sort of half-finished JSON in that in-between time. The thread title being correct makes sense because the app gets that from the post in the catalog, not the thread.

**Comment by ghost** [comment]
Maybe the API just breaks sometimes lol

**Comment by Adamantcheese** [comment]
Gonna close this one because it's probably just a server issue that isn't resolvable on the application end.

**Comment by ghost** [comment]
Could there be some way to remedy this with the refresh function? As it stands I need to close the app to get the posts to show up.

**Comment by Adamantcheese** [comment]
I honestly want to know how this keeps happening to you and seemingly only you specifically. The only plausible reason I have right now is you have some Remove filter set up VERY poorly.
