### ISSUE TITLE
[Feature Request] Bring WebM streaming back

### ISSUE THREAD

**Issue by floppyD** [Adamantcheese/Kuroba#97]
It was working fine here (aside from the bug that some webms would not play, that was kind rare and just playing them again would fix), and it was way faster than having to wait for them being downloaded. Could you at least make streaming optional?

**Comment by Adamantcheese** [comment]
@ekisu, can you test to see if streaming actually improves webm loading times on VERY slow connections? I can add it back as an option if it does improve performance; additionally, if there was some sort of user facing feedback that the stream is starting (like the progress bar for when the file is being downloaded), that would probably alleviate some of the annoyances of people saying "IT ISN'T WORKING BLACK SCREEN". Also put all the webm stuff into one branch, if possible.
