### ISSUE TITLE
[BUG] Post divider is missing between some posts

### ISSUE THREAD

**Issue by Astridchan** [Adamantcheese/Kuroba#971]
Latest Dev build:

![Screenshot_20200701-221657956 (1)](https://user-images.githubusercontent.com/40862101/86282869-b1eb0e00-bbe8-11ea-91d2-a069d1cab3c1.jpg)

EDIT:
Also this happens
![Screenshot_20200702-010523650 (1)](https://user-images.githubusercontent.com/40862101/86295984-69d7e580-bc00-11ea-932e-5143dad8fc76.jpg)

**Comment by ghost** [comment]
This issue still exists in the latest dev build, at least for the replies menu.

**Comment by Adamantcheese** [comment]
Can't reproduce, provide a screenshot I guess?

**Comment by ghost** [comment]
Yeah, here you go
https://i.imgur.com/PSSCRyn.jpg
