### ISSUE TITLE
[BUG] Highlight filter no longer applies to replies

### ISSUE THREAD

**Issue by Astridchan** [Adamantcheese/Kuroba#972]
Filter highlighting no longer works for replies, only for threads. It still works on v4.13.4 stable build so whatever change broke it must have happened after that.

**Comment by Astridchan** [comment]
Great, thanks for the quick fix!

**Comment by Adamantcheese** [comment]
I changed a bunch of stuff for layouts to work in Android Studio's previewer and then borked it all up on the actual app. Now it should work for both, without any more issues I hope.
