### ISSUE TITLE
Enhancement request: Folders for thread batch downloads but single images save to board folder 

### ISSUE THREAD

**Issue by shatteredhalo** [Adamantcheese/Kuroba#982]
Apologies if I'm just retarded and misunderstanding how to set up this behavior, but is it or would it be possible to have batch downloaded pictures from a thread go into their own folder but also have single image downloads go into their board folder, instead of also creating a new thread folder for that single image? This is something from Clover I've been missing since I finally decided to give Kuroba a try. I appreciate your consideration!

**Comment by Adamantcheese** [comment]
Ah yeah, that's behavior I changed from Clover. Batch downloads don't download into their own folders in the root save directory anymore and just download directly into the root folder/board folder/thread folder specified by whatever combination of folder settings you have enabled. It's a bit more consistent for download management in the application code. #809 is a related feature request. I'll accept a PR for it if someone implements it.

**Comment by Adamantcheese** [comment]
Closed with merge of #1001.
