### ISSUE TITLE
Report "Background thread watcher"

### ISSUE THREAD

**Issue by K1rakishou** [Adamantcheese/Kuroba#991]
UUID: 502d398ad39226130878e69730ff240a
Build flavor: stable
Version name: v4.13.4
OS info: Android 6.0.1, sdk version: 23
Report description: Background watcher only updating threads and sending out notifications when app opens after applying latest realease update.
Also, for some reason the notification icon flashes every couple seconds when in-app.

SM-J500M
Android 6.0.1

**Comment by Adamantcheese** [comment]
Background watching is working fine, probably some sort of power restriction that some ROMs enable that kill off background alarms and whatever.
