### ISSUE TITLE
Post your Theme Requests Here?

### ISSUE THREAD

**Issue by Pentaphon** [Adamantcheese/Kuroba#993]
@Adamantcheese Can this issue be kept open and linked to in the README so people can post their theme requests and the community can give them a thumbs up to show volunteer themers how many people want that specific theme? You can close this if you don't think this is a good idea of course, but if you do close it, can you give us another way to request themes?

_I'll start by requesting Vimyanized Dark by Seaweed from the Oneechan userscript._

Edit: Thanks, Cheese!

### **Everybody post your theme requests below and vote on them by using the reaction button!**

**Comment by Adamantcheese** [comment]
I'm closing this only because it hasn't been used in 7 months.
