### ISSUE TITLE
Update notification icon does not reset after an update

### ISSUE THREAD

**Issue by lewri** [Adamantcheese/Kuroba#994]
May be hard to reproduce since you can only really do it once (maybe you can reproduce with dev tools). But the little icon in the menu to let you know there's an update (circle with an ! inside) doesn't seem to reset after an update. 

I'm guessing the app isn't checking for updates on launch once one is available, and as such it never resets on its own. It is reset by manually toggling the "tap to check for updates button".

Not a problematic bug per se, I suppose more an annoyance.

**Comment by lewri** [comment]
The dev toggle to mark app as not updated, then restarting the app, does not produce this behaviour.

It seems specifically related to launching the app immediately after the update.

**Comment by Astridchan** [comment]
>May be hard to reproduce since you can only really do it once 

You can simply install an older version of the app and then update through the in-app updater to reproduce it.

**Comment by Adamantcheese** [comment]
Guess my fix for #962 didn't do it, I'll keep this one open for tracking even though it's a dupe.
