### ISSUE TITLE
[Feature Request] Open images from right side of screen

### ISSUE THREAD

**Issue by cuubix** [Adamantcheese/Kuroba#997]
My phone is too big and I'm right handed. Is it possible to have an option to add another button to the right side of the screen which can be clicked to open an image, behaving the same as if you clicked the thumbnail? 

Attached image shows a similar system used by the Sync app 

![nexusae0_2014-02-03-07 53 32](https://user-images.githubusercontent.com/12398027/87837445-84959580-c861-11ea-9513-bd6d05449e55.png)

**Comment by floppyD** [comment]
A tap on the filename area could work too
![Screenshot_20200717-221017_Kuroba](https://user-images.githubusercontent.com/29208110/87841252-743de480-c87a-11ea-93d0-d13c4c8640f3.png)

**Comment by Astridchan** [comment]
What about adding a setting to change thumbnail position from the left side to the right?

![Screenshot_20200718-095248752 (1)_resize_32](https://user-images.githubusercontent.com/40862101/87846975-d7f8f980-c8dc-11ea-8cae-63dc321e3ef3.jpg)
![Screenshot_20200718-095703635 (1)_resize_60](https://user-images.githubusercontent.com/40862101/87847007-273f2a00-c8dd-11ea-8bae-35f4695c8708.jpg)

**Comment by ghost** [comment]
Tap on filename would probably be inconvenient since long press on that box is what links a post in quick reply

**Comment by Adamantcheese** [comment]
Filename area would not work very on boards that allow more than 1 image per post, or if a post has inlined media, as only the first image in that post would be openable that way. Switching the directionality of the cell itself is the better option, however would require some additional work to fit with shift-post formatting.
